### ISSUE TITLE
problems installing HTTP_OAuth

### ISSUE THREAD

**Issue by callsuper** [puphpet/puphpet#1042]
Hi there,

I keep getting this error when I run vagrant provision:

```
Error: pear -d preferred_state=stable install  pear.php.net/HTTP_OAuth returned 1 instead of one of [0]
Error: /Stage[main]/Main/Php_pear_mod[HTTP_OAuth]/Puphpet::Php::Pear[HTTP_OAuth]/Php::Pear::Module[HTTP_OAuth]/Exec[pear-HTTP_OAuth]/returns: change from notrun to 0 failed: pear -d preferred_state=stable install  pear.php.net/HTTP_OAuth returned 1 instead of one of [0]
```

and then the pecl installs fail, however everything is fine if I exclude HTTP_OAuth.

My config.yaml looks like this:

example

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                aRANiqk5aiMH:
                    host: '9748'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            2me34qgn8LKQ:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - build-essential
        - git-core
        - curl
        - htop
        - libpcre3-dev
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - ssl
    vhosts:
        G6zMVKQyXzEX:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/html
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl: '0'
        a6zMVKQyXzEX:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/html
            port: '443'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        FsnAuAKKbAdt:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - intl
            - mcrypt
        pear:
            - HTTP_OAuth
            - SOAP
        pecl:
            - memcache
            - memcached
            - mysqlnd_memcache
            - mysql
            - oauth
            - PDO
            - PDO_MYSQL
            - pecl_http
            - imagick
            - perl
            - mailparse
            - POP3
            - phar
            - solr
    ini:
        display_errors: Off
        error_reporting: '-1'
        error_log: '/var/www/error_log.txt'
        session.save_path: /var/lib/php/session
    timezone: Europe/London
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        1stU8sgx3sy9:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        sVviOOqZwrn2:
            version: ''
mysql:
    install: '1'
    root_password: 123
    adminer: 0
    databases:
        EqWjvc4qxreC:
            grant:
                - ALL
            name: prsite
            host: localhost
            user: user
            password: 123
            sql_file: ''
        VDxx82EmaxZb:
            grant:
                - DELETE
                - INSERT
                - SELECT
                - UPDATE
            name: secure_login
            host: localhost
            user: user
            password: 123
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true
```

Any help would be greatly appreciated.

Many thanks,

Joe
