### ISSUE TITLE
Apache running as user apache, not www-data

### ISSUE THREAD

**Issue by eoinoc** [puphpet/puphpet#1055]
Hey,

from what I understand from my config.yaml below, Apache should be running as user `www-data`.

Apache seems to be running as user `apache`. **Is this a bug or a feature?**

On the machine, in `/var/www/mysite` I created a file `test.php`. The contents where this:

```
<?php
echo shell_exec("whoami");
```

The output is: `apache`.

As a background, this seems to have caused two issues for me so far:

* Sometimes a PHP seesion file error (see #1009), where there is a "Permission denied" error on PHP's stored session files
* I'm unable to execute a binary file from PHP via `shell_exec()` or `exec()` since the synced file is owned by `www-data` but is being executed by `apache`.
  * As a fix, I updated `Vagrantfile` to give `777` permission on synced directories and files.

`config.yaml`:

```
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.151
            forwarded_port:
                TtBrHpLCg8E9:
                    host: '8080'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            fwnBw7pm8NQj:
                source: ./
                target: /var/www/mysite
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - ImageMagick
        - ImageMagick-devel
        - ImageMagick-perl
        - htop
firewall:
    install: '1'
    rules:
        Sh2ABK44XaNU:
            port: '9200'
            priority: '100'
            proto: tcp
            action: accept
        CYWj2edaT1iF:
            port: '1080'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - headers
        - rewrite
    vhosts:
        0dGyLV73Rhgg:
            servername: mysite.localhost
            docroot: /var/www/mysite
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        FefFjKXELXxk:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            location: .php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: ''
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mbstring
            - mcrypt
        pear:
            - SOAP
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: UTC
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    ini: {  }
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    root_password: mysite456
    adminer: '1'
    databases:
        ZkQyFfKlS52I:
            grant:
                - ALL
            name: mysite_db
            host: localhost
            user: umysite
            password: mysite456
            sql_file: /var/www/mysite/.db_schema/generic_mysite.sql
        MQlVqDnJPpEd:
            grant:
                - ALL
            name: mysite_ee
            host: localhost
            user: umysite
            password: mysite456
            sql_file: /var/www/mysite/.db_schema/generic_ee.sql
postgresql:
    install: '0'
    settings:
        root_password: '456'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '456'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true
```
