### ISSUE TITLE
Can't start Apache on Debian Wheezy 7.5 x32

### ISSUE THREAD

**Issue by ksubileau** [puphpet/puphpet#1057]
Hi,

I've just started to use PuPHPet, but I can't launch Apache on a freshly installed box based on Debian Wheezy 7.5 **32 bits** (unfortunately my CPU doesn't support Intel VT,  so I can't run a 64 bits guest).

In fact, during vagrant up, I get several errors. First, apt-get fails to fetch a repository : 

```
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy-php55/all Translation-en_US
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy-php55/all Translation-en
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy/all Translation-en_US
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Ign http://repo.puphpet.com wheezy/all Translation-en
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Fetched 2,482 kB in 12s (202 kB/s)
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: Failed to fetch http://www.d7031.de/debian/dists/wheezy-experimental/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns:
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Some index files failed to download.
 They have been ignored, or old ones used instead.
==> default: Error: /Stage[main]/Apt::Update/Exec[apt_update]: Failed to call refresh: /usr/bin/apt-get update returned 100 instead of one of [0]
==> default: Error: /Stage[main]/Apt::Update/Exec[apt_update]: /usr/bin/apt-get update returned 100 instead of one of [0]
```

It seems that this repository doesn't provide packages for 32 bits OS.
And finally, apache return an error on starting (even if I try to start it manually later) : 

```
Starting web server: apache2
apache2: Syntax error on line 36 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/access_compat.load: Cannot load /usr/lib/apache2/modules/mod_access_compat.so into server: /usr/lib/apache2/modules/mod_access_compat.so: cannot open shared object file: No such file or directory 
```

Actually, if I look at the folder `/usr/lib/apache2/modules`, there is no file named `mod_access_compat.so`. If I delete the file `/etc/apache2/mods-enabled/access_compat.load`, I get another similar error with another module name, and so on until I get another error about an Invalid command 'Mutex' in ssl.conf.

It looks like the configuration deployed is dedicated to Apache **2.4**, but the installed version is **2.2.22** because the 2.4 is provided by the repository that APT fails to fetch.

**config.yaml** : 

``` yaml

---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x32
        box_url: puphpet/debian75-x32
        hostname: ''
        memory: '768'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            1WUfNizVxkUP:
                source: 'D:\\Developpement'
                target: /mnt/www/
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        wHgVHYAlPdkJ:
            servername: photos.local.dev
            docroot: /mnt/www/photos.local.dev
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        dgUXiFfIpLJT:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - gd
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Paris
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        r3iOUDomzFFP:
            version: ''
nodejs:
    install: '1'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        nS1PwOdLOg8Z:
            version: ''
mysql:
    install: '1'
    root_password: mysql
    adminer: 0
    databases: {  }
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true
```
