### ISSUE TITLE
php5-apc unmet dependencies, can't provision our setup (apc, api, common)

### ISSUE THREAD

**Issue by selbyk** [puphpet/puphpet#1083]
``` bash
The following packages have unmet dependencies:
 php5-apc : Depends: phpapi-20100525
            Depends: php5-common (= 5.4.32-1~dotdeb.1) but 5.5.16-1~dotdeb.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I can't figure out how to work around this. Here is my config :

``` yaml

---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: 'localhost'
        memory: '256'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                ft02MOkDQ3qI:
                    host: '5669'
                    guest: '22'
                qW8DUXrPL9DI:
                    host: '8080'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            HJBU0BUNwlbS:
                source: ./sparehanger
                target: /srv/www/sparehanger
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - htop
firewall:
    install: '1'
    rules:
        z6UfNKTAnClA:
            priority: '100'
            proto: tcp
            action: accept
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        6toCxGN1Fy2x:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /srv/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.php
                - index.html
                - index.htm
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            rewrite_to_https: '1'
            spdy: '1'
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - cgi
            - curl
            - fpm
            - geoip
            - imagick
            - mysql
            - pspell
            - recode
            - snmp
        pear: {  }
        pecl:
            - pecl_http
            - APC
            - APCu
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        wQvz9s6XfDWx:
            version: ''
nodejs:
    install: '1'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        gTUWUOqXObAV:
            version: ''
mysql:
    install: 0
    root_password: '123'
    adminer: 0
    databases:
        75GhRurKvPNJ:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '1'
    root_password: root
    adminer: '1'
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true
```
