### ISSUE TITLE
XDebug throws errors

### ISSUE THREAD

**Issue by HMAZonderland** [puphpet/puphpet#1094]
XDebug throws the following errors:
```cmd
Error: cp /.puphpet-stuff/xdebug/modules/xdebug.so  returned 1 instead of one of [0]
Error: /Stage[main]/Puphpet::Php::Xdebug/Exec[cp /.puphpet-stuff/xdebug/modules/xdebug.so ]/returns: change from notrun to 0 failed: cp /.puphpet-stuff/xdebug/modules/xdebug.so  returned 1 instead of one of [0]
Warning: /Stage[main]/Puphpet::Php::Xdebug/Puphpet::Php::Ini[xdebug/zend_extension]/Php::Augeas[XDEBUG/zend_extension-/xdebug.so]/Augeas[php_ini-XDEBUG/zend_extension-/xdebug.so]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Service[php5-fpm]: Skipping because of failed dependencies
```

Config file
```yaml
---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: xxx
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                Pnrkv0qwoUej:
                    host: '6177'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            n7p2be2IHo6m:
                source: ../xxx
                target: /var/www/xxx
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
            gN79WAPw7NGo:
                source: ../xxxx
                target: /var/www/xxxx
                sync_type: default
                rsync:
                    auto: 'false'
            b0RsFLP7Ox0m:
                source: ../xxx
                target: /var/www/xxx
                sync_type: default
                rsync:
                    auto: 'false'
            MPdgT2rDiau5:
                source: ../xxx
                target: /var/www/xxx
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - git
firewall:
    install: '1'
    rules:
        Uq2wIkCKFoTn:
            port: '5123'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        I538yEQxEtOz:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        mpXEKaxYr9uD:
            server_name: xxx.xxx
            server_aliases:
                - xxx
            www_root: /var/www/xxx/src/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        aeOmK08i76Bu:
            server_name: xxx
            server_aliases:
                - xxx
            www_root: /var/www/xxx/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        Bn8SyXcjvCWi:
            server_name: xxx
            server_aliases:
                - xxx
            www_root: /var/www/xxx/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        Ybfq1A0tPZLr:
            server_name: xxx
            server_aliases:
                - xxx
            www_root: /var/www/xxx/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        OTB0Lnil44Ar:
            server_name: xxx
            server_aliases:
                - xxx
            www_root: /var/www/xxx/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - common
            - curl
            - fpm
            - mysql
            - xmlrpc
        pear: {  }
        pecl: {  }
    ini:
        display_errors: Off
        error_reporting: 'E_ALL^E_STRICT'
        session.save_path: /var/lib/php/session
        log_errors: '1'
        error_log: /var/log/php/error.log
    timezone: Europe/Amsterdam
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: ERROR
        error_reporting: '32766'
    timezone: Europe/Amsterdam
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        PXBRrGgvdTvR:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    root_password: '123'
    adminer: 0
    databases:
        Lu4tCoZq0fa8:
            grant:
                - ALL
            name: xxx
            host: localhost
            user: xxx
            password: '123'
            sql_file: /var/www/xxx/database/database_script.sql
        cobMtt9yzEFi:
            grant:
                - ALL
            name: test
            host: localhost
            user: x
            password: '123'
            sql_file: /var/www/xxx/database/createscript.sql
        qphUp2LwAcQS:
            grant:
                - ALL
            name: xxx
            host: localhost
            user: xxx
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true

``

**Comment by fnagel** [comment]
@jtreminio Is this issue fixed or did you close it by accident?

**Comment by jtreminio** [comment]
@fnagel haven't had any responses in over 2 months.

**Comment by fnagel** [comment]
Yeah thats a problem :-D

Sadly I'm not quite sure which of my VMs had this issue but I will try to add my config as I run into this problem again...

**Comment by darienhf** [comment]
For the people haven't found any solution. 

I just found the `xdebug.so` lib was not copy to the php lib folder during the provisioning and it is located in `/usr/lib/php5/20131226-zts`, it does not look like que xdebug lib but it is. What you have to do is:

1 - Copy this file to the php lib folder, in my case 
`$ sudo cp /usr/lib/php5/20131226-zts /usr/lib/php5/20131226/xdebug.so`

2 - Change the permissions to 644
`$ sudo chmod 644 /usr/lib/php5/20131226/xdebug.so`

3 - Edit the file 
`$ sudo vim /etc/php5/cli/conf.d/zzzz_custom.ini`
```
[XDEBUG]
 ...
 zend_extension=/usr/lib/php5/20131226-zts/xdebug.so

 [XDEBUG]
 ...
 zend_extension=/usr/lib/php5/20131226/xdebug.so
```
4 - Restart php5-fpm
`$ sudo service php5-fpm restart`

5 - Execute 
`$ php -v`
```
PHP 5.6.5-1~dotdeb.1 (cli) (built: Jan 28 2015 05:40:56)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.3.0dev, Copyright (c) 2002-2015, by Derick Rethans
```

Done!! Now Xdebug is working on the box.

**Comment by clempat** [comment]
Is it possible that it is `/usr/lib/php5/20131226` when you use nginx ?

**Comment by jtreminio** [comment]
Hi all,

If you're having this issue please regenerate your archive. I fixed it in December.

**Comment by clempat** [comment]
Hi,

I maybe misunderstood.  I use this box: `puphpet/debian75-x64` and I use php5-fpm with nginx. on my machine the path is `/usr/lib/php5/20131226` but on [this line](https://github.com/puphpet/puppet-puphpet/blob/master/manifests/php/xdebug.pp#L24) it is `/usr/lib/php5/20131226-zts` I guess it is why the directory not found copy the compiled xdebug as this file: 20131226-zts

Thanks

**Comment by jtreminio** [comment]
@clempat thanks! Looks like I was dreaming when I fixed this as I missed an important piece.

**Comment by clempat** [comment]
I am not sure it will work in my case as the directory does not exists.

**Comment by darienhf** [comment]
@clempat Follow the step I described, the solution is exactly for this case. I tried to fixed onto the puppet's source, but I couldn't.

**Comment by clempat** [comment]
@darienhf Yes it is what I did and I confirm it worked. I wanted as well to fix it in the source code or keep the issue open.

**Comment by clempat** [comment]
There is some solution but would be some hack :) I wanted first to understand why this folder is different.

**Comment by jtreminio** [comment]
@clempat paste your config.yaml

**Comment by clempat** [comment]
I took a simple basic config as exemple:
```
---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                KS0mAxrRcsCj:
                    host: '9309'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            rAyaMbJb5kei:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        8v8f9o9nizkm:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                rjbp6wrghhww:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        rk1qg3p5nokz:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases:
        MERLP22RX0hh:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

I can suggest u a solution in a few.
