### ISSUE TITLE
Vagrant up error - Digital Ocean - Ubuntu

### ISSUE THREAD

**Issue by thiagotalma** [puphpet/puphpet#1146]
I made a setting to use the Digital Ocean but I've tried several ways and can not install the machine, always with the same error.

Can anyone help me understand and solve the problem, please?

I'm usign:
Windows 7
cwRsync (%PATH% ok)

Command:

```
D:\Server\Vagrant_DigitalOcean>vagrant up
Bringing machine 'default' up with 'digital_ocean' provider...
==> default: Creating new SSH key: Vagrant...
==> default: Creating a new droplet...
==> default: Assigned IP address: 104.131.888.88
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
Enter passphrase for D:/Server/DigitalOcean/Keys/admserver:mypass
==> default: Creating user account: admserver...
==> default: Rsyncing folder: /cygdrive/d/www_cloud/ => /var/www...
There was an error when attemping to rsync a share folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/www_cloud/
Guest path: /var/www
Error: Warning: Permanently added '104.131.888.88' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.1pre1]
```

Test SSH:

```
D:\Server\Vagrant_DigitalOcean>vagrant ssh
Enter passphrase for key 'D:/Server/DigitalOcean/Keys/admserver':
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Tue Oct 14 13:02:40 EDT 2014

  System load:  0.5               Processes:           71
  Usage of /:   9.5% of 19.56GB   Users logged in:     0
  Memory usage: 10%               IP address for eth0: 104.131.888.88
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

admserver@mydomain:~$ rsync --version
rsync  version 3.1.0  protocol version 31
Copyright (C) 1996-2013 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

admserver@mydomain:~$ 
```

My config.yaml

``` YAML

---
vagrantfile-digital_ocean:
    vm:
        box: digital_ocean
        hostname: mydomain.com
        network:
            private_network: 192.168.88.103
            forwarded_port: {  }
        provider:
            digital_ocean:
                image: 'Ubuntu 14.04 x64'
                region: nyc2
                size: 512mb
                token: xxxxxxxxxxxxxxxxxxx
                ssh_key_name: Vagrant
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            2WnYDdoMksXS:
                source: 'd:\www_cloud'
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: 'D:\Server\DigitalOcean\Keys\admserver'
        username: admserver
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - rsync
        - cron
        - curl
        - memcached
        - nano
        - wget
firewall:
    install: '1'
    rules: null
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        0qOtQGuWP27g:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        o7OM4HyEMtRz:
            server_name: mydomain.com
            server_aliases:
                - www.mydomain.com
            www_root: /var/www/prod/frontend/web
            listen_port: '80'
            location: \.php$
            index_files:
                - index.php
            engine: php
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
        FC8z7XUXhIdo:
            server_name: adm.mydomain.com
            www_root: /var/www/prod/backend/web
            listen_port: '80'
            location: \.php$
            index_files:
                - index.php
            engine: php
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
        RMC0QixT3r6k:
            server_name: dev.mydomain.com
            www_root: /var/www/dev/frontend/web
            listen_port: '80'
            location: \.php$
            index_files:
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        g4HgbNahf2c6:
            server_name: beta.mydomain.com
            www_root: /var/www/beta/frontend/web
            listen_port: '80'
            location: \.php$
            index_files:
                - index.php
            engine: php
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - common
            - curl
            - gd
            - intl
            - mcrypt
            - memcache
            - memcached
            - mysql
            - mysqlnd
            - tidy
        pear: {  }
        pecl:
            - APC
            - pecl_http
    ini:
        display_errors: On
        session.save_path: /var/lib/php/session
        allow_url_include: Off
        expose_php: Off
        error_reporting: E_ALL
        cgi.fix_pathinfo: '0'
    timezone: America/Sao_Paulo
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.remote_connect_back: '1'
        xdebug.remote_mode: req
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        5sjJVNmv3UBF:
            version: ''
nodejs:
    install: '1'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    root_password: xxxxxxxx
    adminer: 0
    databases:
        nGL1N2VHUcAK:
            grant:
                - ALL
            name: mydomain
            host: localhost
            user: mydomain
            password: xxxxxxxxx
            sql_file: ''
        PZexF9CystoW:
            grant:
                - ALL
            name: dev_mydomain
            host: localhost
            user: dev_mydomain
            password: xxxxx
            sql_file: ''
        VJVAPVaaWYLU:
            grant:
                - ALL
            name: beta_mydomain
            host: localhost
            user: beta_mydomain
            password: xxxxx
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '1'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true
```
