### ISSUE TITLE
Xdebug Compile issue

### ISSUE THREAD

**Issue by mrsimonbennett** [puphpet/puphpet#1160]
```
Error: phpize && ./configure --enable-xdebug && make returned 2 instead of one of [0]
Error: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: change from notrun to 0 failed: phpize && ./configure --enable-xdebug && make returned 2 instead of one of [0]
Warning: /Stage[main]/Puphpet::Php::Xdebug/Exec[cp /.puphpet-stuff/xdebug/modules/xdebug.so ]: Skipping because of failed dependencies
Warning: /Stage[main]/Puphpet::Php::Xdebug/Puphpet::Php::Ini[xdebug/zend_extension]/Php::Augeas[XDEBUG/zend_extension-/xdebug.so]/Augeas[php_ini-XDEBUG/zend_extension-/xdebug.so]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Service[php5-fpm]: Skipping because of failed dependencies
```

```

---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 172.16.1.5
            forwarded_port:
                6v6ptpeFbyaB:
                    host: '1080'
                    guest: '1080'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            obSjXRr1sbqJ:
                source: ./
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - htop
firewall:
    install: '1'
    rules:
        SpAzq2sQ8CYc:
            port: '1080'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        Tk5mMI7FuJL5:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        mnf9m3MnDDrs:
            server_name: s.local
            server_aliases:
                - www.s.local
                - api.s.local
            www_root: /var/www/public
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mysql
            - memcached
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/London
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        AJfzpNlDQ3sI:
            version: ''
nodejs:
    install: '1'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        0KOeHk7n5C2p:
            version: ''
mysql:
    install: '1'
    root_password: '123'
    adminer: 0
    databases:
        10Wr9918NbwW:
            grant:
                - ALL
            name: n
            host: localhost
            user: u
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true

```

```
[02:37 PM]-[vagrant@packer-virtualbox-iso]-[/tmp/vagrant-puppet-3]
$ php -v
PHP 5.6.2-1~dotdeb.1 (cli) (built: Oct 21 2014 19:58:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```

Having errors with xdebug ( I think) any help would be great :)
