### ISSUE TITLE
Centos 6.5 ZendOpCache won't install through pecl

### ISSUE THREAD

**Issue by kanariezwart** [puphpet/puphpet#1179]
In my config.yaml
```yaml
...
 modules:
    php:
        - bcmath
        - cli
        - common
        - fpm
        - intl
        - mbstring
        - mcrypt
        - soap
    pear: {}
    pecl: 
        - APCu
        -  ...
        - ZendOpcache
...
```
outputs the following error
```bash
default: Error: Could not find package php-pecl-zendopcache
default: Error: /Stage[main]/Main/Php_pecl_mod[ZendOpcache]/Puphpet::Php::Pecl[ZendOpcache]/Package[php-pecl-zendopcache]/ensure: change from absent to present failed: Could not find package php-pecl-zendopcache
```

However when I do manual search on opcache, I do find it. 
``` bash
$ pecl search opcache
Matched packages, channel pecl.php.net:
=======================================
Package     Stable/(Latest) Local
ZendOpcache 7.0.3 (beta)          The Zend OPcache provides faster PHP execution through opcode caching and optimization.
```
It's still in beta. Can I force an install?
```bash
$ pecl install -f zendopcache
```
A quick yum search:
```
$ yum search opcache
2418 packages excluded due to repository priority protections
====== N/S Matched: opcache php-opcache.x86_64 : The Zend OPcache

php-pecl-zendopcache.x86_64 : The Zend OPcache
php54-php-pecl-zendopcache.x86_64 : The Zend OPcache
php55-php-opcache.x86_64 : The Zend OPcache
php56-php-opcache.x86_64 : The Zend OPcache
```
What be the best way to get this library working for now for CentOS 6.5 through pecl or yum?
