### ISSUE TITLE
Version of npm package

### ISSUE THREAD

**Issue by charlie-wasp** [puphpet/puphpet#1202]
Hello, I wonder, if there is a way to set npm package version in puphpet config? In my situation I must have less compiler on my virtual machine. I have this config:

```
nodejs:
    install: '1'
    npm_packages:
        - less
```

But after running vagrant there is no less installed. I install it manually. And suddenly I've ran into issue that I've installed less version 1.7.5 and all worked perfectly, but my colleague has installed version 2.0 (less has new release recently), and it crashed build.
