### ISSUE TITLE
A way to set custom nginx config

### ISSUE THREAD

**Issue by d-ph** [puphpet/puphpet#1206]
Hi,

I'd like to set these two directives in my nginx vhost config:

[client_max_body_size ](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)
[fastcgi_read_timeout](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout)

How can I do it? I tried to put those in the vhost config in my `config.yaml`:
```
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        zf6UWt12NCKi:
            server_name: dev.wrap.me
            server_aliases:
                - dev.wrap.me
            www_root: /var/www/wrap.me/public
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: php
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            rewrite_to_https: '1'
            client_max_body_size: 0
            fastcgi_read_timeout: 3600
```
but I get these errors during the provision time:
```
==> default: Error: Invalid parameter fastcgi_read_timeout on node packer-virtualbox-iso
==> default: Error: Invalid parameter client_max_body_size on node packer-virtualbox-iso
```

Is there a way to set custom nginx directives in the `config.yaml`?
