### ISSUE TITLE
Add Mongo PHP extension

### ISSUE THREAD

**Issue by kororo** [puphpet/puphpet#1219]
Hi there,

I am wondering whether you able to add this piece of Puppet code for adding PHP support of Mongo? Maybe this will useful for others. I am sure there is better place to integrate to the core Puphpet but at the moment, I just use the site.pp

```
// this is your config.yaml
php:
    install: '1'
    version: '54'
    composer: '0'
    composer_home: ''
    modules:
        php:
            - cli
        pear: {  }
        pecl:
            - mongo
    ini:
```

```
// this is your site.pp
puphpet::php::ini { 'add mongo ini extension':
  php_version  => $php_values['version'],
  webserver    => $php_webserver_service,
  ini_filename => 'mongo.ini',
  entry        => 'Mongo/extension',
  value        => 'mongo.so',
  ensure       => 'present',
  require      => Puphpet::Php::Pecl["mongo"]
}
```

Hope it helps :)
