### ISSUE TITLE
Add V8JS PHP support

### ISSUE THREAD

**Issue by kororo** [puphpet/puphpet#1220]
Hi There,

I am suggesting to add V8JS support in the core Puphpet to have Javascript support in the PHP. I been researching this extension and I found out that this is very difficult to get work in the Centos, so the only place that I can get it works is in ubuntu precise version.

```
// this is your config.yaml
php:
    install: '1'
    version: '54'
    composer: '0'
    composer_home: ''
    modules:
        php:
            - cli
        pear: {  }
        pecl:
            - v8js-0.1.3
    ini:
```

```
// this is your site.pp
puphpet::php::ini { 'add v8js ini extension':
  php_version  => $php_values['version'],
  webserver    => $php_webserver_service,
  ini_filename => 'v8js.ini',
  entry        => 'V8JS/extension',
  value        => 'v8js.so',
  ensure       => 'present',
  require      => Puphpet::Php::Pecl["v8js-0.1.3"]
}
```

Hope it helps :)
