### ISSUE TITLE
firewall ports can not be multiple

### ISSUE THREAD

**Issue by head1328** [puphpet/puphpet#1236]
i typed 3 ports into "firewall rule port" input field (80 443 1080) but config.yml generated has only one port:

``` yaml
firewall:
    install: '1'
    rules:
        fQ0TdAbcrubY:
            port: '80'
            priority: '100'
            proto: tcp
            action: accept
        Kyz228wsXscG:
            port: '80'
            priority: '100'
            proto: udp
            action: accept
```
