### ISSUE TITLE
Defining MongoDB version in config.yaml

### ISSUE THREAD

**Issue by scottalan** [puphpet/puphpet#1245]
Is it possible to define a newer version of MongoDB? By default it installs 2.4.12. I need at least 2.6.0

I tried adding a version in `settings:` and where it is below:

```
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    version: '2.6.5'
    databases:
        P1Cn9sCq8PUH:
            name: NAME
            user: USER
            password: PASSWORD
redis:
    install: '0'
```

Thanks!
