### ISSUE TITLE
runnine multiple boxes at once

### ISSUE THREAD

**Issue by MarsVard** [puphpet/puphpet#1249]
I tried running multiple boxes at once, but noticed they conflicted because the vms had the same name.

after some googling I came up with this solution, hope this helps somebody, and maybe this could be added to all generated vms?

// added this to 'Vagrantfile'
config.vm.define "#{data['vm']['box_name']}"

// added this to 'config.yaml' 
box_name: 'unique_box_name'

**Comment by hedinfaok** [comment]
Sorry to comment on a closed issue, but we ran into the same problem today in our shop.  I just commented out `hostname` from the config.yml file. The code above would look like the following:

```
    ---
    vagrantfile-local:
        vm:
            box_name: 'myuniqueboxname'
            box: puphpet/centos65-x64
            box_url: puphpet/centos65-x64
            #hostname: 'test.drupal.dev'
            memory: '512'
            cpus: '1'
            chosen_provider: virtualbox
            ...
```

Don't forget to grab the ip address of the vagrant box and edit any web server hostname configurations to accommodate the second concurrently running Vagrant box from that project.
