### ISSUE TITLE
Provisioning crashes with "Error: Failed to apply catalog: metric name nil is not a string"

### ISSUE THREAD

**Issue by DigitalMachinist** [puphpet/puphpet#1250]
I've been grappling with is problem all day as I've been trying to customize a box to meet my needs, and I think I have almost everything figured out, but this problem keeps stopping me from making progress. I've installed other boxes with PuPHPet using the same VM OS, but with less specific configurations and everything was fine, but once I started using this config, I've been having awful luck.

I've tried removing all of my startup and exec scripts in case they were the issue.

I noted that I was also given a warning relating to "fact fqdn", but it's so far back in my bash output that I've lost its exact working. Also, I noted that all of the npm packages I listed to install were rejected by Puppet with an error like

``` bash
Error: /Stage[main]/Main/Package[{gulp}]: Could not evaluate: Puppet::Util::Log requires a message
```

Unlikely that these things are all related, but I figured it best to clarify my situation. If I need to run a few npm installs in my exec-once I can live with that workaround.

Please let me know if there's any more information I can provide to assist in finding the problem.

My config.yaml:

``` yaml

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x32
        box_url: puphpet/ubuntu1404-x32
        hostname: ''
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                8nG4EUPRK3qo:
                    host: '9999'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            IhmmuRUfXQgn:
                owner: www-data
                group: www-data
                source: ./
                target: /vagrant
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - git
firewall:
    install: '1'
    rules: null
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        460derZMCu4W:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts: {  }
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Toronto
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        wxAhwtmO2Jwx:
            version: ''
nodejs:
    install: '1'
    npm_packages:
        - '{gulp}'
        - '{grunt}'
        - '{nodemon}'
        - '{strongloop}'
        - '{pm2}'
python:
    install: '1'
    packages: {  }
    versions:
        w0K3eGQYnA6g:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: 'AIfow@1655D#404'
    adminer: 0
    databases:
        thwCfBhwSqWf:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

The last few lines of my bash terminal outout:

``` bash
...
==> default: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[git clone https://github.com/xdebug/xdebug.git /.puphpet-stuff/xdebug]/returns: executed successfully
==> default: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[phpize && ./configure --enable-xdebug && make]/returns: executed successfully
==> default: Notice: /Stage[main]/Puphpet::Php::Xdebug/Exec[cp /.puphpet-stuff/xdebug/modules/xdebug.so /usr/lib/php5/20131226]/returns: executed successfully
==> default: Notice: /Stage[main]/Puphpet::Php::Xdebug/Puphpet::Php::Ini[xdebug/zend_extension]/Php::Augeas[XDEBUG/zend_extension-/usr/lib/php5/20131226/xdebug.so]/Augeas[php_ini-XDEBUG/zend_extension-/usr/lib/php5/20131226/xdebug.so]/returns: executed successfully
==> default: Info: Php::Augeas[XDEBUG/zend_extension-/usr/lib/php5/20131226/xdebug.so]: Scheduling refresh of Service[php5-fpm]
==> default: Notice: /Stage[main]/Main/Service[php5-fpm]: Triggered 'refresh' from 17 events
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 200.37 seconds
==> default: Error: Failed to apply catalog: metric name nil is not a string
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
