### ISSUE TITLE
The CPU and Memory settings in the config.yaml file are ignored

### ISSUE THREAD

**Issue by gplusdotgr** [puphpet/puphpet#1255]
I've set it as:

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '4096'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.102
            forwarded_port:
                VNbBU1aiFEBb:
                    host: '9501'
                    guest: '22'
                FBcBU2aiCFFe:
                    host: '3000'
                    guest: '3000'
                GVdCU5ahSCMf:
                    host: '9500'
                    guest: '9500'
        post_up_message: ''
        provider:
            virtualbox:
                memory: '4096'
                cpus: '2'
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
```

I provisioned but I still see 1 cpu and 1024MB ram in my virtualbox machine settings..
