### ISSUE TITLE
php log

### ISSUE THREAD

**Issue by erdemece** [puphpet/puphpet#1278]
Hi,

I'm not able to find php errors in the server. I'm not even sure that they are being created.. what is the exact path for php error logs in the server. this my configuration;

```
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        error_log: syslog
    timezone: Europe/London
    mod_php: 0
```

thank you.
