### ISSUE TITLE
Can't add multiple ports in one firewall rule

### ISSUE THREAD

**Issue by Ducatel** [puphpet/puphpet#1282]
With the web site, I can't add 2 ports in one firewall rule.

For example, when in try to add 27017 and 28017, puphpet add just the last port

```
firewall:
    install: '1'
    rules:
        GdiK0gU7LNTq:
            port: '28017'
            priority: '100'
            proto: tcp
            action: accept
```
