### ISSUE TITLE
Error: Invalid parameter proxy_enabled on node develop.local

### ISSUE THREAD

**Issue by lichnow** [puphpet/puphpet#1285]
When vagrant up the puphpet,I get an error,
"Error: Invalid parameter proxy_enabled on node develop.local"
how can solve it?

**Comment by kusmierz** [comment]
I've the same error.

```yaml
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        s073yqigbewy:
            proxy_enabled: '0'
            proxy: ''
            server_name: foobar.dev
            server_aliases:
                - .foobar.dev
            www_root: /var/www/foobar/
```

I just have removed `proxy_enabled` line and it works just fine.

@jtreminio Here you have a part of the config with proxy_enabled (just downloaded this config from https://puphpet.com/)

**Comment by thiagotalma** [comment]
Same here.

```RUBY
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams:
        v1Jqk5aJOfFk:
            name: socket_nodes
            fail_timeout: 10s
            members:
                - 'io.myserver.dev:5000'
    vhosts:
        pmlwmnfzlsru:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
        hvdwio9byavs:
            proxy_enabled: '1'
            proxy: 'http://socket_nodes'
            server_name: ''
            www_root: ''
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
```

**Comment by deizel** [comment]
Creating a VM without touching the "Proxy" checkbox under Nginx:

````yaml
    vhosts:
        c0td25jvhd1u:
            proxy: ''
````

Creating a VM having checked the "Proxy" checkbox under Nginx:

````yaml
    vhosts:
        c0td25jvhd1u:
            proxy_enabled: '1'
            proxy: ''
````

Creating a VM having checked, then unchecked, the "Proxy" checkbox under Nginx:

````yaml
    vhosts:
        c0td25jvhd1u:
            proxy_enabled: '0'
            proxy: ''
````
