### ISSUE TITLE
Apache directory owner/group is 'root' for non-synced vhost

### ISSUE THREAD

**Issue by boite** [puphpet/puphpet#1287]
The owner and group is 'root' for the docroot of vhosts that aren't shared with the host. In the config there's a sync'd dir `/var/www/foo.src` and two vhosts at `/var/www/foo.dev` and `...foo.prod`:-

```
$ ls -l /var/www
total 20
drwxr-xr-x 2 root     root     4096 Dec 23 02:39 html/
drwxrwxr-x 2 root     root     4096 Dec 23 02:37 foo.dev/
drwxrwxr-x 2 root     root     4096 Dec 23 02:37 foo.prod/
drwxrwxr-x 1 www-data www-data 8192 Dec 22 23:10 foo.src/
```

I expected to see all three `foo.*` dirs with owner/group `www-data`. If I change [Line 43 of Apache.pp](https://github.com/puphpet/puphpet/blob/master/archive/puphpet/puppet/nodes/Apache.pp#L43) to this:-

```
$vhost_docroot_group = 'www-data'
```

Then I see the following, which is enough to allow me to vagrant ssh to the box and rsync from `foo.src` to `foo.dev`:-

```
$ ls -l /var/www
total 20
drwxr-xr-x 2 root     root     4096 Dec 23 03:37 html/
drwxrwxr-x 2 root     www-data 4096 Dec 23 03:35 foo.dev/
drwxrwxr-x 2 root     www-data 4096 Dec 23 03:35 foo.prod/
drwxrwxr-x 1 www-data www-data 8192 Dec 22 23:10 foo.src/
```

Config:-

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        name: foo-test
        hostname: 'foobox'
        memory: '768'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.17
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            64I4NspYau4u:
                owner: www-data
                group: www-data
                source: ../
                target: /var/www/foo.src
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: false
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        YhnQeR1iGjK2:
            servername: foo.local
            docroot: /var/www/foo.prod
            port: '80'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
        1kkzZEFAOBVa:
            servername: foo-dev.local
            docroot: /var/www/foo.dev
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_DEBUG true'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
    mod_pagespeed: 0
nginx:
    install: '0'
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        short_open_tag: '0'
        apc.enabled: '1'
    timezone: Europe/London
    mod_php: '0'
hhvm:
    install: '0'
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.remote_connect_back: '0'
        xdebug.max_nesting_level: '250'
        xdebug.remote_host: 127.0.0.1
xhprof:
    install: '0'
wpcli:
    install: '0'
drush:
    install: '0'
ruby:
    install: '1'
    versions:
        oUJyyq8482nT:
            version: ''
nodejs:
    install: '0'
python:
    install: '1'
    packages: {  }
    versions:
        C765uapxiOUR:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: xxxx
    adminer: 0
    databases:
        cln731MgpMzP:
            grant:
                - ALL
            name: foo
            host: localhost
            user: foo_dbuser
            password: xxxx
            sql_file: /vagrant/database/latest/foo.sql
        r459tj6kmbe8o0:
            grant:
                - ALL
            name: foo_dev
            host: localhost
            user: foo_dbuser
            password: xxxx
            sql_file: /vagrant/database/latest/foo.sql
postgresql:
    install: '0'
mariadb:
    install: '0'
sqlite:
    install: '0'
mongodb:
    install: '0'
redis:
    install: '0'
mailcatcher:
    install: '0'
beanstalkd:
    install: '0'
rabbitmq:
    install: '0'
elastic_search:
    install: '0'
solr:
    install: '0'
```
