### ISSUE TITLE
redis session handler not accepted

### ISSUE THREAD

**Issue by head1328** [puphpet/puphpet#1288]
it's not possible use redis (or memcache) as session handler

```
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
            - redis
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_handler: 'redis'
        session.save_path: 'tcp://127.0.0.1:6379'
    timezone: Europe/Berlin
    mod_php: 0
```

error message: Error: Parameter creates failed on Exec[mkdir -p tcp://127.0.0.1:6379]: creates must be a fully qualified path at /tmp/vagrant-puppet-3/manifests/nodes/Php.pp:139
