### ISSUE TITLE
Group issue with NFS with Bindfs plugin 

### ISSUE THREAD

**Issue by laurentlemaire** [puphpet/puphpet#1300]
Hi,

My config.yaml : http://pastie.org/9805136

I have installed the bindfs plugin, and have configured a folder to by synced in NFS.
Folder is synced/mounted but the group is set to '501'.

When looking at the Vagrantfile I found something that looked wrong to me #83:
if folder['sync_type'] == 'nfs'
        config.vm.synced_folder "#{folder['source']}", "#{folder['target']}", id: "#{i}", type: 'nfs'
        if Vagrant.has_plugin?('vagrant-bindfs')
          config.bindfs.bind_folder "#{folder['target']}", "/mnt/vagrant-#{i}"
        end

Where we can see that no options is passed to the config.bindfs.
I've tried to replace #86
config.bindfs.bind_folder "#{folder['target']}", "/mnt/vagrant-#{i}"
by
config.bindfs.bind_folder "#{folder['target']}", "/mnt/vagrant-#{i}", owner: "www-data", group: "www-data"

After those changes I "vagrant halt", then "vagrant up" it again and the issue remained.

Thanks

**Comment by KLVTZ** [comment]
@laurentlemaire copy over your config.yaml folder and re-archive a new `puphpet.zip`. Try a fresh provision on the latest stack of vagrant, vagrant-bindfs, and virtualbox.

 I experienced a similar issue: #1293 with permissions. I tried the provision this morning, and everything remains as owned by the `www-data` group. I notice that puppet provisions fail once in a while due to time-out and other obscure third-party resources. 

Let us know if you still experience the issue.

**Comment by j3ll3nl** [comment]
I still had the problem.

This is what i did to fix it:
I set the group-owner to www-data on al project folders in local. (sudo chown [local user]:www-data machines -R)
This causes to to have www-data as group-owner in the virtual machine also.
This fixed al writing issues for me (Working with Drupal and drush on guest machine)

**Comment by KLVTZ** [comment]
@j3ll3n @laurentlemair this worked fine in Ubuntu. But I faced the issue of the permissions not changing under a half-provisioned instance of CentOS on vmware. A hack I did was change the HTTPD `DocumentRoot` from `/var/www` to the `mnt/vagrant` folder. That gave me the same `www-data` permissions. Not correct, but an alternative I tried and worked.

But, again, try my suggestion above as that resolved all my issues.

**Comment by jtreminio** [comment]
I think the issue may be the nested shared folders you've got set up:

`target: /var/www` and `target: /var/www/travelyo`

Please try with different directories - I believe I've run into this problem before, but there's not much I can do on the puphpet side.

**Comment by rpensek** [comment]
@jtreminio I know this is closed, but I don't wish to create another issue. Anyhow this is the main part of config.yaml:
```
synced_folder:
            vflsf_cijctvln75fu:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
```

Now my questions is: shouldn't this www-data be the owner and have write / ownership permissions on `/var/www` based on `config.yaml`? The thing is that i'm using centOS and it seems as if these settings are not being used. To fix my PHP write permissions issues I had to modify `puphpet/vagrant/vagrantfile-local` and in there manually add before the last line basically the same thing that I presume is nuPHPet job:

```
...
config.vm.synced_folder "./", "/var/www",
          owner: "www-data",
          group: "www-data",
          mount_options: ["dmode=775,fmode=775"]
...
```

Is this intended use, or should there be a better way to handle this, since every project needs some sort of permissions to write and by searching over the internet a lot of folks are having basically the same issues.
