### ISSUE TITLE
Mysql override_settings do not get applied after provision

### ISSUE THREAD

**Issue by marcosgdf** [puphpet/puphpet#1303]
I've got some override_settings in mysql block but they are not applied unless I reboot mysql service after puppet provision.

```
---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.42.101
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            XURLecNigGej:
                owner: ''
                group: ''
                source: ../dolibarr
                target: /var/www/dolibarr
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - ack-grep
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        jio3vb1ccsxv:
            servername: dolibarr.local
            docroot: /var/www/dolibarr/htdocs
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                bfbbnd3chmfh:
                    provider: directory
                    path: /var/www/dolibarr/htdocs
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        twhkytkntejm:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            location: .php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - gd
            - imagick
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        sendmail_path: '"/usr/bin/env catchmail"'
    timezone: UTC
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    ini: {  }
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options:
        mysqld:
            sql_mode: 'STRICT_ALL_TABLES,ONLY_FULL_GROUP_BY,NO_ZERO_DATE'
    root_password: root
    adminer: '1'
    databases:
        9Ys80MpEn4Rb:
            grant:
                - ALTER
                - CREATE
                - DELETE
                - DROP
                - INDEX
                - INSERT
                - SELECT
                - UPDATE
            name: dolibarr
            host: localhost
            user: user
            password: user
            sql_file: /var/www/dolibarr/dev/initdata/mysqldump_dolibarr_3.5.0.sql
postgresql:
    install: '1'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: ''
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

```

**Comment by Zeromax** [comment]
Same Problem here:
```yaml
mysql:
    install: '1'
    override_options:
        mysqld:
            datadir: '/vagrant/mysql-data'
    root_password: root
    adminer: 0
    databases: {  }
```

I have to restart mysql Service everytime.

**Comment by jtreminio** [comment]
You can create an exec-always bash script to run after every `$ vagrant up` and `$ vagrant provision`.

**Comment by Zeromax** [comment]
@jtreminio sure that's what I have done. But I think the config should work without Manual restarting any Services.

**Comment by marcosgdf** [comment]
So... am I supposed to restart MySQL service after every provision because Puppet didn't do it?

**Comment by jtreminio** [comment]
In `mysql.settings` you can define a key `restart`. It now defaults to `true`, which solves your immediate problem.

These commits also enable overriding any value in `mysql.settings`. Note that this is a new key containing `override_options` and `root_password`, they have been moved so your existing config.yaml will not work as is.

Take a look here for more information: https://github.com/puphpet/puphpet/commit/f8d57438edfbabf1e999354c78378bc0b881cd7c#diff-cc5b4e884c97878c8f3a2fb08e276885L3

**Comment by bitmatix** [comment]
Currently there seems to be the problem that the settings for mysqld doesn't get applied (to "/etc/mysql/my.cnf") for the the first provisioning. I've got to do a "vagrant halt" and then a "vagrant up --provision".

The MySQL settings in my config.yaml are:

```
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: mysql2k16
        override_options:
            mysqld:
                sql_mode: 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'
        restart: true
```
