### ISSUE TITLE
Message: cannot load such file -- fog/version

### ISSUE THREAD

**Issue by byhoratiss** [puphpet/puphpet#1325]
Hi, I'm getting this error message when using "vagrant up", "destroy", "provision", everything.
Even I tried to use a little older version than 1.7.2 of Vagrant, but no luck.

```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/myuser/Sites/informes/Vagrantfile
Message: cannot load such file -- fog/version
```

Vagrant Version: 1.7.2

I'm using Ubuntu 14.10, here is my config.yml:
```
---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '256'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                3fenTsHOE6yb:
                    host: '6300'
                    guest: '22'
                Tcadh7hTg8XQ:
                    host: '33060'
                    guest: '3306'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            Out2GweE9JD0:
                owner: ''
                group: ''
                source: ./
                target: /var/www/prieto/informes
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
            3tYaBrqeN7KG:
                owner: ''
                group: ''
                source: ./../prieto
                target: /var/www/prieto
                sync_type: nfs
                rsync:
                    exclude:
                        - informes/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
vagrantfile-rackspace:
    vm:
        box: rackspace
        hostname: master
        provider:
            rackspace:
                server_name: rackspace-server
                image: b279d8e6-1cbd-4e7c-875a-f6dbffc4c4a0
                region: dfw
                size: '512MB Standard Instance'
                username: RACKSPACE_USERNAME
                api_key: RACKSPACE_API_KEY
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            4RDj1aBMyUb0:
                source: ./
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        public_key_path: ~/.ssh/id_rsa.pub
        username: PRIVATE_KEY_USER
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
vagrantfile-linode:
    vm:
        box: linode
        hostname: master
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        provider:
            linode:
                distribution: 'Debian 7.7'
                datacenter: newark
                plan: '1024'
                token: LINODE_API_KEY
                ssh_key_name: Vagrant
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            1HkLYAyMfBI9:
                source: ./
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        username: PRIVATE_KEY_USER
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
vagrantfile-softlayer:
    vm:
        box: softlayer
        hostname: softlayer-server
        provider:
            softlayer:
                username: SOFTLAYER_USERNAME
                api_key: SOFTLAYER_API_KEY
                ssh_key: 'SOFTLAYER SAVED PUBLIC KEY NAME'
                operating_system: DEBIAN_7_64
                datacenter: ams01
                max_memory: '1024'
                start_cpus: '1'
                domain: test.com
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            MTnj1KiFIFXY:
                source: ./
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        public_key_path: null
        username: null
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
vagrantfile-aws:
    vm:
        box: aws
        hostname: master
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        provider:
            aws:
                access_key_id: ''
                secret_access_key: ''
                keypair_name: ''
                ami: ami-4b124a22
                region: us-east-1
                instance_type: m1.small
                security_groups: {  }
                tags:
                    Source: Puphpet
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            ACUgqyUOcgJq:
                source: ./
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        username: admin
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
vagrantfile-gce:
    vm:
        box: gce
        hostname: master
        provider:
            gce:
                project_id: GCE_PROJECT_ID
                client_email: GCE_CLIENT_EMAIL
                key_location: /PATH/TO/PRIVATE_KEY.PK12
                machine_type: n1-standard-1
                image: debian-7-wheezy-v20141205
                name: instance-name
                tags: null
                zone: us-central1-a
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            mZI4aOlC6ZLY:
                source: ./
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        public_key_path: ~/.ssh/id_rsa.pub
        username: PRIVATE_KEY_USER
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - deflate
        - expires
        - headers
        - rewrite
    vhosts:
        sn8cnxbt10fw:
            servername: prieto.dev
            serveraliases:
                - www.prieto.dev
            docroot: /var/www/prieto
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                etv8b3xxug0z:
                    provider: directory
                    path: /var/www/prieto
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        zv6capnxwkjw:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - gd
            - geoip
            - intl
            - mcrypt
            - memcache
            - memcached
            - mysql
            - sqlite
            - sybase
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: America/Argentina/Buenos_Aires
    timezone: America/Argentina/Buenos_Aires
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: null
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '1'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases:
        S58bXaWah0o4:
            grant:
                - ALL
            name: prieto
            host: localhost
            user: prieto
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: null
        java_install: true
solr:
    install: '0'
    settings:
        version: null
        port: ''
```
