### ISSUE TITLE
PHP 5.6, Nginx with SSL and SPDY fails

### ISSUE THREAD

**Issue by gcds** [puphpet/puphpet#1327]
Hello,

I have made a application with php 5.6, nginx with vhost enabled ssl and spdy. But it fails:

```
==> default: Info: /Stage[main]/Main/Nginx_vhost[pal4qwae3alk]/Nginx::Resource::Vhost[awesome.dev]/Nginx::Resource::Location[awesome.dev-default]/Concat::Fragment[048eaed5721cd4e907dab2dc224370b9]/File[/var/lib/puppet/concat/_etc_nginx_sites-available_awesome.dev.conf/fragments/800_048eaed5721cd4e907dab2dc224370b9]: Scheduling refresh of Exec[concat_/etc/nginx/sites-available/awesome.dev.conf]
==> default: Notice: /Stage[main]/Main/Nginx_vhost[pal4qwae3alk]/Nginx::Resource::Vhost[awesome.dev]/Concat[/etc/nginx/sites-available/awesome.dev.conf]/Exec[concat_/etc/nginx/sites-available/awesome.dev.conf]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Nginx_vhost[pal4qwae3alk]/Nginx::Resource::Vhost[awesome.dev]/Concat[/etc/nginx/sites-available/awesome.dev.conf]/Exec[concat_/etc/nginx/sites-available/awesome.dev.conf]: Triggered 'refresh' from 7 events
==> default: Notice: /Stage[main]/Main/Nginx_vhost[pal4qwae3alk]/Nginx::Resource::Vhost[awesome.dev]/Concat[/etc/nginx/sites-available/awesome.dev.conf]/File[/etc/nginx/sites-available/awesome.dev.conf]/ensure: defined content as '{md5}78a6796dae68b598f487972410cf0f27'
==> default: Info: /Stage[main]/Main/Nginx_vhost[pal4qwae3alk]/Nginx::Resource::Vhost[awesome.dev]/Concat[/etc/nginx/sites-available/awesome.dev.conf]/File[/etc/nginx/sites-available/awesome.dev.conf]: Scheduling refresh of Class[Nginx::Service]
==> default: Info: Nginx::Resource::Location[awesome.dev-default]: Scheduling refresh of Class[Nginx::Service]
==> default: Info: Concat[/etc/nginx/sites-available/awesome.dev.conf]: Scheduling refresh of Class[Nginx::Service]
==> default: Notice: /Stage[main]/Main/Nginx_vhost[pal4qwae3alk]/Nginx::Resource::Vhost[awesome.dev]/File[awesome.dev.conf symlink]/ensure: created
==> default: Info: /Stage[main]/Main/Nginx_vhost[pal4qwae3alk]/Nginx::Resource::Vhost[awesome.dev]/File[awesome.dev.conf symlink]: Scheduling refresh of Service[nginx]
==> default: Info: Class[Nginx::Service]: Scheduling refresh of Service[nginx]
==> default: Error: /Stage[main]/Nginx::Service/Service[nginx]: Failed to call refresh: Could not restart Service[nginx]: Execution of '/etc/init.d/nginx restart' returned 1:
==> default: Error: /Stage[main]/Nginx::Service/Service[nginx]: Could not restart Service[nginx]: Execution of '/etc/init.d/nginx restart' returned 1:
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 1008.79 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
```

Config file:
```
---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '4096'
        cpus: '4'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.16.101
            forwarded_port:
                nlh1Bk3WRwuy:
                    host: '9437'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            bo3kjg9D3cZU:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - htop
        - curl
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        ix0f8oxbe7on:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                annozoeo3mam:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        pal4qwae3alk:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/web
            listen_port: '443'
            location: \.php$
            index_files:
                - app_dev.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            rewrite_to_https: '1'
            spdy: '1'
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Vilnius
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        ZR1NbzFZK4CW:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        ylFqOhSLHFQF:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: root
    adminer: 0
    databases:
        xGCxKrQ84fcZ:
            grant:
                - ALL
            name: awesome
            host: localhost
            user: awesome
            password: awesome
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

The problem is that it creates nginx vhost with location in wrong place:

```
  location ~ \.php$ {

    root  /var/www/web;
    try_files $uri $uri/ /app_dev.php /index.php$is_args$args$is_args$args;
    index  index.html index.htm index.php;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $request_filename;
    fastcgi_param APP_ENV dev;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
  }

server {
  listen       *:443 ssl spdy;

  server_name  awesome.dev www.awesome.dev;

  ssl on;

  ssl_certificate           /etc/nginx/awesome.dev.crt;
  ssl_certificate_key       /etc/nginx/awesome.dev.key;
  ssl_session_cache         shared:SSL:10m;
  ssl_session_timeout       5m;
  ssl_protocols             SSLv3 TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers               HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers on;
  client_max_body_size 1m;
    index  app_dev.php;

  access_log            /var/log/nginx/ssl-awesome.dev.access.log;
  error_log             /var/log/nginx/ssl-awesome.dev.error.log;


  location / {

    root  /var/www/web;
    try_files $uri $uri/ app_dev.php /index.php$is_args$args;
  }
  location ~ \.php$ {

    root  /var/www/web;
    try_files $uri $uri/ /app_dev.php /index.php$is_args$args$is_args$args;
    index  index.html index.htm index.php;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $request_filename;
    fastcgi_param APP_ENV dev;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    include fastcgi_params;
  }
  sendfile off;
}
```

The output then I run `/etc/init.d/nginx restart`
```
[09:12 PM]-[vagrant@packer-virtualbox-iso]-[/etc/nginx/sites-available]
$ sudo /etc/init.d/nginx restart
 * Restarting nginx nginx                                                                                                                                                                                                                                                     
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/sites-enabled/awesome.dev.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```
