### ISSUE TITLE
hostmanager not updating /etc/hosts file

### ISSUE THREAD

**Issue by toby-griffiths** [puphpet/puphpet#1349]
I've seen this working in the past fine, but it looks like the hostmanager plugin is not updating my hosts file any more.

Here's my vagrant plugins...
```
$ vagrant plugin list
vagrant-bindfs (0.3.2)
vagrant-hostmaster (0.6.2)
vagrant-share (1.1.4, system)
```

And my config.yaml file contains...
```
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - ssl
    vhosts:
        cib7ozpdvtfg:
            servername: tools-api.vm
            serveraliases:
                - tools-api.dev
            docroot: /var/www/tools-api/public
            port: '443'
            setenv:
                - 'APP_ENV dev'
            directories:
                6rvmctawwkue:
                    provider: directory
                    path: /var/www/tools-api/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: "# Required for mod_rewrite in .htaccess\r\nAllowOverride FileInfo\r\n\r\nOptions All -Indexes\r\n\r\nDirectoryIndex index.php index.shtml index.html\r\n \r\n<IfModule php5_module>\r\n    # For Development only!\r\n    php_flag display_errors On\r\n</IfModule>\r\n\r\n# Enable gzip compression\r\n<ifModule filter_module>\r\n    AddOutputFilterByType DEFLATE application/json\r\n</ifModule>"
            engine: php
            custom_fragment: "<IfModule rewrite_module>\r\n    RewriteEngine on\r\n\r\n    ## Throw a 403 (forbidden) status for non secure requests\r\n    RewriteCond %{SERVER_PORT} !^443$\r\n    RewriteRule ^.*$ - [L,R=403]\r\n</IfModule>"
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
```

Any ideas why this would not be working?  I do get prompted for the admin password, but I think this might be for the bindfs/NFS setup on each reload.
