### ISSUE TITLE
Multiple Apache VHosts in CentOS, fix for mod_rewrite not working

### ISSUE THREAD

**Issue by Mark-L6n** [puphpet/puphpet#1354]
When adding extra Apache Virtual Hosts in a CentOS box, *mod_rewrite* would work in the first VHost defined, but not the extra VHosts.  The result for a Drupal site was that the home page would load fine, but the 'clean urls' (e.g. *[domain]/web-page-name*) would return a 404 'not found' error.
The immediate cause was that the rewrite rules in `.htaccess` files were not being found, due to Apache `AllowOverride` settings of `None` rather than `All`.
However, on the puphpet Webserver page, `Allow Override` was set to `All` for each VHost.
Examining the httpd configuration files with `sudo egrep -ri "AllowOverride" /etc/httpd` showed a `.conf` file for the first defined VHost, but none of the extras.
Comparison of the the 1st and subsequent VHost entries in `config.yaml` showed 2 differences:
* `setenv: 'APP_ENV dev'` was not defined for the latter entries.  I don't think this was important; the difference was due to the `Environment Variables` section not containing `APP_ENV dev` by default, as the 1st VHost did.  You might want to make this a default for the extra VHosts, though, just to be consistent.
* `directories: path:` was blank in the latter VHosts.  In the first VHost entry, its value was the same as `docroot:`.  So, in the extra VHosts I copied the `docroot:` value to  `directories: path:` and ran `vagrant provision`.  This fixed the problem of httpd configuration files not existing for the extra VHosts.  Perhaps puphpet should automatically do the same thing.

However, another problem came up, which was that the httpd daemon would fail after trying to load a file `/etc/httpd/modules/mod_access_compat.so` that didn't exist.  Taking a hint from https://github.com/puphpet/puphpet/issues/1051 , I switched to `mod_php` from ` PHP-FPM` and finally, everything ran correctly.

```
config.yaml
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                MmuEdIjawYWd:
                    host: '5148'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            6MO1wyIPnbcT:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups:
        - [group]
    users:
        - '[user]:[group]'
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        0eemsdtfiyoc:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                w3kwtzkmz4fh:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        qy6vtng4h0z4:
            servername: drupal.v1
            serveraliases:
                - www.drupal.v1
            docroot: /var/www/d1
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                ezgnqhnmhipq:
                    provider: directory
                    path: /var/www/d1
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        4tkj6b79qthf:
            servername: drupal.v2
            serveraliases:
                - www.drupal.v2
            docroot: /var/www/d2
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                lqiqwyl2gpkd:
                    provider: directory
                    path: /var/www/d2
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        emyyl6xtgbyw:
            servername: drupal.v3
            serveraliases:
                - www.drupal.v3
            docroot: /var/www/d3
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                sre2yyyyujsf:
                    provider: directory
                    path: /var/www/d3
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        wdhcvkvanxx7:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - mbstring
        pear: {  }
        pecl:
            - pecl_http
    ini:
        session.save_path: /var/lib/php/session
        display_errors: Off
        error_log: /var/log/php_errors.log
        error_reporting: 32767
    timezone: America/New_York
    mod_php: '1'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        e7C3W6pZDnGu:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        INcXYWEb5ukj:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: [password]
    adminer: '1'
    databases:
        aVBPr0knFaER:
            grant:
                - ALL
            name: d1
            host: localhost
            user: [user]
            password: [password]
            sql_file: ''
        ZwZM4dLbJ8rV:
            grant:
                - ALL
            name: d2
            host: localhost
            user: [user]
            password: [password]
            sql_file: ''
        mDyKSVZBlwUE:
            grant:
                - ALL
            name: d3
            host: localhost
            user: [user]
            password: [password]
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
