### ISSUE TITLE
sync_folder owner/group keys named differently in Vagrantfile & Config

### ISSUE THREAD

**Issue by beporter** [puphpet/puphpet#1356]
The currently-generated `config.yaml` file defines the "owner" and "group" for synced folders using `owner` and `group` keys:

**pupgpet/config.yaml**:
```yaml
        synced_folder:
            tzXSeBhTGLj6:
                owner: www-data      # <-- Key name is "owner" here.
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
```

However, the bundled `Vagrantfile` refers to these keys as `sync_owner` and `sync_group`:

**Vagrantfile**:
```ruby
  data['vm']['synced_folder'].each do |i, folder|
    if folder['source'] != '' && folder['target'] != ''
      sync_owner = !folder['sync_owner'].nil? ? folder['sync_owner'] : 'www-data' # <-- Key name is "sync_owner" here?!
      sync_group = !folder['sync_group'].nil? ? folder['sync_group'] : 'www-data'
```

Unless I'm misreading something, I think this means that the config settings are **never** used and the default `www-data` user is always the account set as the owner of the shared folders inside the VM.
