### ISSUE TITLE
NFS mount timeout

### ISSUE THREAD

**Issue by clawfire** [puphpet/puphpet#1357]
So. I made a freshly generated config on PuPHPet, download it, extract and fire a `vagrant up`. 
I'm stuck with nfs mounting :
```
$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'puphpet/ubuntu1204-x64'. This can take some time...
==> default: Checking if box 'puphpet/ubuntu1204-x64' is up to date...
==> default: A newer version of the box 'puphpet/ubuntu1204-x64' is available! You currently
==> default: have version '1.2'. The latest is version '2.0'. Run
==> default: `vagrant box update` to update.
==> default: Verifying vmnet devices are healthy...
==> default: Pruning invalid NFS exports. Administrator privileges will be required...
Password:
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.108.160:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 9524
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
==> default: Installing NFS client...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.57.1:'/Users/thibault/github/clients/XXX/XXX /mnt/vagrant-eiZzmEyjF0gB

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: Connection timed out
```
So I tried to switch to `virtualbox`, same error. It's not a provider error I think so. Maybe more with NFS. but where ? ...

**My OS** : os X 10.10.2
**Vagrant** : 1.7.2
**Vagrant plugins** :
- hostmanager (1.2.2)
- vagrant-bindfs (0.4.0)
- vagrant-hosts (2.3.0)
- vagrant-omnibus (1.4.1)
- vagrant-share (1.1.3, system)
- vagrant-vmware-fusion (3.2.0)

**VmWare** : 7.1.0
**VirtualBox** : 4.3.20
**My `config.yaml`**
```yaml
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: vmware
        network:
            private_network: 192.168.57.101
            forwarded_port:
                ckMc9H05Kq17:
                    host: '9524'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            eiZzmEyjF0gB:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www/XXX
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - htop
        - vim
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - expires
        - ssl
    vhosts:
        kqifku4gazyv:
            servername: XXX.dev
            docroot: /var/www/XXX
            port: '443'
            setenv:
                - 'APP_ENV dev'
            directories:
                evdkaz0iirzv:
                    provider: directory
                    path: /var/www/ucb
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl: '1'
            ssl_cert: /var/www/XXX/server.crt
            ssl_key: /var/www/XXX/server.key
            ssl_chain: ''
            ssl_certs_dir: ''
        mwles0csmvxt:
            servername: ucb.dev
            docroot: /var/www/XXX
            port: '80'
            directories:
                7qndjtnct88j:
                    provider: directory
                    path: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: 'Redirect permanent / https://XXX.dev'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        d98zbrvfmdut:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Australia/Sydney
    mod_php: '1'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        cZbXTYnlM6L5:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        a0RTkC2EnodF:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: XXX
    adminer: '1'
    databases:
        wGDoDbV7h6bc:
            grant:
                - ALL
            name: XXX
            host: localhost
            user: XXX
            password: XXX
            sql_file: /var/www/XXX/XXX.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
