### ISSUE TITLE
SSL certs and Apache: Apache won't start

### ISSUE THREAD

**Issue by Danno040** [puphpet/puphpet#1379]
Ever since I started using SSL with Apache (in the `puphpet/ubuntu1404-x64` box), I've noticed that Apache wasn't starting when I upped the machine.

Given a config.yaml like this:
```yaml
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - expires
        - headers
        - mime_magic
        - rewrite
        - ssl
    vhosts:
        example:
            servername: example.com
            docroot: /vagrant/example.com/
            port: '443'
            engine: php
            custom_fragment: ''
            ssl: '1'
            ssl_cert: '/vagrant/ssl-certs/dev-box.crt'
            ssl_key: '/vagrant/ssl-certs/dev-box.key'
            ssl_chain: '/vagrant/ssl-certs/dev-rootCA.pem'
            ssl_certs_dir: '/vagrant/ssl-certs'
            priority: 20
```

When the VM boots, Apache will fail to start because the `/vagrant` directory isn't mounted yet.

I tried fixing this by changing the paths to point to directories inside the VM and using an `exec-once` to copy the certs. This caused provisioning to fail because the certs haven't been copied yet. However, once provisioned, Apache will start on boot just fine.

Is there an accepted way of getting around this issue?
