### ISSUE TITLE
.htaccess ignored on ssl vhost if directory has another non-ssl vhost

### ISSUE THREAD

**Issue by Norcoen** [puphpet/puphpet#1387]
When using mod_rewrite (TYPO3 with realurl) it only works with the non-ssl adress (commenting out the redirect to test it).

This is because, when generating the site_enabled config for apache, the ssl-vhost ist missing the directory configuration part, especially the "AllowOverride":
```
<Directory "/var/www/typo3">
    Options Indexes FollowSymlinks MultiViews
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>
```

Part of my config.yaml created by puphpet:
```
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - userdir
        - vhost_alias
        - ssl
    vhosts:
        frvus8ysbs9f:
            servername: test.local
            serveraliases:
                - www.test.local
            docroot: /var/www/typo3
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                cnu0mabsd5w6:
                    provider: directory
                    path: /var/www/typo3
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: 'Redirect permanent / https://www.test.local/'
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        fnie9xilc508:
            servername: test.local
            serveraliases:
                - www.test.local
            docroot: /var/www/typo3
            port: '443'
            setenv:
                - 'APP_ENV dev'
            directories:
                gorqeqqblyog:
                    provider: directory
                    path: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
```
