### ISSUE TITLE
Typo in nodes/Php.pp

### ISSUE THREAD

**Issue by moderndeveloperllc** [puphpet/puphpet#1405]
I can't find the right repo so I can clone and make a pull request. In the zipped file, go to nodes/Php.pp and look at line 126:
```each( $php_values['modules']['pear'] ) |$name| {```
should be 
```each( $php_values['modules']['pecl'] ) |$name| {```

as this code deals with PECL extensions, not PEAR classes.

**Comment by moderndeveloperllc** [comment]
@jtreminio Thanks. Even with that fix, I'm having an issue with the PECL extensions not generating .ini files. The .so files are created, but nothing is put into `/etc/php5/mods-available` nor aliases into `/etc/php5/fpm/conf.d`. The custom configs, xdebug, and module configs are doing fine - just PECL. Below is my config.yaml
```
---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: macbookdevbox.wpm
        memory: '512'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                sshPort:
                    host: '8056'
                    guest: '22'
                sslPort:
                    host: '4433'
                    guest: '443'
                httpPort:
                    host: '8080'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            websitesSync:
                owner: www-data
                group: www-data
                source: /Users/xxxxxxx/Sites
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - git
        - memcached
        - sendmail
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: false
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - deflate
        - expires
        - headers
        - ssl
    vhosts:
        inventory80:
            servername: xxx.xxx
            docroot: /var/www/xxx/xxx/src/public
            port: '80'
            directories:
                ccl3tdbzwekk:
                    provider: directory
                    path: /var/www/xxx/xxx/src/public
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: 'DirectoryIndex index.html'
            engine: php
            custom_fragment: 'Redirect permanent / https://xxx.xxx/'
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        inventory443:
            servername: xxx.xxx
            docroot: /var/www/xxx/xxx/src/public
            port: '443'
            setenv:
                - 'APPLICATION_ENVIRONMENT development'
            directories:
                cb0pq8v0ylyx:
                    provider: directory
                    path: /var/www/xxx/xxx/src/public
                    options:
                        - All
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: 'DirectoryIndex index.html'
            engine: php
            custom_fragment: "SSLProtocol all -SSLv2 -SSLv3\r\nSSLHonorCipherOrder on\r\nSSLCipherSuite FIPS\r\nHeader set Strict-Transport-Security \"max-age=31536000; includeSubDomains\""
            ssl: '1'
            ssl_cert: /etc/apache2/ssl/xxxx.crt
            ssl_key: /etc/apache2/ssl/xxxx.key
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        xkdxn340xqeo:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - imagick
            - mbstring
            - memcached
            - mysqlnd
        pear: {  }
        pecl:
            - timezonedb
            - mongo
            - uuid
            - yaml
            - igbinary
            - scrypt
    ini:
        display_errors: On
        error_reporting: E_ALL
        session.save_path: /var/lib/php/session
        asp_tags: Off
        short_open_tag: Off
    timezone: America/Chicago
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - bower
        - gulp
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: 'xxxxxxxxx'
    adminer: 0
    databases:
        xxxxx:
            grant:
                - ALL
            name: xxxxxx
            host: 127.0.0.1
            user: 'xxxxxxx'
            password: 'xxxxxxxxx'
            sql_file: '/vagrant/puphpet/sql/xxxxxxxxx.sql'
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases:
        a2EKjarDlucX:
            name: inventory
            user: inventoryUser
            password: xxxxxxxxxxxxx
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
