### ISSUE TITLE
config-custom.yaml override does not work in some cases

### ISSUE THREAD

**Issue by Zeromax** [puphpet/puphpet#1414]
Since #1370 the cool Feature is added to override some config stuff from the puphpet yaml.
This works like a charm, if the Option in the `config.yaml` exists.

like:
```yaml
vagrantfile-local:
    vm:
        box_url: 'special box url'
```
if the Option does not exist, the override does not work.
Original snippet `config.yaml`:
```yaml
mysql:
    install: '1'
    override_options: {  }
    root_password: root
    adminer: 0
    databases: {  }
```

the override `config-custom.yaml`:
```yaml
mysql:
    override_options:
        mysqld:
            datadir: '/vagrant/mysql-data'
```
