### ISSUE TITLE
Changing Apache user and group to "apache" on CentOS

### ISSUE THREAD

**Issue by philbates35** [puphpet/puphpet#1416]
On CentOS, by default Apache runs with user "apache" and group "apache". This is how my production server is set up, and I would like to replicate this using Puphpet.

I changed the apache section of the config.yaml to the following:
```
apache:
    install: '1'
    settings:
        user: apache
        group: apache
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts: {  }
    mod_pagespeed: 0
```

And the synced_folder section:

```
synced_folder:
            6URdMgj5A7P1:
                sync_owner: vagrant
                sync_group: apache
                source: 'C:\www'
                target: /home/www
                sync_type: default
                rsync:
                    auto: 'false'
```

However, I get an error on a fresh `vagrant up`:

```
mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group apache | cut -d: -f3`,d
mode=775,fmode=764 6URdMgj5A7P1 /home/www
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g apache`,dmode=775,fmode=764 6U
RdMgj5A7P1 /home/www

The error output from the last command was:

id: apache: No such user
gid= requires an argument (i.e. gid==<arg>)
```

The user "apache" isn't being created, and therefore when the "apache" group is made the group owner of the shared folder, it fails.

As a workaround, I thought that I could manually create the "apache" user in the `users_groups` section of `config.yaml` but that doesn't seem like the best solution. In fact, after a quick look through the source code I can see many hard coded references to "www-data", rather than pulling the values from the selected webserver's user and group configuration in `config.yaml`.

I believe all RedHat derived OS's Apache uses "apache" as user and group so some flexibility here would be great.

My full `config.yaml` for reference:

```
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '4096'
        cpus: '4'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                QlTb5Q9vmFrp:
                    host: '5077'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            6URdMgj5A7P1:
                sync_owner: vagrant
                sync_group: apache
                source: 'C:\www'
                target: /home/www
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - mercurial
        - htop
        - mc
        - php-xml
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: apache
        group: apache
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts: {  }
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts: {  }
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mbstring
            - mcrypt
        pear: {  }
        pecl:
            - memcached
            - pecl_http
            - xmlReader
            - xmlwriter
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        html_errors: On
        short_open_tag: On
        max_execution_time: '360'
        post_max_size: 100M
        upload_max_filesize: 100M
        max_input_vars: '10000'
        memory_limit: 2048M
        sendmail_path: /usr/bin/catchmail
        suhosin.post.max_value_length: '67108864'
        suhosin.post.max_vars: '10000'
        suhosin.request.max_vars: '10000'
    timezone: Europe/London
    mod_php: '1'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.remote_autostart: '0'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_host: 10.0.2.2
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - gulp
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: '123'
    adminer: '1'
    databases: {  }
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
