### ISSUE TITLE
Errors shown within Windows but not in Linux or OSX

### ISSUE THREAD

**Issue by timmigrant** [puphpet/puphpet#1417]
Hi,

Our company's IT is separated in two departments with each team lead defining the equipment used within each department.  My team works exclusively with Mac's and Vagrant / PuPHPet has functioned well, however, now that we are bringing in another department on Windows, we are experiencing challenges to get a single environment to work on both teams.

Here is a quote of what the Windows users are seeing:

> : command not foundnt/puphpet/shell/os-detect.sh: line 2:
> : command not foundnt/puphpet/shell/os-detect.sh: line 9:
> '=> default: grep: invalid option -- '
> ==> default: Usage: grep [OPTION]... PATTERN [FILE]...
> ==> default: Try `grep --help' for more information.
> ==> default: /vagrant/puphpet/shell/os-detect.sh: line 15: syntax error near unexpected token `elif'
> '=> default: /vagrant/puphpet/shell/os-detect.sh: line 15: `elif [ -f '/etc/redhat-release' ]; then
> : command not foundnt/puphpet/shell/os-detect.sh: line 2:
> : command not foundnt/puphpet/shell/os-detect.sh: line 9:
> '=> default: grep: invalid option -- '
> ==> default: Usage: grep [OPTION]... PATTERN [FILE]...
> ==> default: Try `grep --help' for more information.
> ==> default: /vagrant/puphpet/shell/os-detect.sh: line 15: syntax error near unexpected token `elif'
> '=> default: /vagrant/puphpet/shell/os-detect.sh: line 15: `elif [ -f '/etc/redhat-release' ]; then
> : command not foundnt/puphpet/shell/os-detect.sh: line 2:
> : command not foundnt/puphpet/shell/os-detect.sh: line 9:
> '=> default: grep: invalid option -- '
> ==> default: Usage: grep [OPTION]... PATTERN [FILE]...
> ==> default: Try `grep --help' for more information.
> ==> default: /vagrant/puphpet/shell/os-detect.sh: line 15: syntax error near unexpected token `elif'
> '=> default: /vagrant/puphpet/shell/os-detect.sh: line 15: `elif [ -f '/etc/redhat-release' ]; then

and 

> ' in file /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Server.pp at > line 49:73
> ' in file /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Server.pp at line 50:56
> ' in file /tmp/vagrant-puppet/modules-> ed24075989631843f626812b7d565632/puphpet/manifests/apache/repo/centos.pp at line 8:24
' in file /tmp/vagrant-puppet/modules-ed24075989631843f626812b7d565632/puphpet/manifests/apache/repo/centos.pp at line 9:55

**Comment by timmigrant** [comment]
```
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                nZDW377X3qqz:
                    host: '8750'
                    guest: '8751'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            kK14SODOmqEs:
                owner: www-data
                group: www-data
                source: Z:\bloomex.ca\projects\bloomex.ca\repos\www.bloomex.ca\
                target: /var/www/development
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - php-soap
users_groups:
    install: '1'
    groups:
        - developer
    users:
        - developer
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        development80:
            servername: www.development.local
            docroot: /var/www/development
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                6yhodtujiq9s:
                    provider: directory
                    path: /var/www/development
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        development443:
            servername: www.development.local
            docroot: /var/www/development
            port: '443'
            setenv:
                - 'APP_ENV dev'
            directories:
                6yhodtujiq9s:
                    provider: directory
                    path: /var/www/development
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        h1ssmuniejdz:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '0'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - mbstring
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        session.save_path: '/var/lib/php/session'
        engine: On
        short_open_tag: Off
        asp_tags: Off
        precision: 14
        y2k_compliance: On
        output_buffering: 4096
        zlib.output_compression: Off
        implicit_flush: Off
        serialize_precision: 100
        allow_call_time_pass_reference: Off
        safe_mode: Off
        safe_mode_gid: Off
        safe_mode_allowed_env_vars: PHP_
        safe_mode_protected_env_vars: LD_LIBRARY_PATH
        expose_php: On
        max_execution_time: 30     
        max_input_time: 60
        memory_limit: 128M
        error_reporting: 'E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED'
        display_startup_errors: On
        log_errors: On
        log_errors_max_len: 1024
        ignore_repeated_errors: Off
        ignore_repeated_source: Off
        report_memleaks: On
        track_errors: On
        html_errors: On
        variables_order: "GPCS"
        request_order: "GP"
        register_globals: Off
        register_long_arrays: Off
        register_argc_argv: Off
        auto_globals_jit: On
        post_max_size: 8M
        magic_quotes_gpc: Off
        magic_quotes_runtime: Off
        magic_quotes_sybase: Off
        default_mimetype: "text/html"
        enable_dl: Off
        file_uploads: On
        upload_max_filesize: 2M
        allow_url_fopen: On
        allow_url_include: Off
        default_socket_timeout: 60
        date.timezone: 'America/Toronto'
        define_syslog_variables : Off
        SMTP: localhost
        smtp_port: 25
        sendmail_path: '/usr/sbin/sendmail -t -i'
        mail.add_x_header: On
        sql.safe_mode: Off
        odbc.allow_persistent: On
        odbc.check_persistent: On
        odbc.max_persistent: -1
        odbc.max_links: -1
        odbc.defaultlrl: 4096
        odbc.defaultbinmode: 1
        mysql.allow_persistent: On
        mysql.max_persistent: -1
        mysql.max_links: -1
        mysql.connect_timeout: 60
        mysql.trace_mode: Off
        mysqli.max_links: -1
        mysqli.default_port: 3306
        mysqli.reconnect: Off
        pgsql.allow_persistent: On
        pgsql.auto_reset_persistent: Off
        pgsql.max_persistent: -1
        pgsql.max_links: -1
        pgsql.ignore_notice: 0
        pgsql.log_notice: 0
        sybct.allow_persistent: On
        sybct.max_persistent: -1
        sybct.max_links: -1
        sybct.min_server_severity: 10
        sybct.min_client_severity: 10
        bcmath.scale: 0
        session.save_handler: files
        session.use_cookies: 1
        session.use_only_cookies: 1
        session.name: PHPSESSID
        session.auto_start: 0
        session.cookie_lifetime: 0
        session.cookie_path: /
        session.serialize_handler: php
        session.gc_probability: 1
        session.gc_divisor: 1000
        session.gc_maxlifetime: 1440
        session.bug_compat_42: Off
        session.bug_compat_warn: Off
        session.entropy_length: 0
        session.cache_limiter: nocache
        session.cache_expire: 180
        session.use_trans_sid: 0
        session.hash_function: 0
        session.hash_bits_per_character: 5
        url_rewriter.tags: "a=href,area=href,frame=src,input=src,form=fakeentry"
        mssql.allow_persistent: On
        mssql.max_persistent: -1
        mssql.max_links: -1
        mssql.min_error_severity: 10
        mssql.min_message_severity: 10
        mssql.compatability_mode: Off
        mssql.secure_connection: Off
        tidy.clean_output: Off
        soap.wsdl_cache_enabled: 1
        soap.wsdl_cache_dir: "/tmp"
        soap.wsdl_cache_ttl: 86400
        mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: 'password123'
    adminer: 0
    databases:
        qpP2xpNBugNP:
            grant:
                - ALL
            name: BLCA_dev
            host: localhost
            user: BLCA_dev
            password: password123
            sql_file: /var/www/__vagrant/mysql/development-build.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
