### ISSUE TITLE
Nfs sync folder and low access

### ISSUE THREAD

**Issue by iLoLo21** [puphpet/puphpet#1439]
Hi

When I try to do a 'cd /my/nfs/sync/folder' on my vagrant, the command is very low to return a response (10/15sec).
If I try to do a ls command : ''ls /my/nfs/sync/folder'' the response time is good.
I have try the same configuration with native vagrant file (nfs, git..) and no problem.
I have try with rsync (instead nfs) and no problem.

```
---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: 'vagrant-test-2'
        cpuexecutioncap: 50%
        memory: '4096'
        cpus: '3'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                36RMusquf878:
                    host: '9513'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    cpuexecutioncap: 50
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: app/config/puphpet/puppet
                manifest_file: social.pp
                module_path: app/config/puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/app/config/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            socialmoov:
                sync_owner: vagrant
                sync_group: www-data
                source: ./
                target: /var/www/test
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: true
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - make
        - zsh
        - memcached
        - php5-memcache
        - php5-dev
        - php5-curl
        - php5-json
        - php5-gd
        - php5-idn
        - php5-imagick
        - php5-imap
        - php5-mcrypt
        - php5-memcache
        - php5-pspell
        - php5-recode
        - php5-tidy
        - php5-xmlrpc
        - php5-xsl
        - php5-common
        - php5-intl
        - php5-mongo
        - php5-apcu
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        test:
            servername: test.dev
            serveraliases:
                - local.dev
            docroot: /var/www/test/web
            port: '80'
            directoryindex: app_dev.php
            directories:
                test:
                    provider: directory
                    path: /var/www/test/web
                    options:
                        - Indexes
                        - FollowSymlinks
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: '128k'
        proxy_buffers: '4256k'
        realpath_cache_size: '4096k'
        realpath_cache_ttl: 7200
    upstreams: {  }
    vhosts:
        zkjlwydew9ys:
            proxy: ''
            server_name: test.dev
            server_aliases:
                - local.dev
            www_root: /var/www
            listen_port: '80'
            location: \.php$
            index_files:
                - app.php
                - app_dev.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
            - mongo-1.5.8
            - memcached
    ini:
        display_errors: On
        error_reporting: 'E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED'
        session.save_path: /var/lib/php/session
        memory_limit: 2048M
        upload_max_filesize: 1050M
        post_max_size: 1050M
        max_execution_time: 999
        max_input_vars: 2000
    timezone: Europe/Paris
    mod_php: 1
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
```

What is wrong with puphpet configuration and nfs sync folder  !?

Thank you :)
