### ISSUE TITLE
PHP not being parsed with PHP-FPM on Apache Vhost

### ISSUE THREAD

**Issue by nmeirik** [puphpet/puphpet#1445]
Using the following config.yaml file, PHP files for the given Apache vhost are not parsed, but rather output as plain text. Reviewing a PuPHPet download I created a few weeks ago, I can see that a ProxyPassMatch line was added to the vhosts created by the provisioning:

`ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/path/to/docroot/$1`

...which seemingly passes all PHP files along to fcgi, but for my most recently download, a ProxyPassMatch line is no longer added when provisioning. Has there been any recent commits to affect this behaviour?

```
---
vagrantfile-aws:
    vm:
        box: aws
        hostname: master
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        provider:
            aws:
                access_key_id: REMOVED
                secret_access_key: REMOVED
                keypair_name: REMOVED
                ami: ami-e34dae94
                region: eu-west-1
                instance_type: m1.medium
                security_groups:
                    - REMOVED
                tags:
                    Source: Puphpet
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder: {  }
    ssh:
        host: null
        port: null
        private_key_path: REMOVED
        username: admin
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - zsh
        - git-flow
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - vhost_alias
    vhosts: 
        ezdemo.eirik.dev.nmcloud.no:
            servername: ezdemo.eirik.dev.nmcloud.no
            docroot: /home/eirik/www/ezdemo/web
            docroot_owner: www-data
            docroot_group: www-data
            port: '80'
            directories:
                dir1:
                    path: /home/eirik/www/ezdemo/web
                    options: 'FollowSymLinks'
                    allow_override: 'All'
                    allow: 'from All'
            directoryindex: index.php
            setenv:
                - 'ENVIRONMENT prod'
                - 'USE_HTTP_CACHE 0'
                - 'APC_CLASSLOADER_PREFIX ezdemo'
                - 'USE_APC_CLASSLOADER 0'
            rewrites:
                - {rewrite_rule: '^/api/[^/]+/v1/ /index_rest.php [L]'}
                - {rewrite_rule: '^/var/([^/]+/)?storage/images(-versioned)?/.* - [L]'}
                - {rewrite_rule: '^/var/([^/]+/)?cache/(texttoimage|public)/.* - [L]'}
                - {rewrite_rule: '^/design/[^/]+/(stylesheets|images|javascript|fonts)/.* - [L]'}
                - {rewrite_rule: '^/share/icons/.* - [L]'}
                - {rewrite_rule: '^/extension/[^/]+/design/[^/]+/(stylesheets|flash|images|lib|javascripts?)/.* - [L]'}
                - {rewrite_rule: '^/packages/styles/.+/(stylesheets|images|javascript)/[^/]+/.* - [L]'}
                - {rewrite_rule: '^/packages/styles/.+/thumbnail/.* - [L]'}
                - {rewrite_rule: '^/var/storage/packages/.* - [L]'}
                - {rewrite_rule: '^/favicon\.ico - [L]'}
                - {rewrite_rule: '^/robots\.txt - [L]'}
                - {rewrite_rule: '^/w3c/p3p\.xml - [L]'}
                - {rewrite_rule: '^/sitemap\.xml - [L]'}
                - {rewrite_rule: '^/bundles/ - [L]'}
                - {rewrite_rule: '^/css/.*\.css - [L]'}
                - {rewrite_rule: '^/js/.*\.js - [L]'}
                - {rewrite_rule: '.* /index.php'}
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        ixqq97zw6kuu:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - imagick
            - curl
            - xsl
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Oslo
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: FT6XGE9mFmyqic
    adminer: 0
    databases: {  }
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
