### ISSUE TITLE
[mysql] ERROR 1045 (28000): Access denied for user 'vagrant'@'localhost'

### ISSUE THREAD

**Issue by loostro** [puphpet/puphpet#1457]
Running symfony2 in a box, when the box is ready and startup scripts fire, im getting:

`SQLSTATE[HY000] [1045] Access denied for user 'vagrant'@'localhost' (using password: YES)`

My config is:

```yaml
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: vagrant
        override_options: {  }
    adminer: 0
    users:
        pcyjz7Pjizom:
            name: vagrant
            password: vagrant
    databases:
        JVEggOLkuOUU:
            name: vagrant
            sql: ''
    grants:
        OXfaFj0tqujX:
            user: vagrant
            table: '*.*'
            privileges:
                - ALL
```

The problem seems to be caused by 

```console
$ mysql -u root -pvagrant -e "SELECT user,host,password from mysql.user"
Warning: Using a password on the command line interface can be insecure.
+------------------+----------------------------------+-------------------------------------------+
| user             | host                             | password                                  |
+------------------+----------------------------------+-------------------------------------------+
| root             | localhost                        | *04E6E1273D1783DF7D57DC5479FE01CFFDFD0058 |
| root             | packer-virtualbox-iso-1422601639 |                                           |
| root             | 127.0.0.1                        |                                           |
| root             | ::1                              |                                           |
|                  | localhost                        |                                           |
|                  | packer-virtualbox-iso-1422601639 |                                           |
| debian-sys-maint | localhost                        | *ADB4FD42A0DB31BA6715D0FAC40F2D237CB83A8E |
| vagrant          | %                                | *04E6E1273D1783DF7D57DC5479FE01CFFDFD0058 |
+------------------+----------------------------------+-------------------------------------------+
```

For some reason, the user is created with `%` host, which does not allow connecting.

```console
$ mysql -u vagrant -pvagrant
Warning: Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'vagrant'@'localhost' (using password: YES)
```

Loggin in as root works.. the password is the same.. the only diffrence is the host. So I changed it:

```console
$ mysql -u root -pvagrant -e "UPDATE mysql.user SET Host='localhost' WHERE User='vagrant'; FLUSH PRIVILEGES;"
```

And TADAA! Now I can log in as `vagrant`.

### How to make PuPHPet create the user with `localhost` host in the first place?
