### ISSUE TITLE
rsync problem on digital-ocean plugin?

### ISSUE THREAD

**Issue by agungsijawir** [puphpet/puphpet#1502]
Hello,

I just tried to create new droplet on d-o using puphpet after found this tool is quite interesting and save my time to develop and work. I follows Digital Ocean Instructions on the page and found this error:
```
ThinkPad T430@THINKPADT430 /d/vagrant/digital_ocean/AntVCG
$ vagrant up
Bringing machine 'default' up with 'digital_ocean' provider...
==> default: Using existing SSH key: Vagrant_xxxx
==> default: Creating a new droplet...
==> default: Assigned IP address: ***.***.***.***
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:********************
Enter passphrase for c:/Users/ThinkPad T430/.ssh/id_rsa:********************
==> default: Creating user account: ********************...
==> default: Rsyncing folder: /cygdrive/d/vagrant/digital_ocean/AntVCG/ => /var/www...
Enter passphrase for key 'c:/Users/ThinkPad T430/.ssh/id_rsa':
Enter passphrase for key 'c:/Users/ThinkPad T430/.ssh/id_rsa':
There was an error when attemping to rsync a share folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/vagrant/digital_ocean/AntVCG/
Guest path: /var/www
Error: Warning: Permanently added '***.***.***.***' (RSA) to the list of known hosts.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.1]
```
after that, the program stop itself. I check my digital-ocean account, and the droplet was created. tried to login via `vagrant ssh`, i can connect and access ssh, but no application (i.e. nginx, mysql, php, etc) installed. It is just "blank" droplet.

i use vagrant 1.7.2 and rysnc manually download from this: `https://www.itefix.net/dl/cwRsync_5.4.1_x86_Free.zip`. And use the following shells gave the same result:
- git bash
- cmd.exe
- windows powershell

and this is my `config.yaml` contents:
```yaml
---
vagrantfile-digital_ocean:
    vm:
        box: digital_ocean
        hostname: ***
        network:
            private_network: ***
            forwarded_port: {  }
        provider:
            digital_ocean:
                image: ubuntu-14-10-x64
                region: sgp1
                size: 512mb
                token: ***
                ssh_key_name: ***
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            IsfynlgiKHfz:
                source: ./
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        username: ***
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
users_groups:
    install: '1'
    groups:
        - ***
    users:
        - '***:***'
        - '***:***'
        - '***:***'
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        p6obz4kfgrb9:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            directories:
                y2j8yqntmh6c:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        q33zyrztlkmf:
                            provider: filesmatch
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 256k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        o3zlrti8v90n:
            proxy: ''
            server_name: ***
            server_aliases:
                - www.***
            www_root: /var/www/***
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 8m
            locations:
                ztlvrz9zlqgv:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                lzwipryo5phr:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
            ssl: '1'
            ssl_cert: /root/ssl/***.crt
            ssl_key: /root/ssl/***.key
            ssl_port: '443'
            rewrite_to_https: '1'
            spdy: '0'
        g2ee8lfjsmof:
            proxy: ''
            server_name: ***
            server_aliases:
                - www.***
            www_root: /var/www/***
            listen_port: '80'
            index_files:
                - index.php
                - index.html
                - index.htm
            client_max_body_size: 8m
            locations:
                izf6d9pupyd6:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
        aqziowgyxach:
            proxy: ''
            server_name: ***
            server_aliases:
                - www.***
            www_root: /var/www/***
            listen_port: '80'
            index_files:
                - index.php
                - index.html
            client_max_body_size: 8m
            locations:
                ennyqcq2uqye:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
php:
    install: '1'
    settings:
        version: '55'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - fpm
            - gd
            - imagick
            - memcache
            - mysql
            - mysqlnd
            - memcached
            - mbstring
            - sqlite
            - xmlrpc
            - cgi
            - common
            - geoip
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: ASIA
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '***'
        override_options: {  }
    adminer: 0
    users:
        cM6JEzndWWUf:
            name: ***
            password: ***
        jlqbt80yr2Ee:
            name: ***
            password: ***
        605YD7IWP9gl:
            name: ***
            password: '***'
    databases:
        IlZU00E9FAW0:
            name: ***
            sql: ''
        0dTNtCJF57lj:
            name: ***
            sql: ''
        pyPEBkQK46wy:
            name: ***
            sql: ''
    grants:
        E2JJU6s0WKId:
            user: ***
            table: ***
            privileges:
                - ALL
        K0YAKIX4C4GT:
            user: ***
            table: ***
            privileges:
                - ALL
        HVabk1TkgA7T:
            user: ***
            table: ***
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
