### ISSUE TITLE
PHP under apache's Alias folder does not work due to fastcgi proxy

### ISSUE THREAD

**Issue by akireikin** [puphpet/puphpet#1507]
In my `config.yaml` I added:
```
apache:
    vhosts:
        yhfguydhiu:
            # ...
            docroot: /var/www/project/frontend
            # ...
            aliases:
                alias: /api
                path: /var/www/project/api/web
```
It works fine, but php in this folder does not work. I made an investigation and found this line in vhost config:
```
ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/project/frontend/$1
```
PuPHPet has dropped support for mod_php. So I forced to use fastcgi. Any ideas?

**Comment by akireikin** [comment]
Worked around the issue by adding:
```
apache:
    vhosts:
        yhfguydhiu:
            # ...
            custom_fragment: 'ProxyPassMatch ^/api/index.php$ fcgi://127.0.0.1:9000/var/www/project/backend/web/index.php'
```
