### ISSUE TITLE
WP CLI has some bug

### ISSUE THREAD

**Issue by shivapoudel** [puphpet/puphpet#1522]
![capture-2](https://cloud.githubusercontent.com/assets/3774827/7147460/d7e8d832-e31a-11e4-81bb-3734adce9b0b.PNG)

```yml
wpcli:
    install: '1'
    version: v0.18.0
```
