### ISSUE TITLE
PHP Settings not archiving correctly

### ISSUE THREAD

**Issue by rcuddy** [puphpet/puphpet#1546]
To Reproduce:
  * Navigate to https://puphpet.com
  * Select Deploy Target: Local - Ubuntu 14.04 LTS
  * Web Servers - Install Apache
  * PHP - Set to 5.5
  * Add "imagick" to PHP Modules
  * Select a PEAR Module - eg, Console_GetoptPlus
  * See PECL Modules already has pecl_http
  * Add PECL Modules: eg, redis
  * Create Archive, inspect config.yaml

PHP config file has reset to version: 56, pear: and pecl: options are empty.
```
php:
    install: '1'
    settings:
        version: '56'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - imagick
        pear: {  }
        pecl: {  }
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
```
![screen shot 2015-04-20 at 3 36 51 pm](https://cloud.githubusercontent.com/assets/4494839/7224266/1c1b562c-e773-11e4-9c94-0f72b895b1cf.png)
