### ISSUE TITLE
Getting XDEBUG dependency error with most recent version of PuPHPet

### ISSUE THREAD

**Issue by blazingarrow** [puphpet/puphpet#1550]
Two weeks ago everything did work finde. Today I've generated a new build and I've following error with Xdebug.

```Xdebug requires Zend Engine API version 220100525. The Zend Engine API version 220131226 which is installed, is newer.```

```
vagrantfile:
    target: local
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_351qjisb6coo:
                    host: '7905'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_vdb0fc47u4fq:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - libfontconfig1
        - memcached
users_groups:
    install: '1'
    groups: {  }
    users:
        - swissredcross
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts: {  }
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - deflate
        - expires
        - headers
        - proxy_fcgi
        - proxy
        - rewrite
        - vhost_alias
    vhosts:
        av_rnu0bd5903cl:
            servername: redcross.ch.dev
            serveraliases:
                - www.redcross.ch.dev
                - www.pflege-entlastung.ch.dev
                - www.proche-aidant.ch.dev
                - www.toolkit-freiwilligenarbeit.ch.dev
                - www.toolkit-benevolat.ch.dev
                - www.magazin-humanite.ch.dev
                - www.rivista-humanite.ch.dev
            docroot: /var/www/redcross.ch
            port: '443'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_6rcjbazopdte:
                    path: /var/www/redcross.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_aorit6xocvc7:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_fd0edv97fqzw:
            servername: migesplus.ch
            serveraliases:
                - www.migesplus.ch.dev
                - www.migesexpert.ch.dev
            docroot: /var/www/migesplus.ch
            port: '80'
            setenv:
                - 'DATABASE_USER migesplus'
                - 'DATABASE_PASSWORD migesCumulus'
                - 'DATABASE_HOST localhost'
                - 'DATABASE_DB migesplus'
                - 'TYPO3_INSTALL dfcb7dfde529eef7bc7aa22e6cb39238'
                - 'TYPO3_ENCRYPTIONKEY dfcb7dfde529eef7bc7aa22e6cb39238'
                - 'TYPO3_DISPLAY_ERRORS 1'
                - 'TYPO3_MAIL_TRANSPORT mbox'
                - 'ENVIRONMENT dev'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_sakcfyswsgv4:
                    path: /var/www/migesplus.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_qmmu35rbbtna:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_swhf19kr4yho:
            servername: 2xweihnachten.ch
            serveraliases:
                - www.2xweihnachten.ch.dev
                - www.2xnoel.ch.dev
                - www.2xchristmas.dev
                - www.2xnatale.ch.dev
                - www.2xnadal.ch.dev
            docroot: /var/www/2xweihnachten.ch
            port: '443'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_l8eoj9clfr4a:
                    path: /var/www/2xweihnachten.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_w9cxggxxzlwl:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_db5s03eu4jmt:
            servername: redcrossheroes.ch
            serveraliases:
                - www.redcrossheroes.ch.dev
            docroot: /var/www/redcrossheroes.ch
            port: '80'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_uzyd5p1dfr91:
                    path: /var/www/redcrossheroes.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5yhn1e2jfi03:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_ybqdl29ls1n9:
            servername: code-standards.dev
            serveraliases:
                - www.code-standards.dev
            docroot: /var/www/code-standards
            port: '80'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_4mvqy044mwtq:
                    path: /var/www/code-standards
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_h04chzktjzba:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - imagick
            - curl
            - gd
            - geoip
            - mbstring
            - memcache
            - mysql
            - xmlrpc
            - fpm
        pear: {  }
        pecl: {  }
    ini:
        display_errors: On
        error_reporting: 'E_ALL & ~E_STRICT'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        memory_limit: 512M
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '1'
    version: null
ruby:
    install: '1'
    versions:
        rv_m65v5l85i29c:
            bundler: '1'
            version: ''
            gems:
                - sass
                - bundler
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - grunt
        - grunt-cli
        - grunt-init
        - grunt-grunticon
        - grunt-contrib-sass
        - grunt-contrib-jshint
        - grunt-contrib-concat
        - grunt-contrib-watch
        - grunt-contrib-connect
        - grunt-contrib-copy
        - grunt-autoprefixer
        - grunt-contrib-clean
        - grunt-postcss
        - grunt-svgmin
        - autoprefixer-core
        - node-sass
        - fontfaceobserver
        - criticalcss
        - bower
        - assemble
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: 17Juli18166
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_4owwzhdfu00e:
            name: migesplus
            password: migesCumulus
        mysqlnu_34a9y6rak4i9:
            name: redcross
            password: 17Juli1866
        mysqlnu_pw16gh02crm2:
            name: 2xweihnachten
            password: 17Juli1866
        mysqlnu_lxl6hq0uwfy2:
            name: redcrossheroes
            password: 17Juli1866
    databases:
        mysqlnd_7eatj8fn6tbo:
            name: redcross
            sql: ''
        mysqlnd_v2w8rabum4hl:
            name: migesplus
            sql: ''
        mysqlnd_cjksmm1cdi29:
            name: 2xweihnachten
            sql: ''
        mysqlnd_6ibgswlwonto:
            name: redcrossheroes
            sql: ''
    grants:
        mysqlng_5i8psq7o352z:
            user: redcross
            table: 'redcross.*'
            privileges:
                - ALL
        mysqlng_5j2sc7w6ouew:
            user: migesplus
            table: 'migesplus.*'
            privileges:
                - ALL
        mysqlng_11dcqto66g5s:
            user: 2xweihnachten
            table: '2xweihnachten.*'
            privileges:
                - ALL
        mysqlng_d7ax145ztpvh:
            user: redcrossheroes
            table: 'redcrossheroes.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '1'
    settings:
        version: 4.10.2
        port: '8080'
```
