### ISSUE TITLE
Nginx using rewrite parametr

### ISSUE THREAD

**Issue by cr0ss** [puphpet/puphpet#1563]
I've have multiple drupal sites in one folder, here's  common **drupal + nginx config** http://wiki.nginx.org/Drupal

In my case it's:
```
location @rewrite {
  # Drupal in a subdirectory
  rewrite ^/([^/]*)/(.*)(/?)$ /$1/index.php?q=$2&$args;
}
```

Config looks as following:
```
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        zqzkuiykwb8w:
            proxy: ''
            server_name: dev
            server_aliases:
                - www.dev
            www_root: /var/www
            listen_port: '80'
            index_files:
                - index.php
                - index.html
                - index.htm
            client_max_body_size: 1m
            locations:
                s3s7qgqcdvw1:
                    location: /
                    try_files:
                        - $uri
                        - "@rewrite"
                s3s7qgqcdvw2:
                    location: "@"rewrite"
                    rewrite: "^/([^/]*)/(.*)(/?)$ /$1/index.php?q=$2&$args"
                s3s7qgqcdvw7:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
```
Looks like I'm close to correct configuration, but still getting error provisioning it to vagrant:
```
DEBUG ssh: stderr: Error: Invalid parameter rewrite on node packer-virtualbox-iso-1422601639
 INFO interface: info: Error: Invalid parameter rewrite on node packer-virtualbox-iso-1422601639
 INFO interface: info: ==> default: Error: Invalid parameter rewrite on node packer-virtualbox-iso-1422601639
==> default: Error: Invalid parameter rewrite on node packer-virtualbox-iso-1422601639
DEBUG ssh: stderr: 
```

I tried different ways to settle it, but no luck so far.
