### ISSUE TITLE
changing ownership of ‘/var/www’: Operation not permitted

### ISSUE THREAD

**Issue by jkenneydaniel** [puphpet/puphpet#1565]
I'm receiving the following error:

```
==> default: Notice: /Stage[main]/Main/Exec[Create apache webroot]/returns: chown: changing ownership of ‘/var/www’: Operation not permitted
==> default: Error: mkdir -p /var/www &&                 chown root:www-data /var/www &&                 chmod 775 /var/www &&                 touch /.puphpet-stuff/apache-webroot-created returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Exec[Create apache webroot]/returns: change from notrun to 0 failed: mkdir -p /var/www &&                 chown root:www-data /var/www &&                 chmod 775 /var/www &&                 touch /.puphpet-stuff/apache-webroot-created returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]/ensure: created
==> default: Info: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]: Scheduling refresh of Service[httpd]
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_80]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_80]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_443]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_443]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Apache::Service/Service[httpd]: Triggered 'refresh' from 3 events
==> default: Notice: /Stage[main]/Main/File[/var/www/html/index.html]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/File[/var/www/html/index.html]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/awesome @ key av_xopquzochr9z]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[exec mkdir -p /var/www/awesome @ key av_xopquzochr9z]: Skipping because of failed dependencies
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 572.92 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

With the following config file:

```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: vmware_fusion
        network:
            private_network: 192.168.57.101
            forwarded_port:
                vflnp_hoczedwst28b:
                    host: '6182'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_hpkugcd1v00x:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_t5qstw6qxd2z:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_wnwd2o9mtdat:
                    location: /
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_ybpf8tvw8s9q:
                    location: '~ \.php$'
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - headers
        - expires
        - pagespeed
        - deflate
    vhosts:
        av_xopquzochr9z:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_uc79dmylr2cr:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_bl1y4c6doc4g:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - imap
            - mbstring
            - memcache
            - mysql
        pear: {  }
        pecl: {  }
    ini:
        display_errors: On
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        error_reporting: E_ALL
    fpm_ini:
        pid: /run/php-fpm.pid
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_blnqk23u1r2n:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: 6.3.0
drush:
    install: '0'
    version: null
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_ypzalxn8kvxx:
            name: awesome
            password: awesome
    databases:
        mysqlnd_ffgnbppz98im:
            name: awesome
            sql: ''
    grants:
        mysqlng_bsyc0uetlzey:
            user: awesome
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
