### ISSUE TITLE
PHP Session Save Path not writable

### ISSUE THREAD

**Issue by cricciuto** [puphpet/puphpet#1583]
I was trying to run an older Zend application in a newly created vagrant box when I initially loaded it I got a Zend error saying permission denied when trying to start a PHP session.

In my search to correct this the "right way" (not just chown and chmod it so it works) I found a couple of bugs were fixed that supposedly made this issue go away but it is still happening for me.

The relevant part in my config.yaml:

```
php:
    install: '1'  
    settings:
        version: '54'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mbstring
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_hqet7wk6pvg3:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
```

And looking in the Php.pp file I see the following:

```
  if array_true($php_inis, 'session.save_path') {
    $php_sess_save_path = $php_inis['session.save_path']

    # Handles URLs like tcp://127.0.0.1:6379
    # absolute file paths won't have ":"
    if ! (':' in $php_sess_save_path) {
      exec { "mkdir -p ${php_sess_save_path}" :
        creates => $php_sess_save_path,
        notify  => Service[$php_service],
      }

      if ! defined(File[$php_sess_save_path]) {
        file { $php_sess_save_path:
          ensure  => directory,
          owner   => 'www-data',
          group   => 'www-data',
          mode    => '0775',
          require => Exec["mkdir -p ${php_sess_save_path}"],
        }
      }
    }
  }
```

Which looks like the php session folder should be chown'ed by `www-data:www-data` and chmod'ed to `0775`.

But it didn't work. I manually ran chown and chmod to follow the Php.pp file's settings and things are working. I'm going to assume if I reset the vm though it'll be reverted back and I'll have to do that again.

Am I doing something wrong or is there a bug somewhere?
