### ISSUE TITLE
sql_file

### ISSUE THREAD

**Issue by ebisbe** [puphpet/puphpet#1586]
Hello,
I've been trying the new version of puphpet and I don't see the option to add sql_files when the database is created. Is that option deprecated?

**Comment by Lyubaev** [comment]
Use `mysql/databases/mysqlnd_2elt3p21ms7h/sql`

```yml
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_ljcb544wkfum:
            name: user
            password: qwerty
    databases:
        mysqlnd_2elt3p21ms7h:
            name: dbname
            sql: /vagrant/dump.sql
    grants:
        mysqlng_ngcolo189ez2:
            user: user
            table: '*.*'
            privileges:
                - ALL
```
