### ISSUE TITLE
Apache: proxy:error | proxy_fcgi:error

### ISSUE THREAD

**Issue by blazingarrow** [puphpet/puphpet#1593]
I'm stuck with following error in the apache log. I have no warnings on vagrant up / provision. I've already destroyed the machine and began from scratch. But the error persists.
```
 [Thu Apr 30 19:22:03.630789 2015] [proxy:error] [pid 11821:tid 140442561480448] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
 [Thu Apr 30 19:22:03.630814 2015] [proxy_fcgi:error] [pid 11821:tid 140442561480448] [client 192.168.56.1:51466] AH01079: failed to make connection to backend: 127.0.0.1
```
I have following config file: 
```
vagrantfile:
    target: local
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: srcweb
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_y5d9e7ghue20:
                    host: '6569'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_o4302c0pg1ge:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - libfontconfig1
users_groups:
    install: '1'
    groups: {  }
    users:
        - swissredcross
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_tvtuhpx9x46k:
            server_name: cineboxx.ch.dev
            server_aliases:
                - www.cineboxx.ch.dev
            www_root: /var/www/cineboxx
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            locations:
                nxvl_cm6mgv2our2v:
                    location: /
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_7z9of0g395o8:
                    location: '~ \.php$'
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - deflate
        - expires
        - headers
        - proxy_fcgi
        - rewrite
        - vhost_alias
    vhosts:
        av_57isbg8f8n0r:
            servername: redcross.ch.dev
            serveraliases:
                - www.redcross.ch.dev
                - www.pflege-entlastung.ch.dev
                - www.proche-aidant.ch.dev
                - www.toolkit-freiwilligenarbeit.ch.dev
                - www.toolkit-benevolat.ch.dev
                - www.magazin-humanite.ch.dev
                - www.rivista-humanite.ch.dev
            docroot: /var/www/redcross.ch
            port: '443'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_t8m2x8r4ezo0:
                    path: /var/www/redcross.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_o4u9f79gdjd7:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_pklbrlafkfac:
            servername: migesplus.ch
            serveraliases:
                - www.migesplus.ch.dev
                - www.migesexpert.ch.dev
            docroot: /var/www/migesplus.ch
            port: '80'
            setenv:
                - 'DATABASE_USER migesplus'
                - 'DATABASE_PASSWORD migesCumulus'
                - 'DATABASE_HOST localhost'
                - 'DATABASE_DB db_migesplus_ch'
                - 'TYPO3_INSTALL dfcb7dfde529eef7bc7aa22e6cb39238'
                - 'TYPO3_ENCRYPTIONKEY dfcb7dfde529eef7bc7aa22e6cb39238'
                - 'TYPO3_DISPLAY_ERRORS 1'
                - 'TYPO3_MAIL_TRANSPORT mbox'
                - 'ENVIRONMENT dev'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_m777vwyemawh:
                    path: /var/www/migesplus.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_nx2nnak33g4a:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_2a5rk0g1z56b:
            servername: 2xweihnachten.ch
            serveraliases:
                - www.2xweihnachten.ch.dev
                - www.2xnoel.ch.dev
                - www.2xchristmas.dev
                - www.2xnatale.ch.dev
                - www.2xnadal.ch.dev
            docroot: /var/www/2xweihnachten.ch
            port: '443'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_e66ppp5rt1wa:
                    path: /var/www/2xweihnachten.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_3b47hfw8g68j:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_q953f2wold0r:
            servername: redcrossheroes.ch
            serveraliases:
                - www.redcrossheroes.ch.dev
            docroot: /var/www/redcrossheroes.ch
            port: '80'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_h1dyd2sdg7m0:
                    path: /var/www/redcrossheroes.ch
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_g814jicdkv6y:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_2fgv6wigtam6:
            servername: code-standards.dev
            serveraliases:
                - www.code-standards.dev
            docroot: /var/www/code-standards
            port: '80'
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            directories:
                avd_fb3yestdb3m5:
                    path: /var/www/code-standards
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_nztpd0f59co6:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - geoip
            - mbstring
            - mysql
            - xmlrpc
            - fpm
            - cgi
        pear: {  }
        pecl: {  }
    ini:
        display_errors: On
        error_reporting: 'E_ALL & ~E_STRICT'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        memory_limit: 256M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: 1
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '1'
    settings:
        server_id: fb874ecb-9353-45b4-bd05-228206988a63
        server_token: e8ddbdb71b5ac4187095ed70cc75946cbd84aa28bd72276a379d00bdcf03a6f6
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: 6.3.0
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_uh60ax9601sy:
            version: 1.9.3
            gems:
                - sass
                - compass
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - grunt
        - grunt-cli
        - grunt-init
        - grunt-contrib-sass
        - grunt-contrib-jshint
        - grunt-contrib-concat
        - grunt-contrib-watch
        - grunt-contrib-imagemin
        - grunt-contrib-uglify
        - grunt-autoprefixer
        - grunt-grunticon
        - grunt-postcss
        - grunt-accessibility
        - grunt-check-dependencies
        - autoprefixer-core
        - node-sass
        - fontfaceobserver
        - criticalcss
        - bower
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: 17Juli18166
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_uc6hd1i4nln8:
            name: migesplus
            password: migesCumulus
        mysqlnu_eqzcyexgxlav:
            name: redcross
            password: 17Juli1866
        mysqlnu_om8fpq6ux4qr:
            name: 2xweihnachten
            password: 17Juli1866
        mysqlnu_2617dgucrl5l:
            name: redcrossheroes
            password: 17Juli1866
    databases:
        mysqlnd_86at51yf34j1:
            name: redcross
            sql: ''
        mysqlnd_3srux3cttqwu:
            name: migesplus
            sql: ''
        mysqlnd_v826xx3lfply:
            name: 2xweihnachten
            sql: ''
        mysqlnd_eojaou426gua:
            name: redcrossheroes
            sql: ''
    grants:
        mysqlng_zxf68dekkzlc:
            user: redcross
            table: 'redcross.*'
            privileges:
                - ALL
        mysqlng_4a63h126be2p:
            user: migesplus
            table: 'migesplus.*'
            privileges:
                - ALL
        mysqlng_mhqn3pc5sd2k:
            user: 2xweihnachten
            table: '2xweihnachten.*'
            privileges:
                - ALL
        mysqlng_xa5ylfbhz7xx:
            user: redcrossheroes
            table: 'redcrossheroes.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '1'
    settings:
        version: 4.10.2
        port: '8080'
```
