### ISSUE TITLE
Default FPM pool, nginx and default site config

### ISSUE THREAD

**Issue by kusmierz** [puphpet/puphpet#1618]
Imagine I've one, default fpm pool, ie:

```yaml
    fpm_pools:
        phpfp_un8hk50plxeg:
            ini:
                prefix: www
                security.limit_extensions: .php
                user: www-user
                group: www-data
                listen: /var/run/php5-fpm.sock
```

what is important here, I'm going to use sockets here instead port binding. But nevertheless, default nginx config has `127.0.0.1:9000`. How could I change it?

```bash
$ cat /etc/nginx/sites-available/_.conf
```

```nginx
server {
  listen                *:80;

  server_name           _;
  client_max_body_size 1m;

  root /var/www/html;
    index  index index.html index.htm index.php;

  access_log            /var/log/nginx/_.access.log;
  error_log             /var/log/nginx/_.error.log;

  location / {

    root  /var/www/html;
    try_files $uri $uri/ index.php;
     autoindex on;


  }
  location ~ \.php$ {

    root  /var/www/html;
    fastcgi_index index.php;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    try_files $uri $uri/ index.php /index.php$is_args$args;
    include /etc/nginx/fastcgi_params;
    fastcgi_pass 127.0.0.1:9000;

    fastcgi_param SCRIPT_FILENAME $request_filename;
    fastcgi_param APP_ENV dev;

  }
  sendfile off;
}
```
