### ISSUE TITLE
RabbitMQ - failed to install rabbitmqadmin

### ISSUE THREAD

**Issue by arogachev** [puphpet/puphpet#1639]
RabbitMQ config looks like this:

```yml
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
```

Console output:

```
==> default: Error: curl  -f -L -o /var/lib/rabbitmq/rabbitmqadmin http://localhost:15672/cli/rabbitmqadmin returned 7 instead of one of [0]
==> default: Error: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/Staging::File[rabbitmqadmin]/Exec[/var/lib/rabbitmq/rabbitmqadmin]/returns: change from notrun to 0 failed: curl  -f -L -o /var/lib/rabbitmq/rabbitmqadmin http://localhost:15672/cli/rabbitmqadmin returned 7 instead of one of [0]
```

```
==> default: Warning: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/File[/usr/local/bin/rabbitmqadmin]: Skipping because of failed dependencies
```

Seems like rabbitmqadmin was not installed at all.

If the whole config is needed, let me know.
