### ISSUE TITLE
RabbitMQ - problems with adding new admin user

### ISSUE THREAD

**Issue by arogachev** [puphpet/puphpet#1641]
RabbitMQ config looks like this:

```yml
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users:
        user-1:
            admin: '1'
            name: admin
            password: admin
            permissions:
                permissions-1:
                    host: /
                    configure_permission: '.*'
                    read_permission: '.*'
                    write_permission: '.*'
    vhosts:
        - /
    plugins: {  }
```

It gives the following error:

```
==> default: Error: Parameter admin failed on Rabbitmq_user[admin]: Invalid value "1". Valid values match /true|false/.
==> default: Wrapped exception:
==> default: Invalid value "1". Valid values match /true|false/.
```

If I change to `true`, it works. But in saved `config.yml` through site GUI there is: `admin: '1'`.
