### ISSUE TITLE
Failed to mount folders in Linux guest - Requires rebuilding vbox boxes

### ISSUE THREAD

**Issue by TiMESPLiNTER** [puphpet/puphpet#1643]
Since today I end up with

```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u www-data`,gid=`getent group www-data | cut -d: -f3`,share EysNcP4Mj1N9 /var/www
mount -t vboxsf -o uid=`id -u www-data`,gid=`id -g www-data`,share EysNcP4Mj1N9 /var/www

The error output from the last command was:

unknown mount option `share'
valid options:
  rw         mount read write (default)
  ro         mount read only
  uid       =<arg> default file owner user id
  gid       =<arg> default file owner group id
  ttl       =<arg> time to live for dentry
  iocharset =<arg> i/o charset (default utf8)
  convertcp =<arg> convert share name from given charset to utf8
  dmode     =<arg> mode of all directories
  fmode     =<arg> mode of all regular files
  umask     =<arg> umask of directories and regular files
  dmask     =<arg> umask of directories
  fmask     =<arg> umask of regular files
```

My shared folder config:

```
synced_folder:
            EysNcP4Mj1N9:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
```

Box config:
```
vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
```

Vagrant version is `1.7.2` and VB is on `4.3.28`. I'm working on OSX `10.10.3`.

I haven't changed anything for the last two weeks.

**Workaround**
Changed `sync_type` from `default` to `nfs`. Now it works again.
