### ISSUE TITLE
How to use the include directive to insert an Apache .conf file?

### ISSUE THREAD

**Issue by aaronbushnell** [puphpet/puphpet#1647]
I'm not sure how to use the [include directive](https://httpd.apache.org/docs/2.2/mod/core.html#include) with a configured virtualhost.

Path to my docroot: `/var/www/my-site/docroot`
Path to my .conf file: `/var/www/my-site/my-conf.conf`
My virtualhost setup in my config.yaml:
```yaml
av_IeiA8eAAm532:
  servername: local.my-site.com
  serveraliases:
      - www.my-site.local
  docroot: /var/www/my-site/docroot
  port: '80'
  setenv:
      - 'APP_ENV dev'
  custom_fragment: 'Include /var/www/my-site/my-conf.conf'
  ssl: '0'
  ssl_cert: ''
  ssl_key: ''
  ssl_chain: ''
  ssl_certs_dir: ''
  ssl_protocol: ''
  ssl_cipher: ''
  directories:
      avd_mlagydqncy1e:
          path: /var/www/my-site/docroot
          options:
              - Indexes
              - FollowSymlinks
              - MultiViews
          allow_override:
              - All
          require:
              - 'all granted'
          custom_fragment: ''
          files_match:
              avdfm_9cszzqperb7v:
                  path: \.php$
                  sethandler: 'proxy:fcgi://127.0.0.1:9000'
                  custom_fragment: ''
                  provider: filesmatch
          provider: directory
```

When I run `vagrant reload --provision` to see the .conf file I get this error:
```
Error: Files must be fully qualified at /tmp/vagrant-puppet-3/manifests/nodes/Apache.pp:179 on node local.lamp
```

When I leave off `Include`. just use the path and then use `vagrant reload --provision` I get further, but then I get this error:
```
==> default: Error: /Stage[main]/Apache::Service/Service[httpd]: Failed to call refresh: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1:
==> default:
==> default: Error: /Stage[main]/Apache::Service/Service[httpd]: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1:
```
