### ISSUE TITLE
box decision ignored

### ISSUE THREAD

**Issue by head82** [puphpet/puphpet#1672]
Since the new gui is online, I always get an ubuntu1404-x64 box after vagrant up but i selected the debian75-x64 box. The config looks like this:

```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/debian75-x64
```
