### ISSUE TITLE
Support for Nginx's proxy_pass

### ISSUE THREAD

**Issue by bountin** [puphpet/puphpet#1688]
I wanted to add a location in a vhost with a proxy_pass but puppet tells me that it "cannot define both directory and proxy in a virtual host". (See config below)

 I've traced this error to the following code that adds a www_root to the location block: https://github.com/puphpet/puphpet/commit/8d695f1c2bd4dc4440648a0a0e493a80c562db82#diff-fd5d2c786b5cd474f6a013017062886eR206. I'd really love to file a pull request to support this (special) case but I must admit that I can't understand what the if clause is meant to do as I'm not really familiar with the puppet DSL or ruby and for me both parts of the or statement are expressing the exactly opposite (and represents therefore a tautology).

Locally I'm now working with the following if statement that skips the addition of www_data and the upstream nginx puppet module handles everything else:
```
if empty($location_no_root['proxy']) and (! defined($location_no_root['fastcgi']) or empty($location_no_root['fastcgi']))
```

Config:
```
    vhosts:
        foo.dev:
            server_name: foo.dev
            www_root: /var/www
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 10m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_amy9n5t1qc0m:
                    location: /
                    www_root: /var/www
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                nxvl_s63hrtjzy71r:
                    location: '~ \.php$'
                    www_root: /var/www
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                ocpu:
                    location: /ocpu/
                    proxy: 'http://localhost:81/ocpu/'
```
