### ISSUE TITLE
Nginx aliases does not work for hostmanager 

### ISSUE THREAD

**Issue by caseycs** [puphpet/puphpet#1694]
In vagrant environment
```
nginx:
    vhosts:
        nxv_fs9uk0f329v0:
            server_name: xxx
            server_aliases:
                - yyy
                - zzz
```

I'll come up with the PR in few minutes
