### ISSUE TITLE
LocationMatch settings in vhost

### ISSUE THREAD

**Issue by samedney** [puphpet/puphpet#1765]
Hi there,

This might just be due to me not understanding the newer versions of Apache / PHP very well yet, but I recently built a new vagrant using Ubuntu 14.04 x64 and PHP 5.6 - for a CodeIgniter based site that was previously running on PHP 5.3.

To cut a long story short, to get the site to work - I had to add the following to my vhost config file.

```
  <LocationMatch "^(.*\.php)$">
    ProxyPass fcgi://127.0.0.1:9000/var/www/mysite.dev
  </LocationMatch>
```

Should I have been able to do this from the phphpet site somehow?

If not - would anyone be kind enough to let me know how to add it to my puppet config?

FWIW - in case anyone else has the same problem... I also had to change my .htaccess to the following:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
```

Thank you in advance - and keep up the great work!

Sam

**Comment by samedney** [comment]
FWIW - in case anyone else has the same problem... I also had to change my .htaccess to the following:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
```

**Comment by bridgesense** [comment]
I was having a bit of an issue with running codeigniter myself, and this post helped me home in on the issue.  I erred in my setup of the apache configuration.  I had set the directories path the same as my docroot, which prevents codeigniter from getting at the protected files.  The directory path should match your synced_folder source directory -- not docroot.  If you're dealing with something similar, hopefully you won't have to modify the sethandler path.

But to answer you question about doing this from the puppet config; yes you can.  You can make changes to the path and sethandler under apache -> vhosts -> directories -> files_match:

```
vhosts:
        av_ze1uoder6jcf:
            servername: dev.website.com
            serveraliases:
                - dev.website.com
            docroot: /var/www/public_html
            port: '443'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_fou3e79fi34n:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_wgxtan37u43u:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
```
