### ISSUE TITLE
elasticsearch: firewall needs to be opened explictly

### ISSUE THREAD

**Issue by Hezion** [puphpet/puphpet#1775]
I was wondering why i couldn't access elasticsearch on port 9200. Turn out that i had to open port 9200 explicitly in the firewall settings. 

```yaml
firewall:
    install: '1'
    rules:
        fr_wz5q0737d3z0:
            port:
                - '9200'
            priority: '100'
            proto: tcp
            action: accept
```

I am not sure whether this is an actual error or intended to be manually configured by the user. In that case there should be notice.
