### ISSUE TITLE
apache rewrite

### ISSUE THREAD

**Issue by ekitakata** [puphpet/puphpet#1776]
It's not more possible to make rewrite in your GUI.

how to make apache rewrite in actual puphpet?

Thanks in advance.

**Comment by pbchase** [comment]
To do a rewrite in puphpet, you have to use custom_fragment. That's implemented in two places in the Apache config:

apache:vhosts:`<vhost_instance`>:custom_fragment: `<some_file_name`>
apache:vhosts:`<vhost_instance`>:directories:`<directory_instance`>:custom_fragment: `<fragment text`>

Within the vhost context, custom_fragment requires a path to a file of apache directives in the guest's file space. That file will be included in the apache configuration file.

Within the directory context, custom_fragment requires the actual text to be inserted in the apache configuration file.  That gets a little tricky with multi-line fragments. The example below works, but the Puphpet web app cannot parse it if you upload you config.yaml.

Here's some example configuration:

```yaml
    apache:
        install: '1'
        settings:
            user: www-data
            group: www-data
            default_vhost: false
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_kx7shasytkep:
                servername: example.org
                serveraliases:
                    - vagrant1
                docroot: /var/www/myapp
                port: '443'
                setenv:
                    - 'APP_ENV dev'
                custom_fragment: '/vagrant/puphpet/redirect_to_web_app.txt'
                ssl: '1'
                ssl_cert: '/etc/apache2/ssl/apache.crt'
                ssl_key: '/etc/apache2/ssl/apache.key'
                ssl_chain: '/etc/apache2/ssl/apache.ca-bundle'
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_qaiu8pzumhch:
                        path: /var/www/myapp/api/v1/
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment:
                            "
                            SetEnvIf Authorization \"(.*)\" KEY=$1\r\n
                            RewriteEngine On\r\n
                            RewriteCond %{REQUEST_FILENAME} !-d\r\n
                            RewriteCond %{REQUEST_FILENAME} !-f\r\n
                            RewriteRule ^ index.php [L]\r\n
                            RewriteBase /api/v1/\r\n
                            "
                        files_match:
                            avdfm_zfcl910xl7rg:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
```
