### ISSUE TITLE
Upgrade from PHP 5.4 to 5.6 issue

### ISSUE THREAD

**Issue by Mark-L6n** [puphpet/puphpet#1801]
I'm trying to upgrade from PHP 5.4 to 5.6.
In `puphpet/config.yaml`, I changed `php:` `version:` from `'54'` to `'56'`.  After that, ran `vagrant provision` and `vagrant reload`.  However, `php --version` and `phpinfo();` show `5.4.37`.  
Ran `vagrant halt` and `vagrant up`, same result.  Ran `vagrant provision` and `vagrant reload` again, same result.

Is there something else that needs to be configured to enable updating PHP 5.4 to 5.6? Thanks!

```yaml
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.103
            forwarded_port:
                M3OBIz5YlSZi:
                    host: '7813'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            VvAMMb0Aba3k:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups:
        - devs
    users:
        - '1234:devs'
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        yai8lddspcoo:
            servername: dev.n1
            serveraliases:
                - www.dev.n1
            docroot: /var/www/n1
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                hj4g0rpwux4z:
                    provider: directory
                    path: /var/www/n1
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        1klkievmjbdh:
            servername: dev.n2
            serveraliases:
                - www.dev.n2
            docroot: /var/www/n2
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                z0hxmjrrwmhk:
                    provider: directory
                    path: /var/www/n2
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        wpwnrh5nkmbq:
            servername: dev.n3
            serveraliases:
                - www.dev.n3
            docroot: /var/www/n3
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                zr9ss1vxh9s7:
                    provider: directory
                    path: /var/www/n3
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        eihoewakobt4:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - mbstring
        pear: {  }
        pecl:
            - pecl_http
    ini:
        session.save_path: /var/lib/php/session
        # display_errors prints errors to screen.  http://php.net/manual/en/errorfunc.configuration.php#ini.display-errors
        display_errors: Off
        # error_log: /var/log/php_errors.log # doesn't work due to permissions; /var/log is 755, php_error owner is www-data:www-data
        # error_log: /tmp/php_errors.log  # works (/tmp is 777)
        # below works:  let system put file where it wants to.  Find by: error_log('funkydoodlygunk') in php file; then: egrep "funkydoodlygunk" -ir /var 2>&-
        #      however, it is in same directory as the file run, which is not good
        error_log: php_errors.log
        # log_errors was on by default, but might as well specify it
        log_errors:  On
        # error_reporting: 'E_ALL & ~E_DEPRECATED & ~E_STRICT'  # php_info shows this to be 22527
        # error_reporting: -1
        # for number value, see http://php.net/manual/en/errorfunc.constants.php
        error_reporting: '32767'
    timezone: America/New_York
    mod_php: '1'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '1'
    version: 7.0.0-alpha3
ruby:
    install: '1'
    versions:
        kGzwuHMy79qS:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        BcLnA7rz1wnx:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: 4321pw
    adminer: '1'
    databases:
        M4pWP69EWv4d:
            grant:
                - ALL
            name: db1
            host: localhost
            user: 1234db
            password: 1234pw
            sql_file: ''
        DswgArmkt34X:
            grant:
                - ALL
            name: db2
            host: localhost
            user: 1234db
            password: 1234pw
            sql_file: ''
        JuQonaeTOzEU:
            grant:
                - ALL
            name: db3
            host: localhost
            user: 1234db
            password: 1234pw
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
