### ISSUE TITLE
Changing mailcatcher's 'form_email_method' then provision does not work

### ISSUE THREAD

**Issue by brianhogg** [puphpet/puphpet#1811]
I'm trying to just change the from_email_method in the mailcatcher block from 'inline' to 'headers', as the codebase I'm testing doesn't seem to have email caught using the inline method.  So I just change the config yaml line:

```        from_email_method: headers```

then vagrant provision, and get the following log at the end:

```
==> default: Notice: /Stage[main]/Puphpet_server/Exec[dotfiles]/returns: executed successfully
==> default: Notice: /Stage[main]/Pyenv/Vcsrepo[/usr/local/pyenv]/revision: revision changed '3cde540ca00208fbfd0a5e7708c3053bc8cca9f5' to 'v0.4.0-20140404'
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: pecl/pecl_http requires package "pecl/raphf" (version >= 1.1.0), installed version is 1.0.4
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: No valid packages found
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: install failed
==> default: Error: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Puphpet::Php::Xdebug/Vcsrepo[/.puphpet-stuff/xdebug]/revision: revision changed '8737484ca6cc8f05ab095d7249952fcb5955fe57' to 'XDEBUG_2_3_1'
==> default: Notice: /Stage[main]/Puphpet_php/Service[php5-fpm]: Dependency Exec[pecl-pecl_http] has failures: true
==> default: Warning: /Stage[main]/Puphpet_php/Service[php5-fpm]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Puphpet_apache/Exec[exec mkdir -p /var/www/html @ key default_vhost_80]/returns: mkdir: cannot create directory '/var/www/html': Permission denied
==> default: Error: mkdir -m 775 -p /var/www/html returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Puphpet_apache/Exec[exec mkdir -p /var/www/html @ key default_vhost_80]/returns: change from notrun to 0 failed: mkdir -m 775 -p /var/www/html returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Puphpet_apache/Exec[exec mkdir -p /var/www/html @ key default_vhost_443]/returns: mkdir: cannot create directory '/var/www/html': Permission denied
==> default: Error: mkdir -m 775 -p /var/www/html returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Puphpet_apache/Exec[exec mkdir -p /var/www/html @ key default_vhost_443]/returns: change from notrun to 0 failed: mkdir -m 775 -p /var/www/html returned 1 instead of one of [0]
==> default: Notice: Finished catalog run in 45.23 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

(The last couple errors are likely due to mapping folders within /var/www/ in addition to /var/www itself, but apache was working with the two mapped folders/virtual hosts before the mailcatcher change)

I'm not seeing any other changes that are made in the config file when choosing between headers and inline in the PuPHPet GUI but perhaps something else in the config needs to be altered to make the switch?

Full config yaml (with from_email_method already changed from inline to headers, everything else is the same as generated from the GUI except for a couple additional synced folders which were working):

```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: local.puphpet
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.57.101
            forwarded_port:
                vflnp_3pp255c27sne:
                    host: '5741'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_2jujluurv90e:
                source: ./
                target: /var/www/
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'true'
                owner: www-data
                group: www-data  
            vflsf_2jujluurv92e:
                source: /var/www/risk-dev
                target: /var/www/risk-dev
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'true'
                owner: www-data
                group: www-data  
            vflsf_2jujluurv93e:
                source: /var/www/community-dev
                target: /var/www/community-dev
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'true'
                owner: www-data
                group: www-data                              
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - git
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - 'en_GB.UTF-8 UTF-8'
            - 'en_US.UTF-8 UTF-8'
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_l2p52d0unojn:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_bayzf5lp7xcu:
                    location: /
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_teunhjdcompx:
                    location: '~ \.php$'
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_bsyh3sb05ro8:
            servername: risk.dev
            docroot: /var/www/risk-dev
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_qxqg4hv7f706:
                    path: /var/www/risk-dev
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_kpvasc03waaf:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_hmf6998pu2ph:
            servername: community.dev
            docroot: /var/www/community-dev
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_xi1n1ijdew4h:
                    path: /var/www/community-dev
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5bp42hyed3up:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_8e2r1y0kw5fu:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_lhq14x8zjuwz:
            name: risk
            password: password
        mysqlnu_z5sz90vwwq49:
            name: community
            password: password
    databases:
        mysqlnd_mpyzzb20tyyg:
            name: risk
            sql: ''
        mysqlnd_70xued5q3p58:
            name: community
            sql: ''
    grants:
        mysqlng_g67iz4pmhjng:
            user: risk
            table: 'risk.*'
            privileges:
                - ALL
        mysqlng_08meabtkibqb:
            user: community
            table: 'community.*'
            privileges:
                - ALL
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_gfmrivyzjrm1:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_mudqap34eopo:
            name: dbname
            sql: ''
    grants:
        mariadbng_ospfpxzg4xod:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```

And running vagrant destroy && vagrant up works fine with this config.

Thanks!
