### ISSUE TITLE
Error: Could not find a suitable provider for pyenv_python

### ISSUE THREAD

**Issue by jccpdev** [puphpet/puphpet#1816]
Hello, Im having the problem... I have never run into if before and I cant find a solution for it..

The error is Error: Could not find a suitable provider for pyenv_python

Here is trace 

```
...
==> default: Notice: /Stage[main]/Puphpet_python/Puphpet::Python::Install[pyenv_ttby9azpzlja]/File[python v2.6.9 symlink]: Dependency Pyenv_python[2.6.9] has failures: true
==> default: Warning: /Stage[main]/Puphpet_python/Puphpet::Python::Install[pyenv_ttby9azpzlja]/File[python v2.6.9 symlink]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Puphpet_python/Puphpet::Python::Install[pyenv_ttby9azpzlja]/File[python v2.6.9 virtualenv symlink]: Dependency Pyenv_python[2.6.9] has failures: true
==> default: Warning: /Stage[main]/Puphpet_python/Puphpet::Python::Install[pyenv_ttby9azpzlja]/File[python v2.6.9 virtualenv symlink]: Skipping because of failed dependencies
==> default: Error: Could not find a suitable provider for pyenv_python
==> default: Notice: Finished catalog run in 103.61 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Here is my config.yaml

```
vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: cbl.local
        memory: '4096'
        cpus: '8'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.12.103
            forwarded_port:
                vflnp_ytm6khbb7d2o:
                    host: '8787'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_db54adjlxdda:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: true
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
        - php-bcmath
        - php-tidy
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_gz4lhab96r5y:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        admin:
            servername: admin.cbl.dev
            docroot: /var/www/palmetto/src/public
            port: '80'
            setenv:
                - 'APP_ENV local'
                - 'APP_STACK admin'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_3c8bueye0pf9:
                    path: /var/www/palmetto/src/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all granted
                    custom_fragment: ''
                    provider: directory
        api:
            servername: api.cbl.dev
            docroot: /var/www/palmetto/src/public
            port: '80'
            setenv:
                - 'APP_ENV local'
                - 'APP_STACK api'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_m3jkkzgrfx5s:
                    path: /var/www/palmetto/src/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all granted
                    custom_fragment: ''
                    provider: directory
        marketing:
            servername: go.cbl.dev
            docroot: /var/www/palmetto/src/public
            port: '80'
            setenv:
                - 'APP_ENV local'
                - 'APP_STACK marketing'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_v12ta3oyfks3:
                    path: /var/www/palmetto/src/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all granted
                    custom_fragment: ''
                    provider: directory
        www:
            servername: cbl.dev
            serveraliases:
                - www.cbl.dev
            docroot: /var/www/palmetto/src/public
            port: '80'
            setenv:
                - 'APP_ENV local'
                - 'APP_STACK www'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_e84qlg9ljamr:
                    path: /var/www/palmetto/src/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all granted
                    custom_fragment: ''
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mbstring
            - mcrypt
        pear: {  }
        pecl:
            - gnupg
            - pecl_http
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/www/session
        memory_limit: 2G
        max_execution_time: '100'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_k31i1mz46sbq:
            version: ''
python:
    install: '1'
    packages: {  }
    versions:
        pyenv_ttby9azpzlja:
            version: 2.6.9
nodejs:
    install: '1'
    npm_packages:
        - gulp@3.8.10
        - bower@1.3.12
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: cbl
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_fi5d62qnzddy:
            name: cbl
            password: cbl
    databases:
        mysqlnd_to79kdf66hlf:
            name: cbl_dev
            sql: /var/www/cbl.sql
    grants:
        mysqlng_ynzwqle0qgqd:
            user: cbl
            table: '*.*'
            privileges:
                - ALL
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users: {  }
    databases: {  }
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```

PLEASE HELP
