### ISSUE TITLE
"sed: can't read /vagrant/puphpet/shell/*.sh: No such file or directory" on El Capitan

### ISSUE THREAD

**Issue by Spriz** [puphpet/puphpet#1819]
Hi!

When trying to do a vagrant up on a fresh puphet machine w/ OSX 10.11 Beta

YAML file: https://gist.github.com/Spriz/ed742afb2813daa0539a

CLI output: https://gist.github.com/Spriz/0671abe085fa6b834370

Vagrant 1.7.4 + Parallels 10.2.1 this is :smile:

**Comment by Teknologica** [comment]
I've had the same error this week. Is your `puphpet` folder at the root of `/Users/spriz/code/`?

**Comment by Spriz** [comment]
Nope, it's at /Users/spriz/code/vagrant-boxes/php56/puphpet or something
equal to that (I'm not at the office anymore for today)

tir. 4. aug. 2015 kl. 20.36 skrev Andrei <notifications@github.com>:

**Comment by arkan78** [comment]
Hi,
I have the same issue
YAML file : https://gist.github.com/arkan78/8973979f0abf6960b8ac
CLI output: https://gist.github.com/arkan78/da07ee137af116c02fa0

Windows 10 + Vagrant 1.7.4

**Comment by bperel** [comment]
Same here with similar outputs on Linux Mint 17.1 + Vagrant 1.7.4 and Virtualbox 4.3.30

**Comment by MathSmath** [comment]
FWIW, I got this error when when NFS mounting didn't work correctly. So the /vagrant/ directory was literally not available on the guest machine. Try to "vagrant ssh" into your VM, and see if /vagrant/ is empty. If so, it's a file sharing problem with Vagrant.

**Comment by ackimwilliams** [comment]
Am also having this issue after upgrading to El Capitan, anyone come up with a work around?

**Comment by jakesyl** [comment]
@MathSmath Mines not mounting either.  Did anyone solve this issue?

**Comment by MathSmath** [comment]
@jakesyl If your NFS shares aren't mounting, it's likely an issue with Vagrant, not with puphpet. Might try looking over there: https://github.com/mitchellh/vagrant/search?q=NFS&type=Issues&utf8=%E2%9C%93

**Comment by Spriz** [comment]
I'm not even sure how this got fixed anymore :-1:

**Comment by frinux** [comment]
I found out that the provision script is looking for /vagrant folder on the guest:
`config.vm.provision :shell, :inline => "sed -i -e 's/\r$//' /vagrant/puphpet/shell/*.sh"`

I fixed this problem by adding a new shared folder (from ./ to /vagrant):

```
            vflsf_5m5s0g913bs9:
                source: .
                target: /vagrant
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
```

This shared folder should be mandatory in generated config.yaml file.
