### ISSUE TITLE
Vagrant not creating a proper Apache configuration

### ISSUE THREAD

**Issue by chartjes** [puphpet/puphpet#182]
I spun up a Ubuntu Precise64 VM using the VMWare provider and it failed to configure Apache correctly. Juan asked me to attach the Vagrant config file, default.pp and common.yaml files to this isuse.

Vagrant file

```
Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"

  config.vm.network "private_network", ip: "192.168.57.101"


  config.vm.synced_folder "~/vm/webreg", "/var/www", id: "webroot", :nfs => true

  config.vm.usable_port_range = (2200..2250)
  config.vm.provider :vmware_fusion do |v|
    v.vmx['memsize'] = "512"
  end

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--name", "webreg-box"]
    virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    virtualbox.customize ["modifyvm", :id, "--memory", "512"]
    virtualbox.customize ["setextradata", :id, "--VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.vm.provision :shell, :path => "shell/update-puppet.sh"
  config.vm.provision :shell, :path => "shell/librarian-puppet-vagrant.sh"
  config.vm.provision :shell, :inline => "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && touch /apt-get-run; fi"
  config.vm.provision :puppet do |puppet|
    puppet.facter = {
      "ssh_username" => "vagrant"
    }

    puppet.manifests_path = "puppet/manifests"
    puppet.options = ["--verbose", "--hiera_config /vagrant/hiera.yaml", "--parser future"]
  end




  config.ssh.username = "vagrant"

  config.ssh.shell = "bash -l"

  config.ssh.keep_alive = true
  config.ssh.forward_agent = false
  config.ssh.forward_x11 = false
  config.vagrant.host = :detect
end
```

common.yaml

```

---
vagrantfile-local:
    vm:
        box: precise64
        box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box'
        hostname: null
        network:
            private_network: 192.168.57.101
            forwarded_port:
                yjoAoz9uMlrj:
                    host: ''
                    guest: ''
        provider:
            virtualbox:
                modifyvm:
                    name: webreg-box
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            'shell, :path': shell/librarian-puppet-vagrant.sh
            'shell, :inline': 'if [[ ! -f /apt-get-run ]]; then sudo apt-get update && touch /apt-get-run; fi'
            puppet:
                manifests_path: puppet/manifests
                options:
                    - --verbose
                    - '--hiera_config /vagrant/hiera.yaml'
                    - '--parser future'
        synced_folder:
            TmsihNu0iqrd:
                id: webroot
                source: ~/vm/webreg
                target: /var/www
                nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages:
        - build-essential
        - vim
        - curl
        - git-core
    dot_files:
        -
            bash_aliases: null
apache:
    modules:
        - php
        - rewrite
    vhosts:
        pHV3Unkcq1Tf:
            servername: webreg.dev
            docroot: /var/www/
            port: '80'
            setenv:
                - 'APP_ENV dev'
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: America/Toronto
xdebug:
    enabled: 1
    ini: {  }
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
postgresql:
    root_password: 1vector
    databases:
        6GjZ7ZgTA7Iu:
            grant: ALL
            name: ibl_stats
            user: stats
            password: st@ts=Fun
            sql_file: ''
```

default.pp

```
## Begin Server manifest

if $server_values == undef {
  $server_values = hiera('server', false)
}

group { 'puppet': ensure => present }
Exec { path => [ '/bin/', '/sbin/', '/usr/bin/', '/usr/sbin/' ] }
File { owner => 0, group => 0, mode => 0644 }

user { $::ssh_username:
    shell  => '/bin/bash',
    home   => "/home/${::ssh_username}",
    ensure => present
}

file { "/home/${::ssh_username}":
    ensure => directory,
    owner  => $::ssh_username,
}

# in case php extension was not loaded
if $php_values == undef {
  $php_values = hiera('php', false)
}

# copy dot files to ssh user's home directory
exec { 'dotfiles':
  cwd     => "/home/${::ssh_username}",
  command => "cp -r /vagrant/files/dot/.[a-zA-Z0-9]* /home/${::ssh_username}/ && chown -R ${::ssh_username} /home/${::ssh_username}/.[a-zA-Z0-9]*",
  onlyif  => "test -d /vagrant/files/dot",
  require => User[$::ssh_username]
}

# debian, ubuntu
case $::osfamily {
  'debian': {
    class { 'apt': }

    Class['::apt::update'] -> Package <|
        title != 'python-software-properties'
    and title != 'software-properties-common'
    |>

    ensure_packages( ['augeas-tools'] )
  }
}

case $::operatingsystem {
  'debian': {
    add_dotdeb { 'packages.dotdeb.org': release => $lsbdistcodename }

    if is_hash($php_values) {
      # Debian Squeeze 6.0 can do PHP 5.3 (default) and 5.4
      if $lsbdistcodename == 'squeeze' and $php_values['version'] == '54' {
        add_dotdeb { 'packages.dotdeb.org-php54': release => 'squeeze-php54' }
      }
      # Debian Wheezy 7.0 can do PHP 5.4 (default) and 5.5
      elsif $lsbdistcodename == 'wheezy' and $php_values['version'] == '55' {
        add_dotdeb { 'packages.dotdeb.org-php55': release => 'wheezy-php55' }
      }
    }
  }
  'ubuntu': {
    apt::key { '4F4EA0AAE5267A6C': }

    if is_hash($php_values) {
      # Ubuntu Lucid 10.04, Precise 12.04, Quantal 12.10 and Raring 13.04 can do PHP 5.3 (default <= 12.10) and 5.4 (default <= 13.04)
      if $lsbdistcodename in ['lucid', 'precise', 'quantal', 'raring'] and $php_values['version'] == '54' {
        apt::ppa { 'ppa:ondrej/php5-oldstable': require => Apt::Key['4F4EA0AAE5267A6C'] }
      }
      # Ubuntu Precise 12.04, Quantal 12.10 and Raring 13.04 can do PHP 5.5
      elsif $lsbdistcodename in ['precise', 'quantal', 'raring'] and $php_values['version'] == '55' {
        apt::ppa { 'ppa:ondrej/php5': require => Apt::Key['4F4EA0AAE5267A6C'] }
      }
    }
  }
}

ensure_packages( $server_values['packages'] )

define add_dotdeb ($release){
   apt::source { $name:
    location          => 'http://packages.dotdeb.org',
    release           => $release,
    repos             => 'all',
    required_packages => 'debian-keyring debian-archive-keyring',
    key               => '89DF5277',
    key_server        => 'keys.gnupg.net',
    include_src       => true
  }
}

## Begin Apache manifest

if $apache_values == undef {
  $apache_values = hiera('apache', false)
}

class { 'apache':
  user          => $apache_values['user'],
  group         => $apache_values['group'],
  default_vhost => $apache_values['default_vhost'],
  mpm_module    => $apache_values['mpm_module']
}

case $apache_values['mpm_module'] {
  'prefork': { ensure_packages( ['apache2-mpm-prefork'] ) }
  'worker':  { ensure_packages( ['apache2-mpm-worker'] ) }
  'event':   { ensure_packages( ['apache2-mpm-event'] ) }
}

create_resources(apache::vhost, $apache_values['vhosts'])

define apache_mod {
  class { "apache::mod::${name}": }
}

if count($apache_values['modules']) > 0 {
  apache_mod { $apache_values['modules']:; }
}

## Begin PHP manifest

if $php_values == undef {
  $php_values = hiera('php', false)
}

if $apache_values == undef {
  $apache_values = hiera('apache', false)
}

if $nginx_values == undef {
  $nginx_values = hiera('nginx', false)
}

Class['Php'] -> Class['Php::Devel'] -> Php::Module <| |> -> Php::Pear::Module <| |> -> Php::Pecl::Module <| |>

if is_hash($apache_values) {
  class { 'php':
    service => 'httpd'
  }
} elsif is_hash($nginx_values) {
  class { 'php':
    package             => 'php5-fpm',
    service             => 'php5-fpm',
    service_autorestart => false,
    config_file         => '/etc/php5/fpm/php.ini',
  }

  service { 'php5-fpm':
    ensure     => running,
    enable     => true,
    hasrestart => true,
    hasstatus  => true,
    require    => Package['php5-fpm']
  }
}

class { 'php::devel': }

if count($php_values['modules']['php']) > 0 {
  php_mod { $php_values['modules']['php']:; }
}
if count($php_values['modules']['pear']) > 0 {
  php_pear_mod { $php_values['modules']['pear']:; }
}
if count($php_values['modules']['pecl']) > 0 {
  php_pecl_mod { $php_values['modules']['pecl']:; }
}

define php_mod {
  php::module { $name: }
}
define php_pear_mod {
  php::pear::module { $name: use_package => false }
}
define php_pecl_mod {
  php::pecl::module { $name: use_package => false }
}

if $php_values['composer'] == 1 {
  class { 'composer':
    target_dir      => '/usr/local/bin',
    composer_file   => 'composer',
    download_method => 'curl',
    logoutput       => false,
    tmp_path        => '/tmp',
    php_package     => 'php5-cli',
    curl_package    => 'curl',
    suhosin_enabled => false,
  }
}

## Begin XDebug manifest

if $xdebug_values == undef {
  $xdebug_values = hiera('xdebug', false)
}

if is_hash($apache_values) {
  $xdebug_webserver_service = 'httpd'
} elsif is_hash($nginx_values) {
  $xdebug_webserver_service = 'nginx'
} else {
  $xdebug_webserver_service = undef
}

class { 'xdebug':
  service => $xdebug_webserver_service
}

if is_hash($xdebug_values['settings']) and count($xdebug_values['settings']) > 0 {
  $xdebug_values['settings'].each { |$key, $value|
    xdebug::augeas { $key:
      value   => $value,
      service => $xdebug_webserver_service
    }
  }
}

## Begin PostgreSQL manifest

if $postgresql_values == undef {
  $postgresql_values = hiera('postgresql', false)
}

class { 'postgresql::server':
  postgres_password => $postgresql_values['root_password'],
}

if is_hash($postgresql_values['databases']) and count($postgresql_values['databases']) > 0 {
  create_resources(postgresql_db, $postgresql_values['databases'])
}

define postgresql_db (
  $user,
  $password,
  $grant,
  $sql_file = false
) {
  postgresql::server::db { $name:
    user     => $user,
    password => $password,
    grant    => $grant
  }

  if $sql_file {
    $table = "${name}.*"

    exec{ "${name}-import":
      command     => "psql ${name} < ${sql_file}",
      logoutput   => true,
      refreshonly => $refresh,
      require     => Postgresql::Server::Db[$name],
      onlyif      => "test -f ${sql_file}"
    }
  }
}

if $php_values == undef {
  $php_values = hiera('php', false)
}

if is_hash($php_values) {
  ensure_packages( ['php5-pgsql'] )
}
```
