### ISSUE TITLE
install pecl_http returned 1 instead of one of [0]

### ISSUE THREAD

**Issue by phirschybar** [puphpet/puphpet#1821]
On `vagrant provision` I am getting this error today:

```
==> default: Error: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
```

and here is my `config.yaml`:

```
---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '2048'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                HGjFaM8IaYBp:
                    host: '7339'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            B8voStJpQtBW:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:

        {... my vhosts ... }

php:
    install: '1'
    settings:
        version: '56'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        short_open_tag: On
        error_reporting: 'E_ERROR'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        upload_max_filesize: 100M
        post_max_size: 100M
        memory_limit: 512M
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '0'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: lapdog
        override_options: {  }
    adminer: 0
    users:
        vsm3Xlyx0AvP:
            name: dbuser
            password: '123'
    databases:
        {... my DBs ...}
    grants:
        JNacNkUWAnsy:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

**Comment by jtreminio** [comment]
Remove `pecl_http`. Something changed recently with it, I've already removed it from defaults.

**Comment by phirschybar** [comment]
thank you, Juan! Keep up the amazing work.

**Comment by brocheafoin** [comment]
What if I actually need pecl_http? I've worked around by specifying the module version (pecl_http-2.4.3) in my config.yaml, but I'd prefer to use the latest versions of everything. The relevant messages are:

`
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: pecl/pecl_http requires package "pecl/raphf" (version >= 1.1.0), installed version is 1.0.4
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: No valid packages found
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: install failed
`

My understanding is that the latest version of pecl/http requires a more recent version of its dependency pecl/raphf, which pecl is not able to install. I can dig in deeper, but my knowledge of Puppet is quite limited.

**Comment by brocheafoin** [comment]
So...

If I add pecl/raphf to my config.yaml and now everything works. Here's the relevant section

```
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
        pear: {  }
        pecl:
            - 'pecl/raphf'
            - pecl_http
            - json
```

This is over my head, but it seems to me that the pecl module should find a way to pass the --onlyreqdeps flag to the install commands, which would ensure dependencies get installed. Not sure if this can be done inside config.yaml with an install_options block or if it's something that would need to be changed in the actual Puppet module. That's where I can no longer help.

In any case, thank you very much for the great work on Puphpet. As evidenced by my messages, I would be completely lost without it! :-)

**Comment by jtreminio** [comment]
@brocheafoin the only thing I can do is add some more logic to https://github.com/puphpet/puppet-puphpet/blob/master/manifests/php/pecl.pp to catch pecl_http. I'll take a look.

**Comment by stiig** [comment]
@brocheafoin 
```
        pecl:
            - raphf
            - pecl_http
            - json
```

it helped get rid of the problem

**Comment by brocheafoin** [comment]
@stiig Yes, that's the manual edit I do now too. Would prefer everything generated by puphpet to work _as is_, but at least I can work around it. If and when I find the time, I may take a crack at a PR for what @jtreminio suggested.

**Comment by therobyouknow** [comment]
Thank you @jtreminio I found that removing pecl_http from beneath pecl: (beneath php:) in the config.yaml to work.

Just to clarify what this precisely what this change is in the config.yaml:

BEFORE:
```
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - 'pecl/raphf'
            - pecl_http
            - json
```

AFTER:

```
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
```

If you just have:
```pecl:```

on its own, this won't work, you'll get an error.

```
==> default: Warning: Could not retrieve fact fqdn
==> default: Error: wrong number of arguments (at least 1) at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/manifest.pp:903 on node packer-virtualbox-iso
==> default: Wrapped exception:
==> default: wrong number of arguments (at least 1)
==> default: Error: wrong number of arguments (at least 1) at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/manifest.pp:903 on node packer-virtualbox-iso
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

 I'm not so familiar with yaml syntax but the {  } means an empty collection and you must have this, as I've described.

I also tried:
```
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - 'pecl/raphf'
            - pecl_http
            - json
```
But this did not work, I got:
```
==> default: Notice: /Stage[main]/Main/Exec[chmod 775 /var/lib/php/session && chown www-data /var/lib/php/session && chgrp www-data /var/lib/php/session]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Exec[dotfiles]/returns: executed successfully
==> default: Notice: /Stage[main]/Drush::Git::Drush/Composer::Exec[drush]/Exec[composer_update_drush]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: pecl/pecl_http requires package "pecl/raphf" (version >= 1.1.0), installed version is 1.0.4
==> default: Notice: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: No valid packages found
==> default: Notice: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: install failed
==> default: Error: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Main/Php_pecl_mod[json]/Puphpet::Php::Pecl[json]/Php::Pecl::Module[json]/Exec[pecl-json]/returns: executed successfully
==> default: Notice: Finished catalog run in 63.36 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
A12Admins-MacBook-Pro:puphpet_20141015_u1204_php55 rob$ 
```

So removing just removing pecl_http asn declaring an empty array/collection for pecl: worked for me (as described above)

```
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
```

**Comment by ebisbe** [comment]
I've just tryied what @brocheafoin suggested and didn't work. I suposo is because my version is 5.6 and his is 5.5.
@therobyouknow your version is 5.5 as seems from your comments?

**Comment by therobyouknow** [comment]
Hi @ebisbe Alright, so did you try 56 in the config.yaml :

INSTEAD of my solution:

```
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
```

DO:

```
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
```

Only difference being 56 instead of 55 


Would this work for you?

**Comment by ebisbe** [comment]
But removing the extension will not solve anything I need that extension. Or I'm missing something?

**Comment by brocheafoin** [comment]
@ebisbe, could you post the relevant parts of Puphpet's output or better yet, a Gist of the whole thing? Same request for your config.yaml.

**Comment by ebisbe** [comment]
Sorry for the delay. 
Console output
```
==> default: Notice: /Stage[main]/Swap_file/Exec[Attach swap file]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Exec[dotfiles]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: pecl/pecl_http requires package "pecl/raphf" (version >= 1.1.0), installed version is 1.0.4
==> default: Notice: /Stage[main]/Main/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: No valid packages found
==> default: Notice: /Stage[main]/Main/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: install failed
==> default: Error: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\\n" | pecl -d preferred_state=stable install pecl_http returned 1 instead of one of [0]
```
config.yaml
```
php:
    install: '1'
    settings:
        version: '56'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - memcached
        pear: {  }
        pecl:
            - raphf
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
```

**Comment by stiig** [comment]
@ebisbe 
you use `vagrant up --provision`? Try it, if not

**Comment by ebisbe** [comment]
@stiig Your command doesn't work because I have already upped my machine. And with provision I still get the same...

**Comment by stiig** [comment]
@ebisbe then use `vagrant provision` or `vagrant reload --provision`

**Comment by jeromegamez** [comment]
Since 2016-01-19, `pecl_http` 3.0 is being the latest stable version, which requires PHP 7.0 or newer. See https://pecl.php.net/package/pecl_http/3.0.0

Is there a way with Puphpet to set a pecl package to a fixed version? 2.5.6 would probably do.

**Comment by wendelyleal** [comment]
Led by @jeromegamez's idea, I managed to get rid of the error suffixing with the version, but It doesn't really installs the extension.

```yaml
php:
...
        pear: {  }
        pecl:
            - pecl/raphf
            - pecl/propro
            - pecl_http-2.5.6
```

No errors, but no `pecl_http` listed.

```console
$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
imagick 3.1.2   stable
mongo   1.6.6   stable
propro  1.0.0   stable
raphf   1.1.0   stable
```

Looks like `precl_http` needs `pecl/raphf` and `pecl/propro` installed **and** being used by PHP: `configure: error: Please install pecl/propro and activate extension=propro.so in your php.ini`. `pecl` module installations are not generating the required .ini files (#1406) and I don't know yet how to automate it, so I `sudo nano /etc/php5/cli/conf.d/zzzz_custom.ini` and:

```ini
[CUSTOM]
...
; required by pecl_http-2.5.6
extension=raphf.so
extension=propro.so
```
```console
$ vagrant provision && vagrant ssh
...
$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package   Version State
imagick   3.1.2   stable
mongo     1.6.6   stable
pecl_http 2.5.6   stable
propro    1.0.0   stable
raphf     1.1.0   stable
```

Right now, it looks fine, but I want to have it on our puphet repository until #1406 isn't fixed. Does anyone know how to add `zzzz_custom.ini` custom lines or something like that?
