### ISSUE TITLE
Change settings of postgresql.conf

### ISSUE THREAD

**Issue by arogachev** [puphpet/puphpet#1835]
How to change settings of `postgresql.conf` through `config,yaml`?

My current settings:

```yaml
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: superuser
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
```

I need to change timezone. I tried inserting

```yaml
timezone: 'Asia/Almaty'
```

into both nodes `global` and `server`, but that didn't help.

I don't want to change it manually since it will be overridden during next provision.
