### ISSUE TITLE
nginx mimetypes

### ISSUE THREAD

**Issue by Amparose** [puphpet/puphpet#1844]
Any idea on how to add custom mimetypes properly in puphpet? I tried adding to config.yaml:

```yaml
types:
    application/vnd.ms-fontobject: eot
    application/x-font-ttf: ttc ttf
    font/opentype: otf
    application/font-woff: woff
```

But was not surprised it didn't work as it was a Hail Mary.
