### ISSUE TITLE
Error when up after successfully install mariadb

### ISSUE THREAD

**Issue by rolies106** [puphpet/puphpet#1847]
After successfully run `vagrant up` for the first time I get this error when I'm trying to reload, halt, or even up the vagrant : 

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

echo; printf $SSH_AUTH_SOCK

Stdout from the command:




Stderr from the command:

printf: usage: printf [-v var] format [arguments]
```

After I run some test, it's caused by `mariadb 10.0` if I'm not include mariadb then it's works like a charm,
my configuration is : 

```
vagrantfile:
    target: local
    vbguest:
        auto_update: false
        no_remote: true
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: mydomain.dev
        memory: '2048'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                ssh:
                    host: '9556'
                    guest: '22'
                mysql:
                    host: '3306'
                    guest: '3306'
                elastic_search:
                    host: '9200'
                    guest: '9200'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            htdocs:
                source: /var/www
                target: /var/www
                sync_type: default
                owner: www-data
                group: www-data                
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        forward_agent: true
        private_key_path: '~/.ssh/id_rsa'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '0'
    groups: {  }
    users: {  }
locale:
    install: '0'
    settings:
        default_locale: 'en_US.UTF-8'
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '0'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        web:
            server_name: mydomain.dev
            server_aliases:
                - mydomain.dev
            www_root: /var/www/webapp/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                web_parent:
                    location: /
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - '$uri $uri/ /index.php?$query_string'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                web_php:
                    location: '~ \.php$'
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - /index.php
                        - =404
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.+)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'APP_ENV dev'
        m:
            server_name: m.mydomain.dev
            server_aliases:
                - m.mydomain.dev
            www_root: /var/www/webapp/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                m_parent:
                    location: /
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - '$uri $uri/ /index.php?$query_string'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                m_php:
                    location: '~ \.php$'
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - /index.php
                        - =404
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.+)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'APP_ENV dev'                    
        api:
            server_name: api.mydomain.dev
            server_aliases:
                - api.mydomain.dev
            www_root: /var/www/api/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                api_parent:
                    location: /
                    autoindex: 'off'
                    try_files:
                        - '$uri $uri/ /index.php?$query_string'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                api_php:
                    location: '~ \.php$'
                    autoindex: 'off'
                    try_files:
                        - $uri
                        - /index.php
                        - =404
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.+)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'APP_ENV dev'
    proxies: {  }
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_5xxpxdkfujei:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
ruby:
    install: '0'
    versions: {  }
python:
    install: '0'
    packages: {  }
    versions: {  }
mariadb:
    install: '1'
    settings:
        version: '10.0'
        root_password: 'root'
        override_options: {  }
    adminer: 0
    databases:
        b2b_db:
            name: mydomain
            sql: ''    
        admin_db:
            name: mydomain_admin
            sql: ''    
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: 'root'
        override_options: {  }
    adminer: 0
    databases:
        b2b_db:
            name: mydomain
            sql: ''    
        admin_db:
            name: mydomain_admin
            sql: ''
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users:
        rmqu_rpsr8e4julia:
            admin: '1'
            name: admin
            password: admin
    vhosts:
        - rabbit.mydomain.dev
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
        config:
            network:
                host: '0.0.0.0'
nodejs:
    install: '1'
    npm_packages: 
        - 'gulp'
        - 'bower'
```
