### ISSUE TITLE
can't change file permission

### ISSUE THREAD

**Issue by deadstar1** [puphpet/puphpet#1862]
I want to change my synced folder permission so i did this 
```
        synced_folder:
            vflsf_j3m2axtj2ekz:
                source: ./
                target: /var/www1
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
                mount_options: ['dmode=666, fmode=666']


```
the the permission of /var/www1 doesn't change :(
