### ISSUE TITLE
Error installing curl 

### ISSUE THREAD

**Issue by lambertb** [puphpet/puphpet#1863]
Hello,
I wanted to add 'curl' to my puppet configuration. Adding it to puphpet/config.yaml and doing an 'vagrant up --provision' gave an error. I use PHP 5.4 as the clients server is running on this one.

```
==> default: Failed to fetch http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu/pool/main/p/php5/php5-curl_5.4.35-1+deb.sury.org~precise+1_i386.deb  404  Not Found
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default: 
==> default: Error: /Stage[main]/Main/Php_mod[curl]/Puphpet::Php::Module[curl]/Php::Module[curl]/Package[PhpModule_curl]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-curl' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following NEW packages will be installed:
==> default:   php5-curl
==> default: 0 upgraded, 1 newly installed, 0 to remove and 157 not upgraded.
==> default: Need to get 29.3 kB of archives.
==> default: After this operation, 115 kB of additional disk space will be used.
==> default: Err http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu/ precise/main php5-curl i386 5.4.35-1+deb.sury.org~precise+1
==> default:   404  Not Found
==> default: Failed to fetch http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu/pool/main/p/php5/php5-curl_5.4.35-1+deb.sury.org~precise+1_i386.deb  404  Not Found
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default: 
==> default: Notice: /Stage[main]/Apache::Service/Service[httpd]: Dependency Package[PhpModule_curl] has failures: true
==> default: Warning: /Stage[main]/Apache::Service/Service[httpd]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 49.32 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Anyone know the problem and a solution?

My config.yaml is where I added the curl in php/modules/php:

```
---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: ''
        memory: '2084'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                RY9msUwTNIZ9:
                    host: '9672'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            MHJ1zbbanCDE:
                source: /Users/Lambert/htdocs/ipp
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        N4XxoSvekGq6:
            servername: vm
            docroot: /var/www/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        vRVOOfS5fBSp:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        post_max_size:  '20M'
        upload_max_filesize: '20M'
        memory_limit: '1024M'
    timezone: Europe/Amsterdam
    mod_php: '1'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        zGUKzpZb3dLX:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        EQz4GPiShdsZ:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: root
    adminer: '1'
    databases:
        zvAFhu6BjYmM:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true
```
