### ISSUE TITLE
misconfigured value for nginx internal location option

### ISSUE THREAD

**Issue by cyluss** [puphpet/puphpet#1869]
# Problem
`vagrant up` command gives the following error message.
```
==> default: Error: "off" is not a boolean.  It looks to be a String at /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/nginx/manifests/resourc
e/location.pp:198 on node local.puphpet                                                                                                                     
```

# Reason
There is misconfigured value for nginx internal location option.
In nginx section of `config.yaml`, nginx.vhosts.{id}.locations.{id}.internals should be either `true` or `false`, not `true` or `off`. This makes `vagrant up` to fail.

# Solution
Please replace `internal: 'off'` with `internal: false` in `config.yaml`.

# Details
## part of `config.yaml`
```
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_rpgwwnhfw7d4:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_y4a4vleov70t:
                    location: /
                    autoindex: 'off'
                    internal: 'true'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_kvb1mymippkw:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
```

## error trace
```
==> default: Running provisioner: puppet...                                                                                                                 
==> default: Running Puppet with site.pp...                                                                                                                 
==> default: stdin: is not a tty                                                                                                                            
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/apt/lib/facter/apt_updates.rb                              
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/apt/lib/facter/apt_update_last_success.rb                  
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/composer/lib/facter/composer_home.rb                       
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/concat/lib/facter/concat_basedir.rb                        
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/firewall/lib/facter/ip6tables_version.rb                   
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/firewall/lib/facter/iptables_persistent_version.rb         
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/firewall/lib/facter/iptables_version.rb                    
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/git/lib/facter/git_exec_path.rb                            
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/git/lib/facter/git_version.rb                              
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/java/lib/facter/java_major_version.rb                      
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/java/lib/facter/java_patch_level.rb                        
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/java/lib/facter/java_version.rb                            
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/php/lib/facter/php_fact_extension_dir.rb                   
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/php/lib/facter/php_fact_version.rb                         
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/puppi/lib/facter/last_run.rb                               
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/puppi/lib/facter/puppi_projects.rb                         
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/puppi/lib/facter/windows_common_appdata.rb                 
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/rvm/lib/facter/rvm_installed.rb                            
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/rvm/lib/facter/rvm_version.rb                              
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/staging/lib/facter/staging_http_get.rb                     
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/staging/lib/facter/staging_windir.rb                       
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/stdlib/lib/facter/facter_dot_d.rb                          
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/stdlib/lib/facter/pe_version.rb                            
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/stdlib/lib/facter/puppet_vardir.rb                         
==> default: Info: Loading facts in /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/stdlib/lib/facter/root_home.rb                             
==> default: Error: "off" is not a boolean.  It looks to be a String at /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/nginx/manifests/resourc
e/location.pp:198 on node local.puphpet                                                                                                                     
==> default: Error: "off" is not a boolean.  It looks to be a String at /tmp/vagrant-puppet/modules-46226714e23c0369093911d4d5ccdbe0/nginx/manifests/resourc
e/location.pp:198 on node local.puphpet                                                                                                                     
The SSH command responded with a non-zero exit status. Vagrant                                                                                              
assumes that this means the command failed. The output for this command                                                                                     
should be in the log above. Please read the output to determine what                                                                                        
went wrong.                                                                                                                                                                                                                                                                                             ```
