### ISSUE TITLE
RabbitMQ - Management

### ISSUE THREAD

**Issue by steefaan** [puphpet/puphpet#1897]
Afer I have installed RabbitMQ with `rabbitmq_management` I'm not able to access the interface with `192.168.50.100:15672`. Regarding the documentation from RabbitMQ it should work directly without any additional configuration. This is how my puphpet configuration looks like.

```
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users:
        rmqu_oabzwvt9o9s4:
            admin: '1'
            name: admin
            password: password
            permissions:
                rmqup_97oi19knbo6q:
                    host: /dev
                    configure_permission: '.*'
                    read_permission: '.*'
                    write_permission: '.*'
    vhosts:
        - /dev
    plugins:
        - rabbitmq_management
```

I get `Connection Timeout` when I try to access the interface. I have also MailCatcher installed at port `1080` and this works without pain. 

Some details about my virtual machine, it may helps:

`netstat -nptl | grep 15672`
```
3:tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      31120/beam
```

`rabbitmq-plugins list`
```
[e*] amqp_client                       3.5.4
[e*] mochiweb                          2.7.0-rmq3.5.4-git680dba8
[E*] rabbitmq_management               3.5.4
[E*] rabbitmq_management_agent         3.5.4
[e*] rabbitmq_web_dispatch             3.5.4
[e*] webmachine                        1.10.3-rmq3.5.4-gite9359c7
```

`rabbitmqctl status`
```
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.5.4"},
     // -->
```

`/var/log/rabbitmq/rabbit@local.log`

```
// -->
=INFO REPORT==== 14-Sep-2015::20:09:31 ===
Management plugin started. Port: 15672
// -->
=INFO REPORT==== 14-Sep-2015::20:09:31 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * webmachine
 * mochiweb
 * rabbitmq_management_agent
 * amqp_client
// -->
```

**Comment by steefaan** [comment]
If someone has the same problem, add the following lines to you config.yml

```
                vflnp_46r7whyi9ns3:
                    host: '5672'
                    guest: '5672'
                vflnp_sogicrjbvzmm:
                    host: '15672'
                    guest: '15672'
```

I keep the ticket open, maybe it would be useful if the ports are automatically forwarded when you setup `RabbitMQ` with puphpet. If not please close this issue.
