### ISSUE TITLE
Apache - Server Alias for Directory

### ISSUE THREAD

**Issue by Zeromax** [puphpet/puphpet#1905]
Screen from default config. See the Directory Block, where the Field name is `Server Alias`.
The Field name is wrong and Should be `Options`.
Btw: `Server Alias` field for Directories is missing ;)

My target is to Add a alias for `phpmyadmin` like:
```
Alias /phpmyadmin "/var/www/phpmyadmin/"
<Directory "/var/www/phpmyadmin">
  AllowOverride All
  Require all granted

  <FilesMatch "\.php$">
    Require all granted
    SetHandler proxy:fcgi://127.0.0.1:9000

  </FilesMatch>
</Directory>
```

![unbenannt](https://cloud.githubusercontent.com/assets/1867177/9959403/faa71810-5e13-11e5-8e16-68813ac9ef58.PNG)

```yaml
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_p0zamrb8wbcg:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_48ptkx7man93:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_svv46zkyr9rx:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
```
