### ISSUE TITLE
Can't see adminer / windows 10

### ISSUE THREAD

**Issue by Andryta** [puphpet/puphpet#1908]
I have the vagrant instance working,  Host file updated with the localhost
192.168.56.101  betbit.local www.betbit.local

Even though, I got "The requested URL /adminer/ was not found on this server."

This is the config.yaml config

```
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '2048'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port: { }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            II54vtWU2126:
                source: .
                target: /vagrant
                sync_type: SMB
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - nodejs
        - npm
        - screen
        - memcached
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: vagrant
        group: vagrant
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        dev:
            servername: dev.betbit
            docroot: /vagrant/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - None
            engine: ''
            custom_fragment: |
                <Directory "/vagrant/web">
                    DirectoryIndex app_dev.php

                    <IfModule mod_rewrite.c>
                        RewriteEngine On
                        RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
                        RewriteRule ^(.*) - [E=BASE:%1]
                        RewriteCond %{ENV:REDIRECT_STATUS} ^$
                        RewriteRule ^app_dev\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]

                        RewriteCond %{REQUEST_FILENAME} -f
                        RewriteRule .? - [L]

                        RewriteRule .? %{ENV:BASE}/app_dev.php [L]
                    </IfModule>
                </Directory>

                ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/vagrant/web/$1
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        prod:
            servername: prod.betbit
            docroot: /vagrant/web
            port: '80'
            setenv:
                - 'APP_ENV prod'
            override:
                - None
            engine: ''
            custom_fragment: |
                <Directory "/vagrant/web">
                    DirectoryIndex app.php

                    <IfModule mod_rewrite.c>
                        RewriteEngine On
                        RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
                        RewriteRule ^(.*) - [E=BASE:%1]
                        RewriteCond %{ENV:REDIRECT_STATUS} ^$
                        RewriteRule ^app\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]

                        RewriteCond %{REQUEST_FILENAME} -f
                        RewriteRule .? - [L]

                        RewriteRule .? %{ENV:BASE}/app.php [L]
                    </IfModule>
                </Directory>

                ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/vagrant/web/$1
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts: {  }
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - intl
            - mcrypt
            - sqlite
            - memcached
            - gd
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/London
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    ini: {  }
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.remote_enable: '1'
        xdebug.remote_connect_back: '0'
        xdebug.profiler_enable_trigger: '1'
        xdebug.profiler_output_dir: /vagrant/profile
        xdebug.remote_host: 10.0.2.2
        xdebug.idekey: PHPSTORM
        xdebug.max_nesting_level: '200'
xhprof:
    install: '0'
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '0'
    root_password: '123'
    adminer: 0
    databases:
        8AdkfJxjPh9K:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '1'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases:
        0xlj2qjF4Som:
            grant: ALL
            name: betbit
            user: betbit
            password: champ10n
            sql_file: ''
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true

```

Thanks for any help
