### ISSUE TITLE
nfs + npm

### ISSUE THREAD

**Issue by WebDevTmas** [puphpet/puphpet#1915]
I'm unable to do a npm install on the nfs share where the owner and group is forceable changed to www-data.
I can hower run npm install --global (after chown -R www-data:www-data /usr/local/bin) or run npm install with a package.json that's not on the nfs share.
I assume this is because of the forced user rights? Running with sudo (which is not done) doesn't work either.

I alos had to chmod /tmp due to errors  as mentiond in: https://github.com/puphpet/puphpet/issues/1839

Here is the error: 
```
npm ERR! tar.unpack untar error /home/vagrant/.npm/plottable.js/0.50.2/package.tgz
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/home/vagrant/.nvm/versions/node/v4.1.1/bin/node" "/home/vagrant/.nvm/versions/node/v4.1.1/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path /var/www/web-app/protected/node_modules/plottable.js/package.json
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall chmod

npm ERR! Error: EPERM: operation not permitted, chmod '/var/www/web-app/protected/node_modules/plottable.js/package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, chmod '/var/www/web-app/protected/node_modules/plottable.js/package.json']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'chmod',
npm ERR!   path: '/var/www/web-app/protected/node_modules/plottable.js/package.json',
npm ERR!   fstream_finish_call: 'chmod',
npm ERR!   fstream_type: 'File',
npm ERR!   fstream_path: '/var/www/web-app/protected/node_modules/plottable.js/package.json',
npm ERR!   fstream_class: 'FileWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/home/vagrant/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/fstream/lib/writer.js:306:21',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/web-app/protected/npm-debug.log

```

Config:

```
vagrantfile:
    target: local
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: thomas.dev
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_3twde752o79p:
                    host: '6933'
                    guest: '22'
                port_80:
                    host: '8080'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_6ob5dbd0phx8:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - htop
        - rsync
        - wget
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: nl_BE.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - nl_BE.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_r4et2or9sbln:
            server_name: spruce.thomas.dev
            server_aliases:
                - www.spuce.thomas.dev
            www_root: /var/www/spruce
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
        nxv_8kzrp075w1ra:
            server_name: redwood.thomas.dev
            server_aliases:
                - www.redwood.thomas.dev
            www_root: /var/www/redwood/web
            listen_port: '80'
            index_files:
                - app.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
        nxv_bslty9sbhwt0:
            server_name: maple.thomas.dev
            server_aliases:
                - www.maple.thomas.dev
            www_root: /var/www/maple
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
        nxv_ncrp6w0lq6zd:
            server_name: web-app.thomas.dev
            server_aliases:
                - www.web-app.thomas.dev
            www_root: /var/www/web-app
            listen_port: '80'
            index_files:
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_v54cf6orw2ce:
                    location: /
                    autoindex: 'off'
                    internal: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_wh4at0rskj3a:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'off'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_lupjpnkym435:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_aq1qsxornqsy:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_b2c99pgwaynb:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '0'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_qxt1ofl1smke:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '1'
    settings:
        server_id: 'f3ab4b52-f705-4bb8-9629-c12bc754f1d1'
        server_token: '89357f74cf8fc0f5a40ce2100e89417ef5fcca026daa20d16d7f1d315a070fd7'
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }pu
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - gulp
        - bower
        - jasmine
        - karma
        - phantomjs
hhvm:
    install: '1'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_h53r2yd4hjlt:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_lrcppsnbpdkm:
            name: dbname
            sql: ''
    grants:
        mysqlng_let2fvhix4sy:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mariadb:
    install: '1'
    settings:
        version: '10.0'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_bl9f9ugdwt30:
            name: thomas
            password: diligentia
        mariadbnu_b6p27ulconch:
            name: peter
            password: diligentia
        mariadbnu_vzaxtef19369:
            name: dimitri
            password: diligentia
        mariadbnu_c2t5rowe0oo2:
            name: matthias
            password: diligentia
    databases: {  }
    grants:
        mariadbng_sqer8qwjh4p7:
            user: thomas
            table: '*.*'
            privileges:
                - ALL
        mariadbng_j4pugasy3nea:
            user: peter
            table: '*.*'
            privileges:
                - ALL
        mariadbng_4dy60n0b4bbk:
            user: matthias
            table: '*.*'
            privileges:
                - ALL
        mariadbng_3hkx9mmbujwv:
            user: dimitri
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
