### ISSUE TITLE
Conflicting configuration hhvm

### ISSUE THREAD

**Issue by WebDevTmas** [puphpet/puphpet#1921]
With hhvm.libxml.ext_entity_whitelist in both server_ini and php_ini I get the following error:

```
==> default: Error: Duplicate declaration: Augeas[hhvm.libxml.ext_entity_whitelist: file,http] is already declared in file /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Hhvm.pp:58; cannot redeclare at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Hhvm.pp:79 on node thomas.dev
==> default: Error: Duplicate declaration: Augeas[hhvm.libxml.ext_entity_whitelist: file,http] is already declared in file /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Hhvm.pp:58; cannot redeclare at /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a/nodes/Hhvm.pp:79 on node thomas.dev
````

However when I just put it in server_ini it works "perfectly". The fix for a bug suggested that it had to be in both files.
https://github.com/facebook/hhvm/issues/3797

```
hhvm:
    install: '1'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.user: vagrant
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
        hhvm.libxml.ext_entity_whitelist: file,http
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
        hhvm.libxml.ext_entity_whitelist: file,http
```
