### ISSUE TITLE
Error: 'false' is not a boolean.

### ISSUE THREAD

**Issue by vincenzo** [puphpet/puphpet#1932]
This relates to #1882. 
I can see there's been an attempt at fixing it, but now it's being set to `'false'` rather than `false`. That is, it's still a string rather than a boolean.

```
==> default: Error: "false" is not a boolean.  It looks to be a String at /tmp/vagrant-puppet/modules-133be20d78918bc00a2511665383c540/nginx/manifests/resource/location.pp:198 on node ...
==> default: Error: "false" is not a boolean.  It looks to be a String at /tmp/vagrant-puppet/modules-133be20d78918bc00a2511665383c540/nginx/manifests/resource/location.pp:198 on node ...
```

And an excerpt of the config file that was generated for me. Note the `'false'` rather than `false` for `internal:`. 

```yaml
locations:
                nxvl_iwxtva3hul6k:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_mqmmu4i6ysu0:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
```
