### ISSUE TITLE
Could not find resource 'Mysql_database[]' for relationship from 'Mysql_user[root@localhost]'

### ISSUE THREAD

**Issue by herzmut** [puphpet/puphpet#1936]
Hello there. You had this issue before (#202) and that pest returned.

I dropped an old Puphpet generated config.yaml into your latest Puphpet generator and it gave me this in the section mysql:

```yaml
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users: {  }
    databases: 
        - devDb
    grants: {  }
```

It was not exactly like the old file which had at least one user.

**Comment by dguhl** [comment]
The error also appeared on a full configured section:

```yaml
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_dey0vya4p9q1:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_jlnqxy8ndylc:
            name: dbname
            sql: ''
    grants:
        mysqlng_ugpq5icjj0nf:
            user: dbuser
            table: 'dbname.*'
            privileges:
                - ALL
```
