### ISSUE TITLE
nginx vhost config files are created twice

### ISSUE THREAD

**Issue by dguhl** [puphpet/puphpet#1938]
Your config files are created and linked twice in /etc/nginx/sites-enabled, once with and once without the generated nxv_ prefixes.

This does not only cause warnings on server start, but it also lets nginx ignore server configurations and leads to unpleasant behavior, like, let's say, download of PHP files?

**Comment by jtreminio** [comment]
Show me your config.yaml - this isn't happening to me or anyone else I've spoken with.

**Comment by dguhl** [comment]
Here you have it. I doubt you'll find anything on the config if the flaw is on the script.

```yaml
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_xrbs35ziv3ss:
                    host: '9140'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_zdwankij21u4:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            4EYcw7i80e0K:
                owner: www-data
                group: www-data
                source: ~/Projects
                target: /var/www
                sync_type: default
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - htop
        - mysql-utilities
        - nfs-common
        - libssh2-php
        - build-essential
users_groups:
    install: '1'
    groups:
        - dev
    users:
        - dev
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_j67r58ptoe44:
            server_name: main.dev
            www_root: /var/www/main/frontend
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
            locations:
                nxvl_dhvze372sjvad:
                    location: '~ \.php$'
                    location_cfg_prepend:
                        rewrite: ^/(.*)/$ /$1 permanent
                    location_cfg_append:
                        fastcgi_read_timeout: 300
                        fastcgi_send_timeout: 300
                        fastcgi_connect_timeout: 300
                        fastcgi_intercept_errors: 'on'
                        error_page: '404 /404.html'
                    autoindex: 'off'
                    internal: false
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                nxvl_duzh673db872365d:
                    location: '/'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
        nxv_71mr2w2y5z09:
            server_name: backend.dev
            www_root: /var/www/main/backend
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
            locations:
                nxvl_67rehcvbae4323:
                    location: '~ \.php$'
                    location_cfg_prepend:
                        rewrite: ^/(.*)/$ /$1 permanent
                    location_cfg_append:
                        fastcgi_read_timeout: 300
                        fastcgi_send_timeout: 300
                        fastcgi_connect_timeout: 300
                        fastcgi_intercept_errors: 'on'
                        error_page: '404 /404.html'
                    autoindex: 'off'
                    internal: false
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                nxvl_3618dhd982zns23t6d:
                    location: '/'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        av_4eq6hg2cmb0m:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_csozg5ls9giy:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        max_input_vars: '99999'
        upload_max_filesize: 512M
        post_max_size: 5M
        default_socket_timeout: '300'
        max_execution_time: '300'
        memory_limit: 128M
        sendmail_path: '/usr/bin/env catchmail -f vagrant@devstudio.de'
        cgi.fix_pathinfo: 0
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_5djly7gzbvjf:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: 1
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '1'
        xdebug.remote_connect_back: '0'
        xdebug.remote_host: 192.168.56.1
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.remote_mode: req
        xdebug.idekey: PhpStorm
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_9nzvhejwrhim:
            default: '1'
            version: 2.1.2
            gems:
                - sass
                - compass
                - mailcatcher
python:
    install: '0'
    packages: {  }
    versions:
        pyenv_u24bnwf8pnod:
            version: 2.7.6
nodejs:
    install: '0'
    npm_packages:
        - grunt@0.4.5
        - grunt-cli
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '0'
    users:
        mysqlnu_dey0vya4p9q1:
            name: database
            password: '123'
    databases:
        mysqlnd_jlnqxy8ndylc:
            name: database
            sql: ''
    grants:
        mysqlng_ugpq5icjj0nf:
            user: database
            table: 'database.*'
            privileges:
                - ALL
mariadb:
    install: '1'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_dey0vya4p9q1:
            name: database
            password: '123'
    databases:
        mysqlnd_jlnqxy8ndylc:
            name: database
            sql: '/var/www/main/dump.sql'
    grants:
        mysqlng_ugpq5icjj0nf:
            user: database
            table: 'database.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
