### ISSUE TITLE
vagrant host name limitation

### ISSUE THREAD

**Issue by webmake** [puphpet/puphpet#1959]
Vagrant having issue with vhosts generation:
currently all projects servername and serveraliases comes into single line at hosts file in windows.
Windows has issue with more than 9 aliases (http://superuser.com/questions/932112/is-there-a-maxium-number-of-hostname-aliases-per-line-in-a-windows-hosts-file) , and that 10th servername ping gives 127.0.53.53 with error in browser: ERR_ICANN_NAME_COLLISION 

Please split vhosts per project, I mean let's say:
```
192.168.56.20 servername1.dev serveraliases1.dev
192.168.56.20 servername2.dev serveraliases2.dev
```
instead of:
`192.168.56.20 servername1.dev serveraliases1.dev servername2.dev serveraliases2.dev`
Either can tell which file responsible for that to make PR, thanks

**Comment by qari** [comment]
use puphpet/config.yaml   hostname: RANDOM_NAME.puphpet

**Comment by webmake** [comment]
Well, to be clear what problem I faced:
```
## vagrant-hostmanager-start id: 85186b5e-9f4b-424e-829a-c49e73ccfe60
192.168.56.101	project.loc.vm.puphpet project1.dev www.project1.dev project2.dev www.project2.dev project3.dev www.project3.dev project4.dev www.project4.dev project5.dev www.project5.dev
## vagrant-hostmanager-end
```
with following configuration.
```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: project.loc.vm.puphpet
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.20
            forwarded_port:
                vflnp_a5aqs6ckbavr:
                    host: '8683'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_7xxnqfy1bhag:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: 'files/dot/ssh'
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules:
        fr_mq5044zj9ahw:
            port:
                - '80'
                - '9000'
                - '9001'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - headers
    vhosts:
        av_1:
            servername: project1.dev
            serveraliases:
                - www.project1.dev
            docroot: /var/www/project1
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_1:
                    path: /var/www/project1
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_1:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_2:
            servername: project2.dev
            serveraliases:
                - www.project2.dev
            docroot: /var/www/project2
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_2:
                    path: /var/www/project2
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_2:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_3:
            servername: project3.dev
            serveraliases:
                - www.project3.dev
            docroot: /var/www/project3
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_3:
                    path: /var/www/project3
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_3:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_4:
            servername: project4.dev
            serveraliases:
                - www.project4.dev
            docroot: /var/www/project4
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_4:
                    path: /var/www/project4
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_4:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_5:
            servername: project5.dev
            serveraliases:
                - www.project5.dev
            docroot: /var/www/project5
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_5:
                    path: /var/www/project5
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        error_log: php_errors.log
        log_errors: '1'
        allow_url_fopen: '1'
        max_execution_time: '60'
        short_open_tag: '1'
        memory_limit: 200m
        display_startup_errors: '1'
        max_input_nesting_level: '60'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_dtomijn0mr4n:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: 'root'
        override_options: {  }
    users:
        mysqlnu_v40asitlcfpi:
            name: 'project'
            password: 'project'
    databases:
        mysqlnd_bkwo1jlyip9b:
            name: 'project'
            sql: ''
    grants:
        mysqlng_zamcii5cq0k8:
            user: 'project'
            table: '*.*'
            privileges:
                - ALL
```
Your mentioned hostname is not solution when I link 5projects with their own aliases in same virtual box. 5th project becomes unreachable, due hosts file limitation (ERR_ICANN_NAME_COLLISION)
