### ISSUE TITLE
PEAR packages version not provisioned

### ISSUE THREAD

**Issue by miaoulafrite** [puphpet/puphpet#1964]
Hi,

thanks a lot for this very handy tool!

i've got troubles with a PEAR package to change version. The box is *puphpet/centos65-x64*

```yaml
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - soap
        pear:
            - PHP_CodeSniffer-1.4.2
        pecl:
            - pecl_http
```

i need to change to version 1.5.6, but if i change the config.yaml to 

```yaml
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - soap
        pear:
            - PHP_CodeSniffer-1.5.6
        pecl:
            - pecl_http
```

and then

```bash
vagrant provision
```

it doesn't change the version.
Is there another way to specify the version of a pear package in the config?
