### ISSUE TITLE
Vagrant Up using an already generated RSA Key

### ISSUE THREAD

**Issue by tlartaud** [puphpet/puphpet#1992]
Hi there,

I'm on **Windows OS**.
Before the really first vagrant up, I configured the file `config.yaml` to contain the following
```
ssh:
        host: null
        port: null
        private_key_path: 'C:\Users\Thomas\.ssh\id_rsa'
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: true
        forward_x11: false
        shell: 'bash -l'
```

In the file https://github.com/puphpet/puphpet/blob/master/archive/puphpet/shell/ssh-keygen.sh, we can read that a new keygen file will be generated.

Is it possible to use the key provided in `private_key_path` instead of generating a new one ?
Actually, the RSA key that I need (and which is already loaded in Pageant [=ssh-agent for windows]) is located in `C:\Users\Thomas\.ssh\id_rsa`. The one used by the VM is located in `C:\Users\Thomas\my_project\puphpet\files\dot\ssh\id_rsa`.

I have some scripts attached to my vagrant up (vagrant-triggers and more) that need my main key to be already added to the authorized_key file inside my VM, because my vagrant up will also try to run a composer installation in the same time. The composer file contain paths to private repository, and the proper RSA Key need to be used to access that repositories.

It would be really helpfull that the keygen script you provide let us chose between a new key generation, or using an already existing and loaded key (via ssh-agent or pageant).

Is it already possible or may I need to create myself an SH script to perform that ?

Thanks a lot.
