### ISSUE TITLE
Untrusted signature, hash sum mismatch, and puppet-agent failure after updating box.

### ISSUE THREAD

**Issue by refringe** [puphpet/puphpet#2023]
This morning I received a notice that my box was in need of an update:
```
==> default: A newer version of the box 'puphpet/ubuntu1404-x64' is available! You currently
==> default: have version '20151128'. The latest is version '20151201'. Run
==> default: `vagrant box update` to update.
```

So I ran `vagrant box update` and it updated successfully.

But now when I `vagrant up` I'm getting a number of errors that were not present before.

```
==> default: Installing RVM and Ruby 1.9.3
==> default: gpg: directory `/root/.gnupg' created
==> default: gpg: new configuration file `/root/.gnupg/gpg.conf' created
==> default: gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
==> default: gpg: keyring `/root/.gnupg/secring.gpg' created
==> default: gpg: keyring `/root/.gnupg/pubring.gpg' created
==> default: gpg: requesting key D39DC0E3 from hkp server keyserver.ubuntu.com
==> default: gpg: /root/.gnupg/trustdb.gpg: trustdb created
==> default: gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
==> default: gpg: no ultimately trusted keys found
==> default: gpg: Total number processed: 1
==> default: gpg:               imported: 1  (RSA: 1)
==> default: Turning on quiet curl mode.
==> default: Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
==> default: Downloading https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
==> default: gpg:
==> default: Signature made Mon 30 Mar 2015 09:52:13 PM UTC using RSA key ID BF04FF17
==> default: gpg:
==> default: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
==> default: gpg:
==> default: WARNING: This key is not certified with a trusted signature!
==> default: gpg:
==> default:          There is no indication that the signature belongs to the owner.
==> default: Primary key fingerprint:
==> default:  409B
==> default:  6B17
==> default:  96C2
==> default:  7546
==> default:  2A17
==> default:
==> default:  0311
==> default:  3804
==> default:  BB82
==> default:  D39D
==> default:  C0E3
==> default:      Subkey fingerprint:
==> default:  62C9
==> default:  E5F4
==> default:  DA30
==> default:  0D94
==> default:  AC36
==> default:
==> default:  166B
==> default:  E206
==> default:  C29F
==> default:  BF04
==> default:  FF17
```

Everything else during the normal `up` appears to run fine. However, I have an [exec-once script](https://gist.github.com/refringe/7154466a2852d5267cfc) that runs `apt-get update` and during that I get this error:

```
==> default: W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch
==> default:
==> default: W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch
==> default:
==> default: W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-i386/Packages  Hash Sum mismatch
==> default:
==> default: E: Some index files failed to download. They have been ignored, or old ones used instead.
```

After that I'm doing an `apt-get upgrade` and I'm getting this error when `puppet-agent` attempts to update.

```
==> default: Setting up puppet-agent (1.3.2-1trusty) ...
==> default:  * Restarting puppet agent
==> default:    ...fail!
==> default: invoke-rc.d: initscript puppet, action "condrestart" failed.
```

**Using Virtualbox 5.0.10 & Vagrant 1.7.4.**

Here's my `config.yaml`:
```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: local.testing
        memory: '768'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_r75iyhjuwhz5:
                source: 'C:\Server'
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - memcached
        - imagemagick
        - autotrace
        - cups-bsd
        - lpr
        - lprng
        - enscript
        - gimp
        - gnuplot
        - grads
        - hp2xx
        - html2ps
        - libwmf-bin
        - mplayer
        - povray
        - radiance
        - sane-utils
        - texlive-base-bin
        - transfig
        - xdg-utils
        - ufraw-batch
        - ttf-baekmuk
        - librsvg2-bin
        - libwmf0.2-7-gtk
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        nxv_g30fwb2wo8w0:
            server_name: beta.testing-en.local
            server_aliases:
                - beta.testing-en.local
            www_root: /var/www/testing/public
            listen_port: '80'
            index_files:
                - index.php
            client_max_body_size: 100m
            client_body_timeout: 300s
            ssl: '1'
            ssl_cert: /var/www/testing/private/certificates/beta.testing-en.local.crt
            ssl_key: /var/www/testing/private/certificates/beta.testing-en.local.key
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_3x40wjima1ha:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_hjr5fzqav6do:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'CI_ENV development'
        nxv_1r4ivq3o9h2c:
            server_name: beta.testing-fr.local
            server_aliases:
                - beta.testing-fr.local
            www_root: /var/www/testing/public
            listen_port: '80'
            index_files:
                - index.php
            client_max_body_size: 100m
            client_body_timeout: 300s
            ssl: '1'
            ssl_cert: /var/www/testing/private/certificates/beta.testing-fr.local.crt
            ssl_key: /var/www/testing/private/certificates/beta.testing-fr.local.key
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_busxr3kud8dg:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_r9nse4i992r0:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'CI_ENV development'
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_8ywog2u2bo9i:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_dkzrsyrpj0ng:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_77ivmf2vryfm:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - geoip
            - imagick
            - ldap
            - mbstring
            - memcache
            - memcached
            - mysql
            - mysqlnd
            - tidy
        pear: {  }
        pecl:
            - pecl_http
    ini:
        memory_limit: 256M
        display_errors: 'On'
        error_reporting: E_ALL
        html_errors: 'Off'
        session.save_path: /var/lib/php/session
        short_open_tag: 'Off'
        post_max_size: 100M
        default_charset: UTF-8
        upload_max_filesize: 100M
        max_file_uploads: '20'
        max_execution_time: '300'
        max_input_time: '300'
        date.timezone: UTC
        session.gc_probability: '1'
        session.gc_divisor: '25'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_jdtk6czw4xp8:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.var_display_max_depth: '-1'
        xdebug.var_display_max_children: '-1'
        xdebug.var_display_max_data: '-1'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: '215484'
        override_options: {  }
    adminer: 0
    users: {  }
    databases:
        mysqlnd_9cho3r1f917h:
            name: testing
    grants: {  }
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '215484'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_nfpw6fovnmoh:
            name: testing
            password: '215484'
    databases:
        mariadbnd_7syp685iejaa:
            name: testing
    grants:
        mariadbng_rx6u0bmmavr5:
            user: testing
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
