### ISSUE TITLE
Installs php5-memcached, but does not enable it. No config (ini) file found.

### ISSUE THREAD

**Issue by refringe** [puphpet/puphpet#2036]
I'm using Vagrant 1.7.4 and VirtualBox 5.0.10 with a fresh puphpet.com archive.

When running a fresh `vagrant up` there are no errors, but the PHP Memcached class is not available. 

The php5-memcached package is installed:
```
sudo apt-get install php5-memcached
Reading package lists... Done
Building dependency tree
Reading state information... Done
php5-memcached is already the newest version.
```

As well as Memcached itself:
```
sudo apt-get install memcached
Reading package lists... Done
Building dependency tree
Reading state information... Done
memcached is already the newest version.
```

Memcached is running fine:
```
[05:02 PM]-[vagrant@local]-[~]
$ ps aux | grep memcached
119:vagrant   9012  0.0  0.0   8868   836 pts/2    S+   17:03   0:00 grep --color=auto -in memcached
121:memcache 13016  0.0  0.1 325400  2620 ?        Sl   16:50   0:00 /usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1

[05:03 PM]-[vagrant@local]-[~]
$ echo "stats settings" | nc localhost 11211
STAT maxbytes 67108864
STAT maxconns 1024
STAT tcpport 11211
STAT udpport 11211
STAT inter 127.0.0.1
STAT verbosity 0
STAT oldest 0
STAT evictions on
STAT domain_socket NULL
STAT umask 700
STAT growth_factor 1.25
STAT chunk_size 48
STAT num_threads 4
STAT num_threads_per_udp 4
STAT stat_key_prefix :
STAT detail_enabled no
STAT reqs_per_event 20
STAT cas_enabled yes
STAT tcp_backlog 1024
STAT binding_protocol auto-negotiate
STAT auth_enabled_sasl no
STAT item_size_max 1048576
STAT maxconns_fast no
STAT hashpower_init 0
STAT slab_reassign no
STAT slab_automove 0
END
```

**When running the `phpinfo()` function. Memcached is not listed.** There is also no memcached config file listed where all of the other package config files are located:

```
ls -la /etc/php5/fpm/conf.d/
total 8
drwxr-xr-x 2 root root 4096 Dec  7 16:54 ./
drwxr-xr-x 4 root root 4096 Dec  7 16:53 ../
lrwxrwxrwx 1 root root   32 Dec  7 16:49 05-opcache.ini -> ../../mods-available/opcache.ini
lrwxrwxrwx 1 root root   28 Dec  7 16:49 10-pdo.ini -> ../../mods-available/pdo.ini
lrwxrwxrwx 1 root root   29 Dec  7 16:54 20-curl.ini -> ../../mods-available/curl.ini
lrwxrwxrwx 1 root root   27 Dec  7 16:54 20-gd.ini -> ../../mods-available/gd.ini
lrwxrwxrwx 1 root root   32 Dec  7 16:54 20-imagick.ini -> ../../mods-available/imagick.ini
lrwxrwxrwx 1 root root   29 Dec  7 16:54 20-intl.ini -> ../../mods-available/intl.ini
lrwxrwxrwx 1 root root   29 Dec  7 16:49 20-json.ini -> ../../mods-available/json.ini
lrwxrwxrwx 1 root root   29 Dec  7 16:54 20-ldap.ini -> ../../mods-available/ldap.ini
lrwxrwxrwx 1 root root   31 Dec  7 16:54 20-mcrypt.ini -> ../../mods-available/mcrypt.ini
lrwxrwxrwx 1 root root   30 Dec  7 16:54 20-mysql.ini -> ../../mods-available/mysql.ini
lrwxrwxrwx 1 root root   31 Dec  7 16:54 20-mysqli.ini -> ../../mods-available/mysqli.ini
lrwxrwxrwx 1 root root   34 Dec  7 16:54 20-pdo_mysql.ini -> ../../mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root   33 Dec  7 16:49 20-readline.ini -> ../../mods-available/readline.ini
lrwxrwxrwx 1 root root   29 Dec  7 16:54 20-tidy.ini -> ../../mods-available/tidy.ini
lrwxrwxrwx 1 root root   40 Dec  7 16:53 zzzz_custom.ini -> /etc/php5/mods-available/zzzz_custom.ini
```

Here are some relevant up notices:
```
==> default: Notice: /Stage[main]/Puphpet_server/Package[augeas-tools]/ensure: created
==> default: Notice: /Stage[main]/Puphpet_server/Package[memcached]/ensure: created
==> default: Notice: /Stage[main]/Puphpet_server/Package[imagemagick]/ensure: created
[...]
``` 

```
==> default: Notice: /Stage[main]/Nginx::Service/Service[nginx]: Triggered 'refresh' from 4 events
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[memcached]/Php::Module[memcached]/Package[PhpModule_memcached]/ensure: created
==> default: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[memcached]/Php::Module[memcached]/Package[PhpModule_memcached]: Scheduling refresh of Service[php5-fpm]
==> default: Info: Puphpet::Php::Module[memcached]: Scheduling refresh of Service[php5-fpm]
==> default: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[intl]/Php::Module[intl]/Package[PhpModule_intl]/ensure: created
[...]
```

Here's my config.yaml:
```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: local.testing
        memory: '768'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_r75iyhjuwhz5:
                source: 'C:\Server'
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - memcached
        - imagemagick
        - autotrace
        - enscript
        - gimp
        - gnuplot
        - grads
        - hp2xx
        - html2ps
        - libwmf-bin
        - mplayer
        - povray
        - radiance
        - texlive-base-bin
        - transfig
        - xdg-utils
        - ufraw-batch
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_g30fwb2wo8w0:
            server_name: beta.testing-en.local
            server_aliases:
                - beta.testing-en.local
            www_root: /var/www/testing/public
            listen_port: '80'
            index_files:
                - index.php
            client_max_body_size: 100m
            client_body_timeout: 300s
            ssl: '1'
            ssl_cert: /var/www/testing/private/certificates/beta.testing-en.local.crt
            ssl_key: /var/www/testing/private/certificates/beta.testing-en.local.key
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_3x40wjima1ha:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_hjr5fzqav6do:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'CI_ENV development'
                    proxy: ''
                    proxy_redirect: ''
        nxv_1r4ivq3o9h2c:
            server_name: beta.testing-fr.local
            server_aliases:
                - beta.testing-fr.local
            www_root: /var/www/testing/public
            listen_port: '80'
            index_files:
                - index.php
            client_max_body_size: 100m
            client_body_timeout: 300s
            ssl: '1'
            ssl_cert: /var/www/testing/private/certificates/beta.testing-fr.local.crt
            ssl_key: /var/www/testing/private/certificates/beta.testing-fr.local.key
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_busxr3kud8dg:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_r9nse4i992r0:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'CI_ENV development'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_8ywog2u2bo9i:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_dkzrsyrpj0ng:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_77ivmf2vryfm:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - memcached
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - geoip
            - imagick
            - ldap
            - mbstring
            - mysql
            - mysqlnd
            - tidy
        pear: {  }
        pecl: {  }
    ini:
        memory_limit: 256M
        display_errors: 'On'
        error_reporting: E_ALL
        html_errors: 'Off'
        session.save_path: /var/lib/php/session
        short_open_tag: 'Off'
        post_max_size: 125M
        default_charset: UTF-8
        upload_max_filesize: 100M
        max_file_uploads: '5'
        max_execution_time: '300'
        max_input_time: '300'
        date.timezone: UTC
        session.gc_probability: '1'
        session.gc_divisor: '25'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_jdtk6czw4xp8:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.var_display_max_depth: '-1'
        xdebug.var_display_max_children: '-1'
        xdebug.var_display_max_data: '-1'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '215484'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_nfpw6fovnmoh:
            name: testing
            password: '215484'
    databases:
        mariadbnd_7syp685iejaa:
            name: testing
            sql: ''
    grants:
        mariadbng_rx6u0bmmavr5:
            user: testing
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: '215484'
        override_options: {  }
    adminer: 0
    users: {  }
    databases:
        mysqlnd_4thi7du5ankq:
            name: testing
            sql: ''
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

This was working fine before I updated my puphpet.com archive. Can someone please help?
