### ISSUE TITLE
Error: Evaluation Error: Error while evaluating a Function Call, undefined method `to_bool' for :undef:Symbol

### ISSUE THREAD

**Issue by jacksonj04** [puphpet/puphpet#2074]
Whilst running a `vagrant up` (or a `vagrant reload --provision`) with this [config.yaml](https://gist.github.com/jacksonj04/ec4574fab9084247e572), I get the following error:

```
Error: Evaluation Error: Error while evaluating a Function Call, undefined method `to_bool' for :undef:Symbol at /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812/NodeJs.pp:6:9 on node wag.local
```

I've double checked I'm running latest versions of Vagrant, and VirtualBox, and the Puphpet bundle was downloaded just this afternoon.

**Comment by jacksonj04** [comment]
Update: Fixed it! Apparently my config.yaml was older than the addition of Node.js versions, and I had selected to install Node.js and some npm packages without selecting a version to install. Selecting a version to install lets `vagrant up` continue as normal.

**Comment by atika** [comment]
Thanks, I modified my `config.yaml` and machine provisioning continued without problem:
```yaml
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages:
        - coffee-script
        - forever
        - fsmonitor
        - hexo-cli
        - less
```
