### ISSUE TITLE
How to add rewrite_rule and rewrite_cond in hieradata/common.yaml?

### ISSUE THREAD

**Issue by firewalker06** [puphpet/puphpet#208]
Since I am using CodeIgniter, I need to add RewriteRule and RewriteCond inside my vhost configuration. Well, you can use .htaccess, but I prefer to configure it in the .conf file.

This is my hieradata/common.yaml file with rewrite_rule and rewrite_cond that I have added:

```
apache:
    modules:
        - php
        - rewrite
    vhosts:
        Gp51WLgjXBYx:
            servername: dapurmasak.dev
            serveraliases:
                - dapurmasak.dev
            docroot: /var/www/dapurmasak
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - 'FollowSymlinks'
            rewrite_cond:
                - '%{REQUEST_FILENAME} !-f'
                - '%{REQUEST_FILENAME} !-d'
            rewrite_rule:
                - '^(.*)$ index.php/$1 [L]'
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
```

And it returns with this error:
"Error: Duplicate declaration: Apache::Mod[rewrite] is already declared in file /etc/puppet/modules/apache/manifests/vhost.pp:277; cannot redeclare at /etc/puppet/modules/apache/manifests/mod/rewrite.pp:3 on node debian-70rc1-x64-vbox4210.vagrantup.com"

How do I add it properly?
