### ISSUE TITLE
Putty ssh freezing for 3 or 5 seconds at random intervals

### ISSUE THREAD

**Issue by AntonioCS** [puphpet/puphpet#2086]
Hey guys,

I have used puphpet numerous times to quickly generate a box and never had any issues until now.

I can connect fine via putty (using ssh key files) and then I start getting random freezes where what I type doesn't immediately show on screen it will only appear a few seconds later.

I have the latest version of box puphpet/ubuntu1404-x64 and I wasn't getting this in the previous version but I started in a new project so I can't say 100% that is the cause.

This is my config.yml

```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: myproject
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.102
            forwarded_port:
                vflnp_aodsoyspi956:
                    host: '9417'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_jcx6n27y14x3:
                source: '/myproject/Projects'
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_pmi002skn625:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_nw24rhndquw9:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_k84ig28azk67:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_5nnqsr5twaea:
            servername: myproject.dev
            serveraliases:
                - www.myproject.dev			
            docroot: /var/www/myproject/rc_mlp_20140609/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_6xestxko8uq6:
                    path: /var/www/myproject/rc_mlp_20140609/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_vhecckpqn7df:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_04ilczut9gyh:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_5155z9g1rzay:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_2jkjo5huwq4e:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_oz9xapyyu6aw:
            name: dbname
            sql: ''
    grants:
        mariadbng_p5j1jtlmdrv0:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_4ak8bbnz7wkc:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_eenb90pokzms:
            name: dbname
            sql: ''
    grants:
        mysqlng_5nj2vmh2mej3:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

**Comment by acedude** [comment]
Got the same issue.

**Comment by AntonioCS** [comment]
Is it just us that are getting this issue???

@acedude is your config.yml similar to mine?

**Comment by acedude** [comment]
Here it is @AntonioCS [config.txt](https://github.com/puphpet/puphpet/files/82567/config.txt)
We're both on Ubuntu and VirtualBox.

**Comment by AntonioCS** [comment]
@acedude Are you running the latest version of 'puphpet/ubuntu1404-x64' ?

**Comment by acedude** [comment]
Yup!

**Comment by AntonioCS** [comment]
Me too. I believe this is an issue with the box.
Maybe if we can downgrade to the previous version this will be fixed.

I will see if there is a way to downgrade the box.

**Comment by AntonioCS** [comment]
This is the box url: https://atlas.hashicorp.com/puphpet/boxes/ubuntu1404-x64
I believe the version I was using that did not have the issue was v2.0.

What I think the next steps are:
- Create a new project
- Set a version [constraint in vagrant](https://docs.vagrantup.com/v2/boxes/versioning.html) (not sure if puphpet allows this in the conf)
- See if the problem still occurs.

I will try to do these steps, this weekend.

**Comment by AntonioCS** [comment]
I was correct about the previous version.


```
$  vagrant box list
puphpet/ubuntu1404-x64 (virtualbox, 2.0)
puphpet/ubuntu1404-x64 (virtualbox, 20151201)
```

**Comment by acedude** [comment]
Well, it's not big of a issue for me personally, but it would be cool to see it fixed.

**Comment by jtreminio** [comment]
I can't replicate this. Not sure how to troubleshoot!

**Comment by AntonioCS** [comment]
@acedude Its not a major issue but it does break the flow a bit.

@jtreminio Are you using version 20151201? I am using virtual box 5.0.12r104815 (which I updated too after I started having this issue in the hopes that it would fix it but it didn't)
Is there any way to specify the vm box version in the config.yml?

**Comment by AntonioCS** [comment]
I have tried this on a machine running windows 7 64bit Pro with puphpet/ubuntu1404-x64 (virtualbox, 2.0) and with the config I have posted here.
It worked fine with out any issues. No putty freezing.

The machine where I initially had these issues is running windows 10 64bit Pro so I will have to go and test on that machine, but at least we now know its not the config.

**Comment by acedude** [comment]
I'm on Windows 8.1 Pro, x64.

**Comment by chrisjz** [comment]
I'm having the same random freezing issue on 2 different PCs with Windows 7 64-bit. It's still working fine though with much older puphpet instances.

Here's my box list:
puphpet/centos65-x64   (virtualbox, 2.0)
puphpet/ubuntu1404-x64 (virtualbox, 20151201)

**Comment by AntonioCS** [comment]
Ok, so I think we now know its related to the box.

I have win 10 pro and win 7 (both 64bit) and the 2.0 ran fine it was only after I updated to 20151201 on the win 10 machine that I started having these freezing issues.

**Comment by HnLn** [comment]
Yep, I got it as well since one of the last upgrades, box version makes sense to me (win10 with an ubuntu box en vagrant-winnfsd plugin, last is irrelevant but might be cool info for win users :-).

**Comment by AntonioCS** [comment]
@jtreminio I think we can see that there is something wrong with the box. What is your OS?

**Comment by tlartaud** [comment]
Ubuntu Box is know to suddently lose the connection sometimes. I don't know if this is related, but you could give a try.

Does it stil happen if you use
```
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                    natdnsproxy1: 'on'
```
