### ISSUE TITLE
Error: No title provided and "Nginx::Resource::Upstream[]" is not a valid resource reference

### ISSUE THREAD

**Issue by sshilko** [puphpet/puphpet#2088]
puphpet/puppet/modules/nginx/manifests/resource/upstream.pp

```
     Nginx::Resource::Upstream::Member <<| upstream == $name |>>
```

in hiera

```
    upstreams:
        phpupstream1:
            ensure: 'present'
            members:
                - 'unix:/var/run/php5-fpm.sock'
            upstream_cfg_prepend:
                keepalive: 45
    vhosts:

```
