### ISSUE TITLE
zzzz_custom.ini: php settings escaped

### ISSUE THREAD

**Issue by sshilko** [puphpet/puphpet#2089]
all the settings gets escaped in zzzz_custom.ini

need to change puphpet/manifests/php/ini.pp

```

  #modified do not QUOTE!
  $changes = $ensure ? {
    present => [ "set '${entry}' \"${value}\"" ],
    absent  => [ "rm \"${entry}\"" ],
  }

  #Quoted ORIGINAL (~ line 215)
  $changes = $ensure ? {
    present => [ "set '${entry}' \"'${value}'\"" ],
    absent  => [ "rm \"'${entry}'\"" ],
  }

```

**Comment by jtreminio** [comment]
Need to show me your config.yaml, or what exactly you're trying to do.

**Comment by sshilko** [comment]
my hiera config is
```
php:
    install: '1'
    settings:
        version: '70'
    modules:
        php:
            - cli
            - intl
        pear: {  }
        pecl: {  }
    ini:
        extension: 'amqp.so' #AMQP extension speeds up the RabbitMQ communications
        display_errors: Off
        error_reporting: E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
        memory_limit: 536870912
        expose_php: Off
```
and all those values gets escaped, for example

```
E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
!=
'E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE'
```
