### ISSUE TITLE
Problems with second PHP FPM Pool under CentOS 6

### ISSUE THREAD

**Issue by head82** [puphpet/puphpet#2094]
required config options are missing:

```
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
php_admin_value[error_log] = /var/log/php-fpm/phpfp_twefne29ofwq-error.log
php_admin_flag[log_errors] = on
```

**Comment by head82** [comment]
Unfortunately this does not work because php_admin_value[error_log] & php_admin_flag[log_errors] are ignored:

```yaml
    fpm_pools:
        phpfp_tgsff09sh8zo:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
        phpfp_tytp42udlfj7:
            ini:
                listen: '127.0.0.1:9090'
                prefix: phpfp_twefne29ofwq
                security.limit_extensions: .php
                user: www-user
                group: www-data
                pm: dynamic
                pm.max_children: 50
                pm.start_servers: 5
                pm.min_spare_servers: 5
                pm.max_spare_servers: 35
                'php_admin_value[error_log]': /var/log/php-fpm/phpfp_twefne29ofwq-error.log
                'php_admin_flag[log_errors]': on
```
