### ISSUE TITLE
MySQL is not being installed on Centos 6

### ISSUE THREAD

**Issue by bassplayer7** [puphpet/puphpet#2096]
I uploaded a previous PuPHPet config file and confirmed that all of the settings looked like what I expected them to. I then downloaded the `.zip` file and ran `vagrant up`. When I try to connect to the VM with Sequel Pro, I get the error message:
<img width="606" alt="screen_shot_2016-01-11_at_12_57_01_pm" src="https://cloud.githubusercontent.com/assets/1171147/12243225/ef2f2460-b862-11e5-9ce9-c7e2c3f61a74.png">

Next, when I SSH into the VM and run the `mysql` command, I receive an error that says: `-bash: mysql: command not found` which indicates to me that MySQL isn't being installed at all.

Any ideas as to what is going on here?

As another note, composer is not installing either with: `php returned 255 instead of one of [0]`. Perhaps the error is related to an error that is preventing the script from reaching the MySQL setup scripts?

My `config.yaml` file are as shown below:
````yaml
vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: LocalBox
        memory: '2048'
        cpus: '3'
        chosen_provider: parallels
        network:
            private_network: 192.168.58.102
            forwarded_port:
                vflnp_vluvsjspj8tr:
                    host: '6224'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: ''
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_pgnk59xyr0z1:
                source: ../
                target: /var/www/sites/www.mysite.com/
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_vy1i6psb0se0:
                source: ../../modules/
                target: /var/www/sites/modules/
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - ImageMagick
        - ImageMagick-devel
        - vim-common
        - php-soap
        - telnet
        - fuse
        - libwebp
        - sendmail
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales: {  }
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs:
        cj_gc5fdzyp0r95:
            name: magento
            user: ''
            command: '/bin/sh /var/www/sites/www.mysite.com/docs/cron.sh'
            minute: '*/5'
            hour: '*'
            weekday: '*'
            month: '*'
            monthday: ''
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts: {  }
    proxies: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - expires
        - headers
        - proxy_fcgi
        - proxy_http
        - proxy
        - rewrite
    vhosts:
        av_74zm6miwakrt:
            servername: mysite.mag
            docroot: /var/www/sites/www.mysite.com/docs/
            port: '443'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_9wcpm2o90in5:
                    path: /var/www/sites/www.mysite.com/docs
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_mgpmnkhthxg6:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_u0xg53o1h5n0:
            servername: mysite.mag
            docroot: /var/www/sites/www.mysite.com/docs/
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_hy9dhsatz7s2:
                    path: /var/www/sites/www.mysite.com/docs
                    options:
                        - Indexes
                        - FollowSymLinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5jp6h0pwo0gr:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - mbstring
        pear: {  }
        pecl:
            - imagick
    ini:
        display_errors: 'On'
        session.save_path: /var/lib/php/session
        error_rep: '0'
        error_reporting: '1'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_l0fzkl0777sy:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9001'
        xdebug.remote_autostart: '1'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: null
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_3b156j10474l:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_3ugoz9mr1q3b:
            name: dbname
            sql: ''
    grants:
        mariadbng_i6uq68exzdqa:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: user123
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_2w6e7apbdhut:
            name: admin
            password: user123
    databases:
        mysqlnd_u0hb3x7l2trr:
            name: site_db
#            sql: /vagrant/databases/output.sql
    grants:
        mysqlng_u19myhmev4oj:
            user: admin
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

````

Migrated from https://github.com/puphpet/puppet-puphpet/issues/32
