### ISSUE TITLE
composer install error under CentOS 6

### ISSUE THREAD

**Issue by head82** [puphpet/puphpet#2098]
OS X with VirtualBox 5.0.12, Vagrant 1.8.1 and Box puphpet/centos65-x64 (virtualbox, 20151130)

```bash
==> default: Error: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Composer/Exec[download_composer]/returns: change from notrun to 0 failed: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
==> default: Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]: Dependency Exec[download_composer] has failures: true
==> default: Warning: /Stage[main]/Composer/File[/usr/local/bin/composer]: Skipping because of failed dependencies
```

```yaml
vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: project.local
        memory: '2048'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.222.11
            forwarded_port:
                vflnp_51xcx96i9d8z:
                    host: '5667'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: ''
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_e9ydmolazjkv:
                source: ./src
                target: /var/www/portal
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_uynb3lhy203h:
                source: ./
                target: /source
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - de_DE.UTF-8
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules:
        fr_yn82cyr1ixic:
            port:
                - '8080'
            priority: '100'
            proto: tcp
            action: accept
        fr_gheo48vn2pcn:
            port:
                - '9090'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_hsi4puvnkco4:
            server_name: cms.project.local
            www_root: /var/www/portal/public
            listen_port: '80'
            index_files:
                - index.php
            client_max_body_size: 400m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            locations:
                nxvl_0cstka6lul9y:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_1f9fwu5aej9d:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_ogdhwmfjuw2v:
            servername: project.dev
            docroot: /var/www/portal/public
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_tv0yg8b7d7ep:
                    path: /var/www/portal/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_pk3eeml13vge:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mbstring
            - gd
            - snmp
            - pdo
            - opcache
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        upload_max_filesize: 400M
        post_max_size: 400M
    fpm_ini:
        error_log: /var/log/php-fpm/php-fpm.log
    fpm_pools:
        phpfp_tgsff09sh8zo:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9900'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '1'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_m9ffu3h1ebwd:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '0.12'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_30uywwx1tnso:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_hfwdv54cd6zj:
            name: dbname
            sql: ''
    grants:
        mariadbng_0cn5wvt9nvg7:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_o44ekr1gt1qg:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_p0imk4wdephi:
            name: dbname
            sql: ''
    grants:
        mysqlng_akaifi89uqoq:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '1'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

**Comment by jackwilsontotemic** [comment]
I get the same error today :(

**Comment by HnLn** [comment]
same here (ubuntu box)

**Comment by tlartaud** [comment]
same error : https://github.com/puphpet/puphpet/issues/2095#issuecomment-170878479

updated this yesterday :
virtualbox 5.0.12
vagrant 1.81
puphpet last version from puphpet.com

also running :
windows 10

**Comment by Cyruxx** [comment]
+1 ubuntu box

**Comment by refringe** [comment]
Same here on Ubuntu.

```
==> default: Error: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Composer/Exec[download_composer]/returns: change from notrun to 0 failed: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
```

**Comment by refringe** [comment]
@jtreminio: Do you think this is related to Puphpet or Composer?

**Comment by stephanebelazouz** [comment]
Same here with debian 7

**Comment by jfw7** [comment]
Having the same issue with CentOS

**Comment by mattkenefick** [comment]
+1 Ubuntu trusty64 updated box today, need to get this fixed.

**Comment by mattkenefick** [comment]
It's similar to this: https://github.com/puphpet/puphpet/issues/1374

**Comment by iomdesign** [comment]
+1 CentOS - same error. 

```
==> default: Notice: /Stage[main]/Php/Package[php-fpm]/ensure: created
==> default: Notice: /Stage[main]/Php::Devel/Package[php-devel]/ensure: created
==> default: Notice: /Stage[main]/Puphpet_php/Exec[set php session path owner/group]/returns: executed successfully
==> default: Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]: Dependency Exec[download_composer] has failures: true
==> default: Error: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Composer/Exec[download_composer]/returns: change from notrun to 0 failed: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
==> default: Warning: /Stage[main]/Composer/File[/usr/local/bin/composer]: Skipping because of failed dependencies
```

New archive modified from another config.yaml that was used to provision a box a couple of days ago and was fine. SSH into the box, su root and run command results in successful-ish install of composer.

```
# curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /root/composer.phar
Use it: php composer.phar
```
Cheers

**Comment by alexdesignworks** [comment]
same here for Ubuntu. I'm afraid to rebuild the box - every time something like this happens. sight.

**Comment by bajax** [comment]
+1 Happens for me on OSX 10.11.2 El Capitan and Windows 10, with the stock default config, latest Vagrant and VirtualBox, absolutely NO customizations.  It's been working so well for the past six months...  Now I have to finish the build out manually every time.

**Comment by iomdesign** [comment]
Had a look to debug but not found an answer.

N.B. If you don't actually need Composer you can edit the archive to prevent it from trying to install.  

change config.yaml to
```
composer: 0
```
and comment out section in /puphpet/puppet/manifests/Php.pp
```
  #if array_true($php, 'composer') and ! defined(Class['puphpet::php::composer']) {
  #  class { 'puphpet::php::composer':
  #    php_package   => $puphpet::php::settings::cli_package,
  #    composer_home => $php['composer_home'],
  #  }
  #}
```

**Comment by mattkenefick** [comment]
I don't have an answer yet, but I set the "composer: 0" as well and manually installed it on the machine via `vagrant ssh`. It worked, but now of course, I'm getting a brand new Ruby error. Sigh.

**Comment by ikari7789** [comment]
I've turned on output for the composer install command. It's missing ```HOME``` or ```COMPOSER_HOME``` environment variables.

```
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: All settings correct for using Composer
==> default:
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The HOME or COMPOSER_HOME environment variable must be set for composer to install correctly' in -:559
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: Stack trace:
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: #0 -(364): getHomeDir()
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: #1 -(111): installComposer(false, false, 'composer.phar', false, false, false)
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: #2 -(13): process(Array)
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns: #3 {main}
==> default: Notice: /Stage[main]/Composer/Exec[download_composer]/returns:   thrown in - on line 559
==> default: Error: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
==> default: Error: /Stage[main]/Composer/Exec[download_composer]/returns: change from notrun to 0 failed: curl -sS https://getcomposer.org/installer | php returned 255 instead of one of [0]
==> default: Notice: /Stage[main]/Composer/File[/usr/local/bin/composer]: Dependency Exec[download_composer] has failures: true
==> default: Warning: /Stage[main]/Composer/File[/usr/local/bin/composer]: Skipping because of failed dependencies
```

**Comment by BartoszBartniczak** [comment]
+1

**Comment by tlartaud** [comment]
@ikari7789 I tried to set `composer_home` to `/home/vagrant` in `config.yaml`, same effect.

@mattkenefick @iomdesign Yes you can manually install composer, but till the install fail, you wont be able to really complete your vagrant process if you are using me like some vagrant triggers that should be triggered after a successful vagrant provisioning. Plus, even if you manually install composer and  reprovision again, composer will be detected as uninstalled, puphpet will try to install it and faill again.

**Comment by drazen-popov-devtech** [comment]
Try to set it like this:

composer_home: /vagrant/.composer
home: /vagrant/.composer

When Vagrant up (for version 2.0) it fails , but after if you do vagrant provision it will work. 
If somebody finds a way to fix the bug so it doesn't fail on vagrant up please post it here.

**Comment by ikari7789** [comment]
The reason for that is because, if set, it writes ```COMPOSER_HOME``` to ```/etc/environment``` but doesn't reload the environment variables before executing the install.
So on a second provision, the value is now in ```/etc/environment``` and can successfully complete.

**Comment by lotar** [comment]
Without too much investigation, problem seems to be either in [puppet-composer](https://travis-ci.org/tPl0ch/puppet-composer) module, or something on composer side that [changed in last few days](https://github.com/composer/composer/commits/master).

Furhter, Puphpet manifest for Composer (`puphpet/puppet/modules/puphpet/manifests/php/composer.pp`) doesn't allow end user to switch `$download_method` that's used by puppet-composer module from YAML config file (it's hard coded to `curl`). And simply changing that download method from `curl` to `wget` in manifest mentioned above seems to work for me as not only it uses different method, but the endpoint is different also:
```
$download_command = "curl -sS https://getcomposer.org/installer | ${composer::php_bin}"
```
vs
```
$download_command = 'wget https://getcomposer.org/composer.phar -O composer.phar'
```

For everyone looking to find quick fix on puphpet side, search for following piece of code in the file mentioned above:
```
  class { '::composer':
    target_dir      => '/usr/local/bin',
    composer_file   => 'composer',
    download_method => 'curl',
    logoutput       => false,
    tmp_path        => '/tmp',
    php_package     => $php_package,
    curl_package    => 'curl',
    suhosin_enabled => false,
  }
```
and change download method so it looks like:
```
  class { '::composer':
    target_dir      => '/usr/local/bin',
    composer_file   => 'composer',
    download_method => 'wget',
    logoutput       => false,
    tmp_path        => '/tmp',
    php_package     => $php_package,
    curl_package    => 'curl',
    suhosin_enabled => false,
  }
```
Again, won't blame anyone, this is just what worked for me without too much investigation.

Regardless, it would be a good thing to patch puphpet so that this is configurable from YAML file.

**Comment by ikari7789** [comment]
I don't think it's due to an update in puppet-composer as it hasn't been updated for quite some time in puphpet. It could possibly be due to composer, but that also seems unlikely.
My biggest question is why isn't "HOME" set during installation? It's a system default environment variable.

**Comment by tlartaud** [comment]
Just an idea ...

```
$download_command = "COMPOSER_HOME=/home/vagrant/.composer curl -sS https://getcomposer.org/installer | ${composer::php_bin}"
```

**Comment by ikari7789** [comment]
The problem point isn't the selfupdate, but the actual install, and for some reason ENV['HOME'] is unset which is why it's causing a problem.

**Comment by tlartaud** [comment]
@ikari7789  Yep, but I think that the $HOME variable being not set is the one of the user who own `php`, not `vagrant` user.

Maybe that puphpet install php with an user that doesnt have a HOME directory ?

**Comment by robme** [comment]
I swear, every time I update vagrant or PuPHPet, or just try to run someone else's VM, I run into something like this that takes days for me to find a solution to.

**Comment by xoza** [comment]
It's not actually a solution, but to unblock ourselves from this problem we have downloaded the .phar file from https://getcomposer.org/composer.phar , copied it in the project vagrant resources directory and done a symlink, somehow like this:

```
  $vagrantResources = '/vagrant/vagrant_resources'
  $composerFilepath = "${vagrantResources}/composer/alpha11/composer.phar"

  exec
  {
    'link_composer':
      command => "ln -s ${composerFilepath} /usr/local/bin/composer",
      unless => "ls /usr/local/bin/composer",
      timeout => 0
  }

  exec
  {
    'composer_self_update':
      command => "php ${composerFilepath} self-update",
      environment => ["COMPOSER_HOME=/home/vagrant/"],
      require => Exec['php-install'],
      timeout => 0
  }
```

Using the installer would be better, but at least we are able to use composer in our VM and perform a complete provision with no issues.

I hope it helps.

**Comment by tlartaud** [comment]
For now, as a workaround, I set `composer` to 0 in config.yaml and i create a `composer.sh` file in `startup-always-unprivileged` folder.

```
#!/usr/bin/env bash

# Test if PHP is installed
php -v > /dev/null 2>&1
PHP_IS_INSTALLED=$?

# Test if HHVM is installed
hhvm --version > /dev/null 2>&1
HHVM_IS_INSTALLED=$?

[[ $HHVM_IS_INSTALLED -ne 0 && $PHP_IS_INSTALLED -ne 0 ]] && { printf "!!! PHP/HHVM is not installed.\n    Installing Composer aborted!\n"; exit 0; }

# Test if Composer is installed
composer -v > /dev/null 2>&1
COMPOSER_IS_INSTALLED=$?

# True, if composer is not installed
if [[ $COMPOSER_IS_INSTALLED -ne 0 ]]; then
    echo ">>> Installing Composer"
    if [[ $HHVM_IS_INSTALLED -eq 0 ]]; then
        # Install Composer
        sudo wget --quiet https://getcomposer.org/installer
        hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 installer
        sudo mv composer.phar /usr/local/bin/composer
        sudo rm installer

        # Add an alias that will allow us to use composer without timeout's
        printf "\n# Add an alias for sudo\n%s\n# Use HHVM when using Composer\n%s" \
        "alias sudo=\"sudo \"" \
        "alias composer=\"hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 -v Eval.Jit=false /usr/local/bin/composer\"" \
        >> "/home/vagrant/.profile"

        # Resource .profile
        # Doesn't seem to work do! The alias is only usefull from the moment you log in: vagrant ssh
        . /home/vagrant/.profile
    else
        # Install Composer
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
    fi
else
    echo ">>> Updating Composer"

    if [[ $HHVM_IS_INSTALLED -eq 0 ]]; then
        sudo hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 -v Eval.Jit=false /usr/local/bin/composer self-update
    else
        composer self-update
    fi
fi
```

**Comment by refringe** [comment]
@tlartaud That brings forth another error for me:

```
==> default: Notice: /Stage[main]/Rvm::System/Exec[system-rvm-gpg-key]/returns: executed successfully
==> default: Error: Could not find command 'rvm'
==> default: Error: /Stage[main]/Puphpet_ruby/Exec[rvm rvmrc warning ignore all.rvmrcs]/returns: change from notrun to 0 failed: Could not find command 'rvm'
==> default: Notice: /Stage[main]/Swap_file/Exec[Create swap file]/returns: executed successfully
```

**Comment by bajax** [comment]
@refringe same issue here.

**Comment by alexdesignworks** [comment]
As a workaround, add 1 line to `puppet/modules/composer/init.pp` at line 140:
```ruby
    exec { 'download_composer':
      command   => $download_command,
      cwd       => $tmp_path,
      require   => $download_require,
      creates   => "${tmp_path}/composer.phar",
      logoutput => $logoutput,
      environment => ["COMPOSER_HOME=\"/home/vagrant/.composer\""],  # <-- ADDED LINE
    }
```

Also, make sure that your default local is set to `en_GB.UTF-8` in `config.yaml` (this is a recently added setting):
```yaml
locale:
    install: '1'
    settings:
        default_locale: "en_GB.UTF-8" # <--- THIS LINE
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
```
