### ISSUE TITLE
Hiera parses %{foo}, making apache rewrite conditions impossible

### ISSUE THREAD

**Issue by jtreminio** [puphpet/puphpet#210]
```
apache:
    vhosts:
        Gp51WLgjXBYx:
            servername: foo.dev
            docroot: /var/www/dapurmasak
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - 'FollowSymlinks'
            rewrite_cond:
                - '%{REQUEST_FILENAME} !-f'
                - '%{REQUEST_FILENAME} !-d'
            rewrite_rule: '^(.*)$ index.php/$1 [L]'
```

Hiera interprets the string `%{REQUEST_FILENAME}`, which equates to no value.

There's currently no way to escape the string: http://projects.puppetlabs.com/issues/16235
