### ISSUE TITLE
PuPHPet trying to install PHP7 while I'm wanting 5.6

### ISSUE THREAD

**Issue by IvoPereira** [puphpet/puphpet#2109]
Hello,

I'm getting the following error:

```
==> local: Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install composer' returned 1: Error: php70u-common conflicts with php-common-5.6.17-1.el6.remi.x86_64
==> local:  You could try using --skip-broken to work around the problem
==> local:  You could try running: rpm -Va --nofiles --nodigest
==> local: Error: /Stage[main]/Puphpet_server/Package[composer]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install composer' returned 1: Error: php70u-common conflicts with php-common-5.6.17-1.el6.remi.x86_64
==> local:  You could try using --skip-broken to work around the problem
==> local:  You could try running: rpm -Va --nofiles --nodigest
```

However I'm explicitly requiring PHP 5.6 in the config.yaml.

```
vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: development.local
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        box_version: ''
        network:
            private_network: 192.168.0.33
            forwarded_port:
                vflnp_12g9hxxt0u3d:
                    host: '10200'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                use_linked_clone: '0'
                check_guest_tools: '0'
                update_guest_tools: '0'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_08ebv90henb6:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - git
        - nano
        - composer
users_groups:
    install: '1'
    groups:
        - user
    users:
        - 'user:group'
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - pt_PT.UTF-8
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - deflate
        - ldap
        - expires
        - headers
        - cache
        - vhost_alias
        - mime_magic
    vhosts:
        av_mffm2wnvxoql:
            servername: development.local
            serveraliases:
                - www.development.local
            docroot: /var/www
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_4kvjaf2bbo6i:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_2ud1zj7vu5l8:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_g0vqkd062qwy:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
ruby:
    install: '1'
    versions:
        rv_b0j325gbumye:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '0.12'
    npm_packages:
        - gulp
        - bower
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: password
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_5c2byanizi4f:
            name: user
            password: password
    databases:
        mysqlnd_um688x7sexg2:
            name: initial_db_name
            sql: /root/sqlfile.sql
    grants:
        mysqlng_mgaujhl4im8j:
            user: user
            table: '*.*'
            privileges:
                - ALL
```

Any idea what I could be missing?

Thanks!
