### ISSUE TITLE
php-memcached installation failed

### ISSUE THREAD

**Issue by x2002uwh** [puphpet/puphpet#2112]
Here is my config xml:

php:
install: '1'
settings:
version: '56'
modules:
php:
- cli
- intl
- common
- curl
- gd
- memcached
- mcrypt
- mysqlnd
- mbstring
- imagick
- xmlrpc
pear: { }
pecl: { }
ini:
display_errors: 'On'
error_reporting: '-1'
session.save_path: /var/lib/php/session
date.timezone: UTC
fpm_ini:
error_log: /var/log/php-fpm.log
fpm_pools:
phpfp_tpjwmv99bilu:
ini:
prefix: www
listen: '127.0.0.1:9000'
security.limit_extensions: .php
user: www-user
group: www-data
composer: '1'
composer_home: ''

And here is what I see from the console:
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[intl]/Php::Module[intl]/Package[PhpModule_intl]/ensure: created
==> local: 
==> local: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[intl]/Php::Module[intl]/Package[PhpModule_intl]: Scheduling refresh of Service[php5-fpm]
==> local: Info: Puphpet::Php::Module[intl]: Scheduling refresh of Service[php5-fpm]
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[curl]/Php::Module[curl]/Package[PhpModule_curl]/ensure: created
==> local: 
==> local: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[curl]/Php::Module[curl]/Package[PhpModule_curl]: Scheduling refresh of Service[php5-fpm]
==> local: Info: Puphpet::Php::Module[curl]: Scheduling refresh of Service[php5-fpm]
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[gd]/Php::Module[gd]/Package[PhpModule_gd]/ensure: created
==> local: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[gd]/Php::Module[gd]/Package[PhpModule_gd]: Scheduling refresh of Service[php5-fpm]
==> local: Info: Puphpet::Php::Module[gd]: Scheduling refresh of Service[php5-fpm]
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[mcrypt]/Php::Module[mcrypt]/Package[PhpModule_mcrypt]/ensure: created
==> local: 
==> local: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[mcrypt]/Php::Module[mcrypt]/Package[PhpModule_mcrypt]: Scheduling refresh of Service[php5-fpm]
==> local: Info: Puphpet::Php::Module[mcrypt]: Scheduling refresh of Service[php5-fpm]
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[mysqlnd]/Php::Module[mysqlnd]/Package[PhpModule_mysqlnd]/ensure: created
==> local: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[mysqlnd]/Php::Module[mysqlnd]/Package[PhpModule_mysqlnd]: Scheduling refresh of Service[php5-fpm]
==> local: Info: Puphpet::Php::Module[mysqlnd]: Scheduling refresh of Service[php5-fpm]
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[imagick]/Php::Module[imagick]/Package[PhpModule_imagick]/ensure: created
==> local: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[imagick]/Php::Module[imagick]/Package[PhpModule_imagick]: Scheduling refresh of Service[php5-fpm]
==> local: Info: Puphpet::Php::Module[imagick]: Scheduling refresh of Service[php5-fpm]
==> local: Notice: /Stage[main]/Puphpet_php/Puphpet::Php::Module[xmlrpc]/Php::Module[xmlrpc]/Package[PhpModule_xmlrpc]/ensure: created
==> local: Info: /Stage[main]/Puphpet_php/Puphpet::Php::Module[xmlrpc]/Php::Module[xmlrpc]/Package[PhpModule_xmlrpc]: Scheduling refresh of Service[php5-fpm]
==> local: Info: Puphpet::Php::Module[xmlrpc]: Scheduling refresh of Service[php5-fpm]
==> local: Notice: /Stage[main]/Puphpet_php/Service[php5-fpm]: Triggered 'refresh' from 40 events
==> local: Notice: /Stage[main]/Puphpet_apache/Apache::Vhost[av_7cklkgnoujop]/Apache::Listen[80]/Concat::Fragment[Listen 80]/File[/opt/puppetlabs/puppet/cache/concat/_etc_apache2_ports.conf/fragments/10_Listen 80]/ensure: defined content as '{md5}d5fcefc335117f400d451de47efeca87'

It shows every PHP package was installed except the Memcached

**Comment by jtreminio** [comment]
I need your full log.

Also, paste your full config.yaml with code indenting.

**Comment by x2002uwh** [comment]
``` yaml
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: local
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        box_version: ''
        network:
            private_network: 192.168.56.100
            forwarded_port:
                vflnp_j3nbowegetvu:
                    host: '8419'
                    guest: '22'
                vflnp_ytzrqa5qksf9:
                    host: '9356'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                use_linked_clone: '0'
                check_guest_tools: '0'
                update_guest_tools: '0'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_p0lr3zwwp5if:
                source: ./
                target: /vagrant
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_2ap6p2jyleic:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_q4a1fz1x3t1d:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_ffkl5blp0jip:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - headers
        - vhost_alias
    vhosts:
        av_7cklkgnoujop:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /vagrant/www/public
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_93i4u5eytpyf:
                    path: /vagrant/www/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_u5w8psk2getv:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - common
            - curl
            - gd
            - mcrypt
            - mysqlnd
            - mbstring
            - imagick
            - xmlrpc
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_tpjwmv99bilu:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '1'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_uru9y0x3sqgw:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_bexf1a8b9b1g:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_64d9ci7utwq8:
            name: dbname
            sql: ''
    grants:
        mariadbng_nx6pebs6cq8x:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.5'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_nmqfptohtqk5:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_93cu4jn8exme:
            name: dbname
            sql: ''
    grants:
        mysqlng_040sney2xh3x:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_duwcot5r3n5r:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

config.yaml is
