### ISSUE TITLE
fpm_pools does not allow env[...] php_admin_value[...] php_flag[...] php_admin_flag[...] settings

### ISSUE THREAD

**Issue by sshilko** [puphpet/puphpet#2113]
```

php:
    fpm_pools:
        www:
             'env[SOMEENV]': 'somevalue'

```
no longer works and produces
```
env=somevalue
```

this worked before (2013)

example affected ini values:

```
;php_admin_value[sendmail_path] = /usr/sbin/sendmail -t -i -f www@my.domain.com
;php_flag[display_errors] = off
;php_admin_value[error_log] = /var/log/fpm-php.www.log
;php_admin_flag[log_errors] = on
;php_admin_value[memory_limit] = 32M
```
