### ISSUE TITLE
Rsync fails on vagrant up - Updated to latest puphpet, Vagrant 1.8.1, VirtualBox 5 (Windows host/cygwin)

### ISSUE THREAD

**Issue by mattsnowboard** [puphpet/puphpet#2140]
This was working fine before with an older Vagrant/VBox but I needed to update and I decided to just try a new puphpet config with the latest changes. Now I'm getting failures on vagrant up.

```
$ vagrant up
Bringing machine 'local' up with 'virtualbox' provider...
==> local: Importing base box 'puphpet/centos65-x64'...
==> local: Matching MAC address for NAT networking...
==> local: Checking if box 'puphpet/centos65-x64' is up to date...
==> local: Setting the name of the VM: globalizedu_local_1454206859796_91966
==> local: Clearing any previously set network interfaces...
==> local: Preparing network interfaces based on configuration...
    local: Adapter 1: nat
    local: Adapter 2: hostonly
==> local: Forwarding ports...
    local: 22 (guest) => 8387 (host) (adapter 1)
    local: 22 (guest) => 2222 (host) (adapter 1)
==> local: Running 'pre-boot' VM customizations...
==> local: Booting VM...
==> local: Waiting for machine to boot. This may take a few minutes...
    local: SSH address: 127.0.0.1:2222
    local: SSH username: vagrant
    local: SSH auth method: private key
    local: Warning: Remote connection disconnect. Retrying...
==> local: Machine booted and ready!
==> local: Checking for guest additions in VM...
==> local: Setting hostname...
==> local: Configuring and enabling network interfaces...
==> local: Rsyncing folder: /cygdrive/d/web_workspace/globalizedu_wp/globalizedu/ => /var/project
==> local:   - Exclude: [".vagrant/", ".git/", "nbproject/", "puphpet", "vendor/", "app/cache/", "app/logs/", "app/boots
trap.php.cache", "usr/uploads", "web/bundles", "web/css", "web/fonts", "web/js", "web/uploads/images/*", "bin/"]
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/web_workspace/globalizedu_wp/globalizedu/
Guest path: /var/project
Command: rsync --verbose --archive -z --delete --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync
-e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/cygwin64/tmp/ssh.129 -o ControlPersist=10m -o StrictHostKeyChecki
ng=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'D:/web_workspace/globalizedu_wp/globalizedu/puphpet/fil
es/dot/ssh/id_rsa' -i 'd:/vm/.vagrant.d/insecure_private_key' --exclude .vagrant/ --exclude .git/ --exclude nbproject/ -
-exclude puphpet --exclude vendor/ --exclude app/cache/ --exclude app/logs/ --exclude app/bootstrap.php.cache --exclude
usr/uploads --exclude web/bundles --exclude web/css --exclude web/fonts --exclude web/js --exclude web/uploads/images/*
--exclude bin/ /cygdrive/d/web_workspace/globalizedu_wp/globalizedu/ vagrant@127.0.0.1:/var/project
Error: Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```

This is under cygwin on a Windows 8.1 host.

Rsync info:
```
$ rsync --version
rsync  version 3.1.2  protocol version 31
Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, no xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

```

config.yaml:
```
vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: globalizedu.vagrant.local
        memory: '2048'
        cpus: '1'
        chosen_provider: virtualbox
        box_version: ''
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_ldclv6p375rv:
                    host: '8387'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                use_linked_clone: '0'
                check_guest_tools: '0'
                update_guest_tools: '0'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_1pug1lgbn7q1:
                source: .
                target: /var/project
                sync_type: rsync
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                        - '--delete'
                    exclude:
                        - .vagrant/
                        - .git/
                        - nbproject/
                        - puphpet
                        - vendor/
                        - app/cache/
                        - app/logs/
                        - app/bootstrap.php.cache
                        - usr/uploads
                        - web/bundles
                        - web/css
                        - web/fonts
                        - web/js
                        - 'web/uploads/images/*'
                        - bin/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_5tyfglfll5fz:
                source: ..\\wp
                target: /var/windows/wp
                sync_type: default
                owner: www-data
                group: www-data
            vflsf_1h5eyaqvpqfb:
                source: ..\\wp
                target: /var/wp
                sync_type: rsync
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                        - nbproject/
                        - puphpet
                        - node_modules/
                        - bower_components/
                        - dist/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_8zzwn9f5c3x4:
                source: 'D:\\web_workspace\\lib\webgrind'
                target: /var/www/webgrind
                sync_type: default
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - emacs
        - git
        - graphviz
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: America/Chicago
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts: {  }
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        av_6939rp5bbbzg:
            servername: globalizedu.dev
            docroot: /var/www/globalizedu
            port: '443'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_iy2sytnxmhs1:
            servername: globalizedu.dev
            docroot: /var/www/globalizedu
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_4cls2qglee95:
            servername: wp.globalizedu.dev
            docroot: /var/www/wp
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_gwqljvwl4cgh:
            servername: village.globalizedu.dev
            docroot: /var/www/wp
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_w5ussewpnt54:
            servername: catalyst.globalizedu.dev
            docroot: /var/www/wp
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_nsxq5kyy7rh8:
            servername: webgrind.dev
            docroot: /var/www/webgrind
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - common
            - imap
            - intl
            - gd
            - mbstring
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        memory_limit: 256M
        max_execution_time: '120'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.max_nesting_level: '256'
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_host: 10.0.2.2
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9001'
        xdebug.remote_log: /tmp/php5-xdebug.log
        xdebug.idekey: netbeans-xdebug
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_4d4un6mnls80:
            default: '1'
            version: 2.1.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: null
    npm_packages:
        - less
        - grunt-cli
        - gulp
        - bower
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users: {  }
    databases: {  }
    grants: {  }
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: 123
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_6qriwb7ju8uf:
            name: globalizedu
            password: aaa
        mysqlnu_elfq3ynorm4p:
            name: globalizedu_wp
            password: aaa
    databases:
        mysqlnd_w6tkfrnxry5s:
            name: globalizedu
            sql: /var/project/globalizedu_test.sql
        mysqlnd_yat8ew8d76ne:
            name: globalizedu_wp
            sql: /var/wp/data/initial.sql
    grants:
        mysqlng_0zk02rwx0m4w:
            user: globalizedu
            table: 'globalizedu.*'
            privileges:
                - ALL
        mysqlng_ct89wr4g9vw1:
            user: globalizedu_wp
            table: 'globalizedu_wp.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: null
        java_install: true
    instances: {  }
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
