### ISSUE TITLE
Error while running make. Halting the installation.

### ISSUE THREAD

**Issue by spectravp** [puphpet/puphpet#2146]
From a clean config generated on 2/2/2016, 10PM EST. 

```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: skeleton.dev
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        box_version: ''
        network:
            private_network: 192.168.56.199
            forwarded_port:
                vflnp_62z41w97he9b:
                    host: '7795'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: false
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                use_linked_clone: '0'
                check_guest_tools: '0'
                update_guest_tools: '0'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_i0pljpxjoh8n:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_US.UTF-8
        timezone: America/New_York
firewall:
    install: '1'
    rules:
        fr_dyi69f56ef09:
            port:
                - '3306'
                - '27017'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_90ummmgj52xx:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_9ewupyhi08f7:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_kavujacy4o6z:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_ogip4osqsf0j:
            servername: skeleton.dev
            serveraliases:
                - www.skeleton.dev
            docroot: /var/www/public
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_mtrnwipfetfu:
                    path: /var/www/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_vc7vyxthai47:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - curl
            - mcrypt
            - gd
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_rcww7fwy2aqm:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.idekey: VAGRANT
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_7jsojgz4wg7m:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_3hnif0mr5fy4:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_uw0lv67l6xnw:
            name: dbname
            sql: ''
    grants:
        mariadbng_0qh3wpd42ugf:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.5'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_igh0orl4o6ct:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_jjqlkbd08mem:
            name: dbname
            sql: ''
    grants:
        mysqlng_8ea6lxnb7voy:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 0.0.0.0
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_eukxwql3qb6w:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

==> local: Error: Execution of '/usr/local/rvm/bin/rvm install 1.9.3 ' returned 2: Searching for binary rubies, this might take some time.
==> local: Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-1.9.3-p551.tar.bz2
==> local: Checking requirements for ubuntu.
==> local: Installing requirements for ubuntu.
==> local: Updating system..........
==> local: Installing required packages: gawk, libyaml-dev, sqlite3, libgdbm-dev, libncurses5-dev, bison, pkg-config.......
==> local: Requirements installation successful.
==> local: ruby-1.9.3-p551 - #configure
==> local: ruby-1.9.3-p551 - #download
==> local:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> local:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13.1M  100 13.1M    0     0  1754k      0  0:00:07  0:00:07 --:--:-- 2306k
==> local: No checksum for downloaded archive, recording checksum in user configuration.
==> local: ruby-1.9.3-p551 - #validate archive
==> local: ruby-1.9.3-p551 - #extract
==> local: ruby-1.9.3-p551 - #validate binary
==> local: Libraries missing for ruby-1.9.3-p551: libruby.so.1.9. Refer to your system manual for installing libraries
==> local: Mounting remote ruby failed with status 10, trying to compile.
==> local: Checking requirements for ubuntu.
==> local: Requirements installation successful.
==> local: Installing Ruby from source to: /usr/local/rvm/rubies/ruby-1.9.3-p551, this may take a while depending on your cpu(s)...
==> local: ruby-1.9.3-p551 - #downloading ruby-1.9.3-p551, this may take a while depending on your connection...
==> local:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> local:                                  Dload  Upload   Total   Spent    Left  Speed
100 9813k  100 9813k    0     0  5504k      0  0:00:01  0:00:01 --:--:-- 5504k
==> local: ruby-1.9.3-p551 - #extracting ruby-1.9.3-p551 to /usr/local/rvm/src/ruby-1.9.3-p551....
==> local: ruby-1.9.3-p551 - #applying patch /usr/local/rvm/patches/ruby/GH-488.patch.
==> local: ruby-1.9.3-p551 - #configuring.............................................
==> local: ruby-1.9.3-p551 - #post-configuration..
==> local: ruby-1.9.3-p551 - #compiling...................................................................................................................................................
==> local: Error running '__rvm_make -j1',
==> local: showing last 15 lines of /usr/local/rvm/log/1454469838_ruby-1.9.3-p551/make.log
==> local:                                    ^
==> local: ossl_ssl.c: In function 'ossl_sslctx_session_remove_cb':
==> local: ossl_ssl.c:431:38: warning: variable 'ret_obj' set but not used [-Wunused-but-set-variable]
==> local:      VALUE ary, sslctx_obj, sess_obj, ret_obj;
==> local:                                       ^
==> local: ossl_ssl.c: In function 'ssl_servername_cb':
==> local: ossl_ssl.c:508:25: warning: variable 'ret_obj' set but not used [-Wunused-but-set-variable]
==> local:      VALUE ary, ssl_obj, ret_obj;
==> local:                          ^
==> local: make[2]: *** [ossl_ssl.o] Error 1
==> local: make[2]: Leaving directory `/usr/local/rvm/src/ruby-1.9.3-p551/ext/openssl'
==> local: make[1]: *** [ext/openssl/all] Error 2
==> local: make[1]: Leaving directory `/usr/local/rvm/src/ruby-1.9.3-p551'
==> local: make: *** [build-ext] Error 2
==> local: ++ return 2
==> local: There has been an error while running make. Halting the installation.
==> local: Error: /Stage[main]/Puphpet_ruby/Puphpet::Ruby::Install[rv_7jsojgz4wg7m]/Rvm_system_ruby[1.9.3]/ensure: change from absent to present failed: Execution of '/usr/local/rvm/bin/rvm install 1.9.3 ' returned 2: Searching for binary rubies, this might take some time.
==> local: Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-1.9.3-p551.tar.bz2
==> local: Checking requirements for ubuntu.
==> local: Installing requirements for ubuntu.
==> local: Updating system..........
==> local: Installing required packages: gawk, libyaml-dev, sqlite3, libgdbm-dev, libncurses5-dev, bison, pkg-config.......
==> local: Requirements installation successful.
==> local: ruby-1.9.3-p551 - #configure
==> local: ruby-1.9.3-p551 - #download
==> local:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> local:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13.1M  100 13.1M    0     0  1754k      0  0:00:07  0:00:07 --:--:-- 2306k
==> local: No checksum for downloaded archive, recording checksum in user configuration.
==> local: ruby-1.9.3-p551 - #validate archive
==> local: ruby-1.9.3-p551 - #extract
==> local: ruby-1.9.3-p551 - #validate binary
==> local: Libraries missing for ruby-1.9.3-p551: libruby.so.1.9. Refer to your system manual for installing libraries
==> local: Mounting remote ruby failed with status 10, trying to compile.
==> local: Checking requirements for ubuntu.
==> local: Requirements installation successful.
==> local: Installing Ruby from source to: /usr/local/rvm/rubies/ruby-1.9.3-p551, this may take a while depending on your cpu(s)...
==> local: ruby-1.9.3-p551 - #downloading ruby-1.9.3-p551, this may take a while depending on your connection...
==> local:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> local:                                  Dload  Upload   Total   Spent    Left  Speed
100 9813k  100 9813k    0     0  5504k      0  0:00:01  0:00:01 --:--:-- 5504k
==> local: ruby-1.9.3-p551 - #extracting ruby-1.9.3-p551 to /usr/local/rvm/src/ruby-1.9.3-p551....
==> local: ruby-1.9.3-p551 - #applying patch /usr/local/rvm/patches/ruby/GH-488.patch.
==> local: ruby-1.9.3-p551 - #configuring.............................................
==> local: ruby-1.9.3-p551 - #post-configuration..
==> local: ruby-1.9.3-p551 - #compiling...................................................................................................................................................
==> local: Error running '__rvm_make -j1',
==> local: showing last 15 lines of /usr/local/rvm/log/1454469838_ruby-1.9.3-p551/make.log
==> local:                                    ^
==> local: ossl_ssl.c: In function 'ossl_sslctx_session_remove_cb':
==> local: ossl_ssl.c:431:38: warning: variable 'ret_obj' set but not used [-Wunused-but-set-variable]
==> local:      VALUE ary, sslctx_obj, sess_obj, ret_obj;
==> local:                                       ^
==> local: ossl_ssl.c: In function 'ssl_servername_cb':
==> local: ossl_ssl.c:508:25: warning: variable 'ret_obj' set but not used [-Wunused-but-set-variable]
==> local:      VALUE ary, ssl_obj, ret_obj;
==> local:                          ^
==> local: make[2]: *** [ossl_ssl.o] Error 1
==> local: make[2]: Leaving directory `/usr/local/rvm/src/ruby-1.9.3-p551/ext/openssl'
==> local: make[1]: *** [ext/openssl/all] Error 2
==> local: make[1]: Leaving directory `/usr/local/rvm/src/ruby-1.9.3-p551'
==> local: make: *** [build-ext] Error 2
==> local: ++ return 2
==> local: There has been an error while running make. Halting the installation.
