### ISSUE TITLE
first up and up --provision fails at loading facts for php

### ISSUE THREAD

**Issue by rayphi** [puphpet/puphpet#2147]
On first `vagrant up` and also after that at `vagrant up --provision` the following error comes up:

```
==> local:  ____        ____  _   _ ____      _      generated using
==> local: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> local: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> local: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> local: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> local: Running provisioner: shell...
    local: Running: C:/Users/raphael/AppData/Local/Temp/vagrant-shell20160203-14324-10rhnoi.sh
==> local: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> local: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> local: Adding generated root key to /root/.ssh/id_rsa
==> local: Adding generated root key to /root/.ssh/id_rsa.pub
==> local: Adding generated root key to /root/.ssh/authorized_keys
==> local: Adding generated key to /home/vagrant/.ssh/id_rsa
==> local: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> local: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> local: Running provisioner: shell...
    local: Running: C:/Users/raphael/AppData/Local/Temp/vagrant-shell20160203-14324-y7zhvz.sh
==> local: Running provisioner: shell...
    local: Running: C:/Users/raphael/AppData/Local/Temp/vagrant-shell20160203-14324-1cjngch.sh
==> local: Successfully installed deep_merge-1.0.1
==> local: Successfully installed activesupport-4.2.5.1
==> local: Successfully installed vine-0.2
==> local: 3 gems installed
==> local: Running provisioner: shell...
    local: Running: C:/Users/raphael/AppData/Local/Temp/vagrant-shell20160203-14324-tdyxqc.sh
==> local: Running files in files/exec-preprovision
==> local: Finished running files in files/exec-preprovision
==> local: To run again, delete hashes you want rerun in /.puphpet-stuff/exec-preprovision-ran or the whole file to rerun all
==> local: Running files in files/
==> local: Finished running files in files/
==> local: Running provisioner: puppet...
==> local: Running Puppet with ...
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Info: Loading facts
==> local: Error: Evaluation Error: Error while evaluating a Function Call, each(): wrong argument type (NilClass; must be something enumerable. at /tmp/vagrant-pupp
et/manifests-75f35e3bc7e32744860c4bb229c88812/Php.pp:100:3 on node m.local
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
(box puphpet/ubuntu1404-x64 is up to date)
following configuration is in use:
```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: m.local
        memory: '1024'
        cpus: '2'
        chosen_provider: virtualbox
        box_version: ''
        network:
            private_network: 192.168.56.112
            forwarded_port:
                vflnp_z6z5y1dai10s:
                    host: '6934'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: false
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                use_linked_clone: '0'
                check_guest_tools: '0'
                update_guest_tools: '0'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_y2htyfdy5uwp:
                source: ./
                target: /var/www
                sync_type: smb
                smb:
                    smb_host: 192.168.0.63
                    smb_username: *******
                    smb_password: *******
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: de_DE.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - de_DE.UTF-8
        timezone: Europe/Berlin
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts: {  }
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - cache
        - deflate
        - headers
        - expires
    vhosts:
        av_j15px8usop8y:
            servername: n.dev
            serveraliases:
                - ndev.local
            docroot: /var/www/www.n.de/docroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_radx1qf8k12u:
                    path: /var/www/www.n.de/docroot
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_iofbesewnlsr:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_3uthgjo7lguo:
            servername: cms.n.dev
            serveraliases:
                - ncmsdev.local
            docroot: /var/www/cms.n.de/docroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=div'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_32kw4lps8gic:
                    path: /var/www/cms.n.de/docroot
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_pv2hlxvk2iyu:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_s1gmyxbqr42t:
            servername: b.dev
            serveraliases:
                - bb.dev
                - bb.local
            docroot: /var/www/b/bb-shop/
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=div'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_kbe6813tejld:
                    path: /var/www/b/bb-shop/
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_bdw9mnhnfb6l:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_tiw1asn5xhod:
            servername: cms.b.dev
            docroot: /var/www/b/TYPO3
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=div'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_v1gdjrqct39a:
                    path: /var/www/b/TYPO3
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_1ixn7u83b1sc:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - imagick
            - xcache
        pear: {  }
        pecl:
            - APC
            - pecl_http
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Berlin
        max_execution_time: '240'
        post_max_size: 75m
        upload_max_filesize: 75m
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_t6r28v80s8m4:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: '500'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_q5clw7suc3bm:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_qh39lzbspewu:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_2c092rd3bfg9:
            name: dbname
            sql: ''
    grants:
        mariadbng_pnildeh9s6yv:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_sodj1l5f98cg:
            name: m
            password: m
    databases:
        mysqlnd_m2be1753qiux:
            name: dev_n_magento
            sql: ''
        mysqlnd_lwzntbluiqsg:
            name: dev_n_typo3
            sql: ''
        mysqlnd_pr837blviqih:
            name: dev_b_magento
            sql: ''
        mysqlnd_n0i0tbv23h5f:
            name: dev_b_typo3
            sql: ''
    grants:
        mysqlng_i2cmtmgknbl0:
            user: m
            table: '*.*'
            privileges:
                - ALL
        mysqlng_3ywsbuhlu61m:
            user: n
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_p4yjfw4x3dev:
            name: es-01
solr:
    install: '1'
    settings:
        version: 4.10.2
        port: '8984'
```
