### ISSUE TITLE
Mailhog UI - ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by JohnHeroHD** [puphpet/puphpet#2151]
I can not access the Mailhog UI on `http://SERVER_IP_ADDRESS:8020`. It gives me the following error:

```
This webpage is not available
ERR_CONNECTION_REFUSED
```

When I run the `mailhog` command inside the VM I get:
```
2016/02/04 11:37:52 [SMTP] Binding to address: 0.0.0.0:1024
2016/02/04 11:37:52 [SMTP] Error listening on socket: listen tcp 0.0.0.0:1024: bind: address already in use
```

There is nothing else running on that port, I have no glue what is going on.

The Mailhog portion of the config.yaml looks like this, freshly generated from https://puphpet.com:

```
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: '1024'
        http_ip: 0.0.0.0
        http_port: '8020'
        path: /usr/local/bin/mailhog
```

It does look like he actually catches mail, because I do not get any in my "real" mailbox.
Now I just need to be able to access those e-mails he catches.
