### ISSUE TITLE
Augeas has failures

### ISSUE THREAD

**Issue by Dandroas** [puphpet/puphpet#2180]
My box used to work fine, but when I tried to `up` it yesterday, I got the below issue. Any Ideas?

```
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.d/default.conf]/ensure: removed
==> default: Info: Class[Nginx::Config]: Scheduling refresh of Class[Nginx::Service]
==> default: Info: Class[Nginx::Service]: Scheduling refresh of Service[nginx]
==> default: Notice: /Stage[main]/Nginx::Service/Service[nginx]/ensure: ensure changed 'stopped' to 'running'
==> default: Info: /Stage[main]/Nginx::Service/Service[nginx]: Unscheduling refresh on Service[nginx]
==> default: Notice: /Stage[main]/Pyenv/Vcsrepo[/usr/local/pyenv]/ensure: Creating repository from present
==> default: Notice: /Stage[main]/Pyenv/Vcsrepo[/usr/local/pyenv]/ensure: created
==> default: Notice: /Stage[main]/Pyenv/File[/usr/local/bin/pyenv]/ensure: created
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[global/error_log: /var/log/php-fpm.log] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[global/pid: /var/run/php-fpm/php-fpm.pid] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[www/listen: 127.0.0.1:9000] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[www/security.limit_extensions: .php] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[www/user: www-user] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[www/group: www-data] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[CUSTOM/cgi.fix_pathinfo: 1] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[CUSTOM/display_errors: On] has failures: true
==> default: 
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[CUSTOM/error_reporting: -1] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[CUSTOM/session.save_path: /var/lib/php/session] has failures: true
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Dependency Augeas[CUSTOM/date.timezone: UTC] has failures: true
==> default: Warning: /Stage[main]/Puphpet_php/Service[php-fpm]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Puphpet_php/Service[php-fpm]: Triggered 'refresh' from 6 events
==> default: Error: Could not find a suitable provider for augeas
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 868.50 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

with config:

```
vagrantfile:
    target: local
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: local.puphpet
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_yvbcjk2h2bvw:
                    host: '8563'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_xfmqe9f8qfhj:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules:
        fr_ofb3uey0zneb:
            port:
                - '80'
                - '3306'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts: {  }
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_05kzgq7l9sdn:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_v8tarw3bp53c:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_7tsc11tii16c:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_ri0z25ckgkux:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_eie060mi59ix:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_p26h52dlcdk1:
            name: dbname
            sql: ''
    grants:
        mysqlng_1xyowgby2783:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mariadb:
    install: '1'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_tbysrbokj4hj:
            name: dbuser
            password: '123'
        mariadbnu_z1h3jwr35t43:
            name: ziipr
            password: '12345'
    databases:
        mariadbnd_oun25veasipv:
            name: dbname
            sql: ''
        mariadbnd_r0pgihx0e31p:
            name: ziipr
            sql: /vagrant/ziipr.sql
        mariadbnd_flk9co1057tf:
            name: ziipr_prod
            sql: /vagrant/ziipr_prod.sql
    grants:
        mariadbng_ztr04xn8ogik:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
        mariadbng_8wv774cunh5x:
            user: ziipr@%
            table: 'ziipr.*'
            privileges:
                - ALL
        mariadbng_20bjeofguutd:
            user: ziipr@%
            table: 'ziipr_prod.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'


```
