### ISSUE TITLE
MongoDB 3.2

### ISSUE THREAD

**Issue by joshuaadickerson** [puphpet/puphpet#2213]
Mongo's stable version is 3.2. Can you add it and 3.0 to the supported versions?

**Comment by jtreminio** [comment]
The puppetlabs-mongodb module does not yet support MongoDB 3+

https://github.com/puppetlabs/puppetlabs-mongodb

**Comment by ebisbe** [comment]
@jtreminio In the changelog of puppetlabS/mongodb says that the version 3.X is already available [Changelog](https://forge.puppet.com/puppetlabs/mongodb/changelog#release-0130)

**Comment by jtreminio** [comment]
@ebisbe Unfortunately the puppetlabs-mongodb repo isn't as compatible as they claim:

https://twitter.com/juantreminio/status/785910397576417280

**Comment by ebisbe** [comment]
Ok, sorry to bother you. I've manage to installit by the way. I've just made a small shell script that replaces the installation of mongo with the new version and all configuration is done through the config.yaml

**Comment by kevinmlong** [comment]
I was curious about this too. I just changed:

```
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.12-1
    databases: {  }
```
to
```
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 3.4.1
    databases: {  }
```
