### ISSUE TITLE
startup-once-unprivileged scripts raise "permission denied" when copying files inside shared folder

### ISSUE THREAD

**Issue by ruslanbes** [puphpet/puphpet#2220]
Hi all. 
I have a mysterious issue with shell scripts in startup-once-unprivileged 
Sorry for lots of code. 

Host: Windows 7 x64, guest: Ubuntu 1404 x64

I have several scripts in startup-once-unprivileged folder, the first two are:
`10-clone-simplesamlphp-from-github.sh # clones github repo and extracts it into shared folders`
`11-initialize-config-and-metadata.sh # copies some files inside shared folders`
### Case 1:

- Run vagrant destroy -f 
- then vagrant up

In this case the `11-initialize-config-and-metadata.sh` script shows "Permission denied" errors when copying files inside the shared folders
### Case 2:

- Run vagrant destroy -f
- move files from startup-once-unprivileged into some tmp dir outside puphpet
- Run vagrant up
- move files back into startup-once-unprivileged
- Run vagrant reload

In this case everything is working perfectly, no errors. Also running the shell scripts from inside VM works fine too. So the problem happens only on the first start of the virtual machine.

Has anyone the idea of why there could be a difference?

### Files:
```
#!/bin/sh
# 10-clone-simplesamlphp-from-github.sh

cd /vagrant/saml-src
rm -rf ./simplesamlphp
git clone https://github.com/simplesamlphp/simplesamlphp.git

cd ./simplesamlphp
git archive master | tar -x -C ../../saml-sp/simplesamlphp
cd ../../
cp -fr ./saml-sp/simplesamlphp ./saml-idp
```

```
#!/bin/sh
# 11-initialize-config-and-metadata.sh
cd /var/saml-idp/simplesamlphp
cp -r config-templates/* config/
cp -r metadata-templates/* metadata/

cd /var/saml-sp/simplesamlphp
cp -r config-templates/* config/
cp -r metadata-templates/* metadata/

```

and my config.yaml is:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_t20sthij37dz:
                        id: simplesamlphp
                        network:
                            private_network: 192.168.56.112
                            forwarded_port:
                                vflmnfp_ojbcjagapa0b:
                                    host: '22112'
                                    guest: '22'
                        hostname: simplesamlphp.dev
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_1v2rlcmssv7g:
                source: ./saml-sp/simplesamlphp
                target: /var/saml-sp/simplesamlphp
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_pl1j2y9k82cj:
                source: ./saml-idp/simplesamlphp
                target: /var/saml-idp/simplesamlphp
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - htop
        - mc
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_jrxa3yqd054e:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_slx97z9gr5h7:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_a3qsuiq9aba7:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_i9xxzv01quq7:
            servername: saml-sp.simplesamlphp.dev
            serveraliases:
                - samlsp.simplesamlphp.dev
            docroot: /var/saml-sp/simplesamlphp/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'SIMPLESAMLPHP_CONFIG_DIR /var/saml-sp/simplesamlphp/config'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_9j7j7aszb42l:
                    path: /var/saml-sp/simplesamlphp/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_yw33lpp6qnan:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_wx8n0jsj9xus:
            servername: saml-sp.simplesamlphp.dev
            serveraliases:
                - samlsp.simplesamlphp.dev
            docroot: /var/saml-sp/simplesamlphp/www
            port: '443'
            setenv:
                - 'APP_ENV dev'
                - 'SIMPLESAMLPHP_CONFIG_DIR /var/saml-sp/simplesamlphp/config'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_kyomfefb059y:
                    path: /var/saml-sp/simplesamlphp/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_s74rn1ld1u94:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_z4xk5ao4frxz:
            servername: saml-idp.simplesamlphp.dev
            serveraliases:
                - samlidp.simplesamlphp.dev
            docroot: /var/saml-idp/simplesamlphp/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'SIMPLESAMLPHP_CONFIG_DIR /var/saml-idp/simplesamlphp/config'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_myknwop5gljr:
                    path: /var/saml-idp/simplesamlphp/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_3dsfaf346iky:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_lsa100qxe6wc:
            servername: saml-idp.simplesamlphp.dev
            serveraliases:
                - samlidp.simplesamlphp.dev
            docroot: /var/saml-idp/simplesamlphp/www
            port: '443'
            setenv:
                - 'APP_ENV dev'
                - 'SIMPLESAMLPHP_CONFIG_DIR /var/saml-idp/simplesamlphp/config'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_hqfy6iprzwx8:
                    path: /var/saml-idp/simplesamlphp/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_x1y9zbtdmn46:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - curl
            - mcrypt
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_xd0vtnjfw6de:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_853asgss9e5f:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_394tg0g6ja3c:
            name: samlsp
            password: samlsp
        mariadbnu_o98zykx3gl6r:
            name: samlidp
            password: samlidp
    databases:
        mariadbnd_dz8o48mt0bwb:
            name: samlsp
            sql: ''
        mariadbnd_gogysg47yuw1:
            name: samlidp
            sql: ''
    grants:
        mariadbng_z6eo00z0ccyr:
            user: samlsp
            table: 'samlsp.*'
            privileges:
                - ALL
        mariadbng_qgmdp1ej57ys:
            user: samlidp
            table: 'samlidp.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_4i10r7wbl85j:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_slwgxm75djhs:
            name: dbname
            sql: ''
    grants:
        mysqlng_6il5qw6zcate:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases:
        postsqlnd_6jtqqikghu9n:
            dbname: samlsp
            owner: samlsp
        postsqlnd_mdx7b6quc9v5:
            dbname: samlidp
            owner: samlidp
    users:
        postsqlnu_7t0201hcox23:
            username: samlsp
            password: samlsp
        postsqlnu_gsxt76t3mdr2:
            username: samlidp
            password: samlidp
    grants: {  }
    adminer: '1'
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_ys5ebb0q6pfx:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```

**Update:** it seems I figured out why the problem may happen. I have the same directory shared twice - as a subdir vagrant shared folder ( /vagrant/saml-sp ) and the second directly time as ( /var/saml-sp ) and these 2 scripts refer to these two different folders. I'll try to rewrite the scripts to use the same shared folder in all scripts and check if it helps
