### ISSUE TITLE
Uploading an existing config doesn't properly populate nginx proxy_redirect

### ISSUE THREAD

**Issue by tetele** [puphpet/puphpet#2230]
When I upload a config file already generated with PuPHPet, this part

```
nginx:
    install: '1'
...
    vhosts:
        nxv_3zh2drsdcjua:
...
            locations:
                nxvl_j2asqegu9poj:
...
                    proxy: 'http://some_upstream'
                    proxy_redirect: 'off'
```

gets turned into this http://screencast.com/t/hYw2awmHNjjQ

**Comment by tetele** [comment]
Obviously, upon re-downloading the config, the new file gets populated with the bad value

```
nginx:
    install: '1'
...
    vhosts:
        nxv_3zh2drsdcjua:
...
            locations:
                nxvl_j2asqegu9poj:
...
                    proxy: 'http://some_upstream'
                    proxy_redirect: 'http://some_upstream'
```
