### ISSUE TITLE
pip install timeout

### ISSUE THREAD

**Issue by olignyf** [puphpet/puphpet#2231]
This is my PuPHPet config:
https://github.com/olignyf/vagrant-puppet-phantomjs-python/commit/4ae920245696b3012b1c7fd67276b051eb470ac0

Somehow it fails to install all my python modules (pip install).
But when the VM is up, I ssh into it and run "pip install xyz" and it all passes without error.

This is an excerpt of the output of initial vagrant up:
==> machine1: Notice: /Stage[main]/Puphpet_php/Exec[mkdir -p /var/lib/php/session]/returns: executed successfully
==> machine1: Info: /Stage[main]/Puphpet_php/Exec[mkdir -p /var/lib/php/session]: Scheduling refresh of Service[php5-fpm]
==> machine1: Error: Command exceeded timeout
==> machine1: Error: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: change from notrun to 0 failed: Command exceeded timeout
==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[easy_install pip]: Dependency
Exec[Download and install ez_setup] has failures: true
==> machine1: Warning: /Stage[main]/Puphpet::Python::Pip/Exec[easy_install pip]: Skipping because of failed dependencies

This is my pip install line :
sudo pip install columnize robotframework fabric ssh paramiko ansible argparse ansicolors ipaddress requests requests_oauthlib lxml jsonschema xmltodict robotframework-sshlibrary tablib openpyxl xlwt xlrd xlutils pymongo ansi2html selenium pexpect

These are the python modules from my config.yaml (also available on github on the link above)

```
python:
    install: '1'
    packages:
        - columnize
        - robotframework
        - fabric
        - ssh
        - ansible
        - argparse
        - ansicolors
        - ipaddress
        - requests
        - requests_oauthlib
        - lxml
        - jsonschema
        - xmltodict
        - tablib
        - openpyxl
        - xlwt
        - xlrd
        - xlutils
        - pymongo
        - ansi2html
        - selenium
        - pexpect
        - pycrypto
        - paramiko
        - robotframework-sshlibrary
    versions: {  }
```
