### ISSUE TITLE
SMB on Windows 10 not working

### ISSUE THREAD

**Issue by bbonora** [puphpet/puphpet#2235]
Windows 10 Home 64bit
Vagrant 1.8.1
VirtualBox 5.0.16

Is there a trick to getting SMB working? I've tried several different things and can't seem to get anything to work. I always run `vagrant up` in PowerShell as the admin user and  below is the error I receive. 

Do I need to install samba on the Virtualbox first and then change my settings?  Any help on this would be much appreciated.

I've heard that SMB is really perfomant on Windows and it would be great if I could get this working.

``` bash
PS C:\Users\Ben\.local.server> vagrant up
Bringing machine 'dev' up with 'virtualbox' provider...
==> dev: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> dev: There was a problem while downloading the metadata for your box
==> dev: to check for updates. This is not an error, since it is usually due
==> dev: to temporary network problems. This is just a warning. The problem
==> dev: encountered was:
==> dev:
==> dev:
==> dev:
==> dev: If you want to check for box updates, verify your network connection
==> dev: is valid and try again.
==> dev: Clearing any previously set forwarded ports...
==> dev: Preparing SMB shared folders...
==> dev: Clearing any previously set network interfaces...
==> dev: Preparing network interfaces based on configuration...
    dev: Adapter 1: nat
    dev: Adapter 2: hostonly
==> dev: Forwarding ports...
    dev: 22 (guest) => 6847 (host) (adapter 1)
    dev: 3306 (guest) => 3308 (host) (adapter 1)
    dev: 22 (guest) => 2222 (host) (adapter 1)
==> dev: Running 'pre-boot' VM customizations...
==> dev: Booting VM...
==> dev: Waiting for machine to boot. This may take a few minutes...
    dev: SSH address: 127.0.0.1:2222
    dev: SSH username: vagrant
    dev: SSH auth method: private key
==> dev: Machine booted and ready!
==> dev: Checking for guest additions in VM...
==> dev: Setting hostname...
==> dev: Configuring and enabling network interfaces...
==> dev: Mounting SMB shared folders...
    dev: Installing SMB "mount.cifs"...
    dev: C:/Users/Ben/projects => /var/www
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o uid=`id -u www-data`,gid=`getent group www-data | cut -d: -f3`,dir_mode=0775,file_mode=0664,sec=ntlm,cr
edentials=/etc/smb_creds_2299426c53ab94bf9797b29e1a584a2b ///2299426c53ab94bf9797b29e1a584a2b /var/www
mount -t cifs -o uid=`id -u www-data`,gid=`id -g www-data`,dir_mode=0775,file_mode=0664,sec=ntlm,credentials=/etc/smb_cr
eds_2299426c53ab94bf9797b29e1a584a2b ///2299426c53ab94bf9797b29e1a584a2b /var/www

The error output from the last command was:

mount.cifs: bad UNC (///2299426c53ab94bf9797b29e1a584a2b)
```

Here is my `config.yaml` file:

``` yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_n3qf8zufyh4g:
                        id: dev
                        network:
                            private_network: 12.12.12.12
                            forwarded_port:
                                vflmnfp_g1kvet2amzb7:
                                    host: '6847'
                                    guest: '22'
                                mysql_ldksksloslhs9:
                                    host: '3308'
                                    guest: '3306'
                        hostname: dev.local
                        memory: '2048'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_x0wgcdprtw8e:
                source: ../projects
                target: /var/www
                sync_type: smb
                smb:
                    smb_host: ''
                    smb_username: 'Ben'
                    smb_password: 'xxxxxxxxx'
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - curl
        - git-core
        - imagemagick
        - sendmail
        - unzip
        - mc
        - siege
        - graphviz
        - memcached
        - apache2-utils
        - libssh2-1-dev
        - libmemcached-dev
        - htop
        - dos2unix
        - percona-toolkit
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: America/Los_Angeles
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_hi3yoycjd43o:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_ugb6kp01v3qe:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_6dvbdk0jagxu:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - headers
        - expires
        - deflate
        - vhost_alias
        - proxy_fcgi
        - pagespeed
    vhosts:
        av_pjon7wkmw7vn:
            servername: frequency.dev
            serveraliases:
                - www.frequency.dev
                - '*.frequency.dev'
            docroot: /var/www/frequency-acsf/docroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_136i4w6d3txj:
                    path: /var/www/frequency-acsf/docroot
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_en2uj5ceeoci:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory

php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
        pear: {}
        pecl: {}
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: '/var/lib/php/session'
        memory_limit: '2G'
        date.timezone: 'America/Los_Angeles'
        upload_max_filesize: '50M'
        max_input_vars: 10000
        max_execution_time: 300
        post_max_size: '500M'
        sendmail_path: "/usr/bin/env catchmail"
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_i4hej802rbos:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '1'
    version: v0.21.1
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_jlrewsli17dh:
            default: '1'
            bundler: '0'
            version:  2.1.2
            gems:
                - deep_merge
                - activesupport
                - vine
                - sass
                - compass
                - livereload
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages:
        - yo
        - gulp
        - bower
        - coffee-script
        - jshint
        - csslint
        - eslint
        - nodemon
        - grunt-cli
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_wp7seg4zpmna:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_jj1zp2shfk4n:
            name: dbname
            sql: ''
    grants:
        mariadbng_4sd4j2bbke1a:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.5'
        root_password: '123'
        override_options:
            'mysqld':
                'bind-address': '0.0.0.0'
                'max_allowed_packet': '128M'
                'wait_timeout': '600'
                'query_cache_type': '1'
                'query_cache_size': '128M'
                'query_cache_limit': '2M'
                'innodb_flush_log_at_trx_commit': '2'
                'innodb_lock_wait_timeout': '40'
    adminer: '1'
    users:
        mysqlnu_axj16hkj430h:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_7wkny2oshe16:
            name: dbname
            sql: ''
    grants:
        mysqlng_shniggzjkpdp:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_65mjn98b2uq5:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```

**Comment by Djuuu** [comment]
It looks like PuPHPet can't guess the smb host address.
Have you tried specifying it explicitly ? (It shoud be the _host_ IP as seen from the _guest_)
```yaml
        # ...
        synced_folder:
            vflsf_x0wgcdprtw8e:
            # ...
                smb:
                    smb_host: '12.12.12.1'
                    # ...
```

**Comment by mattyhansen** [comment]
@bbonora - Try removing the empty string on `smb_host`:

```
smb:
    smb_host:
    smb_username: 'Ben'
    smb_password: 'xxxxxxxxx'
```

I prefer letting vagrant prompt for username and password, like this:

```
smb:
    smb_host:
    smb_username:
    smb_password:
```
