### ISSUE TITLE
vagrant up fails at ruby

### ISSUE THREAD

**Issue by VoidZoneInteractive** [puphpet/puphpet#2243]
For some reason I cannot make this to work:

I'm receiving following messages:

> /10_Listen 80]/ensure: defined content as '{md5}d5fcefc335117f400d451de47efeca87'
> ==> machine1: Info: /Stage[main]/Puphpet_apache/Apache::Vhost[av_xhwdd1he4aks]/Apache::Listen[80]/Concat::Fragment[Listen 80]/File[/opt/puppetlabs/puppet/cache/concat/_etc_apache2_ports.conf/fragments/10_Listen 80]: Scheduling refresh of Exec[concat_/etc/apache2/ports.conf]
> ==> machine1: Notice: /Stage[main]/Puphpet_apache/Apache::Vhost[av_e49amhhm55fs]/Apache::Listen[443]/Concat::Fragment[Listen 443]/File[/opt/puppetlabs/puppet/cache/concat/_etc_apache2_ports.conf/fragments/10_Listen 443]/ensure: defined content as '{md5}462e40c14c182d965ae6448e832ebb9a'
> ==> machine1: Info: /Stage[main]/Puphpet_apache/Apache::Vhost[av_e49amhhm55fs]/Apache::Listen[443]/Concat::Fragment[Listen 443]/File[/opt/puppetlabs/puppet/cache/concat/_etc_apache2_ports.conf/fragments/10_Listen 443]: Scheduling refresh of Exec[concat_/etc/apache2/ports.conf]
> ==> machine1: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/Exec[concat_/etc/apache2/ports.conf]/returns: executed successfully
> ==> machine1: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/Exec[concat_/etc/apache2/ports.conf]: Triggered 'refresh' from 5 events
> ==> machine1: Info: Computing checksum on file /etc/apache2/ports.conf
> ==> machine1: Info: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/etc/apache2/ports.conf]: Filebucketed /etc/apache2/ports.conf to puppet with sum a961f23471d985c2b819b652b7f64321
> ==> machine1: Notice: /Stage[main]/Apache/Concat[/etc/apache2/ports.conf]/File[/etc/apache2/ports.conf]/content: content changed '{md5}a961f23471d985c2b819b652b7f64321' to '{md5}7c4742adc3e33066c74a24c77716ccce'
> ==> machine1: Info: Concat[/etc/apache2/ports.conf]: Scheduling refresh of Class[Apache::Service]
> ==> machine1: Info: Computing checksum on file /etc/apache2/apache2.conf
> ==> machine1: Info: /Stage[main]/Apache/File[/etc/apache2/apache2.conf]: Filebucketed /etc/apache2/apache2.conf to puppet with sum da32fcc6a783acaebf0d74c17c726bf7
> ==> machine1: Notice: /Stage[main]/Apache/File[/etc/apache2/apache2.conf]/content: content changed '{md5}da32fcc6a783acaebf0d74c17c726bf7' to '{md5}6dd7537b6b40104b01103ddde980b66a'
> ==> machine1: Info: /Stage[main]/Apache/File[/etc/apache2/apache2.conf]: Scheduling refresh of Class[Apache::Service]
> ==> machine1: Notice: /Stage[main]/Puphpet_apache/Exec[Create apache webroot]/returns: executed successfully
> ==> machine1: Info: Class[Apache::Service]: Scheduling refresh of Service[httpd]
> ==> machine1: Notice: /Stage[main]/Puphpet_apache/File[/var/run/apache2/ssl_mutex]/ensure: created
> ==> machine1: Info: /Stage[main]/Puphpet_apache/File[/var/run/apache2/ssl_mutex]: Scheduling refresh of Service[httpd]
> ==> machine1: Notice: /Stage[main]/Apache::Service/Service[httpd]: Triggered 'refresh' from 2 events
> ==> machine1: Notice: /Stage[main]/Puphpet_apache/Exec[Set /var/www/html/index.html contents]/returns: executed successfully
> ==> machine1: Info: Stage[main]: Unscheduling all events on Stage[main]
> ==> machine1: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
> ==> machine1: Notice: Applied catalog in 333.78 seconds
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> 

My config:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/debian75-x64
                box_url: puphpet/debian75-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_huq7cpxz4mzn:
                        id: machine1
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_2tj3uy6nuufi:
                                    host: '5485'
                                    guest: '22'
                        hostname: local.puphpet
                        memory: '4096'
                        cpus: '8'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_r3dzajyf15c6:
                source: ../../
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: vagrant
                group: vagrant
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - mc
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules:
        fr_w6159b4q41ma:
            port:
                - '80'
                - '443'
                - '3306'
                - '21'
                - '4444'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_6dluh1oqrnty:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_t37ulu3yx4tb:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_f3xjr8vo21b4:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - headers
        - expires
    vhosts:
        av_xhwdd1he4aks:
            servername: cdn.vagrant
            serveraliases:
                - www.cdn.site
                - cdn.site
            docroot: /var/www/coupon-admin/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_sde8y0timsmd:
                    path: /var/www/coupon-admin/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_1wwgzcuqst5k:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_e49amhhm55fs:
            servername: cdn.vagrant
            serveraliases:
                - www.cdn.site
                - cdn.site
            docroot: /var/www/coupon-admin/web
            port: '443'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: /vagrant/cdn.site.crt
            ssl_key: /vagrant/cdn.site.key
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_4p0rj0h3yfif:
                    path: /var/www/coupon-admin/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_78v0ej5xte7i:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_0to32uuxeatk:
            servername: gs.vagrant
            serveraliases:
                - www.gs.site
                - gs.site
            docroot: /var/www/coupon-frontend/web
            port: '443'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: /vagrant/gs.site.crt
            ssl_key: /vagrant/gs.site.key
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_hsa3cq83wi9m:
                    path: /var/www/coupon-frontend/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5xdnpf2t7lxp:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_iq53inh387f1:
            servername: gs.vagrant
            serveraliases:
                - www.gs.site
                - gs.site
            docroot: /var/www/coupon-frontend/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_u67rrwy008kj:
                    path: /var/www/coupon-frontend/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_vzremk12ab84:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_n1tgj1a13zyw:
            servername: white.vagrant
            serveraliases:
                - www.white.site
                - white.site
            docroot: /var/www/coupon-whitelabel/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_0hfi3ecyhzep:
                    path: /var/www/coupon-whitelabel/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_9uu5arm4eus6:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_3nkq4jts750b:
            servername: webgears.vagrant
            serveraliases:
                - www.webgears.site
                - webgears.site
            docroot: /var/www/homepage-v3
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_yg7r5pjz5gob:
                    path: /var/www/homepage-v3
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_c6ho8rmq81wb:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_9l4ykomymuow:
            servername: gs-widget.vagrant
            serveraliases:
                - www.gs-widget.site
                - gs-widget.site
            docroot: /var/www/gs-widget
            port: '443'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: /vagrant/gs-widget.site.crt
            ssl_key: /vagrant/gs-widget.site.key
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_1r8qcmvvw304:
                    path: /var/www/gs-widget
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_o2y4k2ju5kts:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_v7r3j8l9rix0:
            servername: voucher-script.vagrant
            serveraliases:
                - www.voucher-script.site
                - voucher-script.site
            docroot: /var/www/voucher-script/server/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_v4xs8mgj7syx:
                    path: /var/www/voucher-script/server/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_sri8wyl3ax7x:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_44802n88tf87:
            servername: afa.vagrant
            serveraliases:
                - www.afa.site
                - afa.site
            docroot: /var/www/afa-seo-rank/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_db8f2nptr7m6:
                    path: /var/www/afa-seo-rank/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_syul9885swy6:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_x4zswvu34bg8:
            servername: gdt-frontend.vagrant
            serveraliases:
                - www.gdt.site
                - gdt.site
            docroot: /var/www/gdt-website/wp
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_wc0sgiopfnna:
                    path: /var/www/gdt-website/wp
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_6c23my926cyt:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_3qle10gdmewf:
            servername: gdt-backend.vagrant
            serveraliases:
                - www.gdt-backend.site
                - gdt-backend.site
            docroot: /var/www/gdt-backend/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
                - 'APP_VAGRANT vagrant'
                - 'APP_PLATFORM vagrant'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_wjm92mf4bhhl:
                    path: /var/www/gdt-backend/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_y6psuyv085cq:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - imap
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Berlin
        memory_limit: '-1'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_4muzhhwzxfjj:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: vagrant
                group: vagrant
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_9ynb8n88ejqa:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_szpne1z0f3i8:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_3u0o99dmgmq0:
            name: gutscheinsammler
            sql: /vagrant/sql/gs.sql
        mariadbnd_kghvfxyu32x2:
            name: cdn
            sql: /vagrant/sql/cdn.sql
        mariadbnd_m28fq62hx6u9:
            name: gs_customer
            sql: ''
        mariadbnd_mxlmix3zmnsc:
            name: voucher-script-partner
            sql: ''
    grants:
        mariadbng_f67frzijhatp:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.5'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_i6idhcgvu2fi:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_jp2v2iws4yck:
            name: dbname
            sql: ''
    grants:
        mysqlng_36h8nwwsbb18:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances: {  }
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
