### ISSUE TITLE
Custom PHP's session.save_path not being applied

### ISSUE THREAD

**Issue by BrendonKoz** [puphpet/puphpet#2245]
I'm having issues with a PHP page that uses sessions declaring, via Xdebug, the following:
> Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/www/processwire/site/assets/sessions) in Unknown on line 0

PuPHPet's default setting for `session.save_path` is `/var/lib/php/session` and there have been a few tickets with regard to it, so I decided to just change it to `/tmp` in the config.yaml. I discovered there was another issue/ticket related to that, and it's suggested to make a subfolder within /tmp, so I did. Unfortunately regardless of the changes I make to the config.yaml file, the changes don't seem to be respected in the actual VM. A quick phpinfo() still shows the `session.save_path` value as being set to `/var/lib/php/session`.

I checked over the `<bundle>/puphpet/puppet/manifests/Php.pp` file, but didn't see anything there that would cause an issue where the custom value wouldn't be set. I've tried `vagrant provision`, `vagrant destroy` and then a `vagrant up` to start from a clean state, and I've tried simply restarting apache, but nothing seems to change the php.ini. I even manually changed the php.ini (located at /etc/php.ini, according to phpinfo() as being the active INI file) and still PHP is looking towards **/var/lib/php/session**. The zzzz_custom.ini *_does_* contain the values from the config.yaml (just discovered this file), but they're not being applied for whatever reason.

I'm not sure if this is a CentOS, PHP-FPM, or Puppet thing.

Related phpinfo() result data below:
```
Server API 	FPM/FastCGI
Virtual Directory Support 	disabled
Configuration File (php.ini) Path 	/etc
Loaded Configuration File 	/etc/php.ini
Scan this dir for additional .ini files 	/etc/php.d 
session.save_path	/var/lib/php/session	/var/lib/php/session
```

My configuration file is below.

```yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos65-x64
                box_url: puphpet/centos65-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_ny2p69afbtfr:
                        id: sspldev01
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_ucxjxnxij49u:
                                    host: '6601'
                                    guest: '22'
                        hostname: sspl.local
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_gj0r1ullez00:
                source: 'C:/Users/bkozlowski.SARWIN2K/Dropbox/development'
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users:
        - sspl
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: America/New_York
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_dcqbj91z0h23:
            server_name: awesome.local
            server_aliases:
                - www.awesome.local
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_us1fk76q92p8:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_uvsi8d4aa9we:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - expires
        - deflate
        - headers
        - vhost_alias
        - userdir
    vhosts:
        av_n0yp4vxevk9g:
            servername: sspl2.org
            serveraliases:
                - www.sspl2.org
            docroot: '/var/www/htdocs2'
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_kj657is8665r:
                    path: /var/www/htdocs2
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                        - Includes
                        - ExecCGI
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_fxnz82mt0tlt:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_sspl-processwire:
            servername: pw.com
            serveraliases:
                - www.pw.com
            docroot: '/var/www/processwire'
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_872jkbn3nm8z:
                    path: '/var/www/processwire'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                        - Includes
                        - ExecCGI
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_89c2zgqdytx1:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_sspl-staffsite:
            servername: test.com
            serveraliases:
                - www.test.com
            docroot: '/var/www/staff.sspl.org'
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_sspl-staffsite:
                    path: '/var/www/staff.sspl.org'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                        - Includes
                        - ExecCGI
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_sspl-staffsite:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_sspl-ssplarchive:
            servername: ssplarchive.com
            serveraliases:
                - www.ssplarchive.com
            docroot: '/var/www/omeka'
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_sspl-ssplarchive:
                    path: '/var/www/omeka'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                        - Includes
                        - ExecCGI
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_sspl-ssplarchive:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_sspl-wpcr:
            servername: wpcr.com
            serveraliases:
                - www.wpcr.com
            docroot: '/var/www/crwp'
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_sspl-wpcr:
                    path: '/var/www/crwp'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                        - Includes
                        - ExecCGI
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_sspl-wpcr:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_sspl-github:
            servername: github.proj
            serveraliases:
                - www.github.proj
            docroot: '/var/www/Github'
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_sspl-github:
                    path: '/var/www/Github'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                        - Includes
                        - ExecCGI
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_sspl-github:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - fpm
            - imap
            - mbstring
            - mysql
            - mysqlnd
            - gd
            - mcrypt
            - xmlrpc
# come pre-installed in CentOS: curl, imagick, memcached, sqlite
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        session.save_path: /tmp/php_sessions
        date.timezone: 'America/New_York'
        error_reporting: 'E_ALL | E_STRICT'
        allow_url_fopen: 'On'
        allow_url_include: 'Off'
        default_charset: 'UTF-8'
        post_max_size: 8M
        upload_max_filesize: 100M
        max_execution_time: '300'
        max_input_time: '60'
        memory_limit: 256M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_nkj81ek9eyqg:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_7fmdjdzwn8f9:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_nfblw6w4ild3:
            name: dbname
            sql: ''
    grants:
        mariadbng_kv0hrcrt1wde:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_2g03i2zawo25:
            name: realm
            password: demonrealm
    databases: {  }
    grants:
        mysqlng_jcunqcg0ml45:
            user: realm
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_2t5owanudff4:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
