### ISSUE TITLE
Errors during vagrant up, php5 fails to install

### ISSUE THREAD

**Issue by LittleBigDev** [puphpet/puphpet#2265]
Hello,

I'm totally lost and have no idea how to troubleshoot this. So, I'll just enumerate facts, and I'll try to answer when you have questions... Any help will be appreciated !

- Just in case you wonder, I was lauching `vagrant up` from my Git Bash terminal. But I had exactly the same issues via windows cmd.
- `vagrant up` has some warnings and errors. 
- **When trying to access my website, php files are not processed (they are downloaded, I can see the files content in the http response)**
- Looks like php5 was not installed (actually, I checked. It's not.)
- config.yaml file is pasted at the end of this post
- `vagrant up` command ended up with this message :
```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
- Here are the warning and errors outputted by the initial `vagrant up` :
```
vagrant up > vagrant.log
[...]
cat vagrant.log | grep 'Error\|Warning'
    boxId: Warning: Remote connection disconnect. Retrying...
==> boxId: Warning: Scope(Apt::Source[d7031.de]): $required_packages is deprecated and will be removed in the next major release, please use package resources instead.
==> boxId: Warning: Scope(Apt::Source[repo.mysql.com-apt]): $required_packages is deprecated and will be removed in the next major release, please use package resources instead.
==> boxId: Warning: Scope(Apt::Source[packages.dotdeb.org-php56-repo.puphpet]): $required_packages is deprecated and will be removed in the next major release, please use package resources instead.
==> boxId: Warning: Scope(Apt::Source[packages.dotdeb.org-repo.puphpet]): $required_packages is deprecated and will be removed in the next major release, please use package resources instead.
==> boxId: Warning: Found multiple default providers for vcsrepo: bzr, cvs, dummy, git, hg, svn; using bzr
==> boxId: Warning: /Apt_key[Add key: 9EB5E8A3DF17D0B3 from Apt::Source d7031.de]: The id should be a full fingerprint (40 characters), see README.
==> boxId: Warning: /Apt_key[Add key: 89DF5277 from Apt::Source packages.dotdeb.org-php56-repo.puphpet]: The id should be a full fingerprint (40 characters), see README.
==> boxId: Notice: /Stage[main]/Locales/Exec[update-locale]/returns: *** update-locale: Error: invalid locale settings:  LANG="fr_FR.UTF-8"
==> boxId: Error: /Stage[main]/Locales/Exec[update-locale]: Failed to call refresh: /usr/sbin/update-locale returned 255 instead of one of [0]
==> boxId: Error: /Stage[main]/Locales/Exec[update-locale]: /usr/sbin/update-locale returned 255 instead of one of [0]
==> boxId: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-mysql' returned 100: Reading package lists...
==> boxId: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Module[mysql]/Php::Module[mysql]/Package[PhpModule_mysql]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-mysql' returned 100: Reading package lists...
==> boxId: Warning: /Stage[main]/Puphpet_php/Service[php5-fpm]: Skipping because of failed dependencies
```
- You can see the full log in this gist : https://gist.github.com/LittleBigDev/4760eff61f7faf2f8160634180e302ca
- My config.yaml :
```yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/debian75-x64
                box_url: puphpet/debian75-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_4v8ru4guo3yh:
                        id: boxId
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_grk9ctv2jszo:
                                    host: '9244'
                                    guest: '22'
                        hostname: boxId
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_3z1b3ems086l:
                source: 'c:/vagrant/webroot'
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups: {  }
    users:
        - username
locale:
    install: '1'
    settings:
        default_locale: fr_FR.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: Europe/Paris
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_6b1dnrmxg6jx:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_me87e98rhk73:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_49bqogdwhp4t:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        av_2lptqc3et094:
            servername: client.companyName.local
            docroot: /var/www/company-client/app/webroot
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - curl
            - gd
            - gmp
            - imap
            - ldap
            - mbstring
            - mysql
            - mysqli
            - xmlrpc
            - xsl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Paris
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.remote_autostart: '1'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_dkajqf5ldwnz:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_fqc6z7qe2hpv:
            name: dbname
            sql: ''
    grants:
        mariadbng_6qc1yr5m1rp2:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: xxxxxxxx
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_ut3iw6odw8a4:
            name: username
            password: xxxxxxxxxx
    databases:
        mysqlnd_wva4ttowf1ks:
            name: myDbName
            sql: ''
    grants:
        mysqlng_bhiqejuf7dbc:
            user: username
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_2h38qjbx4u6f:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
