### ISSUE TITLE
Error during elastic search install 'Operator '[]' is not applicable ...'

### ISSUE THREAD

**Issue by davidnjuko** [puphpet/puphpet#2266]
When running vagrant provision to install elastic search with current configuration

```
...
elastic_search:
   install: '1'
   settings:
      version: 2.0.2
      java_install: true
   instances:
      esi_fpwopil7s5wp:
         name: es-01
...
```

I got this error message :

Error: Evaluation Error: Operator '[]' is not applicable to an Undef Value. at /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812/ElasticSearch.pp:9:35 on node xxx

it seems to be linked to java_install parameter

box : debian / VirtualBox
