### ISSUE TITLE
Support installing ElasticSearch plugins 

### ISSUE THREAD

**Issue by stof** [puphpet/puphpet#2308]
https://github.com/elastic/puppet-elasticsearch supports installing plugins. I'm not aware of a way to configure them through the config.yaml file though.
Is it already possible ? If no, could it be added ?

**Comment by yguedidi** [comment]
It's possible using a `config.yml` like that:
```yaml
elastic_search:
    install: '1'
    settings:
        version: 2.1.2
        java_install: true
        plugins:
            elasticsearch/elasticsearch-mapper-attachments/3.1.2:
                instances: es-01
    instances:
        esi_38s5qionbmxm:
            name: es-01
```
It's just not possible to do that using the UI.
