### ISSUE TITLE
Warnings: PDO en pecl_http

### ISSUE THREAD

**Issue by Vesquen** [puphpet/puphpet#2326]
This is in my config.yaml:

```
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - curl
            - mcrypt
            - intl
            - memcache
            - memcached
            - mysql
            - gd
            - imagick
            - mysqlnd
            - sybase
        pear: {  }
        pecl:
            - pecl_http
            - PDO
            - memcache
            - memcached
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_dak68xb5kt14:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
```

On vagrant provision it returns following errors:

```
==> dev-machine: Error: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]
==> dev-machine: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]
```

```
==> dev-machine: Error: printf "\n" | pecl -d preferred_state=stable install PDO && pecl info PDO returned 1 instead of one of [0]
==> dev-machine: Error: /Stage[main]/Puphpet_php/Puphpet::Php::Pecl[PDO]/Php::Pecl::Module[PDO]/Exec[pecl-PDO]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install PDO && pecl info PDO returned 1 instead of one of [0]
```

I tried installing my vagrant box without pecl_http and PDO, but I do receive warnings:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/PDO.so' - /usr/lib/php5/20121212/PDO.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/pecl_http.so' - /usr/lib/php5/20121212/pecl_http.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

OS: Debian Wheezy 7 x64
