### ISSUE TITLE
Virtual hosts not being created

### ISSUE THREAD

**Issue by Anahkiasen** [puphpet/puphpet#233]
I have the following in my `common.yaml` :

``` yaml
vhosts:
    quickvox:
        servername: quickvox.dev
        serveraliases:
            - www.quickvox.dev
            - www.quickvox.local
            - quickvox.local
            - '*.ngrok.com'
            - '*.local.madewithlovehq.com'
        docroot: /var/www/public
        port: '80'
        setenv:
            - 'APP_ENV dev'
        override:
            - All
```

However the `/etc/apache2/sites-available` folder is empty after building the machine, and doing a `service apache2 start` yields me the following :

``` shell
vagrant@precise64:/var/www$ service apache2 start
 * Starting web server apache2                                                                                                                                   /usr/sbin/apache2ctl: 87: ulimit: error setting limit (Operation not permitted)
[Mon Oct 28 12:29:14 2013] [warn] NameVirtualHost *:80 has no VirtualHosts
(13)Permission denied: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
Unable to open logs
Action 'start' failed.
The Apache error log may have more information.
```

Did I do something wrong somewhere ? The YAML file is straight from the generator.
