### ISSUE TITLE
Apache does not work

### ISSUE THREAD

**Issue by sobit** [puphpet/puphpet#235]
OS: Mac OS X 10.9 Mavericks
Vagrant: 1.3.5
VirtualBox: 4.3.0
VM box: precise64

Hiera yaml:

```

---
vagrantfile-local:
    vm:
        box: precise64
        box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                Hbr3wgvZ9G8c:
                    host: ''
                    guest: ''
        provider:
            virtualbox:
                modifyvm:
                    name: yakdu
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puppet/manifests
                options:
                    - --verbose
                    - '--hiera_config /vagrant/hiera.yaml'
                    - '--parser future'
        synced_folder:
            l0Ma87lkysO3:
                id: vagrant-root
                source: ./
                target: /var/www/yakdu
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages:
        - build-essential
        - vim
        - curl
        - git-core
    dot_files:
        -
            bash_aliases: null
apache:
    modules:
        - php
        - rewrite
    vhosts:
        YVwWc2VzLpSY:
            servername: yakdu.dev
            serveraliases:
                - www.yakdu.dev
            docroot: /var/www/yakdu/web
            port: '80'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: Asia/Dushanbe
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
    location: /var/www/xhprof
mysql:
    root_password: root
    phpmyadmin: 0
    databases:
        j3rOQ1hQPGxZ:
            grant:
                - ALL
            name: yakdu_db
            host: localhost
            user: yakdu
            password: yakdu
            sql_file: ''

```

Hiera is generated by puphpet. Doesn't have any customisations on it. After running vagrant up process ends up with next errors:

```
Warning: Could not retrieve fact fqdn
Error: /Stage[main]/Apache::Service/Service[httpd]: Failed to call refresh: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 
Error: /Stage[main]/Apache::Service/Service[httpd]: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 
```

And I don't have apache running after that.

Trying to run the above command from inside the VM fails to the following error:

```
$ /etc/init.d/apache2 start
 * Starting web server apache2                                                                                                                                                                                                                                                 * 
 * The apache2 configtest failed.
Output of config test was:
apache2: Syntax error on line 36 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/authz_default.load: Cannot load /usr/lib/apache2/modules/mod_authz_default.so into server: /usr/lib/apache2/modules/mod_authz_default.so: cannot open shared object file: No such file or directory
Action 'configtest' failed.
The Apache error log may have more information.
```

Any suggestions?
