### ISSUE TITLE
Notice: Cannot open ./mydb.sql - No such file.

### ISSUE THREAD

**Issue by FieldMarshallVague** [puphpet/puphpet#2360]
Hi,

I've tried many combinations of folder paths in the synced_folder setting and the db import 'sql' file, but whenever I do vagrant up or provision it just doesn't see the file.  I'm wondering if I'm completely misunderstand the relationship between the synced folder and the mysql import sql file path.

Where should I put the *.sql file I'm trying to import (I'm importing 3 DBs)?  I've tried my user folder, the vagrant folder where I'm running vagrant up and a random folder, but nothing seems to work and I've spent several hours on this now.

The box I'm creating is on a remote DigitalOcean droplet.  Here's the config.yaml:

```
vagrantfile:
    target: digitalocean
    vm:
        provider:
            digitalocean:
                image: ubuntu-14-04-x64
                token: mytoken
                ssh_key_name: Vagrant
                setup: true
                ipv6: false
                private_networking: false
                backups_enabled: false
                machines:
                    vfdom_cadc1jjas9hu:
                        id: digitalocean1
                        hostname: digitalocean1.puphpet
                        region: lon1    # Lon1 (London)
                        size: 2gb
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vfdosf_y81wp75d0kk5:
                source: ./
                target: /var/www/html
        post_up_message: ''
    ssh:
        username: me
        private_key_path: ~/.ssh/id_rsa
        public_key_path: null
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups:
        - www-data
    users:
        - www-user:www-data
locale:
    install: '1'
    settings:
        default_locale: en_GB.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: GMT
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_n142xychufkq:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_zqv0lxawwk89:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_zg6ryr28f4o9:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - deflate
        - cache
        - expires
        - headers
        - vhost_alias
        - proxy_fcgi
        - pagespeed
    vhosts:
        av_phhvdrn31yfa:
            servername: me.stg
            serveraliases:
                - www.me.stg
            docroot: /var/www/html/me.com
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_t74ls016dw81:
                    path: /var/www/html/me.com
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_hbzm3ekvxlgq:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: me@me.com
    domains: {  }
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - xsl
            - curl
            - mcrypt
        pear:
            - XML_Util2
            - XML_RPC2
        pecl:
            - zip
    ini:
        display_errors: On
        error_reporting: 'E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED'
        memory_limit: '1700M'
        upload_max_filesize: '512M'
        post_max_size: '512M'
        max_execution_time: '1200'
        realpath_cache_size: '16M'
        realpath_cache_ttl: '3600'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_2b2ud21tn3r1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '1'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_4mrvbsqsnhrf:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_6oyc8z6aadl4:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_mbta0dq9uh3g:
            name: dbname
            sql: ''
    grants:
        mariadbng_yi76fyombohf:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_bw3h6s4gm6md:
            name: me
            password: '1.&-34553fz0'
    databases:
        mysqlnd_9enfuk279nmx:
            name: test
            sql: ''
        mysqlnd_xrpxc9ibrcsr:
            name: mydb
            sql: ./mydb.sql
    grants:
        mysqlng_nyjxtrewh523:
            user: me
            table: '*.*'
            privileges:
                - ALL
                - GRANT OPTION
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_7nlekbaa0xll:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'


```
