### ISSUE TITLE
PHP Extension Installation from Web App

### ISSUE THREAD

**Issue by nfourteen** [puphpet/puphpet#2365]
Today I configured a new box from puphpet.com and needed to install PHP 5.6 and the imagick extension (among others). Here is the PHP config from `config.yaml`:

```
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - curl
            - gd
            - mcrypt
        pear: {  }
        pecl:
            - memcached
            - mysql
            - PDO_MYSQL
            - imagick
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_fm65ro3nujsy:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
```

Upon running `vagrant up`, I created an `info.php` file and noticed that the `pecl` extensions were not loaded. I searched `/etc` and found the following directories: `/etc/php/5.6`, `/etc/php/7.0`, and `/etc/php5/mods-available`. All of the `pecl` extension ini files were located in `/etc/php5/mods-available`, but PHP 5.6 was installed into the `/etc/php/5.6` directory. Running `sudo php5enmod imagick` gives me the expected `WARNING: Module imagick ini file doesn't exist under /etc/php/5.6/mods-available`. 

How can I configure PHP 5.6 to be installed into `/etc/php5/` so the `pecl` extensions are compiled correctly?
