### ISSUE TITLE
nginx vhost location rewrite regex error

### ISSUE THREAD

**Issue by alexbwang** [puphpet/puphpet#2366]
Hello,

I use nginx vhost location rewrite to generate my web server. I found generated nginx config file does not work as exprect. 
I use config.xml as follows,

```
                    rewrites:
                            when: '!-e $request_filename'
                            regex: ^(/ajax/)*(.*)$ /index.php?s=$2 last;
                            target: break
```

but the generated nginx config file as follows, which add addition double quotation mark

```
                    if (!-e $request_filename) {
                           rewrite "^(/ajax/)*(.*)$ /index.php?s=$2 last;"
                           break;
                     }
```

Could you help me to fix it?

Thanks,
Alex

nginx -> vhost -> location -> rewrite -> regex error

---

```
nxv_sp:
            server_name: sp.haha.com
            server_aliases:
                - '*.sp.haha.com'
            www_root: /data/wwwroot/product/b2b/Public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
                - default.html
                - default.htm
                - default.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_sp_1:
                    location: /
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                    rewrites:
                        nxvlrw_fhwxf3l30d4p:
                            when: '!-e $request_filename'
                            regex: ^(/ajax/)*(.*)$ /index.php?s=$2 last;
                            target: break
```
