### ISSUE TITLE
Links to certificate files cannot be created.

### ISSUE THREAD

**Issue by cobhimself** [puphpet/puphpet#2371]
I've specified the path to my ssl certificates and keys within my config.yaml file but puphpet complains links cannot be created:

```
Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/var/www/ssl/self_signed/mysite.crt, /etc/nginx/nxv_bdtmwz3tn2tt.crt)
==> fc-server-bravo: Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/var/www/ssl/self_signed/mysite.crt, /etc/nginx/nxv_bdtmwz3tn2tt.crt)
==> fc-server-bravo: Wrapped exception:
==> fc-server-bravo: File exists @ sys_fail2 - (/var/www/ssl/self_signed/mysite.crt, /etc/nginx/nxv_bdtmwz3tn2tt.crt)
==> fc-server-bravo: Error: /Stage[main]/Puphpet_nginx/Nginx::Resource::Vhost[nxv_bdtmwz3tn2tt]/File[/etc/nginx/nxv_bdtmwz3tn2tt.crt]/ensure: change from absent to link failed: Could not set 'link' on ensure: File exists @ sys_fail2 - (/var/www/ssl/self_signed/mysite.crt, /etc/nginx/nxv_bdtmwz3tn2tt.crt)
==> fc-server-bravo: Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/var/www/ssl/self_signed/mysite.key, /etc/nginx/nxv_bdtmwz3tn2tt.key)
==> fc-server-bravo: Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/var/www/ssl/self_signed/mysite.key, /etc/nginx/nxv_bdtmwz3tn2tt.key)
==> fc-server-bravo: Wrapped exception:
==> fc-server-bravo: File exists @ sys_fail2 - (/var/www/ssl/self_signed/creativepastors.key, /etc/nginx/nxv_bdtmwz3tn2tt.key)
==> fc-server-bravo: Error: /Stage[main]/Puphpet_nginx/Nginx::Resource::Vhost[nxv_bdtmwz3tn2tt]/File[/etc/nginx/nxv_bdtmwz3tn2tt.key]/ensure: change from absent to link failed: Could not set 'link' on ensure: File exists @ sys_fail2 - (/var/www/ssl/self_signed/mysite.key, /etc/nginx/nxv_bdtmwz3tn2tt.key)
```

## Config.yaml

```yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: 'false'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_smdfyixq10uu:
                        id: fc-server-bravo
                        hostname: fc-server-bravo
                        network:
                            private_network: 192.168.33.12
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_f5oaw3quoufo:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups:
        - WebStaff
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_bdtmwz3tn2tt:
            server_name: dev.mysite.com
            www_root: /var/www/mysite/www
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: /var/www/ssl/self_signed/mysite.crt
            ssl_key: /var/www/ssl/self_signed/mysite.key
            ssl_port: '443'
            ssl_protocols: 'TLSv1.1 TLSv1.2'
            ssl_ciphers: 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA'
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_wu3im2b79k8r:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_hws2y7h7kcwr:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_7qplgz13edmy:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_htev7a7yrc6s:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_k8jwrjax17dr:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - imagick
            - imap
            - gd
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        memory_limit: 4002M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_lkwbnqjqkabi:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                group: www-data
                user: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_port: '9001'
        xdebug.remote_mode: req
        xdebug.cli_color: '1'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_9b1okb1773ve:
            version: ''
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: null
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.0'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_beswhtikysj9:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_zdj5uqjqe419:
            name: dbname
            sql: ''
    grants:
        mariadbng_n93s0r7a22fp:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_i3yr19g3zyki:
            name: web
            password: cYcs345awei2v
        mysqlnu_n0c1pn62u518:
            name: dev
            password: 78asdf3a8C3
    databases:
        mysqlnd_k1glkl51xs2c:
            name: fc_db_ee_cp
            sql: ''
        mysqlnd_473ou13ynnje:
            name: fc_db_ee_elevate
            sql: ''
        mysqlnd_hmi5bwqg6dy2:
            name: fc_db_ee_yngadults
            sql: ''
    grants:
        mysqlng_tmfs5h74ragk:
            user: web
            table: '*.*'
            privileges:
                - ALL
        mysqlng_4vc5iuwtjrev:
            user: dev
            table: '*.*'
            privileges:
                - 'CREATE TEMPORARY TABLES'
                - DELETE
                - DROP
                - INSERT
                - 'LOCK TABLES'
                - SELECT
                - 'SHOW DATABASES'
                - UPDATE
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
    instances: {  }
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
