### ISSUE TITLE
Vagrant up issue, pecl redis with php v5.4 says it requires 7 but I need it to be 5.4

### ISSUE THREAD

**Issue by GaxZE** [puphpet/puphpet#2384]
Error:

``` php
==> local.dev: Notice: /Stage[main]/Puphpet_redis/Puphpet::Php::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: pecl/redis requires PHP (version >= 7.0.0, version <= 7.1.0, excluded versions: 6.0.0), installed version is 5.4.45-1~dotdeb+7.1
==> local.dev: Notice: /Stage[main]/Puphpet_redis/Puphpet::Php::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: No valid packages found
==> local.dev: Notice: /Stage[main]/Puphpet_redis/Puphpet::Php::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: install failed
==> local.dev: Error: printf "\n" | pecl -d preferred_state=stable install redis && pecl info redis returned 1 instead of one of [0]
==> local.dev: Info: Php::Pecl::Module[redis]: Unscheduling all events on Php::Pecl::Module[redis]
==> local.dev: Notice: /Stage[main]/Puphpet_redis/Puphpet::Php::Pecl[redis]/Puphpet::Php::Ini[redis]/File[/etc/php5/mods-available/redis.ini]/ensure: created
==> local.dev: Error: /Stage[main]/Puphpet_redis/Puphpet::Php::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install redis && pecl info redis returned 1 instead of one of [0]
```

So I have redis & php 5.4 being installed and this was working a few weeks ago but since i destroyed my machine i've been unable to fix this issue.

**Comment by jtreminio** [comment]
Fixed in latest

**Comment by TMC-LLB** [comment]
I had this same issue, so added a pecl requirement:

`        
pecl:
            - redis-2.2.8
`

However this now gives me a different issue when I up **"Could not evaluate: invalid byte sequence in UTF-8"**:

Any ideas on how to resolve this?

```
==> dev: Info: Puphpet::Php::Module::Pecl[redis-2.2.8]: Scheduling refresh of Service[php5.6-fpm]
==> dev: Notice: /Stage[main]/Puphpet::Php::Install/Service[php5.6-fpm]: Dependency Exec[pecl-redis] has failures: true
==> dev: Info: /Stage[main]/Puphpet::Php::Install/Service[php5.6-fpm]: Unscheduling all events on Service[php5.6-fpm]
==> dev: Info: Class[Puphpet::Php::Install]: Unscheduling all events on Class[Puphpet::Php::Install]
==> dev: Error: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]: Could not evaluate: invalid byte sequence in UTF-8
==> dev: Warning: /Stage[main]/Puphpet::Php::Install/Service[php5.6-fpm]: Skipping because of failed dependencies
==> dev: Notice: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[check alternatives for php]: Dependency Exec[pecl-redis] has failures: true
==> dev: Warning: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[check alternatives for php]: Skipping because of failed dependencies
==> dev: Notice: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[update alternatives for php to 5.6]: Dependency Exec[pecl-redis] has failures: true
==> dev: Warning: /Stage[main]/Puphpet::Php::Alternatives/Puphpet::Alternatives_update[php]/Exec[update alternatives for php to 5.6]: Skipping because of failed dependencies
```

Full config:

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_vjrbftsvctvj:
                        id: backend
                        hostname: backend.dev
                        network:
                            private_network: 192.168.56.111
                            forwarded_port:
                                vflmnfp_q1o6bbfbudgv:
                                    host: '9325'
                                    guest: '22'
                        memory: '1024'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_kr9tqi3apquc:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                        - .idea/
                        - puphpet/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim-common
        - htop
        - cifs-utils
        - imagemagick
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_GB.UTF-8
        locales:
            - en_GB.UTF-8
        timezone: Europe/London
firewall:
    install: '1'
    rules:
        fr_z4fdzbiayku5:
            port:
                - '3000'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs:
        cj_py1blnxlhrha:
            name: laravel_artisan_schedule_runner
            user: vagrant
            command: 'php /var/www/site/artisan schedule:run >> /dev/null 2>&1'
            minute: '*'
            hour: '*'
            weekday: '*'
            month: '*'
            monthday: ''
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_pecjtqzj4h5t:
            server_name: backend.dev
            www_root: /var/www/site/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_qbmfh0ffdf54:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_d4tv6hc5nmpm:
                    location: '~ \.php$'
                    autoindex: 'on'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_s54necypa8pv:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_vyej1bf0aqfg:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_c91eckw6g12r:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '5.6'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mbstring
            - xml
            - imagick
            - soap
        pear: {  }
        pecl:
            - redis-2.2.8
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_7uip22m0sl38:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: a1e33f67-16f7-44db-bde7-a6185c2cba7a
        server_token: a6028cd802a416117e105fe1172106e577bc7febdd20c83bdb38c9e3e849bccf
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_39vuv2fq70yt:
            version: ''
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: ''
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_kx0difoztkby:
            name: dbuser
            password: ''
    databases:
        mariadbnd_8ugo7el5ybod:
            name: dbname
            sql: ''
    grants:
        mariadbng_8qzxjdkh1gv7:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: ''
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_5zlpa9w1c49i:
            name: 
            password: 
    databases:
        mysqlnd_o4n9lc11hbf8:
            name: 
            sql: ''
    grants:
        mysqlng_h02d76d67emd:
            user: 
            table: '.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: '2.6'
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_g9thbbdzrn17:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```

**Comment by TMC-LLB** [comment]
Leaving this as a note in case anyone has the same issue, specifying redis-2.2.8 as a pecl requirement doesn't stop what ever 'default' redis is being installed from pecl.

I think the below in redis.pp only checks for redis and not if someone has put a specific version in to the pecl list?
```
  if array_true($php, 'install') and ! defined(Puphpet::Php::Module::Pecl['redis']) {
    puphpet::php::module::pecl { 'redis':
      service_autorestart => $webserver_restart,
      require             => Class['redis']
    }
  }
```

I just manually changed this file to the version I wanted, i.e. puphpet::php::module::pecl { '**redis-2.2.8**':

and it worked, though this might not have been the best way to fix it!

**Comment by jtreminio** [comment]
ah yes that could be an issue...

**Comment by TMC-LLB** [comment]
Not sure if this is related, but additionally redis no longer starts as a service, trying to start it directly results in:

```
Starting redis-server: 
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 33
>>> 'tcp-backlog 511'
Bad directive or wrong number of arguments
failed
```

Though starting it directly without any conf works

**Comment by srotsch** [comment]
Facing the same issue and followed the suggestions from this thread to find a workaround, I can confirm both

(a) enforcing a version in config.yaml ("pecl: - redis-2.2.8") fails with "Could not evaluate: invalid byte sequence in UTF-8"

(b) adding the version number in redis/install.pp (" puphpet::php::module::pecl { 'redis-2.2.8':") works

**Comment by vincenzo** [comment]
@jtreminio Can't you support a version attribute for redis in the config.yaml?

Something like

```yaml
redis:
    install: '1'
    version: '2.2.8'
    settings:
        port: '6379'
```
