### ISSUE TITLE
vagrant up ask for a sudo password...

### ISSUE THREAD

**Issue by jchatard** [puphpet/puphpet#240]
Here is my `common.yaml`:

``` yaml

---
vagrantfile-local:
    vm:
        box: wheezy64
        box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                UwmasJZzq6bJ:
                    host: ''
                    guest: ''
        provider:
            virtualbox:
                modifyvm:
                    name: debian55
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puppet/manifests
                options:
                    - --verbose
                    - '--hiera_config /vagrant/hiera.yaml'
                    - '--parser future'
        synced_folder:
            4WHe9xCG3bvU:
                id: vagrant-root
                source: /Applications/MAMP/htdocs/Annonces
                target: /var/www
                nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
nginx:
    vhosts:
        NBFOglLTX09U:
            server_name: classifieds.dev
            server_aliases:
                - www.classifieds.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - gd
            - imagick
            - curl
            - common
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
    location: /var/www/xhprof
mysql:
    root_password: '123'
    phpmyadmin: 0
    databases:
        m0zWx8QRk4SE:
            grant:
                - ALL
            name: foo
            host: localhost
            user: root
            password: root
            sql_file: ''
```
