### ISSUE TITLE
Mounted folders empty unless some manual actions are taken and unable to git init (permissions)

### ISSUE THREAD

**Issue by gkatsanos** [puphpet/puphpet#2413]
I created a new vm, with a (fixed) old config.yaml (below).
My mounted folders are _empty_ unless I follow [these instructions](https://github.com/mitchellh/vagrant/issues/3341#issuecomment-39015570) .
Here is my config.yaml 
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: 'false'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_zikppsmvd9bh:
                        id: training
                        hostname: vm.puphpet
                        network:
                            private_network: 192.168.56.102
                        memory: '2048'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_2bmh7px72aue:
                source: /Users/gplus/vm
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0777'
                        file_mode: '0666'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts: {  }
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy
        - rewrite
        - vhost_alias
    vhosts:
        av_t1oi796s4p0n:
            servername: angular2demo
            serveraliases:
                - www.angular2demo.dev
            docroot: /var/www/angular2demo/
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_afjm25cj965j:
            servername: demoapp
            serveraliases:
                - www.demoapp.dev
            docroot: /var/www/demoapp/
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_4bdejrnzau1u:
            servername: mitterndorfer
            serveraliases:
                - www.mitterndorfer.dev
            docroot: /var/www/mitterndorfer
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_atjy1kp1sidn:
            servername: locafox
            serveraliases:
                - www.locafox.dev
            docroot: /var/www/locafox
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_702so7r5xjfi:
            servername: snapengage
            serveraliases:
                - www.snapengage.dev
            docroot: /var/www/snapengage
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_6oowmkdqi84y:
            servername: gplus
            serveraliases:
                - www.gplus.dev
            docroot: /var/www/gplus
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '0'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions:
        pyenv_zvtio4ho02zq:
            version: 2.6.9
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages:
        - bower
        - jshint
        - grunt-cli
        - gulp-cli
        - yo
        - generator-angular-2-webpack
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users: {  }
    databases: {  }
    grants: {  }
mysql:
    install: '0'
    settings:
        version: '5.5'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users: {  }
    databases: {  }
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: null
        java_install: true
    instances: {  }
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```

After I follow the instructions above, I have the following:
```
$ git init
error: chmod on /var/www/angular2demo/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.repositoryformatversion' to '0'

[12:29 PM]-[vagrant@vm]-[/var/www/angular2demo]-[git (ref: re...)] 
$ ls -la
total 60
drwxrwxr-x 14 www-data www-data  476 Aug 26 12:28 ./
drwxrwxr-x 19 www-data www-data  646 Aug 26 11:52 ../
-rw-rw-r--  1 www-data www-data 6148 Aug 26 11:32 .DS_Store
drwxrwxr-x  9 www-data www-data  306 Aug 26 12:29 .git/
-rw-rw-r--  1 www-data www-data    8 Aug 26 10:46 .gitignore
drwxrwxr-x  7 www-data www-data  238 Aug 26 11:30 .idea/
-rw-rw-r--  1 www-data www-data  104 Aug 26 10:37 README.md
drwxrwxr-x  6 www-data www-data  204 Aug 26 10:37 config/
drwxrwxr-x  3 www-data www-data  102 Aug 26 10:37 images/
-rw-rw-r--  1 www-data www-data 1311 Aug 26 10:37 package.json
drwxrwxr-x  8 www-data www-data  272 Aug 26 10:37 src/
-rw-rw-r--  1 www-data www-data  419 Aug 26 10:37 tsconfig.json
-rw-rw-r--  1 www-data www-data  103 Aug 26 10:37 typings.json
-rw-rw-r--  1 www-data www-data   53 Aug 26 10:37 webpack.config.js

[12:29 PM]-[vagrant@vm]-[/var/www/angular2demo]-[git (ref: re...)] 
$ 
```
