### ISSUE TITLE
PuPHPet Vagrant Debian - Can't change provisioned node.js version

### ISSUE THREAD

**Issue by ifthenelse** [puphpet/puphpet#2420]
I want to change the node.js version provisioned with my custom machine (debian75-x64) from v0.12.15 to v4.5.0. I change the ```config.yml``` from (original):
```yaml
nodejs:
    install: '1'
    settings:
        version: '0.12'
    npm_packages:
        - bower
        - gulp
        - grunt-cli
        - browser-sync
```
to
```yaml
nodejs:
    install: '1'
    settings:
        version: '4'
    npm_packages:
        - bower
        - gulp
        - grunt-cli
        - browser-sync
```
then run ```$ vagrant provision```, but after launching a new ssh session I keep seeing:
```sh
$ node --version
v0.12.15
```
no matter restarting the machine and provisioning again. With other packages (```wp-cli``` as instance) I just needed to change version number and launch provisioning.
Am I missing anything else to do?

**Comment by jtreminio** [comment]
Inside your VM delete `/.puphpet-stuff/nodesource` and try again.

**Comment by goemaeret** [comment]
I'm still having this issue even after deleting `/.puphpet-stuff/nodesource` and running `vagrant provision` again. I've initially installed node v4 on my puphpet machine but after changing to node v5 in the config.yaml file it's still shows the following on my machine (**ubuntu1604-x64**), a brand new archive I just configured today through the puphpet GUI:

```
$ node -v
v4.6.1
```

My config.yaml looks like this:
```
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages:
        - grunt-cli
        - gulp-cli
        - yarn
        - bower
```

Also noticed the following lines in the log when running vagrant provision, maybe useful;

```
==>: Notice: /Stage[main]/Puphpet::Nodejs::Install/Puphpet::Server::Wget[/.puphpet-stuff/nodesource]/Exec[download https://deb.nodesource.com/setup_5.x]/returns: executed successfully
==>: Notice: /Stage[main]/Puphpet::Nodejs::Install/Puphpet::Server::Wget[/.puphpet-stuff/nodesource]/File[/.puphpet-stuff/nodesource]/mode: mode changed '0664' to '0775' (a+x)
==>: Info: /Stage[main]/Puphpet::Nodejs::Install/Puphpet::Server::Wget[/.puphpet-stuff/nodesource]/File[/.puphpet-stuff/nodesource]: Scheduling refresh of Exec[add nodejs repo]
==>: Notice: /Stage[main]/Puphpet::Nodejs::Install/Exec[add nodejs repo]: Triggered 'refresh' from 1 events
```

Am I missing something here?

Thx in advance
