### ISSUE TITLE
doesn't work with win32 open-ssh

### ISSUE THREAD

**Issue by smbkr** [puphpet/puphpet#2424]
I get the following error when trying to run `vagrant up` in a PowerShell on Win 10 with open-ssh Win32 5.30:

```
❯ vagrant up
Bringing machine 'Machine-local' up with 'virtualbox' provider...
==> Machine-local: Importing base box 'puphpet/ubuntu1404-x64'...
==> Machine-local: Matching MAC address for NAT networking...
==> Machine-local: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> Machine-local: Setting the name of the VM: newtest_Machine-local_1473409398267_7602
==> Machine-local: Fixed port collision for 22 => 3307. Now on port 10200.
==> Machine-local: Fixed port collision for 22 => 2222. Now on port 10201.
==> Machine-local: Clearing any previously set network interfaces...
==> Machine-local: Preparing network interfaces based on configuration...
    Machine-local: Adapter 1: nat
    Machine-local: Adapter 2: hostonly
==> Machine-local: Forwarding ports...
    Machine-local: 22 (guest) => 10200 (host) (adapter 1)
    Machine-local: 22 (guest) => 10201 (host) (adapter 1)
==> Machine-local: Running 'pre-boot' VM customizations...
==> Machine-local: Booting VM...
==> Machine-local: Waiting for machine to boot. This may take a few minutes...
    Machine-local: SSH address: 127.0.0.1:10201
    Machine-local: SSH username: vagrant
    Machine-local: SSH auth method: private key
    Machine-local: Warning: Remote connection disconnect. Retrying...
==> Machine-local: Machine booted and ready!
==> Machine-local: Checking for guest additions in VM...
==> Machine-local: Setting hostname...
==> Machine-local: Configuring and enabling network interfaces...
==> Machine-local: Mounting shared folders...
    Machine-local: /var/www/Machine => C:/Users/stuart/projects/vagrant/newtest
    Machine-local: /tmp/vagrant-puppet/modules-82abae1f07774f607834f1cdf2134372 => C:/Users/stuart/projects/vagrant/newtest/puphpet/puppet/modules
    Machine-local: /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812 => C:/Users/stuart/projects/vagrant/newtest/puphpet/puppet/manifests ==> Machine-local: Running provisioner: hostmanager...
==> Machine-local: Running provisioner: shell...
    Machine-local: Running: inline script
==> Machine-local: sed: can't read /vagrant/puphpet/shell/*.sh: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I guess because there is no sed in PowerShell.

Config.yml:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_07hrt9c64ttu:
                        id: Machine-local
                        hostname: machine.vm
                        network:
                            private_network: 192.168.33.15
                            forwarded_port:
                                vflmnfp_np29o81mm7lx:
                                    host: '3307'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_b5c8v8kom7vj:
                source: .
                target: /var/www/machine
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
users_groups:
    install: '1'
    groups:
        - developer
    users:
        - developer
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_pc0ogpo33d68:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_8ityqynq3dal:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_7qjgkc0wj1id:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_sw5oh58kl48f:
            servername: machine.local
            serveraliases:
                - www.machine.local
                - machine.dev
                - www.machine.dev
            docroot: /var/www/machine
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_oems01btfkxa:
                    path: /var/www/machine
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_0p9lde5qn8lj:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '0'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '55'
    modules:
        php:
            - cli
            - intl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        error_reporting: 'E_ALL & ~ E_DEPRECATED & ~E_STRICT'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_ekxkhajyznyb:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '0'
    versions: {  }
python:
    install: '0'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_oc4kxengipk7:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_9cntpz5mv3x8:
            name: dbname
            sql: ''
    grants:
        mariadbng_nhqxyh2h2yn1:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: jL!t3
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_fk0ghtfsvpnn:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_o10qrlnpiw67:
            name: _release
            sql: ./_release.sql
    grants:
        mysqlng_ggbz1ulf2bqv:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_ju7j52zfi3sp:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```
