### ISSUE TITLE
Issue with memory and CPU settings on VMWare Workstation

### ISSUE THREAD

**Issue by coolfarmer** [puphpet/puphpet#2437]
Hi,

I think the memory & CPU setting for machines doesn't work.
To test that I generated a fresh new VM on Puphpet and I have only modified the memory (3072) and CPU (2).

```
machines:
    vflm_53bpl1xblzhq:
        id: machine1
        hostname: machine1.puphpet
        network:
            private_network: 192.168.57.101
            forwarded_port:
                vflmnfp_e5o2emqsyylj:
                    host: '6529'
                    guest: '22'
        memory: '3072'
        cpus: '2'
```

And check here the result
![2016-10-03_18-51-49](https://cloud.githubusercontent.com/assets/4965519/19057160/e5a1ec60-899b-11e6-9cbe-08d1bad8bcf9.png)

VMware show me 512 and 1 CPU and the SSH show me too 512 with I do "free -m".

You can see the entire config file here : https://gist.github.com/coolfarmer/ddadf2c861142c1ea64c982cb1f0b8d8

Where is the problem? Puphpet? VMware? Vagrant?
I need some help please! :)

Thanks,
Olivier
