### ISSUE TITLE
NFS options in config.yaml

### ISSUE THREAD

**Issue by sauron918** [puphpet/puphpet#2466]
How to add configuration:
 ```
config.vm.synced_folder "./", "/var/www/", type: "nfs",  mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=2']
``` 
to **config.yaml** ?

I tried to use:
```
synced_folder:
            vflsf_qh8opu6nkhih:
                source: ./
                target: /var/www
                sync_type: nfs
                nfs:
                    mount_options:
                        actimeo: 2
```
But it does't work
