### ISSUE TITLE
Ubuntu 16.04 shows error upon boot

### ISSUE THREAD

**Issue by kanduvisla** [puphpet/puphpet#2469]
When I use Ubuntu 16.04 I get the following error on boot:

    intel_rapi: no valid rapl domains found in package 0tialized - upgrade BIOS or use force_addr=0xaddr

I have the latest version of Vagrant and VirtualBox. What might be going on here?

![screen shot 2016-10-12 at 10 07 24](https://cloud.githubusercontent.com/assets/346681/19302280/b75e1616-9063-11e6-9d2f-2ac591926e3b.png)

`config.yaml`:

    vagrantfile:
        target: local
        vm:
            provider:
                local:
                    box: puphpet/ubuntu1604-x64
                    box_url: puphpet/ubuntu1604-x64
                    box_version: '0'
                    chosen_virtualizer: virtualbox
                    virtualizers:
                        virtualbox:
                            modifyvm:
                                natdnshostresolver1: false
                            showgui: 1
                        vmware:
                            numvcpus: 1
                        parallels:
                            linked_clone: 0
                            check_guest_tools: 0
                            update_guest_tools: 0
                    machines:
                        vflm_axes8g4j2b8c:
                            id: machine
                            hostname: machine.puphpet
                            network:
                                private_network: 192.168.56.101
                                forwarded_port:
                                    vflmnfp_gud5bbttqmgu:
                                        host: '8080'
                                        guest: '80'
                                    vflmnfp_l0q1dxoilt15:
                                        host: '8443'
                                        guest: '443'
                                    vflmnfp_8wnpkhb3qq51:
                                        host: '8025'
                                        guest: '8025'
                            memory: '2048'
                            cpus: '2'
            provision:
                puppet:
                    manifests_path: puphpet/puppet/manifests
                    module_path:
                        - puphpet/puppet/modules
                        - puphpet/puppet/manifests
                    options:
                        - '--verbose'
                        - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
            synced_folder:
                vflsf_pc3jq7j7rnbk:
                    source: ./
                    target: /var/www
                    sync_type: nfs
                    smb:
                        smb_host: ''
                        smb_username: ''
                        smb_password: ''
                        mount_options:
                            dir_mode: '0775'
                            file_mode: '0664'
                    rsync:
                        args:
                            - '--verbose'
                            - '--archive'
                            - '-z'
                        exclude:
                            - .vagrant/
                            - .git/
                        auto: 'true'
                    owner: www-data
                    group: www-data
            usable_port_range:
                start: 10200
                stop: 10500
            post_up_message: ''
        ssh:
            host: 'false'
            port: 'false'
            private_key_path: 'false'
            username: vagrant
            guest_port: 'false'
            keep_alive: '1'
            forward_agent: 'false'
            forward_x11: 'false'
            shell: 'bash -l'
            insert_key: 'false'
        vagrant:
            host: detect
        proxy:
            http: ''
            https: ''
            ftp: ''
            no_proxy: ''
    server:
        install: '1'
        packages:
            - vim
            - htop
    users_groups:
        install: '1'
        groups: {  }
        users: {  }
    locale:
        install: '1'
        settings:
            default_locale: en_US.UTF-8
            locales:
                - en_GB.UTF-8
                - en_US.UTF-8
            timezone: UTC
    firewall:
        install: '1'
        rules: {  }
    cron:
        install: '1'
        jobs: {  }
    nginx:
        install: '1'
        settings:
            version: present
            default_vhost: 1
            proxy_buffers: '4 256k'
            proxy_buffer_size: 128k
            proxy_connect_timeout: 600s
            proxy_send_timeout: 600s
            proxy_read_timeout: 600s
            names_hash_bucket_size: 128
        upstreams: {  }
        vhosts:
            nxv_ipbdsodqkjfv:
                server_name: dev.machine.com
                www_root: /var/www/public
                listen_port: '80'
                index_files:
                    - index.html
                    - index.htm
                    - index.php
                client_max_body_size: 1m
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_port: '443'
                ssl_protocols: ''
                ssl_ciphers: ''
                rewrite_to_https: '1'
                spdy: '1'
                locations:
                    nxvl_914ex182ldwm:
                        location: /
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: ''
                        fastcgi_index: ''
                        fastcgi_split_path: ''
                        proxy: ''
                        proxy_redirect: ''
                    nxvl_ubn08szrx9yq:
                        location: '~ \.php$'
                        try_files:
                            - $uri
                            - $uri/
                            - /index.php$is_args$args
                        fastcgi: '127.0.0.1:9000'
                        fastcgi_index: index.php
                        fastcgi_split_path: '^(.+\.php)(/.*)$'
                        fast_cgi_params_extra:
                            - 'SCRIPT_FILENAME $request_filename'
                            - 'APP_ENV dev'
                        set:
                            - '$path_info $fastcgi_path_info'
                        proxy: ''
                        proxy_redirect: ''
        proxies: {  }
    apache:
        install: '0'
        settings:
            version: 2.4
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0
        modules:
            - proxy_fcgi
            - rewrite
        vhosts:
            av_4rnm4dd8find:
                servername: awesome.dev
                serveraliases:
                    - www.awesome.dev
                docroot: /var/www/awesome
                port: '80'
                setenv:
                    - 'APP_ENV dev'
                setenvif:
                    - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
                custom_fragment: ''
                ssl: '0'
                ssl_cert: ''
                ssl_key: ''
                ssl_chain: ''
                ssl_certs_dir: ''
                ssl_protocol: ''
                ssl_cipher: ''
                directories:
                    avd_3vdl74krwc7e:
                        path: /var/www/awesome
                        options:
                            - Indexes
                            - FollowSymlinks
                            - MultiViews
                        allow_override:
                            - All
                        require:
                            - 'all granted'
                        custom_fragment: ''
                        files_match:
                            avdfm_x9u8wdv49b94:
                                path: \.php$
                                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                                custom_fragment: ''
                                provider: filesmatch
                        provider: directory
    letsencrypt:
        install: '1'
        settings:
            email: ''
        domains: {  }
    php:
        install: '1'
        settings:
            version: '7.0'
        modules:
            php:
                - cli
                - intl
                - xml
                - curl
                - gd
                - mbstring
                - mcrypt
                - mysql
                - xmlrpc
                - xsl
                - zip
            pear: {  }
            pecl: {  }
        ini:
            display_errors: 'On'
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
            date.timezone: UTC
        fpm_ini:
            error_log: /var/log/php-fpm.log
        fpm_pools:
            phpfp_9m1f1313y4c8:
                ini:
                    prefix: www
                    listen: '127.0.0.1:9000'
                    security.limit_extensions: .php
                    user: www-user
                    group: www-data
        composer: '1'
        composer_home: ''
    xdebug:
        install: '0'
        settings:
            xdebug.default_enable: '1'
            xdebug.remote_autostart: '0'
            xdebug.remote_connect_back: '1'
            xdebug.remote_enable: '1'
            xdebug.remote_handler: dbgp
            xdebug.remote_port: '9000'
    blackfire:
        install: '0'
        settings:
            server_id: ''
            server_token: ''
            agent:
                http_proxy: ''
                https_proxy: ''
                log_file: stderr
                log_level: '1'
            php:
                agent_timeout: '0.25'
                log_file: ''
                log_level: '1'
    xhprof:
        install: '0'
    wpcli:
        install: '0'
        version: v0.24.1
    drush:
        install: '0'
        version: 8.0.5
    ruby:
        install: '1'
        versions: {  }
    python:
        install: '1'
        packages: {  }
        versions: {  }
    nodejs:
        install: '0'
        settings:
            version: '6'
        npm_packages: {  }
    hhvm:
        install: '0'
        composer: '1'
        composer_home: ''
        settings: {  }
        server_ini:
            hhvm.server.host: 127.0.0.1
            hhvm.server.port: '9000'
            hhvm.log.use_log_file: '1'
            hhvm.log.file: /var/log/hhvm/error.log
        php_ini:
            display_errors: 'On'
            error_reporting: '-1'
            date.timezone: UTC
    mariadb:
        install: '1'
        settings:
            version: '10.2'
            root_password: xxx
            override_options: {  }
        adminer: 0
        users: {  }
        databases: {  }
        grants: {  }
    mysql:
        install: '0'
        settings:
            version: '5.7'
            root_password: '123'
            override_options: {  }
        adminer: 0
        users:
            mysqlnu_cur96nyz0sib:
                name: dbuser
                password: '123'
        databases:
            mysqlnd_nx1ie73r5gbm:
                name: dbname
                sql: ''
        grants:
            mysqlng_erlex8y0we6j:
                user: dbuser
                table: '*.*'
                privileges:
                    - ALL
    postgresql:
        install: '0'
        settings:
            global:
                encoding: UTF8
                version: '9.6'
            server:
                postgres_password: '123'
        databases: {  }
        users: {  }
        grants: {  }
        adminer: 0
    mongodb:
        install: '0'
        settings:
            bind_ip: 127.0.0.1
            port: '27017'
        globals:
            version: 2.6.0
        databases: {  }
    redis:
        install: '0'
        settings:
            port: '6379'
    sqlite:
        install: '0'
        adminer: 0
        databases: {  }
    mailhog:
        install: '1'
        settings:
            smtp_ip: 0.0.0.0
            smtp_port: 1025
            http_ip: 0.0.0.0
            http_port: '8025'
            path: /usr/local/bin/mailhog
    beanstalkd:
        install: '0'
        settings:
            listenaddress: 0.0.0.0
            listenport: '11300'
            maxjobsize: '65535'
            maxconnections: '1024'
            binlogdir: /var/lib/beanstalkd/binlog
            binlogfsync: null
            binlogsize: '10485760'
        beanstalk_console: 0
    rabbitmq:
        install: '0'
        settings:
            port: '5672'
        users: {  }
        vhosts: {  }
        plugins: {  }
    elastic_search:
        install: '0'
        settings:
            version: 2.3.1
            java_install: true
        instances:
            esi_frasi355vi2a:
                name: es-01
    solr:
        install: '0'
        settings:
            version: 5.5.2
            port: '8984'

**Comment by godler** [comment]
Same issue, Host machine Ubuntu 16.04, VirtualBox 5.0.24, Vagrant 1.8.6

    ==> betstore: Waiting for machine to boot. This may take a few minutes...
    betstore: SSH address: 127.0.0.1:2222
    betstore: SSH username: vagrant
    betstore: SSH auth method: private key
    Timed out while waiting for the machine to boot. This means that
    Vagrant was unable to communicate with the guest machine within
    the configured ("config.vm.boot_timeout" value) time period.

    If you look above, you should be able to see the error(s) that
    Vagrant had when attempting to connect to the machine. These errors
    are usually good hints as to what may be wrong.

    If you're using a custom box, make sure that networking is properly
    working and you're able to connect to the machine. It is a common
    problem that networking isn't setup properly in these boxes.
    Verify that authentication configurations are also setup properly,
    as well.

    If the box appears to be booting properly, you may want to increase
    the timeout ("config.vm.boot_timeout") value.

config.yaml

	vagrantfile:
	    target: local
	    vm:
		provider:
		    local:
		        box: puphpet/ubuntu1604-x64
		        box_url: puphpet/ubuntu1604-x64
		        box_version: '0'
		        chosen_virtualizer: virtualbox
		        virtualizers:
		            virtualbox:
		                modifyvm:
		                    natdnshostresolver1: false
		                showgui: 1
		            vmware:
		                numvcpus: 1
		            parallels:
		                linked_clone: 0
		                check_guest_tools: 0
		                update_guest_tools: 0
		        machines:
		            vflm_2s8c3blj9bzx:
		                id: betstore
		                hostname: betstore.puphpet
		                network:
		                    private_network: 192.168.56.101
		                    forwarded_port:
		                        vflmnfp_158l2mmvp4m6:
		                            host: '8081'
		                            guest: '22'
		                memory: '512'
		                cpus: '1'
		provision:
		    puppet:
		        manifests_path: puphpet/puppet/manifests
		        module_path:
		            - puphpet/puppet/modules
		            - puphpet/puppet/manifests
		        options:
		            - '--verbose'
		            - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
		synced_folder:
		    vflsf_twpuj52w5isa:
		        source: ./
		        target: /var/www
		        sync_type: default
		        smb:
		            smb_host: ''
		            smb_username: ''
		            smb_password: ''
		            mount_options:
		                dir_mode: '0775'
		                file_mode: '0664'
		        rsync:
		            args:
		                - '--verbose'
		                - '--archive'
		                - '-z'
		            exclude:
		                - .vagrant/
		                - .git/
		            auto: 'true'
		        owner: www-data
		        group: www-data
		usable_port_range:
		    start: 10200
		    stop: 10500
		post_up_message: ''
	    ssh:
		host: 'false'
		port: 'false'
		private_key_path: 'false'
		username: vagrant
		guest_port: 'false'
		keep_alive: '1'
		forward_agent: 'false'
		forward_x11: 'false'
		shell: 'bash -l'
		insert_key: 'false'
	    vagrant:
		host: detect
	    proxy:
		http: ''
		https: ''
		ftp: ''
		no_proxy: ''
		enabled: '0'
	server:
	    install: '1'
	    packages: {  }
	users_groups:
	    install: '1'
	    groups: {  }
	    users: {  }
	locale:
	    install: '1'
	    settings:
		default_locale: en_US.UTF-8
		locales:
		    - en_GB.UTF-8
		    - en_US.UTF-8
		    - pl_PL.UTF-8
		timezone: UTC
	firewall:
	    install: '1'
	    rules: {  }
	cron:
	    install: '1'
	    jobs: {  }
	nginx:
	    install: '1'
	    settings:
		version: present
		default_vhost: 1
		proxy_buffers: '4 256k'
		proxy_buffer_size: 128k
		proxy_connect_timeout: 600s
		proxy_send_timeout: 600s
		proxy_read_timeout: 600s
		names_hash_bucket_size: 128
	    upstreams: {  }
	    vhosts:
		nxv_czivo3csyykz:
		    server_name: betstore.dev
		    server_aliases:
		        - www.betstore.com
		    www_root: /var/www/betstore
		    listen_port: '80'
		    index_files:
		        - index.html
		        - index.htm
		        - index.php
		    client_max_body_size: 1m
		    ssl: '0'
		    ssl_cert: ''
		    ssl_key: ''
		    ssl_port: '443'
		    ssl_protocols: ''
		    ssl_ciphers: ''
		    rewrite_to_https: '1'
		    spdy: '1'
		    locations:
		        nxvl_ltmm8pz9gj19:
		            location: /
		            try_files:
		                - $uri
		                - $uri/
		                - /index.php$is_args$args
		            fastcgi: ''
		            fastcgi_index: ''
		            fastcgi_split_path: ''
		            proxy: ''
		            proxy_redirect: ''
		        nxvl_5f4c1gbffkx2:
		            location: '~ \.php$'
		            try_files:
		                - $uri
		                - $uri/
		                - /index.php$is_args$args
		            fastcgi: '127.0.0.1:9000'
		            fastcgi_index: index.php
		            fastcgi_split_path: '^(.+\.php)(/.*)$'
		            fast_cgi_params_extra:
		                - 'SCRIPT_FILENAME $request_filename'
		                - 'APP_ENV dev'
		            set:
		                - '$path_info $fastcgi_path_info'
		            proxy: ''
		            proxy_redirect: ''
	    proxies: {  }
	apache:
	    install: '0'
	    settings:
		version: 2.4
		user: www-data
		group: www-data
		default_vhost: true
		manage_user: false
		manage_group: false
		sendfile: 0
	    modules:
		- proxy_fcgi
		- rewrite
	    vhosts:
		av_zq98753sa1dk:
		    servername: awesome.dev
		    serveraliases:
		        - www.awesome.dev
		    docroot: /var/www/awesome
		    port: '80'
		    setenv:
		        - 'APP_ENV dev'
		    setenvif:
		        - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
		    custom_fragment: ''
		    ssl: '0'
		    ssl_cert: ''
		    ssl_key: ''
		    ssl_chain: ''
		    ssl_certs_dir: ''
		    ssl_protocol: ''
		    ssl_cipher: ''
		    directories:
		        avd_hr5tg7mm26rh:
		            path: /var/www/awesome
		            options:
		                - Indexes
		                - FollowSymlinks
		                - MultiViews
		            allow_override:
		                - All
		            require:
		                - 'all granted'
		            custom_fragment: ''
		            files_match:
		                avdfm_itqdv089d51x:
		                    path: \.php$
		                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
		                    custom_fragment: ''
		                    provider: filesmatch
		            provider: directory
	letsencrypt:
	    install: '1'
	    settings:
		email: ''
	    domains: {  }
	php:
	    install: '1'
	    settings:
		version: '7.0'
	    modules:
		php:
		    - cli
		    - intl
		    - xml
		pear: {  }
		pecl: {  }
	    ini:
		display_errors: 'On'
		error_reporting: '-1'
		session.save_path: /var/lib/php/session
		date.timezone: UTC
	    fpm_ini:
		error_log: /var/log/php-fpm.log
	    fpm_pools:
		phpfp_i6pk4hm6m075:
		    ini:
		        prefix: www
		        listen: '127.0.0.1:9000'
		        security.limit_extensions: .php
		        user: www-user
		        group: www-data
	    composer: '1'
	    composer_home: ''
	xdebug:
	    install: '0'
	    settings:
		xdebug.default_enable: '1'
		xdebug.remote_autostart: '0'
		xdebug.remote_connect_back: '1'
		xdebug.remote_enable: '1'
		xdebug.remote_handler: dbgp
		xdebug.remote_port: '9000'
	blackfire:
	    install: '0'
	    settings:
		server_id: ''
		server_token: ''
		agent:
		    http_proxy: ''
		    https_proxy: ''
		    log_file: stderr
		    log_level: '1'
		php:
		    agent_timeout: '0.25'
		    log_file: ''
		    log_level: '1'
	xhprof:
	    install: '0'
	wpcli:
	    install: '0'
	    version: v0.24.1
	drush:
	    install: '0'
	    version: 8.0.5
	ruby:
	    install: '1'
	    versions:
		rv_uylrxdbwia9y:
		    default: '1'
		    bundler: '1'
		    version: 2.3.1
		    gems:
		        - deep_merge@1.0.1
		        - activesupport@4.2.6
		        - vine@0.2
	python:
	    install: '1'
	    packages: {  }
	    versions: {  }
	nodejs:
	    install: '0'
	    settings:
		version: '6'
	    npm_packages: {  }
	hhvm:
	    install: '0'
	    composer: '1'
	    composer_home: ''
	    settings: {  }
	    server_ini:
		hhvm.server.host: 127.0.0.1
		hhvm.server.port: '9000'
		hhvm.log.use_log_file: '1'
		hhvm.log.file: /var/log/hhvm/error.log
	    php_ini:
		display_errors: 'On'
		error_reporting: '-1'
		date.timezone: UTC
	mariadb:
	    install: '1'
	    settings:
		version: '10.1'
		root_password: '123'
		override_options: {  }
	    adminer: 0
	    users:
		mariadbnu_yjsai59bv8sc:
		    name: dbuser
		    password: '123'
	    databases:
		mariadbnd_zn8uw797fm4z:
		    name: dbname
		    sql: ''
	    grants:
		mariadbng_n8u1hn6510pc:
		    user: dbuser
		    table: '*.*'
		    privileges:
		        - ALL
	mysql:
	    install: '0'
	    settings:
		version: '5.7'
		root_password: '123'
		override_options: {  }
	    adminer: 0
	    users:
		mysqlnu_rztuzkhrzk1r:
		    name: dbuser
		    password: '123'
	    databases:
		mysqlnd_0sup77d24n9i:
		    name: dbname
		    sql: ''
	    grants:
		mysqlng_lncqtkx9v7wp:
		    user: dbuser
		    table: '*.*'
		    privileges:
		        - ALL
	postgresql:
	    install: '0'
	    settings:
		global:
		    encoding: UTF8
		    version: '9.6'
		server:
		    postgres_password: '123'
	    databases: {  }
	    users: {  }
	    grants: {  }
	    adminer: 0
	mongodb:
	    install: '0'
	    settings:
		bind_ip: 127.0.0.1
		port: '27017'
	    globals:
		version: 2.6.0
	    databases: {  }
	redis:
	    install: '0'
	    settings:
		port: '6379'
	sqlite:
	    install: '0'
	    adminer: 0
	    databases: {  }
	mailhog:
	    install: '0'
	    settings:
		smtp_ip: 0.0.0.0
		smtp_port: 1025
		http_ip: 0.0.0.0
		http_port: '8025'
		path: /usr/local/bin/mailhog
	beanstalkd:
	    install: '0'
	    settings:
		listenaddress: 0.0.0.0
		listenport: '11300'
		maxjobsize: '65535'
		maxconnections: '1024'
		binlogdir: /var/lib/beanstalkd/binlog
		binlogfsync: null
		binlogsize: '10485760'
	    beanstalk_console: 0
	rabbitmq:
	    install: '0'
	    settings:
		port: '5672'
	    users: {  }
	    vhosts: {  }
	    plugins: {  }
	elastic_search:
	    install: '0'
	    settings:
		version: 2.3.1
		java_install: true
	    instances:
		esi_5iv06yzgga99:
		    name: es-01
	solr:
	    install: '0'
	    settings:
		version: 5.5.2
		port: '8984'

**Comment by m0sviatoslav** [comment]
**Same issue**
Ubuntu 16.04
Vagrant 1.8.6
VirtualBox 5.0.26 

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1604-x64
                box_url: puphpet/ubuntu1604-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_xawkoeyuuo35:
                        id: machine1
                        hostname: machine1.puphpet
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_gp91n4b7tq08:
                                    host: '7264'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_fd4k2llvulyh:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_fe763vn2gxws:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_my1bhafboyrf:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_zunrmw0q5kfu:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_ishpzr35a3qx:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_cnb4ru26txnv:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_t7okhduotvqx:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.0'
    modules:
        php:
            - cli
            - intl
            - xml
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_ur9w5cy2y8wa:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_cb68633atj8q:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_pyulmf4fcauc:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_kbpi5znq25cg:
            name: dbname
            sql: ''
    grants:
        mariadbng_k9kstrqtb1ux:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_m7lpti2jj5jk:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_hyofyh6js6qr:
            name: dbname
            sql: ''
    grants:
        mysqlng_0biiuct65bem:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_bzyjf2w1ak2f:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'
```
