### ISSUE TITLE
php7.0-fpm service fails to start: returns nginx 502

### ISSUE THREAD

**Issue by celowsky** [puphpet/puphpet#2476]
Hi fellow puphpet fans,

**Setting**
- I'm running a on a freshly-installed Linux Mint 18 Cinnamon 64-bit host
- I'm trying to create a vagrant VM using the newest puphpet/ubuntu1404-x64 box
- I'm using nginx as my web server

**Problem**
I'm not able to start the php7.0-fpm service using `sudo service start php7.0-fpm`
- I believe the issue is coming from a missing php-fpm socket

Note: I've also attached my config.yaml as well as the full output of my initial `vagrant up --debug` below

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_gqajylv4phwp:
                        id: Anonymous
                        hostname: anonymous.puphpet
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_618bhdsoj29i:
                                    host: '6119'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_nup5vb0o6l7c:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - php-curl
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_wmnhwet91bhu:
            server_name: anonymous.dev
            server_aliases:
                - www.anonymous.dev
            www_root: /var/www/anonymous/web
            listen_port: '80'
            index_files:
                - app.php
            client_max_body_size: 32m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_d5ii2utqwoq5:
                    location: /
                    try_files:
                        - $uri
                        - /app.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_1zyzlh8v80wn:
                    location: '~ \.php(/|$)'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $realpath_root$fastcgi_script_name'
                        - 'DOCUMENT_ROOT $realpath_root'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_zk6a9vxg3j7r:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_iv88on1lxrog:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_wpcp36zgnsum:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '70'
    modules:
        php:
            - cli
            - intl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
        upload_max_filesize: 32M
        post_max_size: 32M
    fpm_pools:
        phpfp_vf3no74mcpz1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.idekey: PHPSTORM
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '1'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9123'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_r6epvhn8gh85:
            default: '1'
            bundler: '1'
            version: 2.3.0
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_9dgaab9iuo9e:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_doqkfl9xx1tn:
            name: dbname
            sql: ''
    grants:
        mariadbng_pl9xrfqech54:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_bwg3u0cdccj9:
            name: web
            password: password
    databases:
        mysqlnd_ox9wcx0ybwa4:
            name: anonymous
            sql: ''
        mysqlnd_ylwdrxohivec:
            name: anonymous_test
            sql: ''
    grants:
        mysqlng_audjyg1kbm5c:
            user: web
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: admin
    databases:
        postsqlnd_2r4p5wrz10ym:
            dbname: anonymous
            owner: ''
        postsqlnd_ceivjs8d4gye:
            dbname: anonymous_test
            owner: ''
    users:
        postsqlnu_08j006ywxqi5:
            username: web
            password: password
            superuser: '1'
    grants:
        postsqlng_uqm0uwdhc8jw:
            role: web
            db: anonymous
            privilege:
                - ALL
        postsqlng_0flz09klibjq:
            role: web
            db: anonymous_test
            privilege:
                - ALL
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_1l9axtjqdyqu:
            name: es-anonymous
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
[vagrant-log.txt](https://github.com/puphpet/puphpet/files/537251/vagrant-log.txt)

**Comment by celowsky** [comment]
I've been looking at some of the solutions on this site for nginx 502 errors, and this appears to be the most recent one [here](https://github.com/puphpet/puphpet/issues/1591). However, it seems as though the php-fpm pool is set up correctly as well as the nginx configuration. Php-fpm writes no error logs, and nginx's error log merely states ```connect() failed (111: Connection refused) while connecting to upstream```

**Comment by celowsky** [comment]
For anyone else looking for the cause of this issue, I ended up upgrading my box to ubuntu1604-x64. The issue itself may have been caused by defining 
```
fpm_ini:
        error_log: /var/log/php-fpm.log
        upload_max_filesize: 32M
        post_max_size: 32M
```
in the php-fpm config. Removing upload_max_filesize and post_max_size fixed installation.
