### ISSUE TITLE
Wrong mysql version installed on Ubuntu 16.04 (5.7 installed instead of 5.6)

### ISSUE THREAD

**Issue by johanvanhelden** [puphpet/puphpet#2495]
In my config I defined version 5.6, but it installed 5.7 (5.7.16-0ubuntu0.16.04.1 to be exact)

This is what the part config section looks like:

```
mysql:
    install: '1'
    settings:
        version: '5.6'
```

This happend with an archive I generated on puphpet.com today.

I am using the `puphpet/ubuntu1604-x64` box.
