### ISSUE TITLE
Unable to provision machine

### ISSUE THREAD

**Issue by iprice-jamersan** [puphpet/puphpet#2504]
Hello, I am having an issue trying to up and provision my vm.

I am running OSX 10.10.5 (It should be noted that other members on my team are on both older and newer versions, and are having no problems provisioning this machine).

I am running Vagrant version 1.8.6 and Virtualbox version 5.1.8

Here is my config.yaml:

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: 'false'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_3kmc7oqunghv:
                        id: localdevelopment
                        hostname: localdev.dev
                        network:
                            private_network: 192.168.5.5
                        memory: '2048'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_6nkoz1a2ac7j:
                source: /Users/iprice/Documents/sites
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_GB.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '0'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_4ga2682kz1z8:
            server_name: magento2.dev
            server_aliases:
                - www.magento2.dev
                - '~^magento2\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/magento2
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_yuag0e4ylrsp:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_igz7kcp6ad3i:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_1l3mej509osh:
            server_name: shop.example.dev
            server_aliases:
                - zebcobrands.dev
                - '~^zebcobrands\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/zebcobrands
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_tq95xk38vy74:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_2f9ghl1metzz:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_lbbe91ovtg9p:
            server_name: example.dev
            server_aliases:
                - '~^example\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/example.com
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_zs0s5yprmqqf:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_9yze1o7ifuj3:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_ogee1hm8cbpm:
            server_name: example2.dev
            server_aliases:
                - www.example2.dev
                - '~^example2\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/example2.com
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_jx5y8vwhway0:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_ahn7oyka3est:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_r3jt0l05r844:
            server_name: phpmyadmin.dev
            server_aliases:
                - www.phpmyadmin.dev
            www_root: /var/www/phpmyadmin.dev/
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_4smhphwna13w:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_smfpq9jup128:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_buecj2mjx46g:
            server_name: example3.dev
            server_aliases:
                - www.example3.dev
                - '~^example3\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/example3.com
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_x316ok7hajen:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - '/index.php?q=$uri&$args'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_d2rf29nypnko:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - '/index.php?q=$uri&$args'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_k862p3j808dl:
            server_name: shop.example3.dev
            server_aliases:
                - www.example3.dev
                - '~^charbroil\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/shop.example3.com
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_e57e869toljn:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_dwe8fumsx1d4:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_82u0wux8xbf6:
            server_name: eu.example3.dev
            server_aliases:
                - dk.example3.dev
                - de.example3.dev
                - '~^example3\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/example3.eu
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_zolw979omd2h:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_kqi9ae1qb8s7:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_hyuq582oguyt:
            server_name: community.example3.dev
            server_aliases:
                - '~^example3\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/community.example3.com
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_5jn2h9gmlf8h:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - '/index.php?q=$uri&$args'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_f30qwn2erp00:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - '/index.php?q=$uri&$args'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_5gapglng17sw:
            server_name: dev.example3.ca
            server_aliases:
                - '~^example3\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/example3.ca
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            spdy: '1'
            locations:
                nxvl_08z8qy85fg7r:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - '/index.php?q=$uri&$args'
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_0j5dlbb8crgs:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - '/index.php?q=$uri&$args'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
        nxv_01af4176nfvz:
            server_name: example3.dev
            server_aliases:
                - www.zebco.dev
                - '~^example3\.(.*)\.vagrantshare\.com$'
            www_root: /var/www/example3
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_9sdoe6booz9s:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_0r8dr2cqs52r:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_05dd7pn36ksw:
            servername: vagrant.dev
            docroot: /var/www
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_ima9pz3ea0uj:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5lr6lnqkvq0f:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '5.6'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - common
            - xml
            - xsl
            - mb
            - soap
            - bcmath
            - mbstring
            - opcache
        pear: {  }
        pecl:
            - zip
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
        max_execution_time: '18000'
        max_input: '50000'
        memory: '1024'
        memory_limit: 1500M
        max_file: 1900M
        max_input_vars: '3000'
        max_input_time: '300'
        upload_max_filesize: 2000M
        post_max_size: 2000M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_k9xefwxz4nxc:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                group: www-data
                user: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '1'
    version: v0.24.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.0'
        root_password: root
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_h701fdc3qrhp:
            name: stag_zebco_usr
            password: root
    databases:
        mariadbnd_t05owurwnni5:
            name: zebcobrands
            sql: ''
        mariadbnd_fer3bf7gu5p1:
            name: tiki
            sql: ''
        mariadbnd_g73r6ggtpnnc:
            name: tikiwp
            sql: ''
        mariadbnd_sz8io1rtrf0j:
            name: wcbradley
            sql: ''
        mariadbnd_9kvmicnihe4q:
            name: cbshop
            sql: ''
        mariadbnd_yw46rtaq4cx9:
            name: cbcommunity
            sql: ''
        mariadbnd_f5powtzzc42h:
            name: cbca
            sql: ''
        mariadbnd_cteowjortx8n:
            name: cbwp
            sql: ''
        mariadbnd_5pbkj76j9iqd:
            name: magento2
            sql: ''
        mariadbnd_941k7ltxfeif:
            name: badlands
            sql: ''
        mariadbnd_5vd0vrrl3g92:
            name: badlands_wp
            sql: ''
        mariadbnd_2rxkrj9xbx54:
            name: zbcms
            sql: ''
    grants:
        mariadbng_nrl1srnnxqk5:
            user: stag_zebco_usr
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    adminer: 0
    users: {  }
    databases:
        mysqlnd_mva5nt10drva:
            name: zebcobrands
            sql: ''
        mysqlnd_pgc6l2qs2t61:
            name: tiki
            sql: ''
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        manage_repo: true
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
    instances: {  }
solr:
    install: '1'
    settings:
        version: 4.10.2
        port: '8984'


```

the output with errors is as follows:

> Bringing machine 'localdevelopment' up with 'virtualbox' provider...
==> localdevelopment: Importing base box 'puphpet/ubuntu1404-x64'...
==> localdevelopment: Matching MAC address for NAT networking...
==> localdevelopment: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> localdevelopment: Setting the name of the VM: vm_localdevelopment_1478299961589_66646
==> localdevelopment: Clearing any previously set network interfaces...
==> localdevelopment: Preparing network interfaces based on configuration...
    localdevelopment: Adapter 1: nat
    localdevelopment: Adapter 2: hostonly
==> localdevelopment: Forwarding ports...
    localdevelopment: 22 (guest) => 2222 (host) (adapter 1)
==> localdevelopment: Running 'pre-boot' VM customizations...
==> localdevelopment: Booting VM...
==> localdevelopment: Waiting for machine to boot. This may take a few minutes...
    localdevelopment: SSH address: 127.0.0.1:2222
    localdevelopment: SSH username: vagrant
    localdevelopment: SSH auth method: private key
==> localdevelopment: Machine booted and ready!
==> localdevelopment: Checking for guest additions in VM...
    localdevelopment: The guest additions on this VM do not match the installed version of
    localdevelopment: VirtualBox! In most cases this is fine, but in rare cases it can
    localdevelopment: prevent things such as shared folders from working properly. If you see
    localdevelopment: shared folder errors, please make sure the guest additions within the
    localdevelopment: virtual machine match the version of VirtualBox you have installed on
    localdevelopment: your host and reload your VM.
    localdevelopment: 
    localdevelopment: Guest Additions Version: 5.0.26
    localdevelopment: VirtualBox Version: 5.1
==> localdevelopment: Setting hostname...
==> localdevelopment: Configuring and enabling network interfaces...
==> localdevelopment: Exporting NFS shared folders...
==> localdevelopment: Preparing to edit /etc/exports. Administrator privileges will be required...
==> localdevelopment: Mounting NFS shared folders...
==> localdevelopment: Mounting shared folders...
    localdevelopment: /vagrant => /Users/iprice/Documents/vm
    localdevelopment: /tmp/vagrant-puppet/modules-3d3aa347fc70270242641e3969707775 => /Users/iprice/Documents/vm/puphpet/puppet/modules
    localdevelopment: /tmp/vagrant-puppet/modules-ce5625721e936f43dc3204dc84519d54 => /Users/iprice/Documents/vm/puphpet/puppet/manifests
    localdevelopment: /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812 => /Users/iprice/Documents/vm/puphpet/puppet/manifests
==> localdevelopment: Running provisioner: shell...
    localdevelopment: Running: inline script
==> localdevelopment: **stdin: is not a tty**
==> localdevelopment: Running provisioner: shell...
    localdevelopment: Running: /var/folders/vh/6ddfcc8s7z9149vlfhdmk5gc980l5t/T/vagrant-shell20161104-3143-rvpp9i.sh
==> localdevelopment: **stdin: is not a tty**
==> localdevelopment: 
==> localdevelopment:  ____        ____  _   _ ____      _      generated using
==> localdevelopment: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> localdevelopment: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> localdevelopment: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> localdevelopment: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> localdevelopment: Running provisioner: shell...
    localdevelopment: Running: /var/folders/vh/6ddfcc8s7z9149vlfhdmk5gc980l5t/T/vagrant-shell20161104-3143-1ixayyz.sh
==> localdevelopment: **stdin: is not a tty**
==> localdevelopment: Pre-existing private key found at 'puphpet/files/dot/ssh/root_id_rsa'
==> localdevelopment: Pre-existing private key found at 'puphpet/files/dot/ssh/id_rsa'
==> localdevelopment: Adding generated root key to /root/.ssh/id_rsa
==> localdevelopment: Adding generated root key to /root/.ssh/id_rsa.pub
==> localdevelopment: Adding generated root key to /root/.ssh/authorized_keys
==> localdevelopment: Adding generated key to /home/vagrant/.ssh/id_rsa
==> localdevelopment: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> localdevelopment: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> localdevelopment: Running provisioner: shell...
    localdevelopment: Running: /var/folders/vh/6ddfcc8s7z9149vlfhdmk5gc980l5t/T/vagrant-shell20161104-3143-1x1btw2.sh
==> localdevelopment: **stdin: is not a tty**
==> localdevelopment: Running provisioner: shell...
    localdevelopment: Running: /var/folders/vh/6ddfcc8s7z9149vlfhdmk5gc980l5t/T/vagrant-shell20161104-3143-rn0vbt.sh
==> localdevelopment: **stdin: is not a tty**
==> localdevelopment: Running files in files/exec-preprovision
==> localdevelopment: Created file /.puphpet-stuff/exec-preprovision-ran
==> localdevelopment: Finished running files in files/exec-preprovision
==> localdevelopment: To run again, delete hashes you want rerun in /.puphpet-stuff/exec-preprovision-ran or the whole file to rerun all
==> localdevelopment: Running provisioner: puppet...
==> localdevelopment: Running Puppet with ...
==> localdevelopment: **stdin: is not a tty**
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: Info: Loading facts
==> localdevelopment: **Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::puphpet::cron for localdev.dev at /tmp/vagrant-puppet/modules-3d3aa347fc70270242641e3969707775/puphpet/manifests/init.pp:12:3 on node localdev.dev
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.**

Any insight as to how this issue can be resolved would be appreciated.
