### ISSUE TITLE
Error: Could not parse application options: invalid option: --manifestdir

### ISSUE THREAD

**Issue by juanpscotto** [puphpet/puphpet#2505]
Hi I'm getting this error. Please Help!!

Error: Could not parse application options: invalid option: --manifestdir

Vagrant version: 1.8.1
virtualbox: 5.0.24

This is my config.yaml file:

```

---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.7.8
            forwarded_port:
                4wODidibgCh4:
                    host: '5433'
                    guest: '22'
                4oiufjwerCh4:
                    host: '9999'
                    guest: '5672'
                4wODidiagCh5:
                    host: '8181'
                    guest: '80'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            AaaKF8uu0OyE:
                owner: www-data
                group: www-data
                source: /var/www/
                target: /var/www/html
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
        - php-Smarty2
users_groups:
    install: '1'
    groups: {  }
    users:
        - gabo
        - cferreira
        - jarce
        - raulintosh
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: null
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
       
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        exqdf5iushce:
            proxy: ''
            server_name: dojo.dev
            www_root: /var/www/html/html/coder
            listen_port: '80'
            location: \.html$
            index_files:
                - index.html
            engine: html
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
        exqdf3iushce:
            proxy: ''
            server_name: telecom.dev
            www_root: /var/www/html/html/www-core/public
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
        exq2ebiushce:
            proxy: ''
            server_name: tellevo.dev
            www_root: /var/www/html/html/tellevo/public
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''

        dywxl3we8pnl:
            proxy: ''
            server_name: monchis.dev
            www_root: /var/www/html/html/monchis-backend/admin/public
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
        byu81bsiaufo:
            proxy: ''
            server_name: momo2.dev
            www_root: /var/www/html/html/momo2-personal/public
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
                 
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - fpm
            - mssql
            - interbase
            - pgsql
            - bcmath
        pear:
            - MDB2
            - MDB2_Driver_mssql
            - MDB2_Driver_ibase
            - MDB2_Driver_pgsql
        pecl:
            - pecl_http
            - APC
            - amqp
            - memcached
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Asuncion
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        Y70rqVwiF92b:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        l5sC0ppheecH:
            version: ''
mysql:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases:
        Vsf1rZ2I8lv2:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '1'
    settings:
        root_password: '1234'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '1'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'


```

**Comment by Renkas** [comment]
Minimum required Vagrant version is 1.8.6
The official recommended Virtualbox version is 5.0.26!

**Comment by juanpscotto** [comment]
Thanks for the repply!. I have updated the both vagrant and virtualbox version to the ones you said me. also generated my puppet again. This is my config.yaml:

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos65-x64
                box_url: puphpet/centos65-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_2gumbfebkf0v:
                        id: machine1
                        hostname: machine1.puphpet
                        network:
                            private_network: 192.168.27.102
                            forwarded_port:
                                vflmnfp_ag32ilgdemsa:
                                    host: '5433'
                                    guest: '22'
                                vflmnfp_8iyogfo1jlf5:
                                    host: '9999'
                                    guest: '5672'
                                vflmnfp_tufy755vyh4a:
                                    host: '8181'
                                    guest: '80'
                        memory: '512'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_67ya9tyv3anw:
                source: /var/www/
                target: /var/www/html
                sync_type: rsync
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim-common
        - htop
        - php-Smarty2
users_groups:
    install: '1'
    groups: {  }
    users:
        - gabo
        - cferreira
        - jarce
        - raulintosh
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: America/Asuncion
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_urwzumi227tk:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_9ltnclsvi37b:
                    www_root: ''
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
        nxv_xesqzxh989ts:
            server_name: dojo.dev
            www_root: /var/www/html/coder
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_5raebodt8s3z:
                    www_root: /var/www/html/coder
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
        nxv_q9brq0yl3m9u:
            server_name: telecom.dev
            www_root: /var/www/html/www-core/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_q9xd0i7o7bg5:
                    www_root: /var/www/html/www-core/public
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
        nxv_uzs8s3focxoe:
            server_name: tellevo.dev
            www_root: /var/www/html/tellevo/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_7lds8gwfh9km:
                    www_root: /var/www/html/tellevo/public
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
        nxv_9nytxgwojl5r:
            server_name: monchis.dev
            www_root: /var/www/html/monchis-backend/admin/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_qpc50z0lqxyh:
                    www_root: /var/www/html/monchis-backend/admin/public
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
        nxv_r1gd5og8hjz0:
            server_name: momo2.dev
            www_root: /var/www/html/momo2-personal/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_ykh0oswdhupy:
                    www_root: /var/www/html/momo2-personal/public
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
        nxv_v7ihxwt65mh0:
            server_name: learning-laravel.dev
            www_root: /var/www/html/learning-laravel/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_8sa9kw3z20z9:
                    www_root: /var/www/html/learning-laravel/public
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
        nxv_iupmmd19kj6t:
            server_name: project.dev
            www_root: /var/www/html/project-dev/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_ggpud147qe5m:
                    www_root: /var/www/html/project-dev/public
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_gz1tmuf83otd:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_gecphv4zs33n:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_l5znypat84wt:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '5.6'
    modules:
        php:
            - cli
            - intl
            - xml
            - mcrypt
            - fpm
            - mssql
            - interbase
            - pgsql
            - bcmath
            - mbstring
        pear:
            - MDB2
            - MDB2_Driver_mssql
            - MDB2_Driver_ibase
            - MDB2_Driver_pgsql
        pecl:
            - pecl_http
            - APC
            - amqp
            - memcached
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_0pbe4dlhu7si:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_lxnnc8htsbjo:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_lxz3vdemzye1:
            name: dbname
            sql: ''
    grants:
        mariadbng_b1ftzqk6o5sr:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_rb4njc3j7ny9:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_jfu7e3okpyw4:
            name: dbname
            sql: ''
    grants:
        mysqlng_51xacb48bz16:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '1234'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_5qyzupzxl13a:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'


```

And the vagrant up is showing these warnings and errors:

**WARNINGS:**

```
==> machine1: Warning: Unknown variable: '::lsbmajdistrelease'. at /tmp/vagrant-puppet/modules-90579250dec84f30434a1157da8d93cd/nginx/manifests/package/redhat.pp:34:12
==> machine1: Warning: Scope(Class[Rabbitmq]): $manage_repos is now deprecated. Please use $repos_ensure instead
==> machine1: Warning: The key 'shib2' is declared more than once at /tmp/vagrant-puppet/modules-90579250dec84f30434a1157da8d93cd/apache/manifests/params.pp:251:21

```

**ERRORS:**
```
==> machine1: Error: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]

==> machine1: Error: /Stage[main]/Puphpet::Php::Modules/Puphpet::Php::Module::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install pecl_http && pecl info pecl_http returned 1 instead of one of [0]

==> machine1: Error: printf "\n" | pecl -d preferred_state=stable install apc && pecl info apc returned 1 instead of one of [0]
==> machine1: Error: /Stage[main]/Puphpet::Php::Modules/Puphpet::Php::Module::Pecl[APC]/Php::Pecl::Module[apc]/Exec[pecl-apc]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install apc && pecl info apc returned 1 instead of one of [0]

==> machine1: Error: printf "\n" | pecl -d preferred_state=stable install amqp && pecl info amqp returned 1 instead of one of [0]
==> machine1: Error: /Stage[main]/Puphpet::Php::Modules/Puphpet::Php::Module::Pecl[amqp]/Php::Pecl::Module[amqp]/Exec[pecl-amqp]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install amqp && pecl info amqp returned 1 instead of one of [0]

==> machine1: Error: printf "\n" | pecl -d preferred_state=stable install memcached && pecl info memcached returned 1 instead of one of [0]
==> machine1: Error: /Stage[main]/Puphpet::Php::Modules/Puphpet::Php::Module::Pecl[memcached]/Php::Pecl::Module[memcached]/Exec[pecl-memcached]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install memcached && pecl info memcached returned 1 instead of one of [0]

==> machine1: Error: printf "\n" | pecl -d preferred_state=stable install redis && pecl info redis returned 1 instead of one of [0]
==> machine1: Error: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install redis && pecl info redis returned 1 instead of one of [0]

```

**AND FINALLY**

```
==> machine1: Notice: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Puphpet::Nginx::Locations[from puphpet::nginx::vhosts, /var/www/html @ key _]/Nginx::Resource::Location[1]/Concat::Fragment[6bba1c0e224da60a4b71285164cd3b6f]/File[/opt/puppetlabs/puppet/cache/concat/_etc_nginx_sites-available__.conf/fragments/500_6bba1c0e224da60a4b71285164cd3b6f]/ensure: defined content as '{md5}11d80a7103e5ff5fbb0a46e7b34917dc'
==> machine1: Info: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Puphpet::Nginx::Locations[from puphpet::nginx::vhosts, /var/www/html @ key _]/Nginx::Resource::Location[1]/Concat::Fragment[6bba1c0e224da60a4b71285164cd3b6f]/File[/opt/puppetlabs/puppet/cache/concat/_etc_nginx_sites-available__.conf/fragments/500_6bba1c0e224da60a4b71285164cd3b6f]: Scheduling refresh of Exec[concat_/etc/nginx/sites-available/_.conf]
==> machine1: Notice: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[_]/Concat[/etc/nginx/sites-available/_.conf]/Exec[concat_/etc/nginx/sites-available/_.conf]/returns: executed successfully
==> machine1: Notice: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[_]/Concat[/etc/nginx/sites-available/_.conf]/Exec[concat_/etc/nginx/sites-available/_.conf]: Triggered 'refresh' from 6 events
==> machine1: Notice: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[_]/Concat[/etc/nginx/sites-available/_.conf]/File[/etc/nginx/sites-available/_.conf]/ensure: defined content as '{md5}1e6c519b71f894ef1ffe79aa6731c4e2'
==> machine1: Info: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[_]/Concat[/etc/nginx/sites-available/_.conf]/File[/etc/nginx/sites-available/_.conf]: Scheduling refresh of Class[Nginx::Service]
==> machine1: Info: Concat[/etc/nginx/sites-available/_.conf]: Scheduling refresh of Class[Nginx::Service]
==> machine1: Info: Class[Nginx::Service]: Scheduling refresh of Service[nginx]
==> machine1: Notice: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[_]/File[_.conf symlink]/ensure: created
==> machine1: Info: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[_]/File[_.conf symlink]: Scheduling refresh of Service[nginx]
==> machine1: Notice: /Stage[main]/Nginx::Service/Service[nginx]/ensure: ensure changed 'stopped' to 'running'
==> machine1: Info: /Stage[main]/Nginx::Service/Service[nginx]: Unscheduling refresh on Service[nginx]
==> machine1: Info: Stage[main]: Unscheduling all events on Stage[main]
==> machine1: Notice: Applied catalog in 1240.95 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

Thank you
