### ISSUE TITLE
all sorts of permission errors with nfs on osx sierra

### ISSUE THREAD

**Issue by steros** [puphpet/puphpet#2524]
I try to install magento 2 on my machine but run into all sorts of permission errors.
It is a pretty standard puphpet configuration with nfs shared folders, apache and PHP 7.0.
Here is the synced_folders part:
```
synced_folder:
            vflsf_0zgbo0fdxqpw:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
```

Magento features a script run from php cli to do all sorts of things like switching to something called "developer mode" and other stuff. What that does except some internals is deleting some cache files and folders.
Running it with the user that you are logged in doing "vagrant ssh" it fails due to file permission errors, it can't delete those files.
So I thought I might have missed some step and reinstalled exactly following the documentation:
http://devdocs.magento.com/guides/v2.1/install-gde/prereq/integrator_install_ce.html#perms-set-two-users
But I already fail at this step 5 as I can't change file ownership at all, not even as root. I did everything proposed on that page as the normal vagrant user (like composer create).

As far as I could find out this is due to root squashing and there is an option you can set in the Vagrantfile to pass this.
https://github.com/puphpet/puphpet/wiki/Shared-Folder:-Permission-Denied

So I set:

```
if folder['sync_type'] == 'nfs'
          if Vagrant.has_plugin?('vagrant-bindfs')
            machine_id.vm.synced_folder "#{folder['source']}", "/mnt/vagrant-#{i}",
              id: "#{i}",
              type: 'nfs',
              :nfs => { :mount_options => ["dmode=777","fmode=776"]},
              :linux__nfs_options => ["rw","no_root_squash","no_subtree_check"] 
            machine_id.bindfs.bind_folder "/mnt/vagrant-#{i}", "#{folder['target']}",
              after: :synced_folders,
              force_user: sync_owner,
              force_group: sync_group,
              perms: "u=rwX:g=rwX:o=rD",
              o: 'nonempty'
          else
            machine_id.vm.synced_folder "#{folder['source']}", "#{folder['target']}",
              id: "#{i}",
              type: 'nfs',
              :nfs => { :mount_options => ["dmode=777","fmode=776"]},
              :linux__nfs_options => ["rw","no_root_squash","no_subtree_check"]
          end
        elsif folder['sync_type'] == 'smb'
```

If I'm reading this right, then that would add something to the line that is put into /etc/exportfs:
http://serverfault.com/questions/487862/vagrant-os-x-host-nfs-share-permissions-error-failed-to-set-owner-to-1000
but nothing is added there about root_squashing. Also it still won't work and I still can't set ownerships even as root user.

I'd be grateful for any input about this!
Maybe all this is pretty unnecessary? I never experienced file permission errors using the default shared folder mode so I don't know much about what I might be doing wrong here.
Unfortunately Magento is not usable without nfs shared folders. So it is not an option to switch back to default shared mode.

**Comment by satyadeep** [comment]
Hi can you post your entire config.yaml? Are you using nginx or apache?

**Comment by steros** [comment]
Sure :)

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1604-x64
                box_url: puphpet/ubuntu1604-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 2
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_ngt3s9mcz3aj:
                        id: magento.testing.com
                        hostname: magento.testing.com
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_8orqq4wcso1f:
                                    host: '5180'
                                    guest: '22'
                        memory: '4096'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_akr6z4teu0ym:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - memcached
users_groups:
    install: '1'
    groups: {  }
    users:
        - 'magento_user:www-data'
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - de_DE.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs:
        cj_y21kbvnzwlxm:
            name: magento_cron_jobs
            user: magento_user
            command: 'php /var/www/share/testing.com/shop_magento/current/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/share/testing.com/shop_magento/current/var/log/magento.cron.log'
            minute: '*'
            hour: '*'
            weekday: '*'
            month: '*'
            monthday: ''
        cj_dm9p0lfd3jrw:
            name: magento_cron_update_log
            user: magento_user
            command: 'php /var/www/share/testing.com/shop_magento/current/update/cron.php >> /var/www/share/testing.com/shop_magento/current/var/log/update.cron.log'
            minute: '*'
            hour: '*'
            weekday: '*'
            month: '*'
            monthday: ''
        cj_wndyiigx552b:
            name: magento_cron_setup
            user: magento_user
            command: 'php /var/www/share/testing.com/shop_magento/current/bin/magento setup:cron:run >> /var/www/share/testing.com/shop_magento/current/var/log/setup.cron.log'
            minute: '*'
            hour: '*'
            weekday: '*'
            month: '*'
            monthday: ''
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_d0oec9oc47cr:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_soh6kh8k572j:
                    www_root: ''
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_9fg2fvnweiv1:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_hzp8608zm8xu:
            servername: testing.com
            serveraliases:
                - www.testing.com
            docroot: /var/www/share/testing.com/htdocs
            port: '443'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_3xkeapkapp9c:
                    path: /var/www/share/testing.com/htdocs
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_rugyetbu9k94:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_eywgnhtx2c7s:
            servername: log.testing.com
            docroot: /var/www/share/log.testing.com/
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_tq5wef0kevp0:
                    path: /var/www/share/log.testing.com
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_vvqtojal71aw:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.0'
    modules:
        php:
            - cli
            - curl
            - gd
            - imagick
            - intl
            - mbstring
            - mcrypt
            - soap
            - xml
            - xsl
            - zip
            - memcache
            - memcached
        pear: {  }
        pecl: {  }
    ini:
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        error_log: /var/www/share/log.testing.com/php_error.log
    fpm_ini:
        error_log: /var/www/share/log.testing.com/fpm_error.log
    fpm_pools:
        phpfp_zsy74rwgdha5:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_e9mh9usfraos:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_bvvzovhx8i8y:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_zy3ncsb7shwk:
            name: dbname
            sql: ''
    grants:
        mariadbng_a3f9uhrs6hyq:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_avwm22d8x716:
            name: magento
            password: magento
    databases:
        mysqlnd_c1xt3rxfq6xw:
            name: magento
            sql: /vagrant/magento.sql
    grants:
        mysqlng_qcpnq88tuw5q:
            user: magento
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_x3b51ct007cf:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'
```
