### ISSUE TITLE
Adminer install causes error in apache manifest (when not using apache!)

### ISSUE THREAD

**Issue by OsakaWebbie** [puphpet/puphpet#2527]
After changing my config.yaml to enable adminer in MySQL, I got this error:

```
==> 7and7: Warning: The key 'shib2' is declared more than once at /tmp/vagrant-puppet/modules-3ba8ddb7972591e2e5765b7ccae47bbd/apache/manifests/params.pp:251:21
==> 7and7: Error: Evaluation Error: Operator '[]' is not applicable to an Undef Value. at /tmp/vagrant-puppet/modules-3ba8ddb7972591e2e5765b7ccae47bbd/puphpet/manifests/apache/params.pp:43:26 on node 7and7.dev
```

Since I'm not even installing Apache, this was surprising. I studied what in the manifests mentions apache (things I use, that is), and remembered that one of the changes I did since the previous successful provision was `adminer: 1` in the MySQL section. So I tried changing it back to `adminer: 0`, and provisioning ran _much, much_ farther (it still says SSH had a non-zero status, but it wasn't right after an error message, and way more stuff ran before it died). I really would like adminer, so what should I do?

Here is my config.yaml:

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos7-x64
                box_url: puphpet/centos7-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_on11ecerpjc4:
                        id: 7and7
                        hostname: 7and7.dev
                        network:
                            private_network: 192.168.56.200
                            forwarded_port:
                                vflmnfp_g0v1522nzz08:
                                    host: '8528'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            sf_webroot:
                source: 'c:/dev/www'
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim-common
        - perl-Tk
        - perl-Digest-MD5
users_groups:
    install: '1'
    groups:
        - l4jp
    users:
        - 'l4jp:l4jp'
        - 'kizunadb:l4jp'
        - 'sambidb:l4jp'
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_US.UTF-8
            - ja_JP.UTF-8
        timezone: Asia/Tokyo
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 0
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        kizunadb:
            server_name: '*.kizunadb.dev'
            www_root: /var/www/kizunadb/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                kizunadb_procedural:
                    location: '~* (\.php$)'
                    www_root: /var/www/kizunadb/procedural
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    # fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
                kizunadb_routed:
                    location: /
                    www_root: /var/www/kizunadb/public
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
                # kizunadb_loc1:
                    # location: /
                    # try_files:
                        # - $uri
                        # - $uri/
                        # - /index.php$is_args$args
                    # fastcgi: ''
                    # fastcgi_index: ''
                    # fastcgi_split_path: ''
                    # proxy: ''
                    # proxy_redirect: ''
                # kizunadb_loc2:
                    # location: '~ \.php$'
                    # try_files:
                        # - $uri
                        # - $uri/
                        # - /index.php$is_args$args
                    # fastcgi: '127.0.0.1:9000'
                    # fastcgi_index: index.php
                    # fastcgi_split_path: '^(.+\.php)(/.*)$'
                    # fast_cgi_params_extra:
                        # - 'SCRIPT_FILENAME $request_filename'
                        # - 'APP_ENV dev'
                    # set:
                        # - '$path_info $fastcgi_path_info'
                    # proxy: ''
                    # proxy_redirect: ''
        sambidb:
            server_name: '*.sambidb.dev'
            www_root: /var/www/sambidb/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                sambidb_loc1:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                sambidb_loc2:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
        tutorial:
            server_name: 'tutorial.dev'
            www_root: /var/www/laravel/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                tutorial_loc1:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                tutorial_loc2:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_3rl8026tiato:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_hcbjy1jztmyj:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_5d5tnpns0taw:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - xml
            - mbstring
            - mcrypt
            - gd
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_1626nucydgdj:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '1'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_jkj8m1hswnsp:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_o7j9jbvsjq9r:
            name: kizunadb
            password: xxx
    databases:
        mariadbnd_z2yoo5xxmdni:
            name: kizuna_dev
            sql: ''
    grants:
        mariadbng_ikn3dfbpo1mv:
            user: kizunadb
            table: 'kizuna_*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: xxx
        override_options: {  }
    adminer: 1
    users:
        mysql_user1:
            name: kizunadb
            password: xxx
        mysql_user2:
            name: sambidb
            password: xxx
        mysql_user2:
            name: tutorial
            password: xxx
    databases:
        mysql_kizuna:
            name: kizuna_dev
            sql: ''
        mysql_sambi:
            name: sambi_dev
            sql: ''
        mysql_tutorial:
            name: tutorial
            sql: ''
    grants:
        mysql_grant1:
            user: kizunadb
            table: 'kizuna_*.*'
            privileges:
                - ALL
        mysql_grant2:
            user: sambidb
            table: 'sambi_*.*'
            privileges:
                - ALL
        mysql_grant3:
            user: tutorial
            table: 'tutorial.*'
            privileges:
                - ALL
vim:
    install: '1'
tree:
    install: '1'
```
