### ISSUE TITLE
Unable to locate PHP 5.5 packages CLI and FPM

### ISSUE THREAD

**Issue by WolfieZero** [puphpet/puphpet#2535]
I'm getting multiple errors installing PHP 5.5 packages CLI and FPM causing a 503 error.

Log: 
```
==> hytheandwaterside: Error: python /.puphpet-stuff/ez_setup.py returned 1 instead of one of [0]
==> hytheandwaterside: Error: /Stage[main]/Puphpet::Python::Pip/Exec[Install ez_setup]/returns: change from notrun to 0 failed: python /.puphpet-stuff/ez_setup.py returned 1 instead of one of [0]
==> hytheandwaterside: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[easy_install pip]: Dependency Exec[Install ez_setup] has failures: true
==> hytheandwaterside: Warning: /Stage[main]/Puphpet::Python::Pip/Exec[easy_install pip]: Skipping because of failed dependencies
==> hytheandwaterside: Notice: /Stage[main]/Timezone/File[/etc/localtime]/target: target changed '/usr/share/zoneinfo/Etc/UTC' to '/usr/share/zoneinfo/UTC'
==> hytheandwaterside: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-fpm' returned 100: Reading package lists...
==> hytheandwaterside: Building dependency tree...
==> hytheandwaterside: Reading state information...
==> hytheandwaterside: E: Unable to locate package php5.5-fpm
==> hytheandwaterside: E: Couldn't find any package by glob 'php5.5-fpm'
==> hytheandwaterside: E: Couldn't find any package by regex 'php5.5-fpm'
==> hytheandwaterside: Error: /Stage[main]/Php/Package[php5.5-fpm]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-fpm' returned 100: Reading package lists...
==> hytheandwaterside: Building dependency tree...
==> hytheandwaterside: Reading state information...
==> hytheandwaterside: E: Unable to locate package php5.5-fpm
==> hytheandwaterside: E: Couldn't find any package by glob 'php5.5-fpm'
==> hytheandwaterside: E: Couldn't find any package by regex 'php5.5-fpm'
==> hytheandwaterside: Notice: /Stage[main]/Php/File[php.conf]: Dependency Package[php5.5-fpm] has failures: true
==> hytheandwaterside: Warning: /Stage[main]/Php/File[php.conf]: Skipping because of failed dependencies
==> hytheandwaterside: Notice: /Stage[main]/Puphpet::Php::Install/Package[php5.5-dev]: Dependency Package[php5.5-fpm] has failures: true
==> hytheandwaterside: Warning: /Stage[main]/Puphpet::Php::Install/Package[php5.5-dev]: Skipping because of failed dependencies
==> hytheandwaterside: Notice: /Stage[main]/Puphpet::Php::Install/Exec[set php session path owner/group]: Dependency Package[php5.5-fpm] has failures: true
==> hytheandwaterside: Warning: /Stage[main]/Puphpet::Php::Install/Exec[set php session path owner/group]: Skipping because of failed dependencies
==> hytheandwaterside: Notice: /Stage[main]/Composer/Exec[download_composer]: Dependency Package[php5.5-cli] has failures: true
==> hytheandwaterside: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-cli' returned 100: Reading package lists...
==> hytheandwaterside: Building dependency tree...
==> hytheandwaterside: Reading state information...
==> hytheandwaterside: E: Unable to locate package php5.5-cli
==> hytheandwaterside: E: Couldn't find any package by glob 'php5.5-cli'
==> hytheandwaterside: E: Couldn't find any package by regex 'php5.5-cli'
==> hytheandwaterside: Error: /Stage[main]/Composer/Package[php5.5-cli]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-cli' returned 100: Reading package lists...
==> hytheandwaterside: Building dependency tree...
==> hytheandwaterside: Reading state information...
==> hytheandwaterside: E: Unable to locate package php5.5-cli
==> hytheandwaterside: E: Couldn't find any package by glob 'php5.5-cli'
==> hytheandwaterside: E: Couldn't find any package by regex 'php5.5-cli'
```

Config:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1604-x64
                box_url: puphpet/ubuntu1604-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_icrduiiop7m4:
                        id: hytheandwaterside
                        hostname: hytheandwaterside.puphpet
                        network:
                            private_network: 192.168.10.101
                            forwarded_port:
                                vflmnfp_h8j0tgqzyjib:
                                    host: '5988'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_7s6z6zf5ekdv:
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_GB.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_pzdy4zrtajfs:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_12s3ty98ln6t:
                    www_root: ''
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_5ldc4iy20aiz:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_q9mpuxt84l2f:
            servername: hytheandwaterside.app
            docroot: /var/www/public
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_bkopkt0c5nxh:
                    path: /var/www/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_1hslocozq51h:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '5.5'
    modules:
        php:
            - cli
            - intl
            - xml
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_djqtgtpe3a2f:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.remote_autostart: '1'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_31yp1lrjjk44:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_xm5nl43bq4r0:
            name: dbname
            sql: ''
    grants:
        mariadbng_bwsbzac3kcgf:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    adminer: 0
    users: {  }
    databases:
        mysqlnd_4kytakfiy212:
            name: hytheandwaterside
            sql: ''
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_63zr33po9gjr:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'
```

Cheers.

**Comment by daniel-daga** [comment]
+1

``` 
==> myname: Notice: /Stage[main]/Apache::Mod::Setenvif/File[setenvif.conf]/content: content changed '{md5}533f5f92761c2c24d6820f1d7d1c45ad' to '{md5}c7ede4173da1915b7ec088201f030c28'
==> myname: Info: /Stage[main]/Apache::Mod::Setenvif/File[setenvif.conf]: Scheduling refresh of Class[Apache::Service]
==> myname: Notice: /Stage[main]/Apache::Mod::Worker/File[/etc/apache2/mods-available/worker.conf]/ensure: defined content as '{md5}1e3caf54ba0d71f3502b6cce6cda38d8'
==> myname: Info: /Stage[main]/Apache::Mod::Worker/File[/etc/apache2/mods-available/worker.conf]: Scheduling refresh of Class[Apache::Service]
==> myname: Notice: /Stage[main]/Php/File[php.conf]: Dependency Package[php5.5-fpm] has failures: true
==> myname: Notice: /Stage[main]/Puphpet::Php::Install/Package[php5.5-dev]: Dependency Package[php5.5-fpm] has failures: true
==> myname: Notice: /Stage[main]/Puphpet::Php::Install/Exec[set php session path owner/group]: Dependency Package[php5.5-fpm] has failures: true
==> myname: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-fpm' returned 100: Reading package lists...
==> myname: Building dependency tree...
==> myname: Reading state information...
==> myname: E: Unable to locate package php5.5-fpm
==> myname: E: Couldn't find any package by regex 'php5.5-fpm'
==> myname: Error: /Stage[main]/Php/Package[php5.5-fpm]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-fpm' returned 100: Reading package lists...
==> myname: Building dependency tree...
==> myname: Reading state information...
==> myname: E: Unable to locate package php5.5-fpm
==> myname: E: Couldn't find any package by regex 'php5.5-fpm'
==> myname: Warning: /Stage[main]/Php/File[php.conf]: Skipping because of failed dependencies
==> myname: Warning: /Stage[main]/Puphpet::Php::Install/Package[php5.5-dev]: Skipping because of failed dependencies
==> myname: Warning: /Stage[main]/Puphpet::Php::Install/Exec[set php session path owner/group]: Skipping because of failed dependencies
==> myname: Notice: /Stage[main]/Composer/Exec[download_composer]: Dependency Package[php5.5-cli] has failures: true
==> myname: Notice: /Stage[main]/Composer/Exec[move_composer_/usr/local/bin]: Dependency Package[php5.5-cli] has failures: true
==> myname: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-cli' returned 100: Reading package lists...
==> myname: Building dependency tree...
==> myname: Reading state information...
==> myname: E: Unable to locate package php5.5-cli
==> myname: E: Couldn't find any package by regex 'php5.5-cli'
==> myname: Error: /Stage[main]/Composer/Package[php5.5-cli]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5.5-cli' returned 100: Reading package lists...
==> myname: Building dependency tree...
==> myname: Reading state information...
==> myname: E: Unable to locate package php5.5-cli
==> myname: E: Couldn't find any package by regex 'php5.5-cli'
==> myname: Warning: /Stage[main]/Composer/Exec[download_composer]: Skipping because of failed dependencies
==> myname: Warning: /Stage[main]/Composer/Exec[move_composer_/usr/local/bin]: Skipping because of failed dependencies
``` 

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_gvfuv2pqgqkt:
                        id: myname
                        hostname: myname.puphpet
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_p1xw6saiep3v:
                                    host: '8488'
                                    guest: '22'
                        memory: '2048'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_i2yv0bi50ylq:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_pg75z96g5ioo:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_a7ouwsna3c8i:
                    www_root: ''
                    location: /
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_qo9tsvsznj5d:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_71zbc9h0znbw:
            servername: myname.dev
            serveraliases:
                - www.myname.dev
            docroot: /var/www/myname
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_hol1tl2qx5jo:
                    path: /var/www/myname
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_asfpregwsea6:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '5.5'
    modules:
        php:
            - cli
            - intl
            - xml
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_pdmqrdsfv28y:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_vgkc8vw4t4r0:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_i9y2mv2uzqx7:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_tq76kbhcm5ig:
            name: dbname
            sql: ''
    grants:
        mariadbng_lrb3yyn4jpyf:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: secret
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_cfrjwjgo476c:
            name: jobs
            password: secret
    databases:
        mysqlnd_ib5yknwsiv87:
            name: jobs
            sql: ''
    grants:
        mysqlng_n1bvanssim5f:
            user: jobs
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_edzbpcn0yn89:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'

```
