### ISSUE TITLE
Nginx downloads php file instead of rendering

### ISSUE THREAD

**Issue by juanpscotto** [puphpet/puphpet#2546]
Hi, i'm using puppet with laravel. But when I access my hosts it download the index.php file.

This is my config.yaml file:

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos65-x64
                box_url: puphpet/centos65-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        use_linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_oq99uj69n7nx:
                        id: mbopigrant
                        network:
                            #public_network: '192.168.27.222'
                            private_network: '192.168.56.102'
                        hostname: mbopigrant
                        memory: '1024'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_avk0ylc1ow08:
                source: /var/www/html
                target: /var/www/html
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'true'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'true'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
        enabled: ''
server:
    install: '1'
    packages:
        - htop
users_groups:
    install: '1'
    groups: {  }
    users:
        - mbopi
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - es_PY.UTF-8
        timezone: America/Asuncion
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_9z26lbl009ud:
            server_name: momo-dev-antell
            server_aliases:
                - www.momo-dev-antell
            www_root: /var/www/html/momo/public/web
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
        nxv_hndoipnygpos:
            server_name: counters-dev-antell
            server_aliases:
                - www.counters-dev-antell
            www_root: /var/www/html/momo/public/counters
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
        nxv_0x5dcz5ggk1e:
            server_name: clients-dev-antell
            server_aliases:
                - www.clients-dev-antell
            www_root: /var/www/html/momo/public/clients
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
        nxv_9z26lbl7899ud:
            server_name: momo.dev
            server_aliases:
                - www.momo.dev
            www_root: /var/www/html/momo2-personal/public/
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
        nxv_lco7l2lzxejs:
            server_name: stocks
            server_aliases:
                - www.stocks
            www_root: /var/www/html/stock-manager/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
        nxv_sdf454bsdf3s:
            server_name: sige-dev
            server_aliases:
                - www.sige-dev
            www_root: /var/www/html/sige-dev/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: ''
            ssl_protocols: ''
            ssl_ciphers: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        av_9wp5yvap6cza:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_zhygjmj95v96:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - fpm
            - mssql
            - interbase
            - pgsql
            - bcmath
            - mbstring
        pear:
            - MDB2_Driver_mssql
            - MDB2_Driver_pgsql
        pecl:
            - APC
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools: {  }
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_2gdq6ziolweh:
            default: '1'
            bundler: '1'
            version: 2.1.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '0.12'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini: {  }
    php_ini: {  }
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users: {  }
    databases: {  }
    grants: {  }
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users: {  }
    databases:
        mysqlnd_ii2mq5uxr63d:
            name: dbname
            sql: ''
    grants: {  }
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: ilovebacon
    databases: {  }
    users: {  }
    grants: {  }
    adminer: '1'
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '1'
    settings:
        listenaddress: 192.168.27.0/24
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
    instances: {  }
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

```

I my /etc/hosts file I added

`192.168.56.102 momo.dev www.momo.dev`

I'm using

Vagrant 1.8.6 and virtualbox  5.0.26 

Can you help me please
