### ISSUE TITLE
adminer is not working

### ISSUE THREAD

**Issue by yuniorsk** [puphpet/puphpet#2564]
hi guys, adminer is not working and also other php scripts under Apache default virtual host, I think it is caused by missing FilesMatch block in default vh configuration. Maybe it has something to do with recent FilesMatch changes. Thanks a lot

**Comment by StudioMaX** [comment]
Temporary fix for this bug in config.yaml:
Set `default_vhost` to `false`
```
apache:
    install: '1'
    settings:
        ...
        default_vhost: false
        ...
```

And add these vhosts:
```
apache:
    ...
    vhosts:
        ...
        default_vhost_80:
            servername: default
            docroot: /var/www/html
            port: '80'
            default_vhost: true
            setenvif: {  }
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_directory_80:
                    path: /var/www/html
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_files_80:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
        default_vhost_443:
            servername: default
            docroot: /var/www/html
            port: '443'
            default_vhost: true
            setenvif: {  }
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_directory_443:
                    path: /var/www/html
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_files_443:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
```
This vhost will be the same as the default vhost.
