### ISSUE TITLE
Unable to run a vagrant provision with postgresql 9.6

### ISSUE THREAD

**Issue by codebymikey** [puphpet/puphpet#2571]
Running a vagrant provision gives me the following error:

```
==> myprojectname: Finished running files in files/exec-preprovision
==> myprojectname: To run again, delete hashes you want rerun in /.puphpet-stuff/exec-preprovision-ran or the whole file to rerun all
==> myprojectname: Running provisioner: puppet...
==> myprojectname: Running Puppet with ...
==> myprojectname: Failed to load feature test for microsoft_windows: ERROR: Failed to build gem native extension.
==> myprojectname:
==> myprojectname:     /opt/puppetlabs/puppet/bin/ruby extconf.rb
==> myprojectname: checking for pg_config... yes
==> myprojectname: Using config values from /usr/bin/pg_config
==> myprojectname: checking for libpq-fe.h... yes
==> myprojectname: checking for libpq/libpq-fs.h... yes
==> myprojectname: checking for pg_config_manual.h... yes
==> myprojectname: checking for PQconnectdb() in -lpq... no
==> myprojectname: checking for PQconnectdb() in -llibpq... no
==> myprojectname: checking for PQconnectdb() in -lms/libpq... no
==> myprojectname: Can't find the PostgreSQL client library (libpq)
==> myprojectname:
==> myprojectname: extconf failed, exit code 1
==> myprojectname:
==> myprojectname: Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.2/gems/pg-0.19.0 for inspection.
==> myprojectname: Results logged to /usr/local/rvm/gems/ruby-2.2.2/extensions/x86_64-linux/2.1.0/pg-0.19.0/gem_make.out
==> myprojectname: Error: Could not initialize global default settings: ERROR: Failed to build gem native extension.
==> myprojectname:
==> myprojectname:     /opt/puppetlabs/puppet/bin/ruby extconf.rb
==> myprojectname: checking for pg_config... yes
==> myprojectname: Using config values from /usr/bin/pg_config
==> myprojectname: checking for libpq-fe.h... yes
==> myprojectname: checking for libpq/libpq-fs.h... yes
==> myprojectname: checking for pg_config_manual.h... yes
==> myprojectname: checking for PQconnectdb() in -lpq... no
==> myprojectname: checking for PQconnectdb() in -llibpq... no
==> myprojectname: checking for PQconnectdb() in -lms/libpq... no
==> myprojectname: Can't find the PostgreSQL client library (libpq)
==> myprojectname:
==> myprojectname: extconf failed, exit code 1
==> myprojectname:
==> myprojectname: Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.2/gems/pg-0.19.0 for inspection.
==> myprojectname: Results logged to /usr/local/rvm/gems/ruby-2.2.2/extensions/x86_64-linux/2.1.0/pg-0.19.0/gem_make.out
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I'm also not sure where it's getting `microsoft_windows` from.

Here's a copy of my vagrant file:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: 'false'
                chosen_virtualizer: vmware_workstation
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_gyn85b7l770n:
                        id: myprojectname
                        hostname: myprojectname.vagrant
                        network:
                            private_network: 192.168.56.109
                            forwarded_port:
                                vflmnfp_p4u6dfhxon8m:
                                    host: '5895'
                                    guest: '22'
                        memory: '1024'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_9rfrb6qcy1fe:
                source: ..
                target: /var/www/myprojectname
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: 'vagrant' # vagrant.
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'true'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - htop
        - vim
        - imagemagick
        - memcached
        - libpq-dev
        - postgresql-contrib
users_groups:
    install: '1'
    groups: {  }
    users:
        - "myprojectname"
locale:
    install: '1'
    settings:
        default_locale: en_GB.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    fr_k59xacerq7o5:
        port:
            - '3000'
            - '3001'
        priority: '100'
        proto: tcp
        action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        myprojectname:
            server_name: myprojectname.vagrant
            server_aliases:
                - www.myprojectname.vagrant
                - '*.vagrantshare.com'
            www_root: /var/www/myprojectname/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_5gevpsxnb6eb:
                    www_root: ''
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_3dck9ozcjn6o:
                    www_root: ''
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - headers
        - proxy_fcgi
        - rewrite
    vhosts:
        av_t1s51hfmjy1e:
            servername: myprojectname.vagrant
            serveraliases:
                - myprojectname
                - '*.vagrantshare.com'
            docroot: /var/www/myprojectname/web
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_1x6o4ly5io8f:
                    path: /var/www/myprojectname/web
                    directoryindex: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
        av_wzq3bdrnmgvi:
            servername: myprojectname.vagrant
            serveraliases:
                - myprojectname
                - '*.vagrantshare.com'
            docroot: /var/www/myprojectname/web
            port: '443'
            custom_fragment: ''
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_naa4taxyjnng:
                    path: /var/www/myprojectname/web
                    directoryindex: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
letsencrypt:
    install: '0'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - mbstring
            - imagick
            - memcached
            - gd
            - dom
            - soap
            - zip
            - xml
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_5fjduv3o397v:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: '250'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_sd1mz2kprsjf:
            default: '1'
            bundler: '1'
            version: 2.2.2
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages:
        - gulp
        - bower
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_ihta4v8ckr8o:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_r3ss8abkz3ou:
            name: dbname
            sql: ''
    grants:
        mariadbng_4em4gvmeokxp:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: '1'
    users:
        mysqlnu_9eg3opyqcwlo:
            name: myprojectname
            password: '123'
    databases:
        mysqlnd_zgbexxxltkvj:
            name: myprojectname
            sql: /var/www/myprojectname/static/db/myprojectname.sql
    grants:
        mysqlng_uoce5tgfd5aj:
            user: myprojectname
            table: 'myprojectname.*'
            privileges:
                - ALL
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.6' # 9.5.2
        server:
            postgres_password: '123'
    databases:
        postsqlnd_nfr86lewyw13:
            dbname: myprojectname_development
            owner: 'vagrant'
        postsqlnd_zp1npql58zux:
            dbname: myprojectname_test
            owner: 'vagrant'
        postsqlnd_y8nckix531o4:
            dbname: myprojectname_production
            owner: 'myprojectname'
    users:
        postsql_user_myprojectname:
            username: myprojectname
            password: '123'
        postsql_user_root:
            username: root
            password: '123'
        postsql_user_vagrant:
            username: vagrant
            password: '123'
    grants:
        postsql_grant_myprojectname_dev:
            role: myprojectname
            db: myprojectname_development
            privilege:
                - ALL
        postsql_grant_myprojectname_vagrant:
            role: vagrant
            db: myprojectname_development
            privilege:
                - ALL
        postsql_grant_myprojectname_root:
            role: root
            db: myprojectname_development
            privilege:
                - ALL
        postsql_grant_myprojectname_test:
            role: myprojectname
            db: myprojectname_test
            privilege:
                - ALL
    adminer: '1'
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
    instances: {  }
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
