### ISSUE TITLE
Issues with Ubuntu 14.04 and mongodb and redis (Segmentation fault)

### ISSUE THREAD

**Issue by Ardakilic** [puphpet/puphpet#2596]
Hello,

I'm trying to create a puphpet box using Ubuntu 14.04 (not 16.04 because of #2461 ), but I get 2 errors during  `vagrant up`

These are the errors:

```
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns:
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns: Build process completed successfully
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns: Installing '/usr/lib/php/20131226/mongo.so'
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns: install ok: channel://pecl.php.net/mongo-1.6.14
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns: configuration option "php_ini" is not set to php.ini location
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns: You should add "extension=mongo.so" to php.ini
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns: Segmentation fault (core dumped)
==> develop: Error: printf "\n" | pecl -d preferred_state=stable install mongo && pecl info mongo returned 139 instead of one of [0]
==> develop: Error: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Php::Pecl::Module[mongo]/Exec[pecl-mongo]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install mongo && pecl info mongo returned 139 instead of one of [0]
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Puphpet::Php::Ini[mongo]/File[/etc/php/5.6/fpm/conf.d/mongo.ini]/ensure: created
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Puphpet::Php::Ini[mongo]/File[/etc/php/5.6/cli/conf.d/mongo.ini]/ensure: created
==> develop: Notice: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Puphpet::Php::Ini[mongo]/Augeas[MODULE/extension: mongo.so]/returns: executed successfully
==> develop: Info: /Stage[main]/Puphpet::Mongodb::Install/Puphpet::Php::Module::Pecl[mongo]/Puphpet::Php::Ini[mongo]/Augeas[MODULE/extension: mongo.so]: Scheduling refresh of Service[php5.6-fpm]
==> develop: Info: Puphpet::Php::Module::Pecl[mongo]: Unscheduling all events on Puphpet::Php::Module::Pecl[mongo]
==> develop: Info: Class[Puphpet::Mongodb::Install]: Unscheduling all events on Class[Puphpet::Mongodb::Install]
==> develop: Notice: /Stage[main]/Puphpet::Rabbitmq::Install/Puphpet::Php::Module::Pecl[amqp]/Php::Pecl::Module[amqp]/Exec[pecl-amqp]/returns: executed successfully
```

And about redis:

```
==> develop: Notice: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: install ok: channel://pecl.php.net/redis-3.1.1
==> develop: Notice: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: configuration option "php_ini" is not set to php.ini location
==> develop: Notice: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: You should add "extension=redis.so" to php.ini
==> develop: Notice: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: Segmentation fault (core dumped)
==> develop: Error: printf "\n" | pecl -d preferred_state=stable install redis && pecl info redis returned 139 instead of one of [0]
==> develop: Error: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Php::Pecl::Module[redis]/Exec[pecl-redis]/returns: change from notrun to 0 failed: printf "\n" | pecl -d preferred_state=stable install redis && pecl info redis returned 139 instead of one of [0]
==> develop: Notice: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Puphpet::Php::Ini[redis]/File[/etc/php/5.6/fpm/conf.d/redis.ini]/ensure: created
==> develop: Notice: /Stage[main]/Puphpet::Redis::Install/Puphpet::Php::Module::Pecl[redis]/Puphpet::Php::Ini[redis]/File[/etc/php/5.6/cli/conf.d/redis.ini]/ensure: created
```

Here's the `puphpet/config.yaml`

```yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_aol5aebp0l5c:
                        id: developweb
                        hostname: developweb.puphpet
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_x0xqbi9235ki:
                                    host: '5196'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_nwiwpb9sd0j8:
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - curl
        - nano
        - git-core
        - zsh
        - wget
users_groups:
    install: '1'
    groups:
        - develop
    users:
        - 'develop:develop'
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: Asia/Istanbul
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_2v0qhgyq4w5d:
            server_name: developtr.dev
            server_aliases:
                - www.developtr.dev
            www_root: /var/www/developtr/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_knrujvp63li4:
                    www_root: /var/www/developtr/public
                    location: /
                    index_files:
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
        nxv_j6n473mxihag:
            server_name: developen.dev
            server_aliases:
                - www.developen.dev
            www_root: /var/www/developen/public
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_cag5sahakaqs:
                    www_root: /var/www/developen/public
                    location: /
                    index_files:
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
        nxv_f9gwcxliyt87:
            server_name: developadmin.dev
            server_aliases:
                - www.developadmin.dev
            www_root: /var/www/developadmin/public
            listen_port: '80'
            client_max_body_size: 4m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_vqe3dixcps1n:
                    www_root: /var/www/developtr/public
                    location: /
                    index_files:
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_q5bb2wykn875:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome/web
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_h7tos7jsyf6a:
                    path: /var/www/awesome/web
                    directoryindex: 'index.php app.dev'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_rs7m4ee6o8e5:
                    path: (app_dev|config)\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV dev'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_kla3j3uf3vnc:
                    path: app\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV prod'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_5sikl4ctjsnk:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '5.6'
    modules:
        php:
            - cli
            - intl
            - xml
            - mcrypt
            - gd
            - imagick
            - redis
            - mysql
            - mongo
            - mongodb
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_3g5c042ayj7h:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_yzb1fugqq4wa:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages: {  }
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    users:
        mariadbnu_fffhq4yiyzsg:
            name: developdev
            password: developdev
    databases:
        mariadbnd_rr45x3f7z1ak:
            name: developdev
            sql: ''
    grants:
        mariadbng_vu3riqxe56sh:
            user: developdev
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    users:
        mysqlnu_qg6ourcgz2sm:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_tncxmb60zlq9:
            name: dbname
            sql: ''
    grants:
        mysqlng_xweprovwbsyn:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
mongodb:
    install: '1'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.12
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users: {  }
    vhosts:
        - developrabbit.dev
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_jjtzky8jfdr1:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'

```

I'm stuck here, any idea would be appreciated.

Thanks in advance,
