### ISSUE TITLE
Rsync type isn't bidirectional

### ISSUE THREAD

**Issue by tlartaud** [puphpet/puphpet#2610]
@jtreminio 

This issue is about this one : https://github.com/puphpet/puphpet/issues/2584

Sorry about this, but I'm really not sure this is a Virtual Box problem. I tried so many things. I reinstalled Vbox 5.0.26 and vagrant. I destroyed my VM and reprovisionned it. No changes.

Then, I decided to change the sync type. So I installed [Babun](https://github.com/babun) which is a great terminal that include rsync and offer an easier installation that cygwin.
It worked properly, My pages are now loading in 100ms, versus about 50 seconds before. Same for composer or grunt commands, which are now really fast.

BUT ! I'm facing some new problems. If I understand  correctly, I have to run `vagrant rsync-auto` in a terminal and let it open to make sure the change I make on my computer will be reflected to the VM. But it looks like its NOT bi-directional.

My question is, what sync-type would your recommend me, as a Windows user, if I need a bidirectional AND automatic sync which would be the fastest option ? The default option was working great for me some time ago until it get that slow.

I really need a bidirectional sync because I often run some commands that connect through SSH to the vm and do some stuff, like `vagrant ssh 'cd /var/www && composer update'` (yeah, I don't want to do this on my computer so I ensure I use the correct PHP/composer/grunt version from the VM)

Please .. help :)

Love you dude <3 ^^

Regards.

**Comment by jtreminio** [comment]
> My question is, what sync-type would your recommend me, as a Windows user, if I need a bidirectional AND automatic sync which would be the fastest option

You want SMB. Otherwise, there are Vagrant plugins for adding NSF support to Windows.

**Comment by tlartaud** [comment]
@jtreminio I know, I already tried SMB without success. Can you help please, I didn't find assistance in your docs even I've read it.

`
vagrant up
Bringing machine 'wp-customerarea' up with 'virtualbox' provider...
==> wp-customerarea: Importing base box 'puphpet/ubuntu1404-x64'...
==> wp-customerarea: Matching MAC address for NAT networking...
==> wp-customerarea: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> wp-customerarea: Setting the name of the VM: wp-customerarealocal_wp-customerarea_1489593066614_45303
==> wp-customerarea: Preparing SMB shared folders...
==> wp-customerarea: Clearing any previously set network interfaces...
==> wp-customerarea: Preparing network interfaces based on configuration...
    wp-customerarea: Adapter 1: nat
    wp-customerarea: Adapter 2: hostonly
==> wp-customerarea: Forwarding ports...
    wp-customerarea: 22 (guest) => 9033 (host) (adapter 1)
    wp-customerarea: 22 (guest) => 2222 (host) (adapter 1)
==> wp-customerarea: Running 'pre-boot' VM customizations...
==> wp-customerarea: Booting VM...
==> wp-customerarea: Waiting for machine to boot. This may take a few minutes...
    wp-customerarea: SSH address: 127.0.0.1:2222
    wp-customerarea: SSH username: vagrant
    wp-customerarea: SSH auth method: private key
==> wp-customerarea: Machine booted and ready!
[wp-customerarea] GuestAdditions 5.0.26 running --- OK.
==> wp-customerarea: Checking for guest additions in VM...
==> wp-customerarea: [vagrant-hostsupdater] Checking for host entries
==> wp-customerarea: [vagrant-hostsupdater]   found entry for: 192.168.56.99 vm.wp-customerarea.local
==> wp-customerarea: Setting hostname...
==> wp-customerarea: Configuring and enabling network interfaces...
==> wp-customerarea: Mounting SMB shared folders...
    wp-customerarea: C:/Users/Thomas/Sites/wp-customerarea.local => /var/www
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o uid=`id -u www-data`,gid=`getent group www-data | cut -d: -f3`,dir_mode=0775,file_mode=0664,sec=ntlm,credentials=/etc/smb_creds_5a1ac5649ef96cd51f3865c2287e9403 ///5a1ac5649ef96cd51f3865c2287e9403 /var/www
mount -t cifs -o uid=`id -u www-data`,gid=`id -g www-data`,dir_mode=0775,file_mode=0664,sec=ntlm,credentials=/etc/smb_creds_5a1ac5649ef96cd51f3865c2287e9403 ///5a1ac5649ef96cd51f3865c2287e9403 /var/www

The error output from the last command was:

mount.cifs: bad UNC (///5a1ac5649ef96cd51f3865c2287e9403)


Process finished with exit code 1
`

As found in your [documentation](https://www.vagrantup.com/docs/synced-folders/smb.html), I've set it like that :

Sync part of **config.yaml**
```
synced_folder:
            vflsf_o8pcrots2gbs:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
```

Sync part of **config-custom.yaml**
```
synced_folder:
            vflsf_o8pcrots2gbs:
                sync_type: smb
                smb:
                    smb_host: ''
                    smb_username: 'Thomas'
                    smb_password: 'myWindowsPassword'
```

I do not really know what a SMB mount is :/ Everything was working fine before. Don't know why the default sync type is now laggy like hell. Maybe I've reinstalled Vagrant and removed a plugin ? But which one ? Any idea pls ?

```
$ vagrant plugin list
vagrant-bindfs (1.0.5)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.7, system)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.13.0)
```
