### ISSUE TITLE
beanstalkd console is not picked up by fpm ?

### ISSUE THREAD

**Issue by diesonne** [puphpet/puphpet#2611]
Instead of showing the beanstalkd console I can see the php code

my config:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_s5b2es3csqva:
                        id: vlaio
                        hostname: vlaio
                        network:
                            private_network: 192.168.55.4
                            forwarded_port:
                                vflmnfp_f99sby6cv90b:
                                    host: '5612'
                                    guest: '22'
                        memory: '4096'
                        cpus: '7'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_p6ylblsxddqd:
                owner: www-data
                group: www-data
                source: ../src
                target: /var/www/src
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - curl
        - zip
        - zsh
        - openjdk-7-jre-headless
        - memcached
users_groups:
    install: '1'
    groups:
        - district01
    users:
        - 'district01:district01'
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - fr_BE.UTF-8
            - fr_FR.UTF-8
            - nl_BE.UTF-8
            - nl_NL.UTF-8
        timezone: Europe/Brussels
firewall:
    install: '1'
    rules:
        fr_pd6i48vzkd9t:
            port:
                - '6379'
            priority: '100'
            proto: tcp
            action: accept
        fr_xrb9eyl431x0:
            port:
                - '3306'
            priority: '100'
            proto: tcp
            action: accept
        fr_u5kaqupsqi3k:
            port:
                - '9000'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_c4x79mfbj339:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                nxvl_96m34nyi64wl:
                    www_root: ''
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_y4ogmduzi8vr:
                    www_root: ''
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - headers
        - proxy_fcgi
        - rewrite
    vhosts:
        av_iab1dzy04wxy:
            servername: vlaio-local.district01.be
            docroot: /var/www/src/vlaio/web
            port: '443'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /var/www/src/vlaio/customSamlApacheConfig
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_jz853feqeqo7:
                    path: /var/www/src/vlaio/web
                    directoryindex: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
                avd_0q2m1893ys9d:
                    path: /var/www/src/vlaio/vendor/simplesamlphp/simplesamlphp
                    directoryindex: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_7oy14uvpa8yu:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.0'
    modules:
        php:
            - cli
            - intl
            - gd
            - curl
            - mbstring
            - mcrypt
            - ldap
            - gmp
            - zip
            - bcmath
            - memcached
            - soap
            - xml
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Brussels
        openssl.capath: /etc/ssl/certs
        openssl.cafile: /etc/ssl/certs/ssl-cert-snakeoil.pem
        curl.cainfo: /etc/ssl/certs/ssl-cert-snakeoil.pem
        soap.wsdl_cache_limit: '20'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_lszkepr535ne:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-data
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '1'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_rvmwjnkvlwqj:
            default: '1'
            bundler: '1'
            version: 2.2.2
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages:
        - grunt
        - bower
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: 123
        override_options: {  }
    users: {  }
    databases: {  }
    grants: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    users: {  }
    databases:
        mysqlnd_bosg63i6nqx3:
            name: vlaio
            sql: ''
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '1'
    settings:
        listenaddress: 127.0.0.1
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
    instances:
        esi_3ejosvv1ziu0:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8983'

```
