### ISSUE TITLE
Deploy to Linode: machine offerings don't match current reality

### ISSUE THREAD

**Issue by OsakaWebbie** [puphpet/puphpet#2622]
I just created a Linode account to become my new production server. (I'm totally new to this kind of cloud hosting instead of a classic VPS.) In PuPHPet, the "Deploy to Linode" tab has a single choice for distro (Ubuntu Trusty 14.04 LTS x64), the 2GB machine choice says 24GB SSD, and the new "Tokyo 2" data center is not an option (there is "Tokyo", but if that only refers to the first one, it is full). But on Linode itself, they offer many distro choices, the 2GB choice is 30GB, and "Tokyo 2" is a data center with available nodes. I created a CentOS 7 machine with 2GB RAM and 30GB SSD using the Linode control panel, and it's running.

So what should I do? I really do want CentOS 7 and Tokyo 2. Do I edit the config.yaml to change "distribution" and "datacenter" and hope it recreates the same kind of machine I already created? Or should I just leave the current machine running and use the vagrant-managed-servers plugin to provision it in place? If the latter, what settings do I need to set in the puphpet.com interface, my config.yaml, and/or Vagrantfile to achieve that?

Here is the first part of my config.yaml with Deploy to Linode selected - as you can see, the OS for "linode" and "local" don't match.

```yaml
vagrantfile:
    target: linode
    vm:
        provider:
            linode:
                token: <redacted>
                ssh_key_name: Vagrant
                distribution: 'Ubuntu 14.04 LTS'
                machines:
                    vflm_3bnfr62ady4g:
                        id: linode1
                        hostname: linode1.puphpet
                        label: linode1-puphpet
                        datacenter: tokyo
                        plan: '2048'
            local:
                box_url: puphpet/centos7-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                box: puphpet/centos7-x64
                machines:
                    vflm_03ulldg0ikw8:
                        id: 7and7
                        hostname: 7and7.dev
                        network:
                            private_network: 192.168.56.200
                            forwarded_port:
                                vflmnfp_qtep7fng8o9c:
                                    host: '8528'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
```
