### ISSUE TITLE
CPU and RAM ignored on VMWare Workstation on Ubuntu Host

### ISSUE THREAD

**Issue by pascalwacker** [puphpet/puphpet#2629]
I tested it on an Ubuntu 16.04 and Ubuntu 16.10 host, with the latest Vagrant and VMWare Workstation. The created VMs are always with one core and 512 MB Ram, no matter what is in the config file:

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1604-x64
                box_url: 'false'
                box_version: '0'
                chosen_virtualizer: vmware_workstation
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_d0cvepp5bc1n:
                        id: foo
                        hostname: foo.bar
                        network:
                            private_network: 192.168.57.101
                            forwarded_port:
                                vflmnfp_sshjxwxapv4a:
                                    host: '80'
                                    guest: '80'
                        memory: '2048'
                        cpus: '3'
...
```
