### ISSUE TITLE
Connect from one VM to the db of another

### ISSUE THREAD

**Issue by Ruud-Zuiderlicht** [puphpet/puphpet#2665]
I'm having two VM's and I want to use the first as database server. But the second machine can't connect, it says `SQLSTATE[HY000] [2002] Connection refused`.

I've forwarded port 3306 in config.yaml, I've manually added the rule using iptables and I've removed all rules and accepted all traffic. The same thing happens for anything else that accesses port 3306 on the first machine. Is there a way to let the two connect (preferably) without ssh?

**Comment by Ruud-Zuiderlicht** [comment]
I've solved it, somewhat similar to #205. 

1. edited `/etc/mysql/my.cnf` to include the lines below (it might be possible to add this to the settings in `config.yaml`?)

    ```
    [mysqld]
    bind-address = 0.0.0.0
    ```

2. added port 3306 to firewall rules in `config.yaml` and provisioned Vagrant.

    ```
    ...
    firewall
    ...
        rules:
        fr_10mlxnjpql1h:
            port:
                - '3306'
            priority: '100'
            proto: tcp
            action: accept
    ```

3. Restarted mysl service (`sudo service mysql restart`). Not sure if this step is required, due to provisioning.

4. Added user permissions to MySQL because otherwise the remote IP will not be granted access.

    ```
    GRANT ALL PRIVILEGES ON *.* TO 'username'@'localhost' WITH GRANT OPTION;
    GRANT ALL PRIVILEGES ON *.* TO 'username'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    ```
