### ISSUE TITLE
Mounting Shared Folders Failing

### ISSUE THREAD

**Issue by acoghlan** [puphpet/puphpet#2678]
After recently updating machines to the latest version (by dumping my config.yaml back into puphpet, fixing any issues then re-downloading the entire resulting package) for Centos7, my machines work perfectly when built for the first time, including the cron jobs (nice!), however when I try to restart them they all fail at the point of trying to mount shared folders.

```
==> api-dev: Mounting shared folders...
    api-dev: /vagrant => C:/Users/AJC/Documents/Projects/api
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

Again - it works fine if I fire up the machine for the first time.

Config.yaml:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/centos7-x64
                box_url: puphpet/centos7-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_f5hu91n2qxfp:
                        id: api-dev
                        hostname: api-dev
                        network:
                            private_network: 192.168.56.122
                            forwarded_port:
                                vflmnfp_yu88mkamglt3:
                                    host: '7599'
                                    guest: '22'
                        memory: '2048'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_3bpeel1u5inq:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www/html/api
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim-common
        - mc
        - nano
        - npm
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_AU.UTF-8
        locales:
            - en_AU.UTF-8
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: Australia/Melbourne
firewall:
    install: '1'
    rules:
        fr_sm8uyd3hm6y1:
            port:
                - '777'
            priority: '100'
            proto: tcp
            action: accept
        fr_8d2wvrwbpyc1:
            port:
                - '10000'
            priority: '100'
            proto: tcp
            action: accept
        fr_gbhzfumoq9j5:
            port:
                - '3306'
            priority: '100'
            proto: tcp
            action: accept
        fr_8sbzzdnb4bmf:
            port:
                - '3306'
            priority: '100'
            proto: udp
            action: accept
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs:
        cj_w8rmlrk6q2t7:
            name: 'Laravel Cron'
            user: apache
            command: 'php /vagrant/artisan schedule:run >> /dev/null 2>&1'
            minute: ''
            hour: ''
            weekday: ''
            month: ''
            monthday: ''
        cj_w8rmlrk6q2t8:
            name: 'Laravel Queue Restart'
            user: vagrant
            command: 'php /vagrant/artisan queue:restart >> /dev/null 2>&1'
            minute: '*/5'
            hour: ''
            weekday: ''
            month: ''
            monthday: ''
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_xn3koqkahdmw:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                nxvl_ldcjgo2vi8v8:
                    www_root: ''
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_jqh37155358v:
                    www_root: ''
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_1up6te2k7c30:
            servername: api-dev.cloud.link
            docroot: /var/www/html/api/public
            port: '443'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /tmp/apache-vhost-directives_api-dev-cloud-link_443
            ssl: '1'
            ssl_cert: /root/certs/api-dev.crt
            ssl_key: /root/certs/api-dev.key
            ssl_chain: /root/certs/api-dev.bundle
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_wn9k69q07bac:
                    path: /var/www/html/api/public
                    directoryindex: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_4jh5gk9izzbm:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
        av_6rqi23szmuxf:
            servername: api-dev.cloud.link
            docroot: /var/www/html/api/public
            port: '80'
            custom_fragment: /tmp/apache-vhost-directives_api-dev-cloud-link_80
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            files_match:
                avfm_u6to42h30vfm:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
letsencrypt:
    install: '1'
    settings:
        email: me@email.com
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.0'
    modules:
        php:
            - cli
            - intl
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        upload_max_filesize: 10M
        post_max_size: 10M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_ae58li2nnsx9:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9001'
        xdebug.profiler_enable: '1'
        xdebug.remote_host: 192.168.56.1
        xdebug.remote_autostart: '1'
        xdebug.remote_log: /vagrant/storage/logs/xdebug.log
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.21.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages: {  }
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: vagrant
        override_options: {  }
    users:
        mariadbnu_jb24tvusvqbl:
            name: vagrant
            password: vagrant
    databases:
        mariadbnd_oipac9zx9oc2:
            name: dev_db
            sql: ''
    grants:
        mariadbng_7sst4c3c6aal:
            user: vagrant
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: vagrant
        override_options: {  }
    users:
        mysqlnu_8rmhuaaxe596:
            name: vagrant
            password: vagrant
    databases:
        mysqlnd_kfs3yekxw02a:
            name: dev_db
            sql: ''
    grants:
        mysqlng_bec80ztircad:
            user: vagrant
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '1'
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_78v7u2f2lxh1:
            name: es-01
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```
