### ISSUE TITLE
MySQL import exceeded timeout

### ISSUE THREAD

**Issue by shiftedreality** [puphpet/puphpet#2687]
Hi,

I'm trying to import huge sql dump into MySQL:

```yaml
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: '1234'
        override_options: {  }
    users:
        mysqlnu_04ucqherqglo:
            name: dbuser
            password: '1234'
    databases:
        mysqlnd_djg39m4p8fur:
            name: box
            sql: /var/www/dump.sql
    grants:
        mysqlng_zob3tss5d811:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
```
And getting execution timeout error:

```
==> box.vagrant: Error: Command exceeded timeout
==> box.vagrant: Error: /Stage[main]/Puphpet::Mysql::Install/Puphpet::Mysql::Databases[from puphpet::mysql::install]/Exec[box-import]/returns: change from notrun to 0 failed: Command exceeded timeout
```

Are there any ways to increase/remove timeout for MySQL?
