### ISSUE TITLE
Breaking issues with Let's Encrypt and Nginx.

### ISSUE THREAD

**Issue by wwwroth** [puphpet/puphpet#2688]
Having some issues trying to add LETSENCRYPT to my NGINX setup. Here's the error.

```
==> giftogram: Error: Failed to set owner to '33': No such file or directory @ chown_internal - /etc/nginx/nxv_zpngsbq1sv00.crt
==> giftogram: Error: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[nxv_zpngsbq1sv00]/File[/etc/nginx/nxv_zpngsbq1sv00.crt]/ensure: change from absent to link failed: Failed to set owner to '33': No such file or directory @ chown_internal - /etc/nginx/nxv_zpngsbq1sv00.crt
==> giftogram: Error: Failed to set owner to '33': No such file or directory @ chown_internal - /etc/nginx/nxv_zpngsbq1sv00.key
==> giftogram: Error: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[nxv_zpngsbq1sv00]/File[/etc/nginx/nxv_zpngsbq1sv00.key]/ensure: change from absent to link failed: Failed to set owner to '33': No such file or directory @ chown_internal - /etc/nginx/nxv_zpngsbq1sv00.key
```

I ran **`vagrant provision`** again and got a new error.

```
==> giftogram: Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/fullchain.pem, /etc/nginx/nxv_zpngsbq1sv00.crt)
==> giftogram: Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/fullchain.pem, /etc/nginx/nxv_zpngsbq1sv00.crt)
==> giftogram: Wrapped exception:
==> giftogram: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/fullchain.pem, /etc/nginx/nxv_zpngsbq1sv00.crt)
==> giftogram: Error: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[nxv_zpngsbq1sv00]/File[/etc/nginx/nxv_zpngsbq1sv00.crt]/ensure: change from absent to link failed: Could not set 'link' on ensure: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/fullchain.pem, /etc/nginx/nxv_zpngsbq1sv00.crt)
==> giftogram: Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/privkey.pem, /etc/nginx/nxv_zpngsbq1sv00.key)
==> giftogram: Error: Could not set 'link' on ensure: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/privkey.pem, /etc/nginx/nxv_zpngsbq1sv00.key)
==> giftogram: Wrapped exception:
==> giftogram: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/privkey.pem, /etc/nginx/nxv_zpngsbq1sv00.key)
==> giftogram: Error: /Stage[main]/Puphpet::Nginx::Install/Puphpet::Nginx::Vhosts[from puphpet::nginx::install]/Nginx::Resource::Vhost[nxv_zpngsbq1sv00]/File[/etc/nginx/nxv_zpngsbq1sv00.key]/ensure: change from absent to link failed: Could not set 'link' on ensure: File exists @ sys_fail2 - (/etc/letsencrypt/live/site.giftogram.dev/privkey.pem, /etc/nginx/nxv_zpngsbq1sv00.key)
```

## Config File

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1404-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_rhf7su3r5xk2:
                        id: giftogram
                        hostname: giftogram.dev
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_n1u8knx03fox:
                                    host: '5915'
                                    guest: '22'
                        memory: '4096'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_2a01zjuzhc7g:
                source: ./
                target: /var/www/current/
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_zpngsbq1sv00:
            server_name: site.giftogram.dev
            server_aliases:
                - www.giftogram.dev
            www_root: /var/www/current/dev/site/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 100m
            ssl: '1'
            rewrite_to_https: '1'
            spdy: '1'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_zzwbk8eesvju:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_it3392rcgf62:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
        nxv_7nqdltwvp7cy:
            server_name: order-api.giftogram.dev
            server_aliases:
                - order-api.giftogram.dev
            www_root: /var/www/current/dev/api/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_r3htz524lvgo:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_zeh1h5e394bz:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
letsencrypt:
    install: '1'
    settings:
        email: phil@giftogram.dev
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - mbstring
            - curl
            - gd
            - imagick
            - xml
            - simplexml
            - dom
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_kf5680umesfd:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
ruby:
    install: '1'
    versions:
        rv_ngk0vz1dm857:
            default: '1'
            bundler: '1'
            version: 1.9.3
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '5'
    npm_packages: {  }
```
