### ISSUE TITLE
Wrong PHP version

### ISSUE THREAD

**Issue by magroski** [puphpet/puphpet#2689]
Here's my config file

```
php:
    install: '1'
    settings:
        version: '7.0'
    modules:
        php:
            - cli
            - intl
            - xml
            - phalcon
            - curl
            - zip
            - mbstring
            - gd
        pear: {  }
        pecl: {  }
```

The provider
```
provider:
            local:
                box: puphpet/ubuntu1604-x64
```

However, it installs PHP CLI 7.1, which is used to run composer and breaks stuff.  How do I enforce the installation of PHP 7.0?
