### ISSUE TITLE
Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: User[www-data] is already declared

### ISSUE THREAD

**Issue by WillJW** [puphpet/puphpet#2699]
Error in full:

```
==> dev: Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: User[www-data] is already declared in file /tmp/vagrant-puppet/modules-2731c47289a6048543745cf297270527/puphpet/manifests/server.pp:42; cannot redeclare at /tmp/vagrant-puppet/modules-2731c47289a6048543745cf297270527/puphpet/manifests/usersgroups.pp:58 at /tmp/vagrant-puppet/modules-2731c47289a6048543745cf297270527/puphpet/manifests/usersgroups.pp:58:7 on node test.dev
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

config.yaml:

```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1604-x64
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_6vr3zietstll:
                        id: dev
                        hostname: test.dev
                        network:
                            private_network: 192.168.56.101
                            forwarded_port:
                                vflmnfp_1ed307b8fxen:
                                    host: '9249'
                                    guest: '22'
                        memory: '512'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_n7gza5iad7bg:
                owner: www-data
                group: www-data
                source: ~/Projects/freshpress
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups:
        - www-data
    users:
        - 'www-data:www-data'
        - 'will:www-data'
locale:
    install: '1'
    settings:
        default_locale: en_GB.UTF-8
        locales:
            - en_GB.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_093d3bz0ykzd:
            server_name: test.dev
            server_aliases:
                - test2.dev
                - test3.dev
                - test4.dev
                - test5.dev
            www_root: /var/www
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                nxvl_btg1ognwb166:
                    www_root: ''
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                    rewrites:
                        nxvlrw_1kdzfsdypna5:
                            when: ''
                            regex: '"^(.*)\.[\da-f]{32}\.(css|js)$"'
                            target: '$1.$2 last'
                nxvl_rfpss07p78p8:
                    www_root: ''
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
letsencrypt:
    install: '1'
    settings:
        email: ''
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - common
            - curl
            - imagick
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_1ehsrimn7frd:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: root
        override_options: {  }
    users:
        mysqlnu_mcvmsh3wtrdk:
            name: wordpress
            password: wordpress
    databases:
        mysqlnd_vvlxyl6h8bbx:
            name: wordpress
            sql: /var/www/resources/sql/initial.sql
    grants:
        mysqlng_b3bu83v76gw8:
            user: wordpress
            table: 'wordpress.*'
            privileges:
                - ALTER
                - 'ALTER ROUTINE'
                - CREATE
                - 'CREATE ROUTINE'
                - 'CREATE TEMPORARY TABLES'
                - 'CREATE VIEW'
                - DELETE
                - DROP
                - EVENT
                - EXECUTE
                - INDEX
                - INSERT
                - 'LOCK TABLES'
                - REFERENCES
                - SELECT
                - 'SHOW VIEW'
                - TRIGGER
                - UPDATE
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
```
