### ISSUE TITLE
PHP 5.4 was installed instead 5.5

### ISSUE THREAD

**Issue by bladeofsteel** [puphpet/puphpet#270]
I try start box based on Debian 7.2 with PHP 5.5. When puppet finish setup I found what php 5.4 was installed.

Here is part of my config:

```
    vm:
        box: debian-wheezy72-x64-vbox43
        box_url: 'https://puphpet.s3.amazonaws.com/debian-wheezy72-x64-vbox43.box'
...

php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
    ini:
        error_reporting: '-1'
        display_errors: On
        error_log: /vagrant/dev/logs/php_errors.log
    timezone: Europe/Moscow
```
