### ISSUE TITLE
Beanstalk only listens on internal interface

### ISSUE THREAD

**Issue by tetele** [puphpet/puphpet#2709]
I have [this config](https://pastebin.com/bKn21q71)

Particularily this part here
```
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
```

When I provision my VM, the content of `/etc/default/beanstalkd` is
```
## Defaults for the beanstalkd init script, /etc/init.d/beanstalkd on
## Debian systems.

BEANSTALKD_LISTEN_ADDR=127.0.0.1
BEANSTALKD_LISTEN_PORT=11300

# You can use BEANSTALKD_EXTRA to pass additional options. See beanstalkd(1)
# for a list of the available options. Uncomment the following line for
# persistent job storage.
#BEANSTALKD_EXTRA="-b /var/lib/beanstalkd"
```

and `netstat -ant | grep LISTEN` returns this
```
[08:26 AM]-[vagrant@api]-[~]
$ netstat -ant | grep LISTEN
3:tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN
4:tcp        0      0 127.0.0.1:11300           0.0.0.0:*               LISTEN
5:tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN
6:tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
7:tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
11:tcp6       0      0 :::8081                 :::*                    LISTEN
12:tcp6       0      0 :::8082                 :::*                    LISTEN
13:tcp6       0      0 :::22                   :::*                    LISTEN
```

Notice that Beanstalk is only listening for connections from 127.0.0.1. This makes the server refuse any connection from another host, although I have set up the `listenaddress` parameter to be 0.0.0.0.

Manually changing 127.0.0.1 to 0.0.0.0 in `/etc/default/beanstalkd` and `sudo service beanstalkd restart` fixes the problem, but I wish it was provisioned properly from the start.

Thanks!
