### ISSUE TITLE
Two projects with the same IP address.

### ISSUE THREAD

**Issue by dawounit** [puphpet/puphpet#2716]
During creating local environment in puphpet we have to determine IP address here: "Deploy Target" > "Locally" > "Machines" > "IP Address". But what if we have two projects with the same IP and both should works in the same time? This option should be configured in separated file with host-depended settings which is not included to GIT repository, right? How to deal with it?

**Comment by jan-obtam** [comment]
By two projects, you mean different projects on different "web-address" right? Like project1.dev and project2.dev which are both hosted on the same PuPHPet box? If so, this works (for apache at least, but I think nginx has the same configuration) and should be generated by default once you use the config tool.

```
....
    vhosts:
        project1dev:
            servername: project1.dev
            serveraliases:
                - www.project1.dev
            docroot: /var/www/project1/public/
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_rete362f8tiw:
                    path: /var/www/project1/public/
                    directoryindex: 'index.php app.dev'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_wrkfjy154inw:
                    path: (app_dev|config)\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV dev'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_vlm3p3xfnzat:
                    path: app\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV prod'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_537p6ysuibiy:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch
                        vhosts:
        project2dev:
            servername: project2.dev
            serveraliases:
                - www.project2.dev
            docroot: /var/www/project2/public/
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_rete362f8tiw:
                    path: /var/www/project2/public/
                    directoryindex: 'index.php app.dev'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
            files_match:
                avfm_wrkfjy154inw:
                    path: (app_dev|config)\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV dev'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_vlm3p3xfnzat:
                    path: app\.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV prod'
                    custom_fragment: ''
                    provider: filesmatch
                avfm_537p6ysuibiy:
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    custom_fragment: ''
                    provider: filesmatch

....
```
