### ISSUE TITLE
 Unit elasticsearch.service is masked and connection refused (9200)

### ISSUE THREAD

**Issue by quoidautre** [puphpet/puphpet#2722]
Hi,
I've installed my new VM and, I'm trying to use ElasticSearch.

I want to restart the service, but I can't :( 
```
[08:57 ]-[vagrant@vm]
$ sudo systemctl start elasticsearch
Failed to start elasticsearch.service: Unit elasticsearch.service is masked.

[08:57 ]-[vagrant@vm]
$ sudo service elasticsearch start
Failed to start elasticsearch.service: Unit elasticsearch.service is masked.

[08:57 ]-[vagrant@vm]
$ curl 0:9200
{
  "name" : "vm-es-01",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

[08:57 ]-[vagrant@vm]
$ sudo cat /etc/iptables/rules.v4
...
-A INPUT -p tcp -m multiport --dports 9000 -m comment --comment "100 tcp/9000" -j ACCEPT
-A INPUT -p tcp -m multiport --dports 9200 -m comment --comment "100 tcp/9200" -j ACCEPT
-A INPUT -p tcp -m multiport --dports 5601 -m comment --comment "100 tcp/5601" -j ACCEPT
...
```
I've changed the configuration : 
```
[09:03 ]-[vagrant@vm]-[/etc/default]
$ sudo vi /etc/elasticsearch/es-01/elasticsearch.yml

network.bind_host: 0
network.host: 0.0.0.0
```

And, Windows OS (> curl vm.data-machine) : 
```
C:\...\...>curl 192.168.56.102:9200
curl: (7) Failed to connect to 192.168.56.102 port 9200: Connection refused

C:\...\...>curl 192.168.56.102
<!DOCTYPE html>
<html lang="en">
<head>
...
```
The windows host file : 
```
...
192.168.56.102 vm.data-machine
...
```
How can I restart the service, and, how can I access the VM on 9200 port :)

Thanks
Fabrice

**Comment by jtreminio** [comment]
You probably already figured this out, but if your config is like below:

```
elastic_search:
    install: 0
    settings:
        version: 6.1.2
        java_install: true
    instances:
        esi_04nkrfa8987r:
            name: es-01
            jvm_options:
                - '-Xms1G'
                - '-Xmx1G'
```

The service you want is actually `elasticsearch-es-01`, _not_ `elasticsearch`.
