### ISSUE TITLE
Vagrant up non-zero status: lsb_release issues in the logs

### ISSUE THREAD

**Issue by pawel-wasiliuk** [puphpet/puphpet#2727]
I am trying to deploy on Amazon EC2 with Vagrant using puphpet. I have met the problem which is giving the non-zero status and preventing the running process of **vagrant up**. All I see in the logs is that there may be some problems connected with **lsb_realease**. Basically, the only steps I did are the following: added aws dummy box from **https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box** and executed **vagrant up --provider=aws**. 
What do you think about it @jtreminio ? May there be any problem connected with **puppet** configuration?

The output from **vagrant up** is the following:

> Bringing machine 'machine' up with 'aws' provider...
> ==> machine: Warning! The AWS provider doesn't support any of the Vagrant
> ==> machine: high-level network configurations (`config.vm.network`). They
> ==> machine: will be silently ignored.
> ==> machine: Launching an instance with the following settings...
> ==> machine:  -- Type: t2.micro
> ==> machine:  -- AMI: ami-15e9c770
> ==> machine:  -- Region: us-east-2
> ==> machine:  -- Keypair: xxxx
> ==> machine:  -- Security Groups: ["xxxx"]
> ==> machine:  -- Block Device Mapping: []
> ==> machine:  -- Terminate On Shutdown: false
> ==> machine:  -- Monitoring: false
> ==> machine:  -- EBS optimized: false
> ==> machine:  -- Source Destination check:
> ==> machine:  -- Assigning a public IP address in a VPC: false
> ==> machine:  -- VPC tenancy specification: default
> ==> machine: Waiting for instance to become "ready"...
> ==> machine: Waiting for SSH to become available...
> ==> machine: Machine is booted and ready for use!
> ==> machine: Rsyncing folder: /cygdrive/c/PHPProjects/project/ => /var/www/project
> ==> machine: Rsyncing folder: /cygdrive/c/PHPProjects/project/ => /vagrant
> ==> machine: Rsyncing folder: /cygdrive/c/PHPProjects/project/puphpet/puppet/manifests/ => /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812
> ==> machine: Rsyncing folder: /cygdrive/c/PHPProjects/project/puphpet/puppet/modules/ => /tmp/vagrant-puppet/modules-a554be627e84b4d5fe32ee5ce6f3b9e5
> ==> machine: Rsyncing folder: /cygdrive/c/PHPProjects/project/puphpet/puppet/manifests/ => /tmp/vagrant-puppet/modules-b544e08d833e289f6dacceb39931fb90
> ==> machine: Running provisioner: file...
> ==> machine: Running provisioner: shell...
>     machine: Running: C:/Users/User/AppData/Local/temp/vagrant-shell20171212-8844-er4gur.sh
>     machine: which: no lsb_release in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin)
>     machine: which: no lsb_release in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin)
>     machine: which: no lsb_release in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin)
>     machine:
> ==> machine: Running provisioner: shell...
>     machine: Running: inline script
> ==> machine: Running provisioner: shell...
>     machine: Running: C:/Users/User/AppData/Local/temp/vagrant-shell20171212-8844-b8a1zb.sh
>     machine: which: no lsb_release in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin)
>     machine: which: no lsb_release in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin)
>     machine: which: no lsb_release in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin)
>     machine: /tmp/vagrant-shell: line 42: /opt/puppetlabs/puppet/bin/gem: No such file or directory
>     machine: /tmp/vagrant-shell: line 43: /opt/puppetlabs/puppet/bin/gem: No such file or directory
>     machine: /tmp/vagrant-shell: line 46: /opt/puppetlabs/puppet/bin/gem: No such file or directory
>     machine: /tmp/vagrant-shell: line 47: /opt/puppetlabs/puppet/bin/gem: No such file or directory
>     machine: /tmp/vagrant-shell: line 50: /opt/puppetlabs/puppet/bin/gem: No such file or directory
>     machine: /tmp/vagrant-shell: line 51: /opt/puppetlabs/puppet/bin/gem: No such file or directory
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

My **config.yaml** content:

```
vagrantfile:
    target: aws
    vm:
        provider:
            aws:
                access_key_id: 'xxxx'
                secret_access_key: 'xxxx'
                machines:
                    vfawsm_7vgukk9wg1ga:
                        id: xxxx
                        hostname: xxxx
                        keypair_name: xxxx
                        private_key_path: '~/.ssh/xxxx.pem'
                        region: us-east-2
                        instance_type: t2.micro
                        ami: ami-15e9c770
                        ssh_username: ec2-user
                        security_groups:
                            - xxxx
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_socd2s61d5bt:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www/project
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        post_up_message: ''
    ssh:
        forward_agent: true
server:
    install: '1'
    packages:
        - vim
        - htop
        - mc
        - nano
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_u13jcc9k2eyu:
            server_name: xxxx
            www_root: /var/www/project/web
            listen_port: '80'
            client_max_body_size: 100m
            ssl: '0'
            locations:
                nxvl_dyooxubidyge:
                    www_root: /var/www/project/web
                    location: /
                    try_files:
                        - $uri
                        - /app.php$is_args$args
                nxvl_nuvg3b8bnq59:
                    www_root: ''
                    location: '~ ^/(app_dev|config)\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: app_dev.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $realpath_root$fastcgi_script_name'
                        - 'DOCUMENT_ROOT $realpath_root'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
                nxvl_ux8ac4vte3my:
                    www_root: ''
                    location: '~ ^/app\.php(/|$)'
                    autoindex: 'off'
                    internal: 'true'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: app.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $realpath_root$fastcgi_script_name'
                        - 'DOCUMENT_ROOT $realpath_root'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - xml
            - mcrypt
            - gd
            - zip
            - curl
            - mbstring
            - mysql
            - fpm
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_4z71savjp0jy:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
ruby:
    install: '1'
    versions:
        rv_mdgdm1xau6rz:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages:
        - jquery
        - bootstrap
        - jquery-ui
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: xxxx
        override_options: {  }
    users:
        mysqlnu_wz32u15i9wbg:
            name: xxxx
            password: xxxx
    databases:
        mysqlnd_sgt64t2ss0il:
            name: xxxx
            sql: ''
    grants:
        mysqlng_9pl322rwvz2p:
            user: xxxx
            table: 'xxxx.*'
            privileges:
                - ALL
```

**Vagrantfile**
```
# -*- mode: ruby -*-

dir = File.dirname(File.expand_path(__FILE__))

require 'yaml'
require "#{dir}/puphpet/ruby/deep_merge.rb"
require "#{dir}/puphpet/ruby/to_bool.rb"
require "#{dir}/puphpet/ruby/puppet.rb"

configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

provider = ENV['VAGRANT_DEFAULT_PROVIDER'] ? ENV['VAGRANT_DEFAULT_PROVIDER'] : 'local'
if File.file?("#{dir}/puphpet/config-#{provider}.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-#{provider}.yaml")
  configValues.deep_merge!(custom)
end

if File.file?("#{dir}/puphpet/config-custom.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
  configValues.deep_merge!(custom)
end

data = configValues['vagrantfile']

Vagrant.require_version '>= 1.8.1'

Vagrant.configure('2') do |config|
  eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
end
```
