### ISSUE TITLE
CentOS PHP-FPM pid path

### ISSUE THREAD

**Issue by fyrye** [puphpet/puphpet#2730]
Originally addressed the issue at #1589 in 2015

My specific case is with `php 5.6` and `CentOS 6.8`.

In the puppet params `/puphpet/puppet/modules/puphpet/manifests/php/params.pp` it is set to:
```puppet
$pid_file = $::osfamily ? {
    'debian' => '/run/php-fpm.pid',
    'redhat' => '/var/run/php-fpm.pid',
  }
```

In `/etc/init.d/php-fpm` it is hard-coded as:
```bash
pidfile=${PIDFILE-/var/run/php-fpm/php-fpm.pid}
```

While this does lead to a bit of confusion when provisioning, 
I initially thought It ccould be worked around in the `/puphpet/config.yml` file until it is patched as:

```yaml
php:
    #...
    fpm_ini:
        pid_file: /var/run/php-fpm/php-fpm.pid
```

but it appended pid_file to the `/etc/php-fpm.conf` file
