### ISSUE TITLE
vagrant provision: conflicts with json

### ISSUE THREAD

**Issue by dieisraels** [puphpet/puphpet#2750]
Hi,

after successful `vagrant up` failed the provision with following error:

```
==> machine11: Error: Could not autoload puppet/parser/functions/array_true: Unable to activate activesupport-4.2.6, because json-2.0.4 conflicts with json (>= 1.7.7, ~> 1.7)
==> machine11: Error: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/array_true: Unable to activate activesupport-4.2.6, because json-2.0.4 conflicts with json (>= 1.7.7, ~> 1.7) (file: /tmp/vagrant-puppet/modules-d8d302ff3066bd2789b814b88c9b24d3/puphpet/manifests/cron.pp, line: 10, column: 11) on node machine11.dev
```

I have not configured any JSON libraries in puphpet.

**Comment by jtreminio** [comment]
Did you update everything in your directory is just config.yaml?

**Comment by dieisraels** [comment]
I only changed some settings in the Apache host configuration. Even if I do
not make any changes, the error appears with the `vagrant provision`
command.

Am 07.02.2018 16:49 schrieb "Juan Treminio" <notifications@github.com>:

**Comment by ibrahim-ih** [comment]
i have the same problem

**Comment by CTIGB** [comment]
I have found that when I created a new config from scratch that fixed my issue. I must add though that I also was on vagrant 1.9 and so updated to vagrant 2 and re-inastalled all my vagrant plugins

**Comment by dieisraels** [comment]
OK, maybe this is the reason. I loaded an old puphpet config with following settings:

```yaml
ruby:
    install: '1'
    versions:
        rv_c82lbgjqljnd:
            default: '1'
            bundler: '1'
            version: '2.3'
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
```

The autogenerated new config looks like:
```yaml
ruby:
    install: '1'
    versions:
        ruby1:
            default: '1'
            bundler: '1'
            version: '2.4'
            gems:
                - deep_merge@1.2.1
                - activesupport@5.1.4
                - vine@0.4
```
There may be some version conflicts wit the box update from `puphpet/ubuntu1604-x64`to `bento/ubuntu-16.04` and the update vom Puppet 3 to 5.
