### ISSUE TITLE
Revert xdebug

### ISSUE THREAD

**Issue by mkindred** [puphpet/puphpet#2751]
I've been pulling out my hair trying to troubleshoot an issue with xdebug/sublime on a new vm, and I finally decided to revert from 2.6.0 back to 2.5.5, and it now works again.

Is there a way to specify xdebug version in the config? I tried, with no success:

```
xdebug:
    install: '1'
    version: 2.5.5
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '1'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
```
