### ISSUE TITLE
Support `charset` property in `mysql.databases` configuration sets

### ISSUE THREAD

**Issue by huebs** [puphpet/puphpet#2753]
Currently, a `charset` parameter present in any MySQL database configuration in `config.yaml` gets [passed](https://github.com/puphpet/puppet-puphpet/blob/master/manifests/mysql/databases.pp#L20) to the MySQL module where [it's already supported](https://github.com/puppetlabs/puppetlabs-mysql/blob/master/lib/puppet/provider/mysql_database/mysql.rb#L35).

I personally find this hidden feature useful because I often use `utf8mb4`.

I've also confirmed that setting the `collate` key to `utf8mb4_general_ci` or `utf8mb4_unicode_ci` doesn't change the default `charset` from `utf8` to `utf8mb4`. Unless the `charset` is specifically set to `utf8mb4`, using either of `utf8mb4_*` collations will lead provisioning to fail.

From what I can tell, fully support this feature requires making only two changes:

In [`src/PuphpetBundle/Resources/config/mysql/defaults.yml`](https://github.com/puphpet/puphpet/blob/master/src/PuphpetBundle/Resources/config/mysql/defaults.yml), change:

```yaml
databases:
    database1:
        name: dbname
        collate: utf8_general_ci
        sql: ~
```

To:

```yaml
databases:
    database1:
        name: dbname
        charset: utf8
        collate: utf8_general_ci
        sql: ~
```

And in [`src/PuphpetBundle/Resources/views/mysql/database.html.twig`](https://github.com/puphpet/puphpet/blob/master/src/PuphpetBundle/Resources/views/mysql/database.html.twig), add:

```html
    <div class="form-group col-xs-12 col-sm-6">
        <label for="{{ idBase }}-charset">
            DB Charset
        </label>
        <input type="text" id="{{ idBase }}-charset"
               name="{{ nameBase }}[charset]"
               placeholder="utf8" class="form-control"
               value="{{ database.charset }}" />
    </div>
```

Is there a reason this isn't officially supported that I'm not seeing? Is there more to fully implementing support than what I've outlined? Would you accept a pull request with these changes?
