### ISSUE TITLE
PHP cannot write to default synced folder

### ISSUE THREAD

**Issue by danielkullik** [puphpet/puphpet#2756]
Hi,

since commit 175f788 the synced folder /var/www belongs to owner vagrant and group vagrant. But because PHP runs as www-user/www-data, i.e. does not belong to the group vagrant, it lacks write-permission inside /var/www.

Is this information sufficient?

Best regards

**Comment by vintagesucks** [comment]
You could try this in your `config.yaml`:

```
vagrantfile:
    vm:
        synced_folder:
            folder1:
                owner: vagrant
                group: www-data
```
