### ISSUE TITLE
Config generator cannot handle multiple databases

### ISSUE THREAD

**Issue by grappler** [puphpet/puphpet#2758]
When defining multiple database for MYSQL the database is defined as a value 1 instead of the name which causes the following error.

`Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: A substring operation does not accept a String as a character index. Expected an Integer (file: /tmp/vagrant-puppet/modules-ed13e3e2de690b216519aea8890270a8/puphpet/manifests/mysql/databases.pp, line: 8, column: 23) (file: /tmp/vagrant-puppet/modules-ed13e3e2de690b216519aea8890270a8/puphpet/manifests/mysql/install.pp, line: 59) on node test.local`

```
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: root
        override_options: {  }
    users:
        mysqlnu_vkixi18m3ojz:
            name: username
            password: password
    databases:
        database_0rm:
            name: test_database
        database_70g: '1'
        database_6x6: '1'
    grants: {  }
````
