### ISSUE TITLE
Upgrade an existing box fails 

### ISSUE THREAD

**Issue by tomasnorre** [puphpet/puphpet#2762]
Hi,

First, Thanks a lot for you work on puphpet, it's really great and simple to use. 
Second, 

I'm currently trying to update an existing box by uploading the config.yml to the webinterface so that I can click through the steps and get update configuration manifests etc. 

But when doing this the first error I get is:
```
==> hostname: Error: Parameter collate failed on Mysql_database[hostname_devbox]: Invalid value "". Valid values match /^\S+$/. (file: /tmp/vagrant-puppet/modules-3c8f2892aec3f57444c972e3ee6b376d/puphpet/manifests/mysql/databases.pp, line: 20)
```

The line looks like this: `create_resources( mysql_database, { "${name}" => $merged })` but I cannot see whats wrong here.. 

Is my config.yml corrupt or incorrect after the update?

```
mysql:
     install: '1'
     settings:
         version: '5.6'
         root_password: super-secret-password
         override_options: {  }
     users:
         mysqlnu_23gjnkhqjwnh:
             name: hostname_devbox
             password: hostname_devbox
     databases:
         mysqlnd_m3znnceqda21:
             name: hostname_devbox
             collate: ''
             sql: ''
     grants:
         mysqlng_37kdjhvljyk6:
             user: hostname_devbox
             table: '*.*'
             privileges:
                 - ALL
```
