### ISSUE TITLE
wizard does not enforce collate for mysql or mariadb

### ISSUE THREAD

**Issue by steros** [puphpet/puphpet#2778]
Apparently it is now mandatory to set a collate for your databases in config.yaml.
Yet when you come with an old config that has an empty collate the wizards just takes this empty value and puts it into the new config resulting in an error whilst building.

> ==> foo: Error: Parameter collate failed on Mysql_database[foo]: Invalid value "". Valid values match /^\S+$/. (file: /tmp/vagrant-puppet/modules-ffd4f2e29888a1dd89b09dadc1db196b/puphpet/manifests/mariadb/databases.pp, line: 21)

Btw. that error informs about Mysql_database even though you want to install MariaDB.

```
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    users:
        mariadbnu_gzefp16af8h8:
            name: foo
            password: 123
    databases:
        mariadbnd_tmui94gwjl64:
            name: foo
            collate: '' < -- this has to be something like 'utf8_unicode_ci'
            sql: ''
    grants:
        mariadbng_a8akcos76yh9:
            user: foo
            table: '*.*'
            privileges:
                - ALL
```
