### ISSUE TITLE
Bug in DigitalOcean config section

### ISSUE THREAD

**Issue by jabocrack1** [puphpet/puphpet#2782]
In generated config
```
vagrantfile:
    target: digitalocean
    vm:
        provider:
            digitalocean:
                image: ubuntu-16-04-x64
                token: <some-token>
                ssh_key_name: Vagrant
                setup: true
                ipv6: false
                private_networking: false
                backups_enabled: false
                machines:
                    machine1:
                        id: digitalocean1
                        hostname: digitalocean1.puphpet
                        region: 'Frankfurt 1'
                        size: 1gb
```
But now `region` field in this format is failed. New format is 'fra1' etc. (3 letters and digit)
