### ISSUE TITLE
Provisioning error

### ISSUE THREAD

**Issue by dmirkitanov** [puphpet/puphpet#2783]
I'm constantly getting this error (tried to import my old config files, then to create one without importing):

```
    travelsite-dev.vm: Your private key for SSH-based authentication has been saved to 'puphpet/files/dot/ssh/id_rsa'!
    travelsite-dev.vm: Adding generated root key to /root/.ssh/id_rsa
    travelsite-dev.vm: Adding generated root key to /root/.ssh/id_rsa.pub
    travelsite-dev.vm: Adding generated root key to /root/.ssh/authorized_keys
    travelsite-dev.vm: Adding generated key to /home/vagrant/.ssh/id_rsa
    travelsite-dev.vm: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
    travelsite-dev.vm: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> travelsite-dev.vm: Running provisioner: shell...
    travelsite-dev.vm: Running: /var/folders/25/j_7x4dd57y934rbz0snhmy3m0000gr/T/vagrant-shell20180424-46588-1dtdjeh.sh
    travelsite-dev.vm: OK
    travelsite-dev.vm: Selecting previously unselected package puppet5-release.
    travelsite-dev.vm: (Reading database ... 39322 files and directories currently installed.)
    travelsite-dev.vm: Preparing to unpack .../puppet5-release-xenial.deb ...
    travelsite-dev.vm: Unpacking puppet5-release (5.0.0-1xenial) ...
    travelsite-dev.vm: Setting up puppet5-release (5.0.0-1xenial) ...
    travelsite-dev.vm: Ign:1 http://apt.puppetlabs.com xenial InRelease
    travelsite-dev.vm: Get:2 http://apt.puppetlabs.com xenial Release [57.5 kB]
    travelsite-dev.vm: Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
    travelsite-dev.vm: Get:4 http://apt.puppetlabs.com xenial Release.gpg [836 B]
    travelsite-dev.vm: Get:5 http://apt.puppetlabs.com xenial/puppet5 amd64 Packages [14.7 kB]
    travelsite-dev.vm: Hit:6 http://archive.ubuntu.com/ubuntu xenial InRelease
    travelsite-dev.vm: Get:7 http://apt.puppetlabs.com xenial/puppet5 i386 Packages [13.0 kB]
    travelsite-dev.vm: Get:8 http://apt.puppetlabs.com xenial/puppet5 all Packages [7,189 B]
    travelsite-dev.vm: Hit:9 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
    travelsite-dev.vm: Hit:10 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
    travelsite-dev.vm: Fetched 93.2 kB in 2s (43.3 kB/s)
    travelsite-dev.vm: Reading package lists...
    travelsite-dev.vm: Reading package lists...
    travelsite-dev.vm: Building dependency tree...
    travelsite-dev.vm: Reading state information...
    travelsite-dev.vm: The following NEW packages will be installed:
    travelsite-dev.vm:   puppet-agent
    travelsite-dev.vm: 0 upgraded, 1 newly installed, 0 to remove and 33 not upgraded.
    travelsite-dev.vm: Need to get 16.3 MB of archives.
    travelsite-dev.vm: After this operation, 91.7 MB of additional disk space will be used.
    travelsite-dev.vm: Get:1 http://apt.puppetlabs.com xenial/puppet5 amd64 puppet-agent amd64 5.3.6-1xenial [16.3 MB]
    travelsite-dev.vm: Fetched 16.3 MB in 2min 59s (90.8 kB/s)
    travelsite-dev.vm: Selecting previously unselected package puppet-agent.
    travelsite-dev.vm: (Reading database ...
    travelsite-dev.vm: (Reading database ... 5%
    travelsite-dev.vm: (Reading database ... 10%
    travelsite-dev.vm: (Reading database ... 15%
    travelsite-dev.vm: (Reading database ... 20%
    travelsite-dev.vm: (Reading database ... 25%
    travelsite-dev.vm: (Reading database ... 30%
    travelsite-dev.vm: (Reading database ... 35%
    travelsite-dev.vm: (Reading database ... 40%
    travelsite-dev.vm: (Reading database ... 45%
    travelsite-dev.vm: (Reading database ... 50%
    travelsite-dev.vm: (Reading database ... 55%
    travelsite-dev.vm: (Reading database ... 60%
    travelsite-dev.vm: (Reading database ... 65%
    travelsite-dev.vm: (Reading database ... 70%
    travelsite-dev.vm: (Reading database ... 75%
    travelsite-dev.vm: (Reading database ... 80%
    travelsite-dev.vm: (Reading database ... 85%
    travelsite-dev.vm: (Reading database ... 90%
    travelsite-dev.vm: (Reading database ... 95%
    travelsite-dev.vm: (Reading database ... 100%
    travelsite-dev.vm: (Reading database ...
    travelsite-dev.vm: 39327 files and directories currently installed.)
    travelsite-dev.vm: Preparing to unpack .../puppet-agent_5.3.6-1xenial_amd64.deb ...
    travelsite-dev.vm: Unpacking puppet-agent (5.3.6-1xenial) ...
    travelsite-dev.vm: Processing triggers for libc-bin (2.23-0ubuntu10) ...
    travelsite-dev.vm: Setting up puppet-agent (5.3.6-1xenial) ...
    travelsite-dev.vm: Created symlink from /etc/systemd/system/multi-user.target.wants/puppet.service to /lib/systemd/system/puppet.service.
    travelsite-dev.vm: Created symlink from /etc/systemd/system/multi-user.target.wants/mcollective.service to /lib/systemd/system/mcollective.service.
    travelsite-dev.vm: Created symlink from /etc/systemd/system/multi-user.target.wants/pxp-agent.service to /lib/systemd/system/pxp-agent.service.
    travelsite-dev.vm: Removed symlink /etc/systemd/system/multi-user.target.wants/pxp-agent.service.
    travelsite-dev.vm: Processing triggers for libc-bin (2.23-0ubuntu10) ...
    travelsite-dev.vm: Successfully installed concurrent-ruby-1.0.5
    travelsite-dev.vm: Successfully installed i18n-0.9.5
    travelsite-dev.vm: Successfully installed thread_safe-0.3.6
    travelsite-dev.vm: Successfully installed tzinfo-1.2.5
    travelsite-dev.vm: Successfully installed activesupport-5.1.4
    travelsite-dev.vm: 5 gems installed
    travelsite-dev.vm: Successfully installed vine-0.4
    travelsite-dev.vm: 1 gem installed
==> travelsite-dev.vm: Running provisioner: shell...
    travelsite-dev.vm: Running: /var/folders/25/j_7x4dd57y934rbz0snhmy3m0000gr/T/vagrant-shell20180424-46588-afpvaf.sh
    travelsite-dev.vm: Running files in files/exec-preprovision
    travelsite-dev.vm: Created file /opt/puphpet-state/exec-preprovision-ran
    travelsite-dev.vm: Finished running files in files/exec-preprovision
    travelsite-dev.vm: To run again, delete hashes you want rerun in /opt/puphpet-state/exec-preprovision-ran or the whole file to rerun all
==> travelsite-dev.vm: Running provisioner: puppet...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cp /tmp/vagrant-puppet/vagrant_facts.yaml /etc/puppetlabs/facter/facts.d/vagrant_facts.yaml

Stdout from the command:



Stderr from the command:

cp: cannot create regular file '/etc/puppetlabs/facter/facts.d/vagrant_facts.yaml': No such file or directory

```

Vagrant version:
```
$ vagrant --version
Vagrant 2.0.4
```

Config file:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: bento/ubuntu-16.04
                box_url: 'false'
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    machine1:
                        id: travelsite-dev.vm
                        hostname: travelsite-dev.vm
                        network:
                            private_network: 192.168.56.177
                            forwarded_port:
                                port1:
                                    host: '6167'
                                    guest: '22'
                        memory: '1024'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
        synced_folder:
            folder1:
                owner: vagrant
                group: vagrant
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - bash-completion
        - htop
        - vim
        - mc
        - php5-imagick
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - ru_RU.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        vhost1:
            server_name: travelsite-dev.vm
            server_aliases:
                - travelsite-dev.vm
            www_root: /var/www/web
            listen_port: '80'
            client_max_body_size: 32m
            ssl: '0'
            locations:
                sf4_base_CYY:
                    www_root: /var/www/public
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    index_files:
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                sf4_index_CYY:
                    www_root: /var/www/public
                    location: '~ ^/index\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'DOCUMENT_ROOT $realpath_root'
                        - 'APP_ENV dev'
        vhost_8mz:
            server_name: travelsite-prod.vm
            server_aliases:
                - travelsite-prod.vm
            www_root: /var/www
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                sf4_base_JGD:
                    www_root: /var/www/public
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    index_files:
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                sf4_index_JGD:
                    www_root: /var/www/public
                    location: '~ ^/index\.php(/|$)'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'DOCUMENT_ROOT $realpath_root'
                        - 'APP_ENV prod'
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        vhost1:
            servername: awesome.test
            serveraliases:
                - www.awesome.test
            docroot: /var/www/awesome
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                php_html:
                    provider: directory
                    path: /var/www/awesome
                    directoryindex: 'index.php index.html'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                php_php:
                    provider: filesmatch
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
letsencrypt:
    install: '1'
    settings:
        email: ''
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.2'
    modules:
        php:
            - cli
            - intl
            - xml
            - curl
            - mcrypt
            - dom
            - imagick
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        upload_max_filesize: 16M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        pool1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
wpcli:
    install: '0'
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        ruby1:
            default: '1'
            bundler: '1'
            version: '2.4'
            gems:
                - deep_merge@1.2.1
                - activesupport@5.1.4
                - vine@0.4
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '6'
    npm_packages: {  }
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    users:
        user1:
            name: dbuser
            password: '123'
    databases:
        database1:
            name: dbname
            collate: utf8_general_ci
            sql: ''
    grants:
        grant1:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    users:
        user1:
            name: dbuser
            password: '123'
    databases:
        database1:
            name: dbname
            collate: utf8_general_ci
            sql: ''
    grants:
        grant1:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases:
        database1:
            dbname: travelsite
            owner: travelsite
    users:
        user1:
            username: travelsite
            password: '123'
    grants:
        grant1:
            role: travelsite
            db: travelsite
            privilege:
                - ALL
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 3.6.2
    databases:
        database1:
            name: dbname
            user: dbuser
            password: '123'
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases:
        database1:
            name: dbname
            owner: www-data
            group: www-data
            sql_file: ''
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users:
        user1:
            admin: '1'
            name: admin
            password: '123'
            tags:
                - admin
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 6.1.2
        java_install: true
    instances:
        instance1:
            name: es-01
            jvm_options:
                - '-Xms2G'
                - '-Xmx2G'
```

**Comment by ShadeDream** [comment]
I ran into this issue as well and it seems to be specific to having vagrant 2.0.4 installed (it does not occur with 2.0.3 or earlier).

I'm not sure of the root cause, but I was able to work around the issue by creating the directory manually by connecting via SSH and running `sudo mkdir -p /etc/puppetlabs/facter/facts.d/`. Once you've done that you should be able to run `vagrant provision` and get it going.

**Comment by mkhabelaj** [comment]
@ShadeDream Thanks your comment was helpful.

**Comment by dmirkitanov** [comment]
Thanks Nicholas, the workaround works! Haven't tried to run it on 2.0.3, but it could be because of some recent changes in the puppet itself..

**Comment by Hlsgs** [comment]
Apparently, this is a Vagrant 2.0.4 regression that is fixable by setting `structured_facts = nil` in the provisioner configuration:
https://github.com/hashicorp/vagrant/issues/9718

How does one do that with PuPHPet?

**Comment by LMulvey** [comment]
@Hlsgs — in your `./puphpet/config.yaml`, find the section for `provision` around line 33 and add this line below `puppet:` :
```
structured_facts: nil
```

Make sure that your indenting and everything matches. It should roughly like this when done:

```
    provision:
            puppet:
                structured_facts: nil
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
```

This fixed it for me and I was able to complete the provisioning process.
