### ISSUE TITLE
macOS NFS timeout

### ISSUE THREAD

**Issue by SebTM** [puphpet/puphpet#2793]
Hello,

I'm trying to use a generated project by PuPHPet. I tried to use NFS for performance reason but it times out on provisioning without and with "vagrant-bindfs" plugin.

macOS 10.13.4
Vagrant 2.1.1
Virtualbox 5.2.12

Did "vagrant destroy" between each tests and deleted ".vagrant" in project-dir (every time)/".vagrant.d" in home-dir (before without plugins, and with "vagrant-bindfs" only - see output for details) before running "vagrant up again"

I've replaced some personal informations like project-name ("PROJECT") and personal username ("USER") with the values afterwards so this should be fine.

Without any plugins:

> Bringing machine 'PROJECT' up with 'virtualbox' provider...
> ==> PROJECT: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
>     PROJECT: Box Provider: virtualbox
>     PROJECT: Box Version: >= 0
> ==> PROJECT: Loading metadata for box 'bento/ubuntu-16.04'
>     PROJECT: URL: https://vagrantcloud.com/bento/ubuntu-16.04
> ==> PROJECT: Adding box 'bento/ubuntu-16.04' (v201803.24.0) for provider: virtualbox
>     PROJECT: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201803.24.0/providers/virtualbox.box
> ==> PROJECT: Box download is resuming from prior download progress
> ==> PROJECT: Successfully added box 'bento/ubuntu-16.04' (v201803.24.0) for 'virtualbox'!
> ==> PROJECT: Importing base box 'bento/ubuntu-16.04'...
> ==> PROJECT: Matching MAC address for NAT networking...
> ==> PROJECT: Checking if box 'bento/ubuntu-16.04' is up to date...
> ==> PROJECT: Setting the name of the VM: vagrantbox_PROJECT_1527899107608_5482
> Vagrant is currently configured to create VirtualBox synced folders with
> the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
> guest is not trusted, you may want to disable this option. For more
> information on this option, please refer to the VirtualBox manual:
> 
>   https://www.virtualbox.org/manual/ch04.html#sharedfolders
> 
> This option can be disabled globally with an environment variable:
> 
>   VAGRANT_DISABLE_VBOXSYMLINKCREATE=1
> 
> or on a per folder basis within the Vagrantfile:
> 
>   config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
> ==> PROJECT: Clearing any previously set network interfaces...
> ==> PROJECT: Preparing network interfaces based on configuration...
>     PROJECT: Adapter 1: nat
>     PROJECT: Adapter 2: hostonly
> ==> PROJECT: Forwarding ports...
>     PROJECT: 22 (guest) => 2222 (host) (adapter 1)
> ==> PROJECT: Running 'pre-boot' VM customizations...
> ==> PROJECT: Booting VM...
> ==> PROJECT: Waiting for machine to boot. This may take a few minutes...
>     PROJECT: SSH address: 127.0.0.1:2222
>     PROJECT: SSH username: vagrant
>     PROJECT: SSH auth method: private key
> ==> PROJECT: Machine booted and ready!
> ==> PROJECT: Checking for guest additions in VM...
> ==> PROJECT: Setting hostname...
> ==> PROJECT: Configuring and enabling network interfaces...
> ==> PROJECT: Exporting NFS shared folders...
> ==> PROJECT: Preparing to edit /etc/exports. Administrator privileges will be required...
> ==> PROJECT: Mounting NFS shared folders...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> mount -o vers=3,udp 192.168.100.1:/Users/USER/Projects/PROJECT/PROJECT /var/www/PROJECT
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> mount.nfs: Connection timed outv

With "vagrant-bindfs":
> Bringing machine 'PROJECT' up with 'virtualbox' provider...
> ==> PROJECT: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
>     PROJECT: Box Provider: virtualbox
>     PROJECT: Box Version: >= 0
> ==> PROJECT: Loading metadata for box 'bento/ubuntu-16.04'
>     PROJECT: URL: https://vagrantcloud.com/bento/ubuntu-16.04
> ==> PROJECT: Adding box 'bento/ubuntu-16.04' (v201803.24.0) for provider: virtualbox
>     PROJECT: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201803.24.0/providers/virtualbox.box
> ==> PROJECT: Successfully added box 'bento/ubuntu-16.04' (v201803.24.0) for 'virtualbox'!
> ==> PROJECT: Importing base box 'bento/ubuntu-16.04'...
> ==> PROJECT: Matching MAC address for NAT networking...
> ==> PROJECT: Checking if box 'bento/ubuntu-16.04' is up to date...
> ==> PROJECT: Setting the name of the VM: vagrantbox_PROJECT_1527899858507_70351
> Vagrant is currently configured to create VirtualBox synced folders with
> the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
> guest is not trusted, you may want to disable this option. For more
> information on this option, please refer to the VirtualBox manual:
> 
>   https://www.virtualbox.org/manual/ch04.html#sharedfolders
> 
> This option can be disabled globally with an environment variable:
> 
>   VAGRANT_DISABLE_VBOXSYMLINKCREATE=1
> 
> or on a per folder basis within the Vagrantfile:
> 
>   config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
> ==> PROJECT: Clearing any previously set network interfaces...
> ==> PROJECT: Preparing network interfaces based on configuration...
>     PROJECT: Adapter 1: nat
>     PROJECT: Adapter 2: hostonly
> ==> PROJECT: Forwarding ports...
>     PROJECT: 22 (guest) => 2222 (host) (adapter 1)
> ==> PROJECT: Running 'pre-boot' VM customizations...
> ==> PROJECT: Booting VM...
> ==> PROJECT: Waiting for machine to boot. This may take a few minutes...
>     PROJECT: SSH address: 127.0.0.1:2222
>     PROJECT: SSH username: vagrant
>     PROJECT: SSH auth method: private key
> ==> PROJECT: Machine booted and ready!
> ==> PROJECT: Checking for guest additions in VM...
> ==> PROJECT: Setting hostname...
> ==> PROJECT: Configuring and enabling network interfaces...
> ==> PROJECT: Exporting NFS shared folders...
> ==> PROJECT: Preparing to edit /etc/exports. Administrator privileges will be required...
> ==> PROJECT: Mounting NFS shared folders...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> mount -o vers=3,udp 192.168.100.1:/Users/USER/Projects/PROJECT/PROJECT /mnt/vagrant-folder1
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> mount.nfs: Connection timed out

_(Tested this to ensure that there are no cross-incompatibilities with my plugins)_
With "vagrant-cachier", "vagrant-vbguest" - without "vagrant-bindfs":

> Bringing machine 'PROJECT' up with 'virtualbox' provider...
> ==> PROJECT: Importing base box 'bento/ubuntu-16.04'...
> ==> PROJECT: Matching MAC address for NAT networking...
> ==> PROJECT: Checking if box 'bento/ubuntu-16.04' is up to date...
> ==> PROJECT: Setting the name of the VM: vagrantbox_PROJECT_1527897756816_50257
> ==> PROJECT: Clearing any previously set network interfaces...
> ==> PROJECT: Preparing network interfaces based on configuration...
>     PROJECT: Adapter 1: nat
>     PROJECT: Adapter 2: hostonly
> ==> PROJECT: Forwarding ports...
>     PROJECT: 22 (guest) => 2222 (host) (adapter 1)
> ==> PROJECT: Running 'pre-boot' VM customizations...
> ==> PROJECT: Booting VM...
> ==> PROJECT: Waiting for machine to boot. This may take a few minutes...
>     PROJECT: SSH address: 127.0.0.1:2222
>     PROJECT: SSH username: vagrant
>     PROJECT: SSH auth method: private key
> ==> PROJECT: Machine booted and ready!
> [PROJECT] GuestAdditions versions on your host (5.2.12) and guest (5.2.6) do not match.
> Reading package lists...
> Building dependency tree...
> Reading state information...
> dkms is already the newest version (2.2.0.3-2ubuntu11.5).
> The following NEW packages will be installed:
>   linux-headers-4.4.0-87 linux-headers-4.4.0-87-generic
> 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
> Need to get 10.7 MB of archives.
> After this operation, 78.0 MB of additional disk space will be used.
> Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 linux-headers-4.4.0-87 all 4.4.0-87.110 [9,892 kB]
> Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 linux-headers-4.4.0-87-generic amd64 4.4.0-87.110 [785 kB]
> dpkg-preconfigure: unable to re-open stdin: No such file or directory
> Fetched 10.7 MB in 2s (5,085 kB/s)
> Selecting previously unselected package linux-headers-4.4.0-87.
> (Reading database ... 38180 files and directories currently installed.)
> Preparing to unpack .../linux-headers-4.4.0-87_4.4.0-87.110_all.deb ...
> Unpacking linux-headers-4.4.0-87 (4.4.0-87.110) ...
> Selecting previously unselected package linux-headers-4.4.0-87-generic.
> Preparing to unpack .../linux-headers-4.4.0-87-generic_4.4.0-87.110_amd64.deb ...
> Unpacking linux-headers-4.4.0-87-generic (4.4.0-87.110) ...
> Setting up linux-headers-4.4.0-87 (4.4.0-87.110) ...
> Setting up linux-headers-4.4.0-87-generic (4.4.0-87.110) ...
> Examining /etc/kernel/header_postinst.d.
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.4.0-87-generic /boot/vmlinuz-4.4.0-87-generic
> Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
> Mounting Virtualbox Guest Additions ISO to: /mnt
> mount: /dev/loop0 is write-protected, mounting read-only
> Installing Virtualbox Guest Additions 5.2.12 - guest version is 5.2.6
> Verifying archive integrity... All good.
> Uncompressing VirtualBox 5.2.12 Guest Additions for Linux........
> VirtualBox Guest Additions installer
> Removing installed version 5.2.6 of VirtualBox Guest Additions...
> Copying additional installer modules ...
> Installing additional modules ...
> VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
> VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
> VirtualBox Guest Additions: Starting.
> An error occurred during installation of VirtualBox Guest Additions 5.2.12. Some functionality may not work as intended.
> In most cases it is OK that the "Window System drivers" installation failed.
> Unmounting Virtualbox Guest Additions ISO from: /mnt
> ==> PROJECT: Checking for guest additions in VM...
> ==> PROJECT: Setting hostname...
> ==> PROJECT: Configuring and enabling network interfaces...
> ==> PROJECT: Exporting NFS shared folders...
> ==> PROJECT: Preparing to edit /etc/exports. Administrator privileges will be required...
> ==> PROJECT: Mounting NFS shared folders...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> mount -o vers=3,udp 192.168.100.1:/Users/USER/Projects/PROJECT/PROJECT /var/www/PROJECT
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> mount.nfs: Connection timed out

_(Tested this to ensure that there are no cross-incompatibilities with my plugins)_
With "vagrant-cachier", "vagrant-vbguest", "vagrant-bindfs":

> Bringing machine 'PROJECT' up with 'virtualbox' provider...
> ==> PROJECT: Importing base box 'bento/ubuntu-16.04'...
> ==> PROJECT: Matching MAC address for NAT networking...
> ==> PROJECT: Checking if box 'bento/ubuntu-16.04' is up to date...
> ==> PROJECT: Setting the name of the VM: vagrantbox_PROJECT_1527898363310_13582
> ==> PROJECT: Clearing any previously set network interfaces...
> ==> PROJECT: Preparing network interfaces based on configuration...
>     PROJECT: Adapter 1: nat
>     PROJECT: Adapter 2: hostonly
> ==> PROJECT: Forwarding ports...
>     PROJECT: 22 (guest) => 2222 (host) (adapter 1)
> ==> PROJECT: Running 'pre-boot' VM customizations...
> ==> PROJECT: Booting VM...
> ==> PROJECT: Waiting for machine to boot. This may take a few minutes...
>     PROJECT: SSH address: 127.0.0.1:2222
>     PROJECT: SSH username: vagrant
>     PROJECT: SSH auth method: private key
> ==> PROJECT: Machine booted and ready!
> [PROJECT] GuestAdditions versions on your host (5.2.12) and guest (5.2.6) do not match.
> Reading package lists...
> Building dependency tree...
> Reading state information...
> dkms is already the newest version (2.2.0.3-2ubuntu11.5).
> The following NEW packages will be installed:
>   linux-headers-4.4.0-87 linux-headers-4.4.0-87-generic
> 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
> Need to get 10.7 MB of archives.
> After this operation, 78.0 MB of additional disk space will be used.
> Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 linux-headers-4.4.0-87 all 4.4.0-87.110 [9,892 kB]
> Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 linux-headers-4.4.0-87-generic amd64 4.4.0-87.110 [785 kB]
> dpkg-preconfigure: unable to re-open stdin: No such file or directory
> Fetched 10.7 MB in 2s (5,088 kB/s)
> Selecting previously unselected package linux-headers-4.4.0-87.
> (Reading database ... 38180 files and directories currently installed.)
> Preparing to unpack .../linux-headers-4.4.0-87_4.4.0-87.110_all.deb ...
> Unpacking linux-headers-4.4.0-87 (4.4.0-87.110) ...
> Selecting previously unselected package linux-headers-4.4.0-87-generic.
> Preparing to unpack .../linux-headers-4.4.0-87-generic_4.4.0-87.110_amd64.deb ...
> Unpacking linux-headers-4.4.0-87-generic (4.4.0-87.110) ...
> Setting up linux-headers-4.4.0-87 (4.4.0-87.110) ...
> Setting up linux-headers-4.4.0-87-generic (4.4.0-87.110) ...
> Examining /etc/kernel/header_postinst.d.
> run-parts: executing /etc/kernel/header_postinst.d/dkms 4.4.0-87-generic /boot/vmlinuz-4.4.0-87-generic
> Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
> Mounting Virtualbox Guest Additions ISO to: /mnt
> mount: /dev/loop0 is write-protected, mounting read-only
> Installing Virtualbox Guest Additions 5.2.12 - guest version is 5.2.6
> Verifying archive integrity... All good.
> Uncompressing VirtualBox 5.2.12 Guest Additions for Linux........
> VirtualBox Guest Additions installer
> Removing installed version 5.2.6 of VirtualBox Guest Additions...
> Copying additional installer modules ...
> Installing additional modules ...
> VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
> VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
> VirtualBox Guest Additions: Starting.
> An error occurred during installation of VirtualBox Guest Additions 5.2.12. Some functionality may not work as intended.
> In most cases it is OK that the "Window System drivers" installation failed.
> Unmounting Virtualbox Guest Additions ISO from: /mnt
> ==> PROJECT: Checking for guest additions in VM...
> ==> PROJECT: Setting hostname...
> ==> PROJECT: Configuring and enabling network interfaces...
> ==> PROJECT: Exporting NFS shared folders...
> ==> PROJECT: Preparing to edit /etc/exports. Administrator privileges will be required...
> ==> PROJECT: Mounting NFS shared folders...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> mount -o vers=3,udp 192.168.100.1:/Users/USER/Projects/PROJECT/PROJECT /mnt/vagrant-folder1
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> mount.nfs: Connection timed out

config.yaml:
```
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: bento/ubuntu-16.04
                box_url: 'false'
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    machine1:
                        id: PROJECT
                        hostname: PROJECT.local
                        network:
                            private_network: 192.168.100.65
                        memory: '2048'
                        cpus: '2'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
        synced_folder:
            folder1:
                owner: vagrant
                group: vagrant
                source: ../PROJECT
                target: /var/www/PROJECT/
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - bash-completion
        - htop
        - vim
        - zip
        - unzip
        - tar
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - de_DE.UTF-8
        timezone: Europe/Berlin
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        vhost1:
            server_name: PROJECT.local
            www_root: /var/www/PROJECT/public/
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                sf4_base_OBZ:
                    www_root: /var/www/PROJECT/public
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    index_files:
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                sf4_index_OBZ:
                    www_root: /var/www/PROJECT/public
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
                        - 'DOCUMENT_ROOT $realpath_root'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        vhost1:
            servername: awesome.test
            serveraliases:
                - www.awesome.test
            docroot: /var/www/awesome
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                php_html:
                    provider: directory
                    path: /var/www/awesome
                    directoryindex: 'index.php index.html'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                php_php:
                    provider: filesmatch
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
letsencrypt:
    install: '1'
    settings:
        email: ''
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.2'
    modules:
        php:
            - cli
            - intl
            - xml
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Berlin
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        pool1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: vagrant
                group: vagrant
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
wpcli:
    install: '0'
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '8'
    npm_packages: {  }
mariadb:
    install: '1'
    settings:
        version: '10.2'
        root_password: root
        override_options: {  }
    users:
        user1:
            name: PROJECT
            password: PROJECT
    databases:
        database1:
            name: PROJECT
            collate: utf8_general_ci
            sql: ''
    grants:
        grant1:
            user: PROJECT
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.7'
        root_password: '123'
        override_options: {  }
    users:
        user1:
            name: dbuser
            password: '123'
    databases:
        database1:
            name: dbname
            collate: utf8_general_ci
            sql: ''
    grants:
        grant1:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases:
        database1:
            dbname: dbname
            owner: dbuser
    users:
        user1:
            username: dbuser
            password: '123'
            superuser: '1'
    grants:
        grant1:
            role: dbuser
            db: dbname
            privilege:
                - ALL
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 3.6.2
    databases:
        database1:
            name: dbname
            user: dbuser
            password: '123'
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases:
        database1:
            name: dbname
            owner: www-data
            group: www-data
            sql_file: ''
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    users:
        user1:
            admin: '1'
            name: admin
            password: admin
            tags:
                - admin
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 6.1.2
        java_install: true
    instances:
        instance1:
            name: es-01
            jvm_options:
                - '-Xms2G'
                - '-Xmx2G'
```

Would be nice if you have an idea how I can solve this :)
