### ISSUE TITLE
Incorrect escaping of variables

### ISSUE THREAD

**Issue by dmromanov** [puphpet/puphpet#2794]
I have added the following Conf Setting to PHP FPM Pool `env["DEBUG"]="true"`.
But in the resulting `config.yaml` the variable is incorrectly escaped resulting in failed vagrant provision.

Expected
```yaml
    fpm_pools:
        pool1:
            ini:
                'env["DEBUG"]': '"true"'
```

Result
```yaml
    fpm_pools:
        pool1:
            ini:
                'env["DEBUG"': '"true"'
```
Notice a missing square bracket.
