### ISSUE TITLE
Apache file write issues

### ISSUE THREAD

**Issue by Ruud-Zuiderlicht** [puphpet/puphpet#2799]
I'm creating a new VM based on the newer bento boxes. However apache is not allowed write access to the synced folders (on Windows; `sync_type: default` and `owner: vagrant`). I checked write access using `is_writable($path)`. So I changed both owner and group to `www-data` and provisioned. After this everything worked again as expected.

Now after `vagrant destroy`, followed by `vagrant up` I receive the following error:

```
==> mosa.vagrant: Machine booted and ready!
==> mosa.vagrant: Checking for guest additions in VM...
==> mosa.vagrant: Setting hostname...
==> mosa.vagrant: Configuring and enabling network interfaces...
    mosa.vagrant: SSH address: 127.0.0.1:2222
    mosa.vagrant: SSH username: vagrant
    mosa.vagrant: SSH auth method: private key
==> mosa.vagrant: Mounting shared folders...
    mosa.vagrant: /vagrant => E:/my_website
    mosa.vagrant: /var/www/my_website => E:/my_website
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

id -u www-data

The error output from the command was:

id: www-data: no such user
```

I could set user and group of apache to vagrant, but **what is the correct way to get write access?** And why isn't this working out of the box?

_I also noticed that fpm_pools is the only setting using www-user._

My config (I left out details for non-installed sections):
```yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: bento/centos-7
                box_url: 'false'
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    machine1:
                        id: mywebsite.vagrant
                        hostname: mywebsite.vagrant.puphpet
                        network:
                            private_network: 192.168.56.99
                            forwarded_port:
                                port1:
                                    host: '9099'
                                    guest: '22'
                        memory: '1024'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
        synced_folder:
            folder1:
                owner: vagrant
                group: vagrant
                source: ./
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - bash-completion
        - htop
        - vim
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
            - nl_NL.UTF-8
        timezone: Europe/Amsterdam
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: false
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - headers
        - deflate
        - expires
    vhosts:
        vhost1:
            servername: my.website
            docroot: /var/www/public
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                php_html:
                    provider: directory
                    path: /var/www
                    directoryindex: 'index.php index.html'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                php_php:
                    provider: filesmatch
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
letsencrypt:
    install: '0'
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - xml
            - gd
            - curl
            - mbstring
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: Europe/Amsterdam
        max_execution_time: 30
        max_file_uploads: 20
        max_input_nesting_level: 64
        max_input_time: 60
        max_input_vars: 1000
        memory_limit: '128M'
        output_buffering: 4096
        post_max_size: '50M'
        short_open_tag: 'Off'
        upload_max_filesize: '50M'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        pool1:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
wpcli:
    install: '0'
drush:
    install: '0'
ruby:
    install: '1'
    versions:
        ruby1:
            default: '1'
            bundler: '1'
            version: '2.4'
            gems:
                - deep_merge@1.2.1
                - activesupport@5.1.4
                - vine@0.4
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options:
            mysqld:
                max_allowed_packet: 32M
    users:
        user1:
            name: vagrant_db_user
            password: '123'
    databases:
        database1:
            name: my_website
            collate: utf8_general_ci
            sql: /vagrant/my_website.sql
    grants:
        grant1:
            user: vagrant_db_user
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
postgresql:
    install: '0'
mongodb:
    install: '0'
redis:
    install: '0'
sqlite:
    install: '0'
mailhog:
    install: '0'
beanstalkd:
    install: '0'
rabbitmq:
    install: '0'
elastic_search:
    install: '0'
```
