### ISSUE TITLE
Prestashop 1.7 and Nginx

### ISSUE THREAD

**Issue by kl3sk** [puphpet/puphpet#2801]
Hi evreyone,

Does someone have a fully working vhost on nginx with Prestashop 1.7
I don't have something working.

thx

**Comment by kl3sk** [comment]
I found something working, here is my config, only ngix vhost part
change the required dns and folder to your needs
update the [admin-folder] name.

Any improvments are welcome

```yml
my_vhost:
    server_name: my-dns.local
    server_aliases:
        - www.my-dns.local
    www_root: /var/www/my-folder
    listen_port: '80'
    client_max_body_size: 1m
    ssl: '0'
    index_files:
        - index.php
    spdy: '0'
    vhost_cfg_append:
        error_page:
            - '404 /index.php?controller=404'
            - '403 /index.php?controller=404'
        add_header:
            - 'Strict-Transport-Security max-age=31536000'
    locations:
        nxvl_admin:
            location: '~ /(international|_profiler|module|product|feature|attribute|supplier|combination|specific-price|configure)/(.*)$'
            try_files:
                - $uri
                - $uri/
                - /index.php?q=$uri&$args
                - /[admin-folder]/index.php$is_args$args
        nxvl_rw:
            location: /
            try_files:
                - $uri
                - $uri/
                - /index.php$uri&$args
            rewrites:
                rewrite_5bg:
                    when: '!-e $request_filename'
                    regex: '^/[a-zA-Z][a-zA-Z]/(index\.php.*)$'
                    target: '/$1 last'
                rewrite_6hc:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: '/img/p/$1/$1$2$3.jpg last'
                rewrite_1ih:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: '/img/p/$1/$2/$1$2$3$4.jpg last'
                rewrite_idb:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: '/img/p/$1/$2/$3/$1$2$3$4$5.jpg last'
                rewrite_43t:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: '/img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last'
                rewrite_qc6:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg
                rewrite_kk4:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: '/img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last'
                rewrite_lt6:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: '/img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last'
                rewrite_f3g:
                    when: '!-e $request_filename'
                    regex: '^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$'
                    target: '/img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last'
                rewrite_lqs:
                    when: '!-e $request_filename'
                    regex: '^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$'
                    target: '/img/c/$1$2$3.jpg last'
                rewrite_j3r:
                    when: '!-e $request_filename'
                    regex: '^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$'
                    target: '/img/c/$1$2.jpg last'
                rewrite_7wk:
                    when: '!-e $request_filename'
                    regex: '^images_ie/?([^/]+)\.(jpe?g|png|gif)$'
                    target: 'js/jquery/plugins/fancybox/images/$1.$2 last'
                rewrite_fw5:
                    when: '!-e $request_filename'
                    regex: '^/api/?(.*)$'
                    target: '/webservice/dispatcher.php?url=$1 last'
                rewrite_j54:
                    when: '!-e $request_filename'
                    regex: '^(/install(?:-dev)?/sandbox)/(.*)'
                    target: '/$1/test.php last'
        nxvl_rewrite_adm:
            rewrites:
                if_exists:
                    when: '!-e $request_filename'
                    regex: '^/.*$'
                    target: '/index.php last'
        nxvl_favicon:
            location: '= /favicon.ico'
            location_cfg_append:
                - 'log_not_found off'
                - 'access_log off'
        nxvl_robots:
            location: '= /robots.txt'
            location_cfg_append:
                - 'auth_basic off'
                - 'allow all'
                - 'log_not_found off'
                - 'access_log off'
        nxvl_deny:
            location: '~/\.'
            location_cfg_append:
                - 'deny all'
                - 'log_not_found off'
                - 'access_log off'
        nxvl_deny2:
            location: '~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor)/'
            location_cfg_append:
                - 'deny all'
                - 'log_not_found off'
                - 'access_log off'
        nxvl_3laa389rmmtd:
            www_root: ''
            location: '~ [^/]\.php(/|$)'
            try_files:
                - $uri
                - $uri/
                - /index.php$is_args$args
            fastcgi: '127.0.0.1:9000'
            fastcgi_index: index.php
            fastcgi_split_path: '^(.+\.php)(/.*)$'
            fast_cgi_params_extra:
                - 'SCRIPT_FILENAME $request_filename'
                - 'APP_ENV dev'
            set:
                - '$path_info $fastcgi_path_info'
            proxy: ''
            proxy_redirect: ''
```
