### ISSUE TITLE
Ubuntu provision stops when chown a vhost directory on an NFS shared folder

### ISSUE THREAD

**Issue by vikenbauer** [puphpet/puphpet#2813]
On an ubuntu 16.04 box, I've shared /var/www with NFS. In config.yaml, I've changed user and group to  be www-data. Shared folder config looks like
```
            folder1:
                owner: www-data
                group: www-data
                source: ./apache01/data
                target: /var/www
                sync_type: nfs
```
Apache config includes a vhost on directory /var/www/test.

Then, provisioning stops when executes chown /var/www/test after creation. Failed command is
`mkdir -p /var/www/test && chown www-data:www-data /var/www/test`
and fails because, as created, this directory is already owned by www-data, so chown to same user fails.

As a workaround, before provisioning I create all vhosts directories in shared folders, but this should be changed to check if this directory is already owned by the user who is going to be in chown command.
