### ISSUE TITLE
nginx set variables does not correctly render multiple key-value pairs

### ISSUE THREAD

**Issue by tetele** [puphpet/puphpet#2817]
For a certain vhost, I have defined multiple key-value set variable pairs. Here's the relevant part:

```
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        vhost1:
            server_name: test.local
            www_root: '/var/www'
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                php_html:
                    www_root: /var/www/public
                    location: /test/
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - '@sfRewrite'
                    rewrites:
                        rewrite_3iv:
                            when: ''
                            regex: '^/test/(.*)$'
                            target: /$1
                php_php:
                    www_root: ''
                    location: '@sfRewrite'
                    autoindex: 'off'
                    internal: 'false'
                    set:
                        - '$path_info $fastcgi_path_info'
                        - '$sfRoot /var/www/public'
                        - '$sfApp index.php'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $sfRoot/$sfApp'
                        - 'SCRIPT_NAME /test/$sfApp'
                        - 'REQUEST_URI /test$uri?$args'
```

This config causes provisioning to fail because
```
==> test: Notice: /Stage[main]/Nginx/Anchor[nginx::end]: Dependency Service[nginx] has failures: true
==> test: Error: Systemd start for nginx failed!
==> test: journalctl log for nginx:
==> test: -- Logs begin at Tue 2018-10-02 11:33:10 UTC, end at Tue 2018-10-02 11:59:34 UTC. --
==> test: Oct 02 11:59:34 test systemd[1]: Starting nginx - high performance web server...
==> test: Oct 02 11:59:34 test nginx[13762]: nginx: [emerg] invalid number of arguments in "set" directive in /etc/nginx/sites-enabled/vhost1.conf:25
==> test: Oct 02 11:59:34 test systemd[1]: nginx.service: Control process exited, code=exited status=1
==> test: Oct 02 11:59:34 test systemd[1]: Failed to start nginx - high performance web server.
==> test: Oct 02 11:59:34 test systemd[1]: nginx.service: Unit entered failed state.
==> test: Oct 02 11:59:34 test systemd[1]: nginx.service: Failed with result 'exit-code'.
```

I've looked into the vhost config and it looks like this:
```
 server {
   listen                *:80;

   server_name           test.local ;
   client_max_body_size 1m;

   root /var/www;
     index  index.html index.htm index.php;

   access_log            /var/log/nginx/vhost1.access.log;
   error_log             /var/log/nginx/vhost1.error.log;
   location /test/ {

     rewrite ^/test/(.*)$ /$1;

     root  /var/www/public;
     try_files $uri @sfRewrite;
      autoindex off;


   }
   location @sfRewrite {


     set $path_info $fastcgi_path_info $sfRoot /var/www/public $sfApp index.php;
     root  /var/www;
     include /etc/nginx/fastcgi_params;
     fastcgi_pass 127.0.0.1:9000;

     fastcgi_param SCRIPT_FILENAME $sfRoot/$sfApp;
     fastcgi_param SCRIPT_NAME /test/$sfApp;
     fastcgi_param REQUEST_URI /test$uri?$args;

   }
   sendfile off;
 }
```

Notice the `set` directive in `location @sfRewrite`:
```
set $path_info $fastcgi_path_info $sfRoot /var/www/public $sfApp index.php;
```

Basically, the array of `set` pairs in `config.yaml` puts all key-value pairs in a single `set` directive in the resulting vhost's config file.
