### ISSUE TITLE
Make config.yaml keys optional for items that are not installed (feature request)

### ISSUE THREAD

**Issue by czukowski** [puphpet/puphpet#2820]
Is it possible for provisioning to work when config keys are omitted for modules that are not being installed?

I often find myself tweaking config.yaml manually after generating it and I feel like there is a lot of information taking space that is not used. I think the ability to make the config smaller and containing only the necessary keys would make it much easier to find and fix issues with the configuration and share it with teammates.

It seems that I can already safely omit config keys for many modules, but there are a few I've had to keep at some bare minimum:

PHP:

```yaml
php:
    install: '0'
    settings:
        version:
```

MySQL:

```yaml
mysql:
    install: '0'
    settings: {  }
```

I'm not asking for the generator to produce more compact config (although that would be great, I realize it may require a lot of work), just that the puppet modules would not insist on having any config if it's not going to be used.
