### ISSUE TITLE
Wildcard subdomains

### ISSUE THREAD

**Issue by Hlsgs** [puphpet/puphpet#2825]
I'm trying to setup wildcard subdomains and they are not working, though i have enabled vhost_alias. The net result is a directory listing of `/var/www/dev/`, regardless of whitch subdomain i try.

Here are the vhosts rules:
```
    vhosts:
        vhost_nossl_1:
            servername: 192.168.2.10.xip.io
            serveraliases:
                - '*.192.168.2.10.xip.io'
            docroot: /var/www/dev/
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                wordpress_fm_NBF1:
                    provider: filesmatch
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
                    setenv:
                        - 'APP_ENV dev'
                wordpress_dir_NBF1:
                    provider: directory
                    path: /var/www/dev/
                    directoryindex: index.php
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
```

The idea is to get folders like `/var/www/dev/FOLDER` to act as subdomains `FOLDER.192.168.2.10.xip.io`, as this rule would do:

```
<Directory "/var/www/dev/">
	    Options Indexes FollowSymLinks MultiViews
	    AllowOverride All
	    Require all granted
</Directory>
<VirtualHost *:80>
       ServerAlias *.192.168.2.10.xip.io
       VirtualDocumentRoot "/var/www/dev/%1/"
</VirtualHost>
```
