### ISSUE TITLE
Xdebug - remote ip address is wrong

### ISSUE THREAD

**Issue by LimeBlast** [puphpet/puphpet#284]
Hi, having some trouble getting xdebug to work. I've stuck with the default settings provided by puphpet, i.e.

```
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
```

Which all look fine, and I've set-up PHPStorm correctly - but anytime I send a debug request, it just times out.

I _think_ this is related to the fact that php seems to think that my IP address (i.e. the `_SERVER["REMOTE_ADDR"]` value) is `192.168.56.1`.

This appears to be the IP address being assigned by the Virtual Box Host-Only Ethernet Adaptor (seen below)

![network](https://f.cloud.github.com/assets/219206/1525787/9f5cc592-4bda-11e3-92a0-9aa29dc01904.png)

although I've used virtualbox machines and it's never used this one for anything before (and, near as I can tell, seems to be the thing preventing xdebug from connecting to PHPStorm.

Any ideas?
