### ISSUE TITLE
elasticsearch version is wrong

### ISSUE THREAD

**Issue by maxttor** [puphpet/puphpet#2843]
The version is specified in the config - 2.4.6:
```
elastic_search:
    install: '1'
    settings:
        version: 2.4.6
        java_install: true
    instances:
        esi_5ifks6jqar3w:
            name: es-01
```
But trying to install version 1.7.2 why?

> ==> smartprogress: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install elasticsearch=1.7.2' returned 100: Reading package lists...
> ==> smartprogress: Building dependency tree...
> ==> smartprogress: Reading state information...
> ==> smartprogress: E: Version '1.7.2' for 'elasticsearch' was not found
> ==> smartprogress: Error: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]/ensure: change from '6.1.2' to '1.7.2' failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install elasticsearch=1.7.2' returned 100: Reading package lists...
> ==> smartprogress: Building dependency tree...
> ==> smartprogress: Reading state information...
> ==> smartprogress: E: Version '1.7.2' for 'elasticsearch' was not found
