### ISSUE TITLE
Mariadb install failed

### ISSUE THREAD

**Issue by maxttor** [puphpet/puphpet#2844]
Config:
```yaml
vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: bento/ubuntu-16.04
                box_url: puphpet/ubuntu1404-x64
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_c3qioxz4n8od:
                        id: smartprogress
                        hostname: smartprogress.loc
                        network:
                            private_network: 192.168.56.101
                        memory: '2048'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_sseumvychpb3:
                owner: www-data
                group: www-data
                source: 'C:\Users\maxxt\Documents\Projects'
                target: /var/www
                sync_type: rsync
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - git
        - mc
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_qy1mbqb57ahc:
            server_name: smartprogress.loc
            www_root: /var/www/smartprogress/smartprogress/
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                nxvl_yjewgg0xyk0n:
                    www_root: /var/www/smartprogress/smartprogress/
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    index_files:
                        - index.html
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                nxvl_dw9qj8yqasv0:
                    www_root: /var/www/smartprogress/smartprogress/
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    index_files:
                        - index.php
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
        nxv_73iblsrsnpnu:
            server_name: katushka.loc
            www_root: /var/www/katushka_net/
            listen_port: '80'
            client_max_body_size: 1m
            ssl: '0'
            locations:
                nxvl_krgp4q0qou0d:
                    www_root: /var/www/katushka_net/
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                nxvl_991lckmh63us:
                    www_root: /var/www/katushka_net/
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    set:
                        - '$path_info $fastcgi_path_info'
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_x6ty80l80gx4:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_kxgeyt8gzdpe:
                    provider: directory
                    path: /var/www/awesome
                    directoryindex: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
letsencrypt:
    install: '1'
    settings:
        email: ''
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.2'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - cgi
            - curl
            - memcache
            - memcached
            - mysql
            - mbstring
            - geoip
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_fre0jjsiaysn:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
wpcli:
    install: '0'
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_5bbkaw1svts3:
            default: '1'
            bundler: '1'
            version: '2.2'
            gems:
                - deep_merge
                - activesupport
                - vine
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
mariadb:
    install: '1'
    settings:
        version: '10.2'
        root_password: '123'
        override_options: {  }
    users:
        mariadbnu_sss5f7abyhad:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_ixlurym0fbsf:
            name: smartprogress
            collate: utf8_general_ci
            sql: ''
    grants:
        mariadbng_xl25qza1tmvk:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    users: {  }
    databases:
        mysqlnd_zzzdpek7rgjx:
            name: smartprogress
            collate: ''
            sql: ''
        mysqlnd_xmqpej23imhg:
            name: katushka
            collate: ''
            sql: ''
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 3.6.2
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 2.4.6
        java_install: true
    instances:
        esi_5ifks6jqar3w:
            name: es-01
```
Ouput logs:
> ==> smartprogress: Error: Could not find a suitable provider for mysql_datadir
> ==> smartprogress: Error: Could not find a suitable provider for rvm_system_ruby
> ==> smartprogress: Error: Could not find a suitable provider for mysql_user
> ==> smartprogress: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
> ==> smartprogress:
> ==> smartprogress: Error: Could not find a suitable provider for rvm_gem
> ==> smartprogress: Error: Could not find a suitable provider for mysql_database
> ==> smartprogress: Notice: Applied catalog in 302.07 seconds
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

[output-logs.txt](https://github.com/puphpet/puphpet/files/3463724/output-logs.txt)

I tried to install different versions, but the result is always the same
