### ISSUE TITLE
rsync auto not work

### ISSUE THREAD

**Issue by maxttor** [puphpet/puphpet#2846]
Config:

```yaml
synced_folder:
            folder1:
                owner: www-user
                group: www-data
                source: 'C:\\Users\\maxxt\\Documents\\Projects'
                target: /var/www
                sync_type: rsync
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
```

But files changes are not visible...
