### ISSUE TITLE
synced_folder: few projects

### ISSUE THREAD

**Issue by maxttor** [puphpet/puphpet#2847]
Try to add two projects to synced_folder:
```
 synced_folder:
            folder1:
                owner: www-user
                group: www-data
                source: 'C:\\Users\\maxxt\\Documents\\Projects\\projects1'
                target: /var/www/project1/
                sync_type: default
            folder2:
                owner: www-user
                group: www-data
                source: 'C:\\Users\\maxxt\\Documents\\Projects\\projects2'
                target: /var/www/project2/
                sync_type: default
```
But after vagrant up got all projects in folder: /var/www (not only projects1 and projects2). Why?
