### ISSUE TITLE
Do not have permissions to write to a file

### ISSUE THREAD

**Issue by edytajordan** [puphpet/puphpet#2851]
Hello,

I am not able to write to a file (any type), do any error logs, etc. None of the things I tried for changing permissions worked. It doesn't work on both Mac or Windows. Not sure what I'm doing wrong.

**Comment by jeromejaglale** [comment]
I was having the same problem. More precisely, I was not able to write into a file in `/var/www`. Writing in `/tmp` was working. I compared the permissions on the folders with a previous install which was working and I noticed that the folder `/var/www` belongs to `www-data` in my previous install and belongs to `vagrant` in the new install. I went into the config.yaml file, changed `vagrant` to `www-data` in this block:

```        
        synced_folder:
            folder1:
                owner: www-data
                group: www-data
                source: ./
                target: /var/www

```

Then it worked as expected.
