### ISSUE TITLE
Random array IDs are not needed

### ISSUE THREAD

**Issue by markushausammann** [puphpet/puphpet#288]
Instead of writing stuff like:

```
    synced_folder:
        CNzCWppMTdmB:
            id: vagrant-root
            source: 'c:/htdocs'
            target: /var/www/vhosts
            nfs: 'false'
```

You can just do

```
    synced_folder:
        -
            id: vagrant-root
            source: 'local/path'
            target: 'remove/path'
            nfs: 'false'
        -
            id: another
            ...
```
