### ISSUE TITLE
Errors on rackspace setup

### ISSUE THREAD

**Issue by phirschybar** [puphpet/puphpet#296]
getting these errors:

```
C:/Users/phirschybar/.vagrant.d/gems/gems/vagrant-rackspace-0.1.4/lib/vagrant-rackspace/action/sync_folders.rb:32:in `block in call': undefined method `downcase' for nil:NilClass (NoMethodError)
        from C:/Users/phirschybar/.vagrant.d/gems/gems/vagrant-rackspace-0.1.4/lib/vagrant-rackspace/action/sync_folders.rb:22:in `each'
        from C:/Users/phirschybar/.vagrant.d/gems/gems/vagrant-rackspace-0.1.4/lib/vagrant-rackspace/action/sync_folders.rb:22:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builtin/provision.rb:54:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/phirschybar/.vagrant.d/gems/gems/vagrant-rackspace-0.1.4/lib/vagrant-rackspace/action/connect_rackspace.rb:40:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:61:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/action/runner.rb:61:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/machine.rb:147:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
```

vagrant file:

```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'rackspace'

Vagrant.configure("2") do |config|
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.username = "benhirsch@gmail.com"

  config.vm.box = "dummy"

  config.vm.hostname = "master"
  config.vm.provider :rackspace do |rs, override|
    rs.username           = "XXXXXXXXXXXXX"
    rs.api_key            = "XXXXXXXXXXXXXXXXXXXXXXXXX"
    rs.flavor             = /1GB/
    rs.image              = "Debian 6.06 (Squeeze)"
    rs.rackspace_region   = "dfw"
    rs.public_key_path    = "~/.ssh/id_rsa.pub"
    rs.server_name        = "canary-space-mine"
    override.ssh.username = "root"
  end

  config.vm.synced_folder "./", "/var/www", id: "webroot"

  config.vm.provision :shell, :path => "shell/initial-setup.sh"
  config.vm.provision :shell, :path => "shell/update-puppet.sh"
  config.vm.provision :shell, :path => "shell/librarian-puppet-vagrant.sh"
  config.vm.provision :puppet do |puppet|
    puppet.facter = {
      "ssh_username" => "benhirsch@gmail.com"
    }

    puppet.manifests_path = "puppet/manifests"
    puppet.options = ["--verbose", "--hiera_config /vagrant/hiera.yaml", "--parser future"]
  end




  config.ssh.shell = "bash -l"

  config.ssh.keep_alive = true
  config.ssh.forward_agent = false
  config.ssh.forward_x11 = false
  config.vagrant.host = :detect
end

```

common.yaml is:

```

---
vagrantfile-rackspace:
    vm:
        box: rackspace
        hostname: master
        provider:
            rackspace:
                server_name: canary-space-mine
                image: 'Debian 6.06 (Squeeze)'
                region: dfw
                size: 1GB
                username: xxxxxxxxxxxxxxxxxxxxxx
                api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        provision:
            puppet:
                manifests_path: puppet/manifests
                options:
                    - --verbose
                    - '--hiera_config /vagrant/hiera.yaml'
                    - '--parser future'
        synced_folder:
            Bgp3OC5pwDt0:
                id: webroot
                source: ./
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        public_key_path: ~/.ssh/id_rsa.pub
        username: benhirsch@gmail.com
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    modules:
        - php
        - rewrite
    vhosts:
        rMvdSCJ1eiJH:
            servername: alpha.localgear.com
            serveraliases:
                - alpha.localgear.com
            docroot: /var/www/localgear
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
php:
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        short_open_tag: on
    timezone: America/Chicago
xdebug:
    install: 0
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
mysql:
    root_password: lapdog
    phpmyadmin: 0
    databases: {  }

```
