### ISSUE TITLE
Issues with running initial librarian-puppet (windows & behind proxy)

### ISSUE THREAD

**Issue by bleepa** [puphpet/puphpet#302]
Hi,

I am using Vagrant 1.3.5 and Virtualbox 4.3.2 on a windows machine that is behind a proxy and getting the following error when running `vagrant up`.
#### Error

```
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'ubuntu-precise12042-x64-vbox43'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /vagrant
[default] -- /var/www
[default] -- /tmp/vagrant-puppet/manifests
[default] Configuring proxy for Apt...
[default] Configuring proxy environment variables...
[default] Running provisioner: shell...
[default] Running: C:/Users/spillai/AppData/Local/Temp/vagrant-shell20131120-111
68-159k7bt
stdin: is not a tty

 ____        ____  _   _ ____      _      generated using
|  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
| |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
|  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
|_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|

Created directory /.puphpet-stuff
Running initial-setup apt-get update
Finished running initial-setup apt-get update
Installing basic curl packages (Ubuntu only)
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Finished installing basic curl packages (Ubuntu only)
[default] Running provisioner: shell...
[default] Running: C:/Users/spillai/AppData/Local/Temp/vagrant-shell20131120-111
68-138zazr
stdin: is not a tty
Downloading http://apt.puppetlabs.com/puppetlabs-release-precise.deb
Finished downloading http://apt.puppetlabs.com/puppetlabs-release-precise.deb
Running update-puppet apt-get update
Finished running update-puppet apt-get update
Updating Puppet to latest version
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Finished updating puppet to latest version: Puppet v3.3.2
Created empty file /.puphpet-stuff/update-puppet
[default] Running provisioner: shell...
[default] Running: C:/Users/spillai/AppData/Local/Temp/vagrant-shell20131120-111
68-s82uvb
stdin: is not a tty
Installing git
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Finished installing git
Copied Puppetfile
Installing base packages for librarian
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Finished installing base packages for librarian
Updating libgemplugin-ruby (Ubuntu only)
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Finished updating libgemplugin-ruby (Ubuntu only)
Installing librarian-puppet
Finished installing librarian-puppet
Running initial librarian-puppet
/var/lib/gems/1.8/gems/librarian-puppet-0.9.10/lib/librarian/puppet/lockfile/par
ser.rb:41:in `parse': Expected DEPENDENCIES topic! (StandardError)
        from /var/lib/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib
/librarian/lockfile.rb:21:in `load'
        from /var/lib/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib
/librarian/action/resolve.rb:31:in `run'
        from /var/lib/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib
/librarian/cli.rb:161:in `resolve!'
        from /var/lib/gems/1.8/gems/librarian-puppet-0.9.10/lib/librarian/puppet
/cli.rb:63:in `install'
        from /var/lib/gems/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `__sen
d__'
        from /var/lib/gems/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.8/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `i
nvoke_command'
        from /var/lib/gems/1.8/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /var/lib/gems/1.8/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /var/lib/gems/1.8/gems/librarian-puppet-0.9.10/vendor/librarian/lib
/librarian/cli.rb:29:in `bin!'
        from /var/lib/gems/1.8/gems/librarian-puppet-0.9.10/bin/librarian-puppet
:9
        from /usr/local/bin/librarian-puppet:19:in `load'
        from /usr/local/bin/librarian-puppet:19
Finished running initial librarian-puppet
[default] Running provisioner: puppet...
Running Puppet with default.pp...
stdin: is not a tty
Warning: Could not retrieve fact fqdn
Error: Could not find class ::ntp for precise64 on node precise64
Error: Could not find class ::ntp for precise64 on node precise64
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

FACTER_ssh_username='vagrant' puppet apply --verbose --hiera_config /vagrant/hie
ra.yaml --parser future --color=false --manifestdir /tmp/vagrant-puppet/manifest
s --detailed-exitcodes /tmp/vagrant-puppet/manifests/default.pp || [ $? -eq 2 ]

Stdout from the command:



Stderr from the command:

stdin: is not a tty
Warning: Could not retrieve fact fqdn
Error: Could not find class ::ntp for precise64 on node precise64
Error: Could not find class ::ntp for precise64 on node precise64
```
#### common.yaml

```

---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'https://puphpet.s3.amazonaws.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                QtVl0bFLMIf9:
                    host: '8080'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    name: hidden-dev
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puppet/manifests
                options:
                    - --verbose
                    - '--hiera_config /vagrant/hiera.yaml'
                    - '--parser future'
        synced_folder:
            eVdwzgb8oEuD:
                id: vagrant-root
                source: ./www
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
nginx:
    vhosts:
        LUzmShs75Gw2:
            server_name: hidden.dev
            server_aliases:
                - www.hidden.dev
            www_root: /var/www
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Australia/Sydney
xdebug:
    install: 0
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
mysql:
    root_password: root
    phpmyadmin: '1'
    databases: {  }
```
#### Vagrantfile

```
Vagrant.configure("2") do |config|

  config.proxy.http     = "ip-hidden"
  config.proxy.https    = "ip-hidden"

  config.vm.box = "ubuntu-precise12042-x64-vbox43"
  config.vm.box_url = "https://puphpet.s3.amazonaws.com/ubuntu-precise12042-x64-vbox43.box"

  config.vm.network "private_network", ip: "192.168.56.101"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder "./www", "/var/www", id: "vagrant-root", :nfs => false

  config.vm.usable_port_range = (2200..2250)
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--name", "hidden-dev"]
    virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    virtualbox.customize ["modifyvm", :id, "--memory", "512"]
    virtualbox.customize ["setextradata", :id, "--VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.vm.provision :shell, :path => "shell/initial-setup.sh"
  config.vm.provision :shell, :path => "shell/update-puppet.sh"
  config.vm.provision :shell, :path => "shell/librarian-puppet-vagrant.sh"
  config.vm.provision :puppet do |puppet|
    puppet.facter = {
      "ssh_username" => "vagrant"
    }

    puppet.manifests_path = "puppet/manifests"
    puppet.options = ["--verbose", "--hiera_config /vagrant/hiera.yaml", "--parser future"]
  end




  config.ssh.username = "vagrant"

  config.ssh.shell = "bash -l"

  config.ssh.keep_alive = true
  config.ssh.forward_agent = false
  config.ssh.forward_x11 = false
  config.vagrant.host = :detect
end

```
