### ISSUE TITLE
Manage npm-packages via common.yaml

### ISSUE THREAD

**Issue by ghost** [puphpet/puphpet#324]
Hi all,

you can manage your npm-packages via the common.yaml.

But be warned,
I only tested on Ubuntu Precise 12.04.
It works but it's not the most elegant solution, as you can run into troubles with the version defined for nodejs. Better have a look at the available version before running `vagrant reload --provision` or `vagrant up` 

To manage your npm packages the following lines to the files below:

**puppet/Puppetfile**

```
mod 'nodejs', :git => 'git://github.com/puppetlabs/puppetlabs-nodejs.git'
```

**default.pp**

```
if $nodejs_values == undef {
    $nodejs_values = hiera('nodejs', false)
}

if count($nodejs_values['version']) > 0 {
    class { 'nodejs': version => $nodejs_values['version'], manage_repo => true }
}

if count($nodejs_values['packages']) > 0 {
  $nodejs_values['packages'].each { |$package, $version|
    package { $package: provider => npm, ensure => $version, require => Package['nodejs'] }
  }
}
```

**common.yaml**

```
nodejs:
    version:
      - 0.10.22-1chl1~precise1
    packages:
      bower: 'latest'
      grunt-cli: 'latest'
      yo: 'latest'
```

This works in a similar way for ruby gems!
See issue below

regards
