### ISSUE TITLE
"SSH connection was refused!" Every. Single. Time. 

### ISSUE THREAD

**Issue by ghost** [puphpet/puphpet#329]
I keep getting this over and over, at the same point of the vagrant up process 

```
generated using
|  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
| |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
|  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
|_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|

Created directory /.puphpet-stuff
Running initial-setup yum update
[default] Running provisioner: shell...
SSH connection was refused! This usually happens if the VM failed to
boot properly. Some steps to try to fix this: First, try reloading your
VM with `vagrant reload`, since a simple restart sometimes fixes things.
If that doesn't work, destroy your VM and recreate it with a `vagrant destroy`
followed by a `vagrant up`. If that doesn't work, contact a Vagrant
maintainer (support channels listed on the website) for more assistance.
```

I've done the reload thing and the destroy/up thing like five times and it keeps doing the same thing every time. 

I didn't do anything outside of the options given on https://puphpet.com/ and I just know this is something really stupid on my end but I am new to this type of stuff so I really don't know what to do or where to look on my computer and Google has not helped me. What things/settings do I need to change to fix this? 

I'm on Mac OS X 10.8.5 and my config is as follows:

```

---
vagrantfile-local:
    vm:
        box: centos64-x64-vbox43-1383512148
        box_url: 'http://box.puphpet.com/centos64-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.102
            forwarded_port:
                0SCvVmfsfpfR:
                    host: ''
                    guest: ''
        provider:
            virtualbox:
                modifyvm:
                    name: liquid
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puppet/manifests
                options:
                    - --verbose
                    - '--hiera_config /vagrant/hiera.yaml'
                    - '--parser future'
        synced_folder:
            Vgt1aYvwL4XF:
                id: vagrant-root
                source: ./
                target: /var/www/public_html
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages:
        - vim-common
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    modules:
        - php
        - rewrite
    vhosts:
        RhrMWHL8vlB7:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/public_html/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
php:
    version: '53'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
xdebug:
    install: 0
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
mysql:
    root_password: '123'
    phpmyadmin: '1'
    databases:
        P6KuNGp6oC9p:
            grant:
                - ALL
            name: test
            host: localhost
            user: test
            password: test
            sql_file: ''
```
