### ISSUE TITLE
Apache override not working on Debian Wheezy 7.2 x64

### ISSUE THREAD

**Issue by glend** [puphpet/puphpet#354]
My .htaccess isn't working for my vhost. I had to SSH and enable it globally to make it work. Here's my config, I just created it:

```
vagrantfile-local:
vm:
    box: debian-wheezy72-x64-vbox43
    box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
    hostname: null
    network:
        private_network: 192.168.56.101
        forwarded_port:
            fk6ihLgMyzQW:
                host: ''
                guest: ''
    provider:
        virtualbox:
            modifyvm:
                name: spazioagenti
                natdnshostresolver1: on
                memory: '512'
            setextradata:
                VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
    provision:
        puppet:
            manifests_path: puppet/manifests
            options:
                - --verbose
                - '--hiera_config /vagrant/hiera.yaml'
                - '--parser future'
    synced_folder:
        OHunDnwv4zwg:
            id: vagrant-root
            source: ./
            target: /var/www
            nfs: 'false'
    usable_port_range: 2200..2250
ssh:
    host: null
    port: null
    private_key_path: null
    username: vagrant
    guest_port: null
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: 'bash -l'
vagrant:
    host: ':detect'
  server:
packages: {  }
dot_files:
    -
        bash_aliases: null
_prevent_empty: ''
apache:
modules:
    - php
    - rewrite
 vhosts:
    x5LsNSbY7D4T:
        servername: spazioagenti.dev
        serveraliases:
            - www.spazioagenti.dev
        docroot: /var/www/spazioagenti
        port: '80'
        setenv:
            - 'APP_ENV dev'
        override:
            - All
user: www-data
group: www-data
default_vhost: true
mpm_module: prefork
php:
version: '55'
composer: '1'
modules:
    php:
        - cli
        - intl
        - mcrypt
        - curl
        - imagick
        - memcached
        - sqlite
    pear: {  }
    pecl:
        - pecl_http
        - PDO
ini:
    display_errors: On
    error_reporting: '-1'
    session.save_path: /var/lib/php/session
timezone: Europe/Tirane
xdebug:
install: '1'
settings:
    xdebug.default_enable: '1'
    xdebug.remote_autostart: '0'
    xdebug.remote_connect_back: '1'
    xdebug.remote_enable: '1'
    xdebug.remote_handler: dbgp
    xdebug.remote_port: '9000'
xhprof:
install: '1'
location: /var/www/xhprof
mysql:
root_password: '123456'
phpmyadmin: '1'
databases:
    c7Iywgb5kiYu:
        grant:
            - ALL
        name: spazioagenti
        host: localhost
        user: spaziouser
        password: '123456'
        sql_file: ''
```
