### ISSUE TITLE
Failed dependencies on pecl and pear

### ISSUE THREAD

**Issue by greggilbert** [puphpet/puphpet#357]
When I try to run `vagrant up`, I get a string of errors about "Skipping because of failed dependencies" on all the pecl and pear includes. When I go into the VM and look in `/usr/lib64/php/modules`, though, I see about half of them there, and looking at `php -i` shows them as being installed. memcached and APC are still missing, though.

Here's my common.yaml. (In case it matters, I've moved all the installation stuff to an install folder, and repathed everything accordingly):

``` yml

---
vagrantfile-local:
    vm:
        box: centos64-x64-vbox43-1383512148
        box_url: 'http://box.puphpet.com/centos64-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                DA07DZUsQHj7:
                    host: ''
                    guest: ''
        provider:
            virtualbox:
                modifyvm:
                    name: MYSITE
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puppet/manifests
                options:
                    - --verbose
                    - '--hiera_config /vagrant/install/hiera.yaml'
                    - '--parser future'
        synced_folder:
            OWRtPzDENAgd:
                id: vagrant-root
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    modules:
        - php
        - rewrite
    vhosts:
        azdq7wRBIIAa:
            servername: MYSITE.dev
            serveraliases:
                - MY.SITE.dev
            docroot: /var/www/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - gd
            - imagick
            - intl
            - mcrypt
            - odbc
            - xmlrpc
            - mbstring
        pear:
            - SOAP
        pecl:
            - pecl_http
            - APC
            - imagick
            - intl
            - memcache
            - memcached
            - oauth
            - PDO_ODBC
            - phar
            - ssh2
            - uuid
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: UTC
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
mysql:
    root_password: '123'
    phpmyadmin: 0
    databases: {  }
```

**Edit:** I think the issue is caused by other parts of the script failing. I took out pear: SOAP, PDO_ODBC, and ssh2, and everything else runs just fine. I did fully delete both the vagrant VM and the box itself and reinstall in case that mattered. Maybe SOAP shouldn't be part of the PEAR module dropdown?

**Edit 2:** Installation is very finicky. I have:

``` yml
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - gd
            - intl
            - mcrypt
            - odbc
            - xmlrpc
            - mbstring
        pear: { }
        pecl:
            - pecl_http
            - imagick
            - intl
            - memcache
            - memcached
            - oauth
            - phar
            - uuid
```

and neither imagick, memcache, or memcached are installed, but intl is. It's very strange and generally inconsistent.
