### ISSUE TITLE
Allow for php.ini configurations per vhost

### ISSUE THREAD

**Issue by reecefowell** [puphpet/puphpet#361]
php supports custom configurations per vhost in php.ini.

They can be contained within the regular php.ini file, you just create a 'section' that specifies a vhost, and then following configs will apply to that vhost.

[See here please](http://php.net/manual/en/ini.sections.php)

It could be used to specify, some refinements for production. Example:

``` YAML
nginx:
    vhosts:
        codeconsortium-prod:
            server_name: codeconsortium.prod
            server_aliases:
                - 'www.codeconsortium.prod'
                - 'codeconsortium.prod'
            www_root: /var/www/codeconsortium.dev/www/public/web
            listen_port: '80'
            index_files:
                - app.php
            envvars:
                - 'APP_ENV prod'
        codeconsortium-dev:
            server_name: codeconsortium.dev
            server_aliases:
                - 'www.codeconsortium.dev'
                - 'codeconsortium.dev'
            www_root: /var/www/codeconsortium.dev/www/public/web
            listen_port: '80'
            index_files:
                - app_dev.php
            envvars:
                - 'APP_ENV dev'
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
            - mysqlnd_qc
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: '/var/lib/php/session'
        session.cookie_httponly: '1'
        session.referer_check: 'codeconsortium.com'
        expose_php: Off
        #open_basedir: '/var/www/'
    ini-section:
        codeconsortium.prod:
            display_errors: Off
            disable_functions: 'getmyuid, getmypid, passthru, leak, listen, diskfreespace, tmpfile, link, ignore_user_abord, shell_exec, dl, exec, highlight_file, source, show_source, fpaththru, virtual, posix_ctermid, posix_getcwd, posix_getegid, posix_geteuid, posix_getgid, posix_getgrgid, posix_getgrnam, posix_getgroups, posix_getlogin, posix_getpgid, posix_getpgrp, posix_getpid, posix, _getppid, posix_getpwnam, posix_getpwuid, posix_getsid, posix_getuid, posix_kill, posix_setegid, posix_seteuid, posix_setgid, posix_setpgid, posix_setsid, posix_setuid, posix_times, posix_ttyname, posix_uname, phpinfo'
```

It is useful for allowing some functions for use in development modes, but for security purposes, disabling them in production environment.

The section keys, can be used as the value for the [HOST], so that this would, once converted would be appended to the standard /etc/php.ini:

``` INI
[HOST=codeconsortium.prod]
display_errors = Off
disable_functions = 'getmyuid, getmypid, passthru, leak, listen, diskfreespace, tmpfile, link, ignore_user_abord, shell_exec, dl, exec, highlight_file, source, show_source, fpaththru, virtual, posix_ctermid, posix_getcwd, posix_getegid, posix_geteuid, posix_getgid, posix_getgrgid, posix_getgrnam, posix_getgroups, posix_getlogin, posix_getpgid, posix_getpgrp, posix_getpid, posix, _getppid, posix_getpwnam, posix_getpwuid, posix_getsid, posix_getuid, posix_kill, posix_setegid, posix_seteuid, posix_setgid, posix_setpgid, posix_setsid, posix_setuid, posix_times, posix_ttyname, posix_uname, phpinfo'
```

Thanks for your consideration.
