### ISSUE TITLE
xhprof fails to install on vagrant up

### ISSUE THREAD

**Issue by mfairchild365** [puphpet/puphpet#410]
This is the result of the vagrant up:
http://pastebin.com/yLFVjG1y

```
The following packages have unmet dependencies:
 php5-xhprof : Depends: phpapi-20090626
E: Unable to correct problems, you have held broken packages.
```

Running `php -i` from command line, I see that the installed phpapi is `20100412`

This is my config.yaml

```

---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                AZzTRbjIYOaJ:
                    host: '8994'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            lF6d6GFPXAap:
                id: vagrant-root
                source: ./../../
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    modules:
        - php
        - rewrite
    vhosts:
        6KtbiKp20Hdk:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
    mod_pagespeed: 0
    mod_spdy: 0
php:
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - intl
            - mcrypt
            - tidy
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '1'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    root_password: '123'
    phpmyadmin: '1'
    adminer: 0
    databases:
        eiIjSzXM0L1P:
            grant:
                - ALL
            name: sitemaster
            host: localhost
            user: sitemaster
            password: password
            sql_file: ''
        WiKHxnVEeur9:
            grant:
                - ALL
            name: sitemaster_test
            host: localhost
            user: sitemaster_test
            password: password
            sql_file: ''
mongodb:
    install: 0
    auth: 1
    port: '27017'
    databases: {  }
beanstalkd:
    install: 0
    listenaddress: 0.0.0.0
    listenport: '13000'
    maxjobsize: '65535'
    maxconnections: '1024'
    binlogdir: /var/lib/beanstalkd/binlog
    binlogfsync: null
    binlogsize: '10485760'


```
