### ISSUE TITLE
Upload script breaks when values surrounded in double quotes

### ISSUE THREAD

**Issue by jtreminio** [puphpet/puphpet#448]
```
settings:
    listenaddress: "0.0.0.0"
    listenport: '13000'
    maxjobsize: '65535'
    maxconnections: '1024'
    binlogdir: "/var/lib/beanstalkd/binlog"
    binlogfsync: ~
    binlogsize: '10485760'
```

This breaks upload script
