### ISSUE TITLE
CentOS will not apply vhost settings correctly (Document Root)

### ISSUE THREAD

**Issue by wiesson** [puphpet/puphpet#487]
I removed the Document Root folder to have `/var/www` as root, however it does not work for me. If I invoke awesome.dev, the `/var/www/html` folder is still the root.  

```
apache:
    modules:
        - php
        - rewrite
    vhosts:
        DWVoNUdWeQ4S:
            servername: awesome.dev
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
    mod_pagespeed: 0
    mod_spdy: 0
```
