### ISSUE TITLE
Cannot install XDebug with nginx

### ISSUE THREAD

**Issue by kohenkatz** [puphpet/puphpet#511]
When running `vagrant up` or `vagrant provision`, I receive the error: `Could not find dependent Service[nginx] for Package[xdebug] at /etc/puppet/modules/puphpet/manifests/xdebug.pp:14`

Here is the config.yaml:

```

---
vagrantfile-local:
    vm:
        box: debian-wheezy72-x64-vbox43
        box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.248.33
            forwarded_port:
                o3cVeyGUwMGo:
                    host: '9273'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '768'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            t2H0xyibpQaZ:
                id: vagrant-root
                source: ./
                target: /srv/www/mysite.com
                nfs: 'false'
            xe26SMimrBTh:
                id: vagrant-root
                source: ../othersite/
                target: /srv/www/othersite.com
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - gearman
        - libmariadbclient-dev
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        path: /usr/local/bin
        log: /var/log/mailcatcher/mailcatcher.log
nginx:
    install: '1'
    vhosts:
        GnK0s824brbJ:
            server_name: local.mysite.com
            server_aliases:
                - www.mysite.local
                - vm.mysite.com
            www_root: /srv/www/mysite.com/public
            listen_port: '80'
            index_files:
                - index.php
            envvars:
                - 'KOHANA_ENV development'
        VLVgkG38V5dk:
            server_name: local.othersite.com
            server_aliases:
                - www.othersite.local
                - vm.othersite.com
            www_root: /srv/www/othersite.com/public
            listen_port: '80'
            index_files:
                - index.php
            envvars:
                - 'KOHANA_ENV development'
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cgi
            - cli
            - curl
            - fpm
            - imagick
            - intl
            - mcrypt
            - readline
            - mysql
            - mysqlnd
        pear: {  }
        pecl:
            - pecl_http
            - gearman
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/New_York
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
mariadb:
    install: '1'
    root_password: abc123
    phpmyadmin: 0
    adminer: 0
    databases:
        jHQ6ISrfBhrO:
            grant:
                - ALL
            name: mysite
            host: localhost
            user: myuser
            password: abc123
            sql_file: ''
        MyEvz4qDDDSL:
            grant:
                - ALL
            name: othersite
            host: localhost
            user: otheruser
            password: abc123
            sql_file: ''
    version: '5.5'
```

I'm wondering if this is similar to #378, which needs the `$real_webserver` fix (see https://github.com/puphpet/puppet-puphpet/blob/master/manifests/ini.pp#L123)
