### ISSUE TITLE
Apache did not start

### ISSUE THREAD

**Issue by Bravehartk2** [puphpet/puphpet#573]
I dosn't matter which Box I chose or which PHP version. I get:

Warning: Could not retrieve fact fqdn
Error: /Stage[main]/Apache::Service/Service[httpd]: Failed to call refresh: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 
Error: /Stage[main]/Apache::Service/Service[httpd]: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: 

My data:
Ubuntu 12.04 64 Bit
vagrant 1:1.5.1
VirtualBox 4.3.8 for Linux  (AMD64)

And here is my config.yaml:

```

---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 33.33.33.10
            forwarded_port:
                A9Rog8BS0Krk:
                    host: '8530'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            OiRPdc9jOGsi:
                id: vagrant-root
                source: ./esoTalk
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - nano
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        6Hco0tyuy9pK:
            servername: local.esotalk.dev
            docroot: /var/www/esoTalk/
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
    mod_pagespeed: '1'
    mod_spdy: '1'
php:
    install: '1'
    version: '53'
    composer: 1
    modules:
        php:
            - cli
            - curl
            - dbg
            - gd
            - intl
            - mcrypt
            - mysql
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Berlin
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: PASSWORD
    phpmyadmin: '1'
    adminer: 0
    databases:
        QPEmzNuJYg47:
            grant:
                - ALL
            name: database
            host: localhost
            user: dbuser
            password: PASSWORD
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

```
