### ISSUE TITLE
HHVM fails to install on 12.04 x64

### ISSUE THREAD

**Issue by andrewryno** [puphpet/puphpet#590]
Just downloaded a fresh `config.yml` and I'm getting the following errors:

```
The following packages have unmet dependencies:
 hhvm : Depends: libboost-filesystem1.49.0 but it is not installable
        Depends: libboost-program-options1.49.0 but it is not installable
        Depends: libboost-system1.49.0 but it is not installable
        Depends: libboost-system1.49.0 but it is not installable
        Depends: libboost-regex1.49.0 but it is not installable
        Depends: libboost-thread1.49.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

There seems to be a ppa for the newest version of boost which fixes this problem (see: https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Ubuntu-12.04). Tried for both nightly and normal build.

Though I'm assuming other people haven't had this problem since searching came up with nothing. My config.yml:

``` yml

---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                WO0nfHV6XJte:
                    host: '9315'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            LOTSmgNG7EvM:
                id: vagrant-root
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - htop
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        TiGe2uRQLSZt:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    vhosts:
        UnVXVoLcEh6k:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
hhvm:
    install: '1'
    nightly: '0'
    settings:
        host: 127.0.0.1
        port: '9000'
mysql:
    install: '1'
    root_password: rootpasswordtest
    phpmyadmin: 0
    adminer: 0
    databases:
        EWagmKCWe6xq:
            grant:
                - ALL
            name: laravel
            host: localhost
            user: laravel
            password: rootpasswordtest
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: '1'
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
```
