### ISSUE TITLE
PhpMyAdmin is unavailable, when I exclude Apache

### ISSUE THREAD

**Issue by seniorpreacher** [puphpet/puphpet#596]
Hi,
I tried several times, with different options, but I could not figure out, how to bring PhpMyAdmin work with nginx.

It gets installed, but I get a 500 error on 'localhost/phpmyadmin'.
On the VM, I have it installed in /etc/phpmyadmin and I found it in /usr/share/phpmyadmin, but with root:root ownership, so I can't just point a vhost there.

Notes:
- The PROJECTNAME in the config above is a placeholder, but the real name is one word without whitspaces or slashes.

---

Here is my configuration file, if anyone can find what's wrong, please help me out!

```
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vdvKj1AqC0tW:
                    host: '9831'
                    guest: '22'
                v8VRdmTbjXsf:
                    host: '80'
                    guest: '80'
                Ykw1xawGZZlF:
                    host: '443'
                    guest: '443'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            bwkgXeDy02Nm:
                id: vagrant-root
                source: ./
                target: /PROJECTNAME
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - nano
        - mc
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        RkSB9VdWGKCC:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    vhosts:
        VIhziekKcVOc:
            server_name: PROJECTNAME.dev
            server_aliases:
                - www.PROJECTNAME.dev
                - admin.PROJECTNAME.dev
                - api.PROJECTNAME.dev
                - facebook.PROJECTNAME.dev
                - static.PROJECTNAME.dev
            www_root: /PROJECTNAME/web/
            listen_port: '80'
            index_files:
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - fpm
            - gmp
            - imagick
            - intl
            - mcrypt
            - mysql
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: UTC
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: yii
    phpmyadmin: '1'
    adminer: 0
    databases:
        X3Z7Muig5CyA:
            grant:
                - ALL
            name: PROJECTNAME_dev
            host: localhost
            user: yii
            password: yii
            sql_file: /PROJECTNAME/app/data/PROJECTNAME_dev.sql
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
```
