### ISSUE TITLE
Empty entries preventing vagrant up in config.yaml after adding&removing shared folders in GUI

### ISSUE THREAD

**Issue by maciej-gurban** [puphpet/puphpet#598]
On the website, while customizing, I accidentally added and then removed a shared folder 3 times. This created the following lines in config.yaml

```
ZftdspwJRISJ:
    id: z0AVqbBI40t3
TTlFoAr2f2JX:
    id: Dg25jC650xmS
lA2eLXTZwkPT:
    id: sNErEZCmDdWK
```

Which in turn threw an error upon vagrant up, treating these as new folders, and failing to mount them. Error message:
vm:
- Shared folder that have NFS enabled do no support owner/group
  attributes. Host path: /
- The shared folder guest path must be absolute: 
- Shared folder that have NFS enabled do no support owner/group
  attributes. Host path:

**Fixed it simply by removing the said lines**
