### ISSUE TITLE
Composer value from form is not string

### ISSUE THREAD

**Issue by AlexSkrypnyk** [puphpet/puphpet#610]
A part of YAML file downloaded from website:

```
php:
    install: '1'
    version: '54'
    composer: 1
```

composer's value is integer (1) instead of string ('1'). This leads to composer not being installed.

Changing to string '1' fixes the issue.

```
php:
    install: '1'
    version: '54'
    composer: '1'
```
