### ISSUE TITLE
Can't install PECL APC

### ISSUE THREAD

**Issue by sobit** [puphpet/puphpet#615]
```
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
php:
    install: '1'
    version: '54'
    modules:
        pecl:
            - APC
    ini:
        apc.enabled: '1'
```

This is a pieces of config.yaml. Can't get APC working.

Although I have this in the `vagrant up` log:

```
Notice: /Stage[main]/Main/Php_pecl_mod[APC]/Php::Pecl::Module[APC]/Exec[pecl-APC]/returns: executed successfully
```

It's not showing up on `php -i`.

Any ideas?
