### ISSUE TITLE
customize php_pear_mod function take extra parameters for install package from a remote repository

### ISSUE THREAD

**Issue by kanariezwart** [puphpet/puphpet#644]
I'm trying to use / extend php_pear_mod function in manifest.pp to take extra parameters in a yaml fashion like

``` yaml
        pear:
            - PHP_CodeSniffer
            - PHPUnit:
                - repository: pear.phpunit.de
                - alldeps: true
```

Currently the function looks like

```
  if ! defined(Php::Pear::Module[$name]) {
    php::pear::module { $name:
      use_package         => false,
      service_autorestart => $php_webserver_restart,
    }
  }
```

And takes only one parameter ($name). PEAR won't discover the additional pear-channel. How can I extend to this take extra parameters and make it compatible with the parent php::pear::module function

```
php::pear::module { $name:
  repository  => $repository:,
  alldeps => $alldeps:,
}

Is this already possible? Any ideas or help is appreciated
```
