### ISSUE TITLE
Error: Could not find declared class ntp

### ISSUE THREAD

**Issue by texdc** [puphpet/puphpet#646]
Provisioning is failing.  VM starts, but port forwarding is not working.  It had been working fine until I modified the memory settings and ran `vagrant provision`.  Below is my best guess at what is failing.

ubuntu-precise12042-x64-vbox43 on OS X:

```
$ FACTER_ssh_username='vagrant' puppet apply --verbose --debug --hiera_config /vagrant/puphpet/puppet/hiera.yaml --parser future --debug --manifestdir /tmp/vagrant-puppet-1/manifests --detailed-exitcodes /tmp/vagrant-puppet-1/manifests/manifest.pp || [ $? -eq 2 ]
Warning: Could not retrieve fact fqdn
Debug: hiera(): Hiera YAML backend starting
Debug: hiera(): Looking up server in YAML backend
Debug: hiera(): Looking for data source config
Debug: hiera(): Found server in config
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class ntp at /tmp/vagrant-puppet-1/manifests/manifest.pp:9 on node precise64
Wrapped exception:
Could not find declared class ntp
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class ntp at /tmp/vagrant-puppet-1/manifests/manifest.pp:9 on node precise64
```

config.yaml

``` yaml

---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: drupal.local
        network:
            private_network: 192.168.56.101
            forwarded_port:
                Mc2xygCiphoL:
                    host: '8000'
                    guest: '80'
                Nc2xygCiphoM:
                    host: '8080'
                    guest: '2201'
                Oc2xygCiphoN:
                    host: '8081'
                    guest: '2202'
                Pc2xygCiphoO:
                    host: '9000'
                    guest: '3306'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '2048'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
                    - '--debug'
                facter:
                    vagrant: 1
        synced_folder:
            fAQEtU0Db412:
                id: vagrant-root
                source: ./
                target: /var/www
                nfs: 'true'
        usable_port_range: 2200..3310
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - ntp
        - vim
        - curl
        - git
        - rsplib-tools
        - nfs-common
        - nfs-kernel-server
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        Y5pxOY9w8v9f:
            servername: drupal
            docroot: /var/www/drupal7/docroot
            port: '2201'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
        Z5pxOY9w8v9g:
            servername: db.admin
            docroot: /var/www/phpmyadmin
            port: '2202'
            override:
                - All
            custom_fragment: ''
    mod_pagespeed: 0
    mod_spdy: 0
php:
    install: '1'
    version: '53'
    composer: 1
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - memcached
            - gd
            - curl
            - mysqlnd
            - imagick
            - memcache
            - snmp
            - fpm
            - sqlite
        pear: {  }
        pecl:
            - pecl_http
            - memcache
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        upload_max_filesize: 6M
        memory_limit: 1024M
        post_max_size: 8M
        max_execution_time: '180'
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9001'
drush:
    install: '1'
    settings:
        drush.tag_branch: 7.x
mysql:
    install: '1'
    root_password: xxxx
    phpmyadmin: '1'
    adminer: 0
    databases:
        GVa4uxvsAYSw:
            grant:
                - ALL
            name: xxxx
            host: localhost
            user: xxxx
            password: xxxx
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
```
