### ISSUE TITLE
When selecting nginx, config.yaml has: install: ''

### ISSUE THREAD

**Issue by d-ph** [puphpet/puphpet#653]
Hello,

steps to reproduce:
1. Go to [puphpet](https://puphpet.com)
2. Go to Webservers.
3. Deselect Apache.
4. Select Nginx.
5, Go to Create.
6. Click the Create button.

Result:
Corrupted config.yaml:

```
nginx:
    install: ''
    vhosts:
        XobXjBfgWx1h:
            server_name: awesome.dev
            server_aliases:
```

Expected result:

```
nginx:
    install: '1'
    vhosts:
        XobXjBfgWx1h:
            server_name: awesome.dev
            server_aliases:
```

Peculiarities: The puphpet wizard sometimes outputs correct config.yaml and sometimes not. Although the above steps to reproduce always leads to corrupted `config.yaml`.

Kthxbb,
d
