### ISSUE TITLE
config.yaml incorrect for NGINX install

### ISSUE THREAD

**Issue by iownspace** [puphpet/puphpet#658]
I created a fairly vanilla Puphpet configuration using NGINX as the web server and it produced the following configuration block that ends up breaking the PHP installation. 

``` yml
nginx:
    install: ''
    vhosts:
        KvlBFwiJAoEE:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
```

Manually changing to install: '1' fixes the issue.
