### ISSUE TITLE
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install php-mysql' returned 1

### ISSUE THREAD

**Issue by peterhough** [puphpet/puphpet#702]
Running a vagrant up on Mac OS X 10.9.2 I get the following error:

```
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install php-mysql' returned 1: Error: Package: php-mysql-5.4.27-1.el6.remi.x86_64 (remi)
           Requires: libmysqlclient.so.18(libmysqlclient_16)(64bit)
           Available: mysql-libs-5.5.36-1.el6.remi.x86_64 (remi)
               libmysqlclient.so.18(libmysqlclient_16)(64bit)
           Removing: mysql-libs-5.1.69-1.el6_4.x86_64 (@updates)
               Not found
           Obsoleted By: mysql-community-libs-compat-5.6.17-4.el6.x86_64 (mysql56-community)
               Not found
           Updated By: mysql-libs-5.5.37-1.el6.remi.x86_64 (remi)
               libmysqlclient.so.18(libmysqlclient_16)(64bit)
           Available: mysql-libs-5.1.71-1.el6.i686 (base)
               Not found
           Available: mysql-libs-5.1.73-3.el6_5.i686 (updates)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Error: /Stage[main]/Main/Php_mod[mysql]/Php::Module[mysql]/Package[PhpModule_mysql]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install php-mysql' returned 1: Error: Package: php-mysql-5.4.27-1.el6.remi.x86_64 (remi)
           Requires: libmysqlclient.so.18(libmysqlclient_16)(64bit)
           Available: mysql-libs-5.5.36-1.el6.remi.x86_64 (remi)
               libmysqlclient.so.18(libmysqlclient_16)(64bit)
           Removing: mysql-libs-5.1.69-1.el6_4.x86_64 (@updates)
               Not found
           Obsoleted By: mysql-community-libs-compat-5.6.17-4.el6.x86_64 (mysql56-community)
               Not found
           Updated By: mysql-libs-5.5.37-1.el6.remi.x86_64 (remi)
               libmysqlclient.so.18(libmysqlclient_16)(64bit)
           Available: mysql-libs-5.1.71-1.el6.i686 (base)
               Not found
           Available: mysql-libs-5.1.73-3.el6_5.i686 (updates)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

My config.yaml file looks like this:

```

---
vagrantfile-local:
    vm:
        box: centos64-x64-vbox43-1383512148
        box_url: 'http://box.puphpet.com/centos64-x64-vbox43.box'
        hostname: puphpet.local
        network:
            private_network: 192.168.56.101
            forwarded_port:
                ckabMnP734MT:
                    host: '6955'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            EBTPoHMThuZM:
                source: ../
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        8A4UdlaSMTF4:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    vhosts:
        umao4PiqNTnM:
            server_name: peterhough.dev
            server_aliases:
                - www.peterhough.dev
            www_root: /var/www/peterhough/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APPLICATION_ENV development'
php:
    install: '1'
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - common
            - fpm
            - gd
            - intl
            - mcrypt
            - mysql
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/London
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: ''
    phpmyadmin: 0
    adminer: 0
    databases: {  }
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
```

Many thanks in advance for any help.

Pete
