### ISSUE TITLE
Virtual document root support

### ISSUE THREAD

**Issue by zeleznypa** [puphpet/puphpet#769]
Both websersvers (Apache and NGINX) support great feature called "virtual document root" (or "Regular expression names" for NGINX) that look for document root folder name based on part of url address.

So you don't have to create as many virtual hosts as you have projects but you can have  just one universal instead.

http://nginx.org/en/docs/http/server_names.html#regex_names
http://httpd.apache.org/docs/2.2/mod/mod_vhost_alias.html

Please add support for this great feature

**Comment by jtreminio** [comment]
With 0d58fcf3aace33c6efd4b254e29575d10af7c6ab you can now add custom keys to config.yaml and they will be passed on to their respective Puppet modules.

**Comment by verenion** [comment]
I have been playing with trying to get virtual document roots working. I have done this manually in apache, but I need to get puphpet to do this for the other developers machines really. 

E.g. example1.dev > /var/www/example1
       example2.dev > /var/www/example2

when adding this: virtual_document_root: /var/www/%1. I get an error when running vagrant up. How do we pass virtual document roots to the puppet module?

**Comment by evamindbench** [comment]
@jtreminio , can you give an example for this apache VirtualDocumentRoot directive?

**Comment by evamindbench** [comment]
A bump, since I didn't get any further on this, @jtreminio , do you have a working example?

**Comment by zeleznypa** [comment]
Currently I'm not using puPHPet because I switched to the Docker technology. But I still think that this can help most people to set their own puphpet just in few steps and use them for all their projects without need of changing configuration each time the new project come.

Especially it help you, when you start with microservices :)

**Comment by evamindbench** [comment]
I managed to do it, but not using the custom config. What did I do?

- Create a new vhost with document root set to '/var/www/' 
- Fill in a path to a file that is to be placed where the puphpet config.yaml is, do this in field 'Virtual Host-Level Custom Directives'
- In that file, place something like `VirtualDocumentRoot /var/www/sites/%-4+`

**Comment by zeleznypa** [comment]
create directory `/var/www/test` in the virtual
set VirtualDocumentRoot like `VirtualDocumentRoot /var/www/%2` (im not test it, just guest)
Try to enter the http://test.puphpet.loc 

And everytime you create folder in the /var/www (respectively in your local computer folder with network link to that directory) you can also access samenamed subdomain

Hope it help

**Comment by steven-klein** [comment]
@evamindbench any chance you could show a complete config example for getting your VirtualDocumentRoot set?

**Comment by evamindbench** [comment]
@steven-klein , it's like this:

```
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - expires
        - headers
        - vhost_alias
        - deflate
    vhosts:
        av_5v31k1gpgc2x:
            servername: stdev.mydomain.nl
            serveraliases:
                - '*.stdev.mydomain.nl'
            docroot: /var/www/sites
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: /vagrant/puphpet/stdev
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_f8v4p8od6qba:
                    path: /var/www/sites
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_fdzxy0ceko8n:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
```

The custom fragment holds:

```
VirtualDocumentRoot /var/www/sites/%-4+B
```
