### ISSUE TITLE
Unable to install MongoDB

### ISSUE THREAD

**Issue by codeclown** [puphpet/puphpet#801]
I've been having problems with installing MongoDB. Here's my config (I removed everything with `install: 0`:

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: null
        memory: '512'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                8qaT6hdr9ECN:
                    host: '8080'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            yaJI18eMKMxD:
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
nginx:
    install: '1'
    vhosts:
        RBVGKEzdt9qn:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: UTC
mysql:
    install: '1'
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases:
        lqDGupjhLQl8:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }


```

And here are the errors I get when I run `vagrant up`. It goes on for a while, then stops here:

```
Warning: Could not retrieve fact fqdn
Error: /Stage[main]/Mongodb::Server::Service/Service[mongodb]: Could not evaluate: Could not find init script or upstart conf file for 'mongodb'
Error: /Stage[main]/Mongodb::Server::Service/Service[mongodb]: Failed to call refresh: Could not find init script or upstart conf file for 'mongodb'
Error: /Stage[main]/Mongodb::Server::Service/Service[mongodb]: Could not find init script or upstart conf file for 'mongodb'
Warning: /Stage[main]/Mongodb::Server/Anchor[mongodb::server::end]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Puphpet::Php::Pecl[mongo]/Package[php5-mongo]: Skipping because of failed dependencies
```

And when I visit the supposed IP address, nothing shows up, even though `vagrant status` gives me `running`. Could simply be that Nginx didn't get to install at all.
