### ISSUE TITLE
Ruby version error

### ISSUE THREAD

**Issue by hotrush** [puphpet/puphpet#806]
```
Warning: Could not retrieve fact fqdn
Error: Execution of '/usr/bin/gem install --no-rdoc --no-ri mailcatcher' returned 1: ERROR:  Error installing mailcatcher:
    mime-types requires Ruby version >= 1.9.2.

Error: /Stage[main]/Mailcatcher::Package/Package[mailcatcher]/ensure: change from absent to present failed: Execution of '/usr/bin/gem install --no-rdoc --no-ri mailcatcher' returned 1: ERROR:  Error installing mailcatcher:
    mime-types requires Ruby version >= 1.9.2.

Warning: /User[mailcatcher]: Skipping because of failed dependencies
Warning: /Stage[main]/Mailcatcher::Config/File[/var/log/mailcatcher]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Supervisord::Program[mailcatcher]/File[/etc/supervisor.d/program_mailcatcher.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Supervisord::Service/Service[supervisord]: Skipping because of failed dependencies
```

config.yaml

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: null
        memory: '512'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                jHPUrQZmzeMF:
                    host: '9272'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    natdnsproxy1: 'on'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            PEESqXKXKwLz:
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - memcached
        - imagemagick
        - gearman-job-server
        - libgearman-dev
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 1
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        LVaGsvzzwf9r:
            servername: dealroom.dev
            serveraliases:
                - www.dealroom.dev
            docroot: /var/www/dealroom_source
            port: '80'
            setenv:
                - 'KOHANA_ENV development'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    vhosts:
        w383xP62qnXr:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: 1
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mysql
            - memcached
            - imagick
            - curl
            - gd
        pear: {  }
        pecl:
            - pecl_http
            - gearman
    ini:
        display_errors: On
        error_reporting: 'E_ALL'
        session.save_path: /var/lib/php/session
        html_errors: On
        post_max_size: '100M'
        display_startup_errors: On
    timezone: Europe/Amsterdam
xdebug:
    install: 0
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: '123'
    phpmyadmin: '1'
    adminer: 0
    databases:
        c8sX75nWiJ7U:
            grant:
                - ALL
            name: dealroom
            host: localhost
            user: dealroom
            password: '123'
            sql_file: /var/www/sql/last_dump.sql
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
```

and have some more bugs:
- some domains can't be resolved, working if i change name server to 8.8.8.8 in /etc/resolv.conf
- pma installing not correct, no phpmyadmin table created

p.s. at 14.04 ubuntu have no problem with ruby version/mailcathcer.
- network issue still here.
- pma now not available at your site :)
- pecl gearman extension was included in config.yaml, installed, but was not enabled for php cli/apache config.
