### ISSUE TITLE
Xdebug configuration not working

### ISSUE THREAD

**Issue by marcosgdf** [puphpet/puphpet#848]
With the following config.yaml:

```
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - gd
            - imagick
            - intl
            - mcrypt
        pear: {  }
        pecl: {  }
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        sendmail_path: '"/usr/bin/env catchmail"'
    timezone: UTC
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
```

This configuration is loaded:

```
xdebug.remote_autostart Off Off
xdebug.remote_connect_back  On  On
xdebug.remote_cookie_expire_time    3600    3600
xdebug.remote_enable    On  On
xdebug.remote_handler   dbgp    dbgp
xdebug.remote_host  localhost   localhost
xdebug.remote_log   no value    no value
xdebug.remote_mode  req req
xdebug.remote_port  9000    9000
```

I see using `grep -R xdebug *` that those settings are stored in `zzzz_custom.ini` but it is  never loaded...

(I am talking about the apache2 php config file)
