### ISSUE TITLE
RabbitMQ dependency Erlang manifest on Centos 6.5

### ISSUE THREAD

**Issue by kanariezwart** [puphpet/puphpet#866]
Using Centos 6.5, the default version of Erlang is not compatible with RabbitMQ. By adding this lib https://github.com/garethr/garethr-erlang, CentOS and RabbitMQ play nice.

I wrote this addition for the manifest.pp and condig.yaml, maybe you can add it, to make RabbitMQ work as well for CentOS?

``` ruby
if hash_key_equals($rabbitmq_values, 'install', 1) {
  # copy yaml file as class
  create_resources('class', { 'rabbitmq' => $rabbitmq_values['settings'] })
...
  # resolve dependency Erlang library for RabbitMQ Management plugin for Centos distro
  if $::operatingsystem== 'CentOS' {
    include 'erlang'
    Class['erlang'] -> Class['rabbitmq']
...
```

Maybe also some configuration options in the config yaml to the manifest.pp, which can be managed through  the config.yaml file?

``` ruby
    # create some users
    if count ($rabbitmq_values['user']) > 0 {
      each($rabbitmq_values['user']) | $username, $values | {
        rabbitmq_user { $username:
          admin    => $values['admin'],
          password => $values['password'],
        }
        each($values['vhosts']) | $vhost | {
         rabbitmq_user_permissions { "${username}@${vhost}":
            configure_permission => '.*',
            read_permission      => '.*',
            write_permission     => '.*',
          }
        }
      }
    }
    # enable plugins
    each($rabbitmq_values['plugins']) | $rabbit_plugin | {
      rabbitmq_plugin { $rabbit_plugin:
        ensure => present,
      }
    }
  }
}
```

config.yaml:

``` yaml
rabbitmq:
    install: '1'
    settings:
        port: '5672'
    ...
    plugins:
        - rabbitmq_management_visualiser
        - rabbitmq_tracing
    user:
      [default-admin-name]:
          password: 'blahblah'
          admin: true
          vhosts:
            - "/"
    ...
```
