### ISSUE TITLE
Pear and PECL errors

### ISSUE THREAD

**Issue by Fynkymynky** [puphpet/puphpet#867]
During provision I'm getting these errors

```
Warning: Could not retrieve fact fqdn
Error: pear -d preferred_state=stable install  pear.php.net/HTTP_OAuth returned 1 instead of one of [0]
Error: /Stage[main]/Main/Php_pear_mod[HTTP_OAuth]/Puphpet::Php::Pear[HTTP_OAuth]/Php::Pear::Module[HTTP_OAuth]/Exec[pear-HTTP_OAuth]/returns: change from notrun to 0 failed: pear -d preferred_state=stable install  pear.php.net/HTTP_OAuth returned 1 instead of one of [0]
Warning: /Stage[main]/Main/Php_pecl_mod[pecl_http]/Puphpet::Php::Pecl[pecl_http]/Php::Pecl::Module[pecl_http]/Exec[pecl-pecl_http]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Php_pecl_mod[oauth]/Puphpet::Php::Pecl[oauth]/Php::Pecl::Module[oauth]/Exec[pecl-oauth]: Skipping because of failed dependencies
Warning: /Stage[main]/Main/Php_pecl_mod[intl]/Puphpet::Php::Pecl[intl]/Php::Pecl::Module[intl]/Exec[pecl-intl]: Skipping because of failed dependencies
```

My config.ymal file is

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: null
        memory: '2048'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                fJQCaYKzFb9X:
                    host: '6993'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            PkvDpYhOApUo:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules: null
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        vePMutZlsE2I:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome.dev/public
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    vhosts:
        0C6ok2nt0bdV:
            server_name: foo.dev
            server_aliases:
                - www.foo.dev
            www_root: /var/www/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - xsl
        pear:
            - HTTP_OAuth
        pecl:
            - pecl_http
            - imagick
            - intl
            - memcache
            - memcached
            - oauth
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/London
xdebug:
    install: 0
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: '123'
    adminer: 0
    databases:
        dqFTJbFuw2Nq:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '1'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true
```

Not sure why the errors are appearing, the rest of the VM builds just fine. It's just it doesn't seem to want to install oauth or any other pear or pecl packages.
