### ISSUE TITLE
Parallels NFS server_values is false

### ISSUE THREAD

**Issue by adear11** [puphpet/puphpet#868]
I'm trying to use Puphet to setup a Parallels box.
When I do `vagrant up`, if I use _nfs_ as the sync_type, I get the following error message:

```
Error: $server_values is false, not a hash or array at /tmp/vagrant-puppet-3/manifests/manifest.pp:189 on node packer-parallels-iso.localdomain
```

However, if I change the sync_type to _default_ the error goes away.

Also, this may or may not be related, when using _default_ as the sync_type, my shared folder ends up mounted to _/vagrant_ instead of _/var/www_ as indicated in my config.yaml.
When I use _default_ I see this in the output of `vagrant up`:

```
default: Mounting shared folders...
default: /var/www => /Users/adear/Documents/localDevelopment/www.mysite.com
default: /vagrant => /Users/adear/Documents/localDevelopment/www.mysite.com
```

For reference, this is my config.yaml:

``` yaml

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: null
        memory: '512'
        chosen_provider: parallels
        network:
            private_network: 192.168.110.10
            forwarded_port:
                aQODXrPvajPX:
                    host: '5413'
                    guest: '22'
                LUbqYFDRfI2n:
                    host: '8080'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            pMPlyJFOln8d:
                source: ./
                target: /var/www
                sync_type: nfs
                rsync:
                    args: '-z'
                    exclude: .vagrant/
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - man-db
        - git-core
        - vim
        - php5-dev
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        bMzZrMcbQIwy:
            servername: hurst.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www
            port: '80'
            setenv:
                - 'HURST_ENV Debug'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    vhosts:
        Kho9AnXpNvrs:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
        pear:
            - DB
        pecl:
            - pecl_http
            - mongo
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        output_buffering: On
        extension: mongo.so
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: 0
    root_password: '123'
    adminer: 0
    databases:
        iIr1mxilAgIa:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
```
