### ISSUE TITLE
Adminer doesn't work

### ISSUE THREAD

**Issue by jroenf** [puphpet/puphpet#873]
I can't open adminer.
The adminer folder is in the root of my shared directory, but can't open it with http://{SERVER_IP_ADDRESS}/adminer, because nginx default folder is not the root of the shared directory. I changed /etc/nginx/conf.d/default.conf on the guest to make it work, but it should work out of the box.

I created a Vagrant box with ubuntu precise, nginx and mariaDB, opting in for Adminer installation:

```

---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: puphpet/debian75-x64
        hostname: null
        memory: '2048'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                y24ylLxNdLcA:
                    host: '6404'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            mlg9PPZD6uYG:
                source: /Users/jeroenfranse/WebsiteProjects/zupr/www
                target: /var/www
                sync_type: nfs
                rsync:
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules: null
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        NJp0ec9m5l6z:
            servername: local.zupr.com
            docroot: /var/www/ZUPR-backend/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    vhosts:
        hFQi4yc3y5pB:
            server_name: local.zupr.com
            www_root: /var/www/ZUPR-backend/web/zupr
            listen_port: '80'
            index_files:
                - app_dev.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
        3s265PMSHPpK:
            server_name: api.local.zupr.com
            www_root: /var/www/ZUPR-backend/web/zupr
            listen_port: '80'
            index_files:
                - app_dev.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - gd
            - intl
            - ldap
            - mcrypt
            - memcache
            - memcached
            - xmlrpc
        pear: {  }
        pecl:
            - APC
            - pecl_http
            - geoip
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Amsterdam
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: '250'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: 0
    root_password: root
    adminer: 0
    databases:
        p34y5eGYrRSa:
            grant:
                - ALL
            name: zupr
            host: localhost
            user: zupr
            password: qwerty
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '1'
    root_password: '123'
    adminer: '1'
    databases:
        MOXb5GnPO6Xv:
            grant:
                - ALL
            name: zupr
            host: localhost
            user: zurp
            password: '123'
            sql_file: ''
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '1'
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true

```
