### ISSUE TITLE
Not reachable from outside the local network

### ISSUE THREAD

**Issue by caffeineflo** [puphpet/puphpet#874]
I can't reach any service within my VM from outside my local network. I'm running a nginx server as well as two Tomcat Servers (different ports each) on this VM. Everything is accessible after adding the corresponding iptable rules from within my local network, but once I'm trying to reach these services from the internet I can't connect to them.
I'm using a bridged network to directly interface with my router. There's a dyndns address setup for this server and the needed ports are open (I confirmed that already with another server where everything works fine).
I'm loosing my mind on this problem as I'm already sitting on this for the last 96hours. 

Please see my config.yaml attached. I added   

```
config.vm.network "public_network", bridge: 'en0'
```

for the public interface.

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: dev.test.de
        memory: '8192'
        chosen_provider: parallels
        network:
            private_network: 192.168.59.103
            forwarded_port:
                HPwsmcgPHeXF:
                    host: '8717'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 4
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            PejrurxCdhjU:
                source: ./share/
                target: /usr/share/hostshare/
                sync_type: default
                rsync:
                    args: '-z'
                    exclude: .vagrant/
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules: 
        frNWro9WKVof:
            port: '3306'
            priority: '100'
            proto: tcp
            action: accept
        ZW0iVWV9vtYI:
            port: '80'
            priority: '100'
            proto: tcp
            action: accept
        gzP8H0N4D9sM:
            port: '443'
            priority: '100'
            proto: tcp
            action: accept
        P8Hgz0NZW0iV:
            port: '5432'
            priority: '100'
            proto: tcp
            action: accept
        uyojASjals12:
            port: '8080'
            priority: '100'
            proto: tcp
            action: accept
        qeuynAJS12JA:
            port: '8090'
            priority: '100'
            proto: tcp
            action: accept
        UEnajsW91JaN:
            port: '1080'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        2XiIEXairMkT:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    vhosts:
        SefBUPaTzOsv:
            server_name: dev.test.de
            www_root: /usr/share/nginx/dev.test.de/
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - fpm
            - gd
            - imagick
            - intl
            - mcrypt
            - memcache
            - memcached
            - mysql
            - sqlite
            - xcache
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Berlin
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: password1234
    adminer: 0
    databases: {  }
postgresql:
    install: '1'
    settings:
        root_password: password1234
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
```
