### ISSUE TITLE
GeoIP functionality is not available from PECL module "geoip"

### ISSUE THREAD

**Issue by jesseforrest** [puphpet/puphpet#877]
Hi all,

In the past, when I configure GeoIP manually I would have access to PHP methods such as:

```
geoip_country_code_by_name
```

However, when I run vagrant up, I don't have access to this method. I receive the following error:

```
Fatal error: Call to undefined function geoip_country_code_by_name()
```

Am I configuring the config.yaml incorrectly?  This is the PHP section of my CentOS config.yaml:

```
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mbstring
        pear:
            - PHP_CodeSniffer
        pecl:
            - memcached
            - pecl_http
            - geoip
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/New_York
```

For reference, in order to get this to work in the past, manually, I would do the following steps on a server:

On Centos 5.x
$ wget http://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm
$ wget http://rpms.famillecollet.com/enterprise/remi-release-5.rpm
$ sudo rpm -Uvh remi-release-5_.rpm epel-release-5_.rpm

On Centos 6.x
$ wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
$ wget http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
$ sudo rpm -Uvh remi-release-6_.rpm epel-release-6_.rpm

Then do the following:
$ vim /etc/yum.repos.d/remi.repo

Edit the [remi] portion of the file so that the enabled option is set to 1. This will enable the remi repository:
enabled=1

$ yum -y install GeoIP GeoIP-devel
$ pecl install geoip
$ vim /etc/php.ini

Add this to end of php.ini:
[geoip]
extension=geoip.so 

$ cd /usr/share/GeoIP
$ wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
$ gunzip GeoLiteCity.dat.gz
$ mv -v GeoLiteCity.dat GeoIPCity.dat

---

Any thoughts are welcome!  Thanks!
