### ISSUE TITLE
Adminer not installed

### ISSUE THREAD

**Issue by marcosgdf** [puphpet/puphpet#879]
I've tried to access Adminer but a 404 error is thrown. I've also looked for it around the filesystem and it seems that it was not installed.

```
[12:11 PM]-[vagrant@packer-virtualbox-iso]-[/var/www]-[git vagrant] 
$ sudo locate adminer
/vagrant/puphpet/puppet/modules/puphpet/manifests/adminer.pp
/var/www/dev/vagrant/dolibarrdev/puphpet/puppet/modules/puphpet/manifests/adminer.pp
```

config.yaml

```

---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: null
        memory: '512'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.42.101
            forwarded_port: {  }
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            jopH6005bn96:
                source: ../../../
                target: /var/www
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - nano
        - ack-grep
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        b2tOrs1TMtoF:
            servername: dev.dolibarr.org
            docroot: /var/www/htdocs
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    vhosts:
        0dU5luf5AnIe:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
hhvm:
    install: 0
    nightly: 0
    settings:
        host: 127.0.0.1
        port: '9000'
mysql:
    install: '1'
    root_password: root
    adminer: 0
    databases:
        V6H3W2FVB7Yq:
            grant:
                - ALTER
                - CREATE
                - DELETE
                - DROP
                - INDEX
                - INSERT
                - SELECT
                - UPDATE
            name: dolibarr
            host: localhost
            user: user
            password: user
            sql_file: /var/www/dev/initdata/mysqldump_dolibarr_3.5.0.sql
postgresql:
    install: '1'
    settings:
        root_password: root
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: '1'
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

```
