### ISSUE TITLE
Error when trying to create wildcard serveralias (wildcard subdomains e.g. *.dev)

### ISSUE THREAD

**Issue by sisuwayn** [puphpet/puphpet#891]
When trying to setup the following vhost in the config.xml I get the error:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /..../Vagrantfile
Message: (/......./vagrant_php55_mysql56/puphpet/config.yaml): did not find expected alphabetic or numeric character while scanning an alias at line 111 column 19

I presume it's a vagrant issue but just wondering if anyone knows a way around this to configure a vhost to use wildcard subdomains. e.g. abc.dev, xyz.dev 

```
vhosts:
    ATGYT4vIxcBL:
        servername: dev
        serveraliases:
            - *.dev
        docroot: /var/www/
        port: '443'
        setenv:
            - 'APP_ENV dev'
        override:
            - All
        options:
            - Indexes
            - FollowSymLinks
            - MultiViews
        custom_fragment: ''
        ssl: '1'
        ssl_cert: ''
        ssl_key: ''
        ssl_chain: ''
        ssl_certs_dir: ''
```
