### ISSUE TITLE
MailCatcher PHP error: "/usr/bin/env: catchmail: No such file or directory"

### ISSUE THREAD

**Issue by eoinoc** [puphpet/puphpet#897]
Sending mail from PHP results in the following item in `/var/log/httpd/error_log`:

> /usr/bin/env: catchmail: No such file or directory

(That's **after** running `mailcatcher --http-ip=0.0.0.0`, since MailCatcher doesn't seem to start with the machine.)

On [MailCatcher's site](http://mailcatcher.me/), I've read under the PHP section:

> sendmail_path = /usr/bin/env catchmail -f some@from.address
> [...]
> If you've installed via RVM this probably won't work unless you've manually added your RVM bin paths to your system environment's PATH. In that case, run `which catchmail` and put that path into the `sendmail_path` directive above instead of `/usr/bin/env catchmail`.

Following those instructions, I did edit `/etc/php.d/zzzz_custom.ini` with `sendmail_path=/usr/local/rvm/gems/ruby-1.9.3-p547/bin/catchmail`, but that just resulted in the next server error:

> /usr/bin/env: ruby_executable_hooks: No such file or directory

I finally ran:

```
ln -s `which ruby_executable_hooks` /usr/bin/ruby_executable_hooks
```

But that resulted in a different error that I couldn't figure out further:

> /usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:313:in `to_specs': Could not find 'mailcatcher' (>= 0) among 12 total gem(s) (Gem::LoadError)

I'd appreciate any thoughts on the configuration to get MailCatcher running without errors with the generated `config.yaml`.

Here's the test file `mail.php` I'm running at `http://mysite.localhost/mail.php`:

```
<?php
mail('example@example.com', 'Helo', 'Hello World.');
```

And `config.yaml`:

```

---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: null
        memory: '1024'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.152
            forwarded_port:
                8H4mfrzPvVdN:
                    host: '9244'
                    guest: '22'
            forwarded_port:
                8H4mfrzPvVdE:
                    host: '8080'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            4oC2qxDHttv1:
                source: ./
                target: /var/www/mysite
                sync_type: default
                rsync:
                    args: '-z'
                    exclude: .vagrant/
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - ImageMagick
        - ImageMagick-devel
        - ImageMagick-perl
        - htop
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules:
        VmT9vkmH8kzW:
            port: '3306'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
        - headers
    vhosts:
        eEWkI24X3D8B:
            servername: mysite.localhost
            docroot: /var/www/mysite
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        TCQSAjHi0CAk:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - soap
            - mbstring
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: Off
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: UTC
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: mysite123
    adminer: '1'
    databases:
        E2NgFMLAezzs:
            grant:
                - ALL
            name: mysite_app
            host: localhost
            user: umysite
            password: mysite
            sql_file: ''
        b1tDeRGJj7fo:
            grant:
                - ALL
            name: mysite_other
            host: localhost
            user: umysite
            password: mysite
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true

```
