### ISSUE TITLE
Ubuntu nginx won't start and mysql shows socket error

### ISSUE THREAD

**Issue by stevechen** [puphpet/puphpet#914]
This is another attempt to use puppet. I used Ubuntu precise. When "vagrant up", there's always nginx error:

```
Error: Could not start Service[nginx]: Execution of '/etc/init.d/nginx start' returned 1:
Error: /Stage[main]/Nginx::Service/Service[nginx]/ensure: change from stopped to running failed: Could not start Service[nginx]: Execution of '/etc/init.d/nginx start' returned 1:
Warning: /Stage[main]/Nginx/Anchor[nginx::end]: Skipping because of failed dependencies
```

and when I tried to login to mysql in the VM:

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

Tried destroy and up again several times, no help.

Also, I started with postgresql installation too, and postgresql simply refuse to install, so I turned it off.

Below is my config file:

---

```
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: null
        memory: '512'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.100.200
            forwarded_port:
                bl1BV93atEoA:
                    host: '7033'
                    guest: '22'
                lZJXQun2QPsz:
                    host: '8890'
                    guest: '80'
                oAYiEURTANna:
                    host: '8891'
                    guest: '3306'
                d0nVtNn0UbOq:
                    host: '5434'
                    guest: '5433'
                # HsTuCxUNYeeN:
                #     host: '52698'
                #     guest: '52698'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            pheb2lPAOKNy:
                source: ./
                target: /var/www
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - nano
        - git
        - mercurial
        - curl
        - phpmyadmin
        - wget
        - gcc
        - make
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules: null
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        uW7JPYwmnzBW:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        E3EAr8F4szRX:
            server_name: test.dev
            server_aliases:
                - www.test.dev
            www_root: /var/www/test.dev/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_EN dev'
            ssl_cert: ''
            ssl_key: ''
        PywTb4PdFWpA:
            server_name: atk43.dev
            server_aliases:
                - www.atk43.dev
            www_root: /var/www/atk43.dev/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_EN dev'
            ssl_cert: ''
            ssl_key: ''
        248uukDeSct6:
            server_name: lara.dev
            server_aliases:
                - www.lara.dev
            www_root: /var/www/lara.dev/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_EN dev'
            ssl_cert: ''
            ssl_key: ''
        ij2wEuFfu4el:
            server_name: xonixe.dev
            server_aliases:
                - www.xonixe.dev
            www_root: /var/www/xonixe.dev/public
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_EN dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cgi
            - cli
            - curl
            - dbg
            - fpm
            - gd
            - geoip
            - imagick
            - intl
            - mbstring
            - mcrypt
            - memcache
            - mysql
            - sqlite
        pear:
            - I18N_UnicodeNormalizer
            - XML_Parser2
        pecl:
            - redis
            - date_time
            - hash
            - oauth
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        allow_url_include: '0'
    timezone: Asia/Taipei
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: '1'
    root_password: ''
    adminer: 0
    databases:
        m5SLkVbcPl55:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
beanstalkd:
    install: '1'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true
```
