### ISSUE TITLE
Custom Nginx locations

### ISSUE THREAD

**Issue by alexandrusavin** [puphpet/puphpet#916]
Hi!

It would be very nice to be able to create custom locations in config.yaml for nginx installations.

I started working on this but it's my first time working with puppet and ruby so it would probably take me some time.

I would do something like this:

``` yml
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        localhost.com:
            server_name: 'localhost.com'
            www_root: /var/www/
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
            locations_append:
                wiki:
                    vhost: 'localhost.com'
                    www_root: '/wiki'
                    location: '^/wiki'
                    location_custom_cfg_append:
                        - "root /var/www/;"
                www:
                    vhost: 'localhost.com'
                    www_root: '/'
                    location: '/?'
                    location_custom_cfg_append:
                        - "if ($host = 'api.localhost.com') { set $new_root /var/www/depot; }"
                        - "if ($arg_app = 'forums') { set $root /var/www/depot/forums; }"
                        - "root $root;"
```

Thanks,
Alex
