### ISSUE TITLE
Wrong box url for debian75-x64

### ISSUE THREAD

**Issue by jjsaunier** [puphpet/puphpet#921]
Hey, 

Currently puphet export the wrong box url inside `puphet/config.yml`

``` yaml
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
```

Expected : 

``` yaml
    vm:
        box: puphpet/debian75-x64
        box_url: https://vagrantcloud.com/puphpet/debian75-x64/version/3/provider/virtualbox.box
```

In my case I use virtualbox, so the link is for virtualbox.
