### ISSUE TITLE
MailCatcher "missing argument -f"

### ISSUE THREAD

**Issue by Grafikart** [puphpet/puphpet#932]
I tried a fresh puphpet install today and I encountered a problem with Mailcatcher. When I try to send email using the mail() function I got some errors in my error.log

.../catchmail:14:... missing argument: -f 
## The problem

I found that the sendmail_path is modified with a zzzz_custom.ini mods for PHP. but it contains

```
sendmail_path=/usr/local/rvm/wrappers/default/catchmail -f
```
## The solution

remove the -f at the end of this option, I can't do a PR since I have no idea where to fix this ^^

**Comment by deizel** [comment]
To summarize for those arriving through Google with the same error message…

Update your `puphpet/config.yaml` like so:

````yaml
mailcatcher:
    install: '1'
    settings:
        ...
        from_email_method: headers
````

… then run `vagrant provision`.

(In my case, it turns out CakePHP passes `From:` as a header.)
