### ISSUE TITLE
Provision bug with lastest zip

### ISSUE THREAD

**Issue by teddy-dubal** [puphpet/puphpet#935]
Hi , 
I just make a package , and provision don't work i have this error

```
Error: Duplicate declaration: Class[Apt] is already declared; cannot redeclare at /tmp/vagrant-puppet-3/manifests/nodes/server.pp:56 on node packer-virtualbox-iso.vagrantup.com
Error: Duplicate declaration: Class[Apt] is already declared; cannot redeclare at /tmp/vagrant-puppet-3/manifests/nodes/server.pp:56 on node packer-virtualbox-iso.vagrantup.com

```

My config.yaml

```

---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: null
        memory: '512'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.103
            forwarded_port:
                MkeKp7y5g1Eq:
                    host: '7227'
                    guest: '22'
                zW4AqNgbk5ny:
                    host: '5672'
                    guest: '5672'
                qD4tN3bLQjwJ:
                    host: '15672'
                    guest: '15672'
                EAXGYPHlRCBg:
                    host: '27017'
                    guest: '27017'
                xeMRUk0iqJY2:
                    host: '9200'
                    guest: '9200'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            ltrl6kwB9Wqz:
                source: ./
                target: /var/www/
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
firewall:
    install: '1'
    rules: null
apache:
    install: 0
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        SoznwaCWwYep:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        1gx0L5szWr4u:
            server_name: xx.xxxx.com.lan
            www_root: /var/www/web
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index_bo.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
        MHcsPgCm4bAB:
            server_name: xxxx.com.lan
            www_root: /var/www/web
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - fpm
            - gd
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Paris
hhvm:
    install: 0
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    modules:
        pear: {  }
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
ruby:
    versions:
        eaGrCRemWhed:
            version: ''
mysql:
    install: '1'
    root_password: '123'
    adminer: 0
    databases:
        kEe3TGkWVhuB:
            grant:
                - ALL
            name: xxxx
            host: localhost
            user: xxxx
            password: xxxx
            sql_file: /var/www/docs/init.sql
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: '1'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '1'
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '1'
    settings:
        port: '5672'
elastic_search:
    install: '1'
    settings:
        java_install: true
        autoupgrade: true


```

Vagrant version 1.6.3
Virtualbox 4.3.12
