### ISSUE TITLE
Fixing tip for the config.vm.usable_port_range

### ISSUE THREAD

**Issue by shivapoudel** [puphpet/puphpet#958]
I have seen `config.vm.usable_port_range = (10200..10500)` but it doesn't set the value provided at config.yaml file. so for the range fix you can do:

In Vagrantfile

``` shell
  # Usable Port Range Settings
  if !data['vm']['usable_port_range'].nil?
    config.vm.usable_port_range = data['vm']['usable_port_range']
  end
```

In configuration YAML file

``` yaml
[vagrantfile...]
  vm:
      usable_port_range: !ruby/range 10200..10500
```
