### ISSUE TITLE
Symfony Application on Apache with PHP-FPM doesn't work properly

### ISSUE THREAD

**Issue by 0x46616c6b** [puphpet/puphpet#964]
Hello community,

i have a strange issue with developing a symfony web application with Apache (2.4) and PHP-FPM.

My configuration

```
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - expires
        - deflate
        - headers
    vhosts:
        lQydyYDWwPkB:
            servername: mail.dev
            docroot: /var/www/web
            port: '80'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - common
            - gd
            - imagick
            - mbstring
            - mysql
            - odbc
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Berlin
    mod_php: 0
```

The following routes are corrupt:

```
/app_dev.php/
/app_dev.php/register
```

All the routes under `/app_dev.php/*` are broken and return a 404, so they not be proxied to PHP-FPM. I identified the problem in a wrong `ProxyPassMatch` configuration. So I played a round and built the following configuration

```
# default Match from PuPHPet
ProxyPassMatch ^/(.*\.php)$ fcgi://127.0.0.1:9000/var/www/web/$1
# additional Match
ProxyPassMatch ^/(.+\.php)(/.+)$ fcgi://127.0.0.1:9000/var/www/web/$1
```

For now the routes I described above are working _but_ on `/app_dev.php/`In only get an error "Access denied." Anybody has experience with this use case?
