### ISSUE TITLE
Installing redis doesn't install igbinary

### ISSUE THREAD

**Issue by kusmierz** [puphpet/puphpet#966]
I've added redis to my php extensions to have `\Redis` class (see https://github.com/nicolasff/phpredis/):

``` yaml
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - redis
```

I know, it's manual change - but adding it under pecl key (as puphpet do) does nothing (I have no \Redis class at all). Anyway - it works, but I can't install redis with igbinary. How could I do it? Thanks in advance for help.
