### ISSUE TITLE
PHPRedis is not enabled by default

### ISSUE THREAD

**Issue by kusmierz** [puphpet/puphpet#968]
I've:

``` yaml
php:
    install: '1'
    version: '55'
    modules:
        php:
            - cli
            - common
        pear: {  }
        pecl:
            - igbinary
            - redis
```

But redis is not present. Why?

``` bash
[06:25 AM]-[vagrant@test]-[~]
$ php -i | grep -i redis
This program is free software; you can redistribute it and/or modify
```

Because there is no ini file (so extension is not loading). Have I create separate exec-once (always?) script or is it a bug? Same thing for pecl/igbinary.

Example exec-once/always file:

``` bash
echo "extension=redis.so" > /etc/php5/mods-available/redis.ini
echo "extension=igbinary.so" > /etc/php5/mods-available/igbinary.ini
ln -s /etc/php5/mods-available/igbinary.ini /etc/php5/fpm/conf.d/10-igbinary.ini
ln -s /etc/php5/mods-available/igbinary.ini /etc/php5/cli/conf.d/10-igbinary.ini
ln -s /etc/php5/mods-available/redis.ini /etc/php5/fpm/conf.d/20-redis.ini
ln -s /etc/php5/mods-available/redis.ini /etc/php5/cli/conf.d/20-redis.ini
```

BTW: as I mentioned in #966 we can also add redis as an extension (in "modules" section) and it works out of the box.

see also #966
