### ISSUE TITLE
Browser ask me to download php file

### ISSUE THREAD

**Issue by ojhaujjwal** [puphpet/puphpet#973]
I generated the Manifest yesterday and today I did `vagrant up` and something like [this](http://stackoverflow.com/questions/5477603/browser-ask-me-to-download-php-file) problem appeared. Whenever, I access a php file, it forces to download the file.

```

---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: null
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                et7YZq37RB33:
                    host: '85'
                    guest: '80'
                z3VzsitNCAxw:
                    host: '2281'
                    guest: '2281'
                1hMi6omnUwAO:
                    host: '2282'
                    guest: '2282'
                t8ZjUjYCNWFt:
                    host: '2283'
                    guest: '2283'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            Kmc8SdxeHeVK:
                source: ../../
                target: /var/www
                sync_type: nfs
                rsync:
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
firewall:
    install: '1'
    rules:
        snOEwd37p0DD:
            port: '2283'
            priority: '1000'
            proto: tcp
            action: accept
        bc81kRaDeocB:
            port: '6533'
            priority: '1000'
            proto: tcp
            action: accept
        w5euRiL3EoJD:
            port: '6534'
            priority: '1000'
            proto: tcp
            action: accept
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: false
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        OSMTQ4oSHQyL:
            servername: ujjwal.dev
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV development'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: ''
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        ntRzfqodYArz:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.php
                - index.html
                - index.htm
            envvars:
                - 'APP_ENV dev'
            engine: ''
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - gd
            - geoip
            - gmp
            - imagick
            - intl
            - mbstring
            - mcrypt
            - memcached
            - mysql
            - mysqlnd
        pear: {  }
        pecl:
            - APC
            - memcached
            - PDO
            - PDO_MYSQL
            - Fileinfo
            - yaml
            - pecl_http
            - imagick
            - intl
            - gearman
            - uploadprogress
            - pthreads
            - SPL_Types
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        default_charset: UTF-8
    timezone: UTC
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: '0'
        port: '0'
    modules:
        pear: {  }
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: ''
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '1'
    npm_packages: {  }
mysql:
    install: '1'
    root_password: hotsamai
    adminer: 0
    databases: {  }
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true
```
