### ISSUE TITLE
nginx downloads file

### ISSUE THREAD

**Issue by HMAZonderland** [puphpet/puphpet#983]
I'm not sure where this goes wrong but when I call one of the vhosts it downloads the index.php file.
Config file:

``` yaml

---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: null
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                ZySImzGJrpVW:
                    host: '6177'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    name: 'webiq.virtualmachine.dev'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            OpmIoFU60OPo:
                source: ../webiq.server.rpc
                target: /var/www/webiq.server.rpc
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
            TwjJogrTas3Q:
                source: ../webiq.client.support
                target: /var/www/webiq.client.support
                sync_type: default
                rsync:
                    auto: 'false'
            4HF0DahVGLAP:
                source: ../webiq.client.cartblank
                target: /var/www/webiq.client.cartblank
                sync_type: default
                rsync:
                    auto: 'false'
            BFnLs3DaDDqW:
                source: ../webiq.server.generator
                target: /var/www/webiq.server.generator
                sync_type: default
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - git
firewall:
    install: '1'
    rules:
        kau2PqsO8Ncl:
            port: '5123'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        ICTM9pkqDwuB:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        emxk5iJ2G7uq:
            server_name: dev3.rpc.webiq.nl
            server_aliases:
                - webiq.server.rpc
            www_root: /var/www/webiq.server.rpc/src/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        rLah1mr2GSBu:
            server_name: dev.support.webiq.nl
            server_aliases:
                - webiq.client.support
            www_root: /var/www/webiq.client.support/src/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        dkyPoympKYyt:
            server_name: dev.cartblank.nl
            server_aliases:
                - webiq.client.cartblank
            www_root: /var/www/webiq.client.cartblank/src/
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
        r16nv0obrbwY:
            server_name: gen.rpc.webiq.nl
            server_aliases:
                - webiq.server.generator
            www_root: /var/www/webiq.server.generator
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '0'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Chicago
    mod_php: 0
hhvm:
    install: '1'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    modules:
        pear:
            - PHP_Beautifier
            - PHP_CodeSniffer
            - PHP_DocBlockGenerator
            - PHP_Archive
            - PHP_UML
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        OS1GslLFcMCD:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
mysql:
    install: '1'
    root_password: '123'
    adminer: 0
    databases:
        U4yr5Ro0poYd:
            grant:
                - ALL
            name: siteiq
            host: localhost
            user: siteiq
            password: '123'
            sql_file: /var/www/webiq.server.rpc/database/databasedump.sql
        BX35k07ShBOu:
            grant:
                - ALL
            name: test
            host: localhost
            user: siteiq
            password: '123'
            sql_file: /var/www/webiq.server.rpc/database/createscript.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true

```
